import {testRoot as developmentTestRoot} from '../../../tools/development-paths.mjs';
/** Actual packaged V5 gestures on disposable Test data. Never use a live profile. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';

const appRoot=fileURLToPath(new URL('../../../',import.meta.url));
const project=path.resolve(appRoot,'../..'),testRoot=developmentTestRoot;
const runRoot=path.join(testRoot,'runs/native-dragdrop-20260917');
const executable=process.env.ASMB_PACKAGED_EXECUTABLE;
assert.deepEqual(process.argv.slice(2),['--run-isolated']);
assert.ok(executable&&path.isAbsolute(executable)&&executable.includes('.app/Contents/MacOS/'));
assert.ok(executable.startsWith(path.join(appRoot,'releases')+'/')||executable.startsWith(testRoot+'/runs/native-package/'));
import {_electron} from '../../../tools/playwright.mjs';
await fs.mkdir(runRoot,{recursive:true});
const output=await fs.mkdtemp(path.join(runRoot,'acceptance-')),data=path.join(output,'data'),tmp=path.join(output,'tmp');
await fs.mkdir(tmp);process.env.TMPDIR=tmp;
const fixture=path.join(output,'fixture'),external=path.join(output,'external'),repo='Drag-QA';
const workspace=path.join(data,'workspaces/asMagicBrain',repo);
for(const dir of ['source/nested/deep','source/empty','target','empty-target'])await fs.mkdir(path.join(fixture,dir),{recursive:true});
const initial='# Drag QA\n\nSaved source stays separate.\n';
const inputs={'README.md':initial,'source/note.md':'# Saved note\n','source/second.md':'# Second note\n','source/nested/deep/leaf.txt':'Nested bytes Ω\n','target/keep.md':'# Keep\n','target/note.md':'# Collision target\n','root-a.md':'# A\n','root-b.md':'# B\n'};
for(const [name,text]of Object.entries(inputs))await fs.writeFile(path.join(fixture,name),text);
for(const dir of ['bundle/nested','bundle/empty','a','b','closing-batch','cancel-batch'])await fs.mkdir(path.join(external,dir),{recursive:true});
await fs.writeFile(path.join(external,'README.md'),'# External README must not overwrite a dirty target\n');
await fs.writeFile(path.join(external,'outside.txt'),'Outside tree must not navigate or import\n');
await fs.writeFile(path.join(external,'empty-tree.txt'),'Empty tree drop\n');
await fs.writeFile(path.join(external,'bundle/nested/leaf.txt'),'External nested bytes Ω\n');
await fs.writeFile(path.join(external,'a/same.txt'),'First same name\n');await fs.writeFile(path.join(external,'b/same.txt'),'Second same name\n');
await fs.writeFile(path.join(external,'large.pdf'),Buffer.alloc(5*1024*1024+17,173));
// A modest multi-file copy gives close/drain a meaningful asynchronous window.
for(let i=0;i<80;i++)await fs.writeFile(path.join(external,'closing-batch',`file-${i}.bin`),Buffer.alloc(128*1024,i));
for(let i=0;i<600;i++)await fs.writeFile(path.join(external,'cancel-batch',`file-${i}.bin`),Buffer.alloc(128*1024,i%256));
const zip=path.join(output,'fixture.zip');execFileSync('/usr/bin/zip',['-q','-r',zip,'.'],{cwd:fixture,env:{PATH:'/usr/bin:/bin',TMPDIR:tmp}});
const sha=async file=>{const h=createHash('sha256');for await(const chunk of createReadStream(file))h.update(chunk);return h.digest('hex');};
const exists=async file=>Boolean(await fs.stat(file).catch(()=>null));
async function inventory(root){const entries=[];async function visit(relative){for(const item of await fs.readdir(path.join(root,relative),{withFileTypes:true})){if(item.name==='.git')continue;const name=path.posix.join(relative,item.name),file=path.join(root,name),stat=await fs.lstat(file);assert.equal(stat.isSymbolicLink(),false);entries.push({path:name,type:item.isDirectory()?'directory':'file',inode:stat.ino,...(item.isFile()?{size:stat.size,sha256:await sha(file)}:{})});if(item.isDirectory())await visit(name);}}await visit('');return entries.sort((a,b)=>a.path.localeCompare(b.path));}
const externalBefore=await inventory(external);await fs.writeFile(path.join(output,'external-before.json'),JSON.stringify(externalBefore,null,2));
const bundle=executable.slice(0,executable.indexOf('.app/Contents/MacOS/')+4),metadata=JSON.parse(await fs.readFile(path.join(bundle,'Contents/Resources/app/native-package.json'),'utf8'));
const events=[],errors=[],consoleErrors=[],requests=[];let app,page,cdp,failure,recorder=null,launchNumber=0;
const record=(name,details={})=>events.push({name,at:new Date().toISOString(),...details});
const button=name=>page.getByRole('button',{name,exact:true});
// Attribute selectors are constructed only from bounded synthetic fixture names.
const node=name=>page.locator(`.rex-node[data-explorer-path="${name}"]`);
const git=(...args)=>execFileSync('/usr/bin/git',['-C',workspace,...args],{encoding:'utf8',env:{PATH:'/usr/bin:/bin',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_OPTIONAL_LOCKS:'0'}}).trim();
async function until(check,label,timeout=20000){const end=Date.now()+timeout;let value;do{try{value=await check();if(value)return value;}catch(e){value=e.message;}await new Promise(r=>setTimeout(r,50));}while(Date.now()<end);throw Error(`Timeout ${label}: ${value}`);}
async function launch(){
 app=await _electron.launch({executablePath:executable,args:['--test-data-root='+data],cwd:output,env:{PATH:process.env.PATH,HOME:process.env.HOME,TMPDIR:tmp}});
 page=await app.firstWindow();page.setDefaultTimeout(15000);launchNumber++;
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 await button(/^Switch local repository:/).waitFor();cdp=await page.context().newCDPSession(page);
 const runtime=await app.evaluate(({app})=>({packaged:app.isPackaged,executable:process.execPath,cwd:process.cwd(),profile:app.getPath('userData')}));assert.equal(runtime.packaged,true);assert.equal(runtime.executable,executable);assert.equal(runtime.cwd,output);assert.equal(runtime.profile,data+'-electron-profile');
 await page.evaluate(()=>{window.__asmbQaDrops=[];for(const kind of ['dragstart','dragenter','dragover','drop'])document.addEventListener(kind,event=>window.__asmbQaDrops.push({kind,trusted:event.isTrusted,time:Date.now(),types:[...(event.dataTransfer?.types??[])],files:[...(event.dataTransfer?.files??[])].map(f=>({name:f.name,size:f.size,type:f.type})),target:event.target.closest?.('[data-explorer-path]')?.getAttribute('data-explorer-path')??event.target.className}),true);});
 record('actual-packaged-launch',{runtime});
}
async function screenshot(name){await page.screenshot({path:path.join(output,name+'.png')});record('screenshot',{file:name+'.png'});}
async function startVideo(){
 await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=1000;const context=canvas.getContext('2d'),chunks=[],mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm;codecs=vp8';const stream=canvas.captureStream(12),recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1500000});window.__asmbQaVideo={canvas,context,chunks,recorder,stream,started:Date.now(),mime};recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start(1000);});
 recorder={started:Date.now(),frames:0,dropped:0,busy:false,listener:null};const state=recorder;
 state.listener=async event=>{void cdp.send('Page.screencastFrameAck',{sessionId:event.sessionId}).catch(()=>{});if(state.busy){state.dropped++;return;}state.busy=true;try{await page.evaluate(async jpeg=>{const v=window.__asmbQaVideo;if(!v)return;const img=new Image();img.src='data:image/jpeg;base64,'+jpeg;await img.decode();v.context.drawImage(img,0,0,v.canvas.width,v.canvas.height);},event.data);state.frames++;}catch(error){state.frameErrors??=[];state.frameErrors.push(String(error));}finally{state.busy=false;}};
 cdp.on('Page.screencastFrame',state.listener);await cdp.send('Page.startScreencast',{format:'jpeg',quality:75,maxWidth:1440,maxHeight:1000,everyNthFrame:1});
}
async function stopVideo(){if(!recorder)return;const state=recorder;await cdp.send('Page.stopScreencast');cdp.off('Page.screencastFrame',state.listener);await until(()=>!state.busy,'video frame drained');const result=await page.evaluate(async()=>{const v=window.__asmbQaVideo;await new Promise(resolve=>{v.recorder.onstop=resolve;v.recorder.stop();});v.stream.getTracks().forEach(t=>t.stop());const blob=new Blob(v.chunks,{type:v.mime}),base64=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(blob);});delete window.__asmbQaVideo;return{base64,mime:v.mime};});const filename=`gestures-${launchNumber}.webm`;await fs.writeFile(path.join(output,filename),Buffer.from(result.base64,'base64'));record('real-gesture-recording',{file:filename,mime:result.mime,durationMs:Date.now()-state.started,capturedFrames:state.frames,droppedFrames:state.dropped,frameErrors:state.frameErrors??[],canvasRate:12,method:'Actual CDP screencast frames encoded through browser MediaRecorder; no reenactment.'});recorder=null;}
async function close(){await stopVideo();const finished=app.waitForEvent('close',{timeout:30000});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close()).catch(e=>{if(!/closed|destroyed/i.test(String(e)))throw e;});await finished;record('normal-native-close');}
async function select(name=repo){await button(/^Switch local repository:/).click();await page.locator('.rh-list').getByRole('button',{name:new RegExp(name)}).click();if(await button('Leave editor').isVisible())await button('Leave editor').click();await until(async()=>await page.locator('.rc-identity h1').innerText()===name,'selected '+name);}
async function files(){await button('Files').click();await page.locator('.rex').waitFor();}
async function expand(name){await node(name).waitFor();const control=button('Expand '+name);if(await control.count())await control.click();}
async function expose(name){const pieces=name.split('/');for(let n=1;n<pieces.length;n++){await expand(pieces.slice(0,n).join('/'));}await node(name).scrollIntoViewIfNeeded();}
async function open(name){await expose(name);await button('More actions for '+name).click();await page.getByRole('menuitem',{name:'Open',exact:true}).click();await until(async()=>await page.getByLabel('File path',{exact:true}).count()?(await page.getByLabel('File path',{exact:true}).inputValue())===name:(await page.locator('.rfe-file-name').innerText())===path.posix.basename(name),'open '+name);}
async function edit(){if(await button('Edit this file').count())await button('Edit this file').click();await page.locator('.cm-content[contenteditable=true]').waitFor();}
async function append(text){const cm=page.locator('.cm-content[contenteditable=true]');await cm.click();await cm.press('Meta+ArrowDown');await page.keyboard.insertText(text);}
async function settled(){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.locator('.rfe-import-progress').waitFor({state:'hidden',timeout:60000});await until(async()=>await page.locator('.rfe-sidebar[inert]').count()===0&&await button('Repository file actions').isEnabled(),'management and refresh settled',60000);}
async function drag(paths,destination,{name='drag',reject=false}={}){
 for(const source of paths)await expose(source);if(destination)await expose(destination);
 if(paths.length>1){await node(paths[0]).locator('.rex-name').click();for(const source of paths.slice(1))await node(source).locator('.rex-name').click({modifiers:['Meta']});}
 await until(async()=>await page.locator('.rfe-sidebar[inert]').count()===0&&await node(paths[0]).getAttribute('draggable')==='true','selection activation settled');await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const before=await page.evaluate(()=>window.__asmbQaDrops.length),start=await node(paths[0]).boundingBox();assert.ok(start);
 await page.mouse.move(start.x+Math.min(90,start.width-20),start.y+start.height/2);await page.mouse.down();await page.mouse.move(start.x+110,start.y+start.height/2+3,{steps:5});
 const target=destination?node(destination):page.locator('.rex-root-drop');await target.waitFor();const box=await target.boundingBox();assert.ok(box);await page.mouse.move(box.x+Math.min(95,box.width/2),box.y+box.height/2,{steps:18});await page.mouse.move(box.x+Math.min(96,box.width/2+1),box.y+box.height/2,{steps:2});await new Promise(r=>setTimeout(r,150));await snapshotBounds(name+'-hover');if(reject){const blocked=Boolean(await page.locator('.rex-drag-preview.is-blocked').count());assert.ok(blocked,'Blocked gesture feedback');}else{assert.equal((await page.locator('.rex-drag-preview').innerText()).trim(),`Move ${paths.length} item${paths.length===1?'':'s'} to ${destination||'repository root'}`,'Valid drag preview must match the actual destination');assert.equal(await(destination?node(destination):page.locator('.rex-root-drop')).evaluate(element=>element.classList.contains(element.matches('.rex-root-drop')?'is-over':'is-drop-target')),true,'Valid destination must be highlighted consistently');}await page.mouse.up();
 const observed=await page.evaluate(index=>window.__asmbQaDrops.slice(index),before);assert.ok(observed.some(e=>e.kind==='dragstart'&&e.trusted),'Actual browser dragstart required');record('mouse-drag',{paths,destination,reject,events:observed});await settled();
}
async function externalDrop(paths,destination,{name='external',outside=false,readOnly=false,settle=true}={}){
 await page.locator('.rfe-import-progress').waitFor({state:'hidden'});await until(async()=>await page.locator('.rfe-sidebar[inert]').count()===0,'previous import UI settled');await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const target=outside?page.locator('.rfe-main'):destination?node(destination):page.locator('.rex-viewport');if(destination&&!outside)await expose(destination);const box=await target.boundingBox();assert.ok(box);let point={x:box.x+Math.min(110,box.width/2),y:box.y+(outside?60:destination?box.height/2:Math.min(box.height-12,80))};
 const payload={items:[],files:paths,dragOperationsMask:1};const before=await page.evaluate(()=>window.__asmbQaDrops.length);await cdp.send('Input.dispatchDragEvent',{type:'dragEnter',...point,data:payload});await cdp.send('Input.dispatchDragEvent',{type:'dragOver',...point,data:payload});
 if(!outside&&!destination){const rootTarget=page.locator('.rex-root-drop');await rootTarget.waitFor();const rootBox=await rootTarget.boundingBox();point={x:rootBox.x+rootBox.width/2,y:rootBox.y+rootBox.height/2};await cdp.send('Input.dispatchDragEvent',{type:'dragOver',...point,data:payload});}
 await snapshotBounds(name+'-hover');await cdp.send('Input.dispatchDragEvent',{type:'drop',...point,data:payload});const observed=await page.evaluate(index=>window.__asmbQaDrops.slice(index),before);assert.ok(observed.some(e=>e.trusted&&(outside||readOnly?e.kind==='dragenter'&&e.types.includes('Files'):e.kind==='drop'&&e.files.length===paths.length)),'Chromium-backed trusted Files delivery required');record('external-os-backed-files-drop',{paths:paths.map(p=>path.relative(output,p)),destination,outside,events:observed,method:'CDP Input.dispatchDragEvent with physical generated paths; not synthetic JS File and not manual Finder.'});if(settle)await settled();
}
async function snapshotBounds(name){const bounds=await page.evaluate(()=>{const select=s=>{const rows=[...document.querySelectorAll(s)].map(e=>e.getBoundingClientRect()).filter(r=>r.width>0&&r.height>0);if(!rows.length)return null;const x=Math.min(...rows.map(r=>r.x)),y=Math.min(...rows.map(r=>r.y));return{selector:s,x,y,width:Math.max(...rows.map(r=>r.right))-x,height:Math.max(...rows.map(r=>r.bottom))-y};};return{dragPreviewText:document.querySelector('.rex-drag-preview')?.textContent??null,viewport:{width:innerWidth,height:innerHeight},V3:select('.rt-bar'),V4:select('.rfe-sidebar-header, .rfe-sidebar .fnc'),V5:select('.rfe-tree'),rootDrop:select('.rex-root-drop'),dragPreview:select('.rex-drag-preview'),internalTarget:select('.rex-node.is-drop-target'),externalTarget:select('.rex-node.is-external-drop-target'),rows:[...document.querySelectorAll('.rex-node')].map(e=>{const r=e.getBoundingClientRect();return{path:e.getAttribute('data-explorer-path'),x:r.x,y:r.y,width:r.width,height:r.height};})};});await fs.writeFile(path.join(output,name+'-bounds.json'),JSON.stringify(bounds,null,2));await screenshot(name);if(name==='v5-internal-moves'||name==='v5-implemented-only'||name==='v5-narrow'||name==='internal-root-hover'||name==='external-large-and-folder-hover')await overlayBounds(name,bounds);}
async function overlayBounds(name,bounds){
 const areas=Object.entries(bounds).filter(([key,value])=>!['viewport','rows','dragPreviewText'].includes(key)&&value&&value.width>0&&value.height>0);
 await page.evaluate(areas=>{const layer=document.createElement('div');layer.id='asmb-qa-area-overlay';layer.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:2147483647';const colors=['#ffbf47','#6ae3ff','#b99cff','#79e4a8','#ff8cb7'];areas.forEach(([label,r],index)=>{const color=colors[index%colors.length],box=document.createElement('div');box.style.cssText=`position:fixed;box-sizing:border-box;left:${r.x}px;top:${r.y}px;width:${r.width}px;height:${r.height}px;border:2px solid ${color};background:${color}10;`;const badge=document.createElement('span');badge.textContent=label;badge.style.cssText=`position:absolute;left:2px;top:2px;background:#15181e;color:${color};font:700 12px system-ui;padding:3px 5px;border-radius:3px`;box.append(badge);layer.append(box);});const legend=document.createElement('div');legend.textContent='Current native UI · V3 repository tabs · V4 sidebar controls · V5 Explorer. Measured DOM boundaries; source screenshot retained.';legend.style.cssText='position:fixed;bottom:8px;right:8px;max-width:55vw;padding:8px;background:#15181eee;color:white;font:12px system-ui';layer.append(legend);document.body.append(layer);},areas);
 try{await page.screenshot({path:path.join(output,name+'-overlay.png')});record('measured-dom-overlay',{raw:name+'.png',overlay:name+'-overlay.png',bounds:name+'-bounds.json'});}finally{await page.evaluate(()=>document.getElementById('asmb-qa-area-overlay')?.remove());}
}

try{
 await launch();await startVideo();await button('Create new options').click();await button('Import repository').click();await page.getByLabel('ZIP archive',{exact:true}).setInputFiles(zip);await page.getByLabel('Repository name',{exact:true}).fill(repo);await page.locator('.zi-dialog').getByRole('button',{name:'Import repository',exact:true}).click();await page.locator('.zi-dialog').waitFor({state:'detached',timeout:60000});await select();git('tag','qa-before-moves');record('head-before-drops',{head:git('rev-parse','HEAD')});await files();await open('source/note.md');await edit();await append('Private dragged draft');
 const intended=page.getByLabel('File path',{exact:true});await intended.fill('source/intended.md');const beforeIntent=await inventory(workspace);await drag(['source/note.md'],'empty-target',{name:'filename-intent-refusal'});await until(async()=>/Save or revert filename changes/.test(await page.locator('body').innerText()),'filename intent refusal');assert.deepEqual(await inventory(workspace),beforeIntent);assert.equal(await intended.inputValue(),'source/intended.md');await intended.fill('source/note.md');record('filename-intent-blocks-move-without-clearing-draft');
 await drag(['source/note.md'],'target',{name:'internal-collision',reject:true});assert.equal(await fs.readFile(workspace+'/source/note.md','utf8'),inputs['source/note.md']);assert.equal(await fs.readFile(workspace+'/target/note.md','utf8'),inputs['target/note.md']);
 await drag(['source/note.md'],'empty-target',{name:'internal-draft-file'});await until(()=>exists(workspace+'/empty-target/note.md'),'moved draft source');assert.equal(await exists(workspace+'/source/note.md'),false);assert.equal(await fs.readFile(workspace+'/empty-target/note.md','utf8'),inputs['source/note.md']);assert.match(await page.locator('.cm-content').innerText(),/Private dragged draft/);
 await drag(['root-a.md','root-b.md'],'target',{name:'internal-multiselect'});await until(()=>exists(workspace+'/target/root-b.md'),'multi move');for(const file of ['root-a.md','root-b.md']){assert.equal(await exists(workspace+'/'+file),false);assert.equal(await fs.readFile(workspace+'/target/'+file,'utf8'),inputs[file]);}
 await drag(['source/nested'],'target',{name:'internal-folder'});await until(()=>exists(workspace+'/target/nested/deep/leaf.txt'),'nested move');await drag(['target/nested'],'',{name:'internal-root'});await until(()=>exists(workspace+'/nested/deep/leaf.txt'),'root move');
 await expand('nested');const beforeInvalid=await inventory(workspace);await drag(['nested'],'nested/deep',{name:'internal-descendant',reject:true});await new Promise(r=>setTimeout(r,200));assert.deepEqual(await inventory(workspace),beforeInvalid);await drag(['target/root-a.md'],'target',{name:'internal-noop',reject:true});await new Promise(r=>setTimeout(r,200));assert.deepEqual(await inventory(workspace),beforeInvalid);
 await drag(['source/empty'],'',{name:'internal-empty-folder'});await until(()=>exists(workspace+'/empty'),'empty folder moved');assert.deepEqual(await fs.readdir(workspace+'/empty'),[]);await snapshotBounds('v5-internal-moves');record('internal-files-multiselect-folders-root-and-guards');
 // Exact historical-ref gesture checks use the same visible tree and remain read-only.
 await open('README.md');await button(/^Switch branches\/tags:/).click();await page.getByRole('tab',{name:'Tags',exact:true}).click();await page.locator('.rp-list').getByRole('button',{name:'qa-before-moves',exact:true}).click();await until(()=>node('root-a.md').count(),'historical tree');const worktreeBeforeReadonly=await inventory(workspace);await expose('root-a.md');const src=await node('root-a.md').boundingBox(),dest=await node('target').boundingBox();await page.mouse.move(src.x+80,src.y+16);await page.mouse.down();await page.mouse.move(dest.x+80,dest.y+16,{steps:15});await page.mouse.up();await new Promise(r=>setTimeout(r,200));assert.deepEqual(await inventory(workspace),worktreeBeforeReadonly);await externalDrop([external+'/outside.txt'],'target',{name:'historical-external-refusal',readOnly:true});await new Promise(r=>setTimeout(r,200));assert.deepEqual(await inventory(workspace),worktreeBeforeReadonly);record('historical-tag-does-not-move-or-copy-into-worktree');await button(/^Switch branches\/tags:/).click();await page.getByRole('tab',{name:'Branches',exact:true}).click();await page.locator('.rp-list').getByRole('button',{name:/main/}).click();await until(()=>node('empty-target').count(),'current tree');
 await open('README.md');await edit();await append('Private collision target draft');const savedReadme=await fs.readFile(workspace+'/README.md','utf8');await externalDrop([external+'/README.md'],'',{name:'external-dirty-collision'});await until(async()=>(await fs.readdir(workspace)).filter(n=>/^README.+\.md$/.test(n)).length>0,'keep-both README');assert.equal(await fs.readFile(workspace+'/README.md','utf8'),savedReadme);assert.match(await page.locator('.cm-content').innerText(),/Private collision target draft/);
 const beforeCancelled=await inventory(workspace);await externalDrop([external+'/cancel-batch'],'',{name:'external-cancel-before-publication',settle:false});await page.locator('.rfe-import-progress').getByRole('button',{name:'Cancel',exact:true}).click();await until(async()=>/Import cancelled/.test(await page.locator('body').innerText()),'cancellation terminal status',60000);assert.deepEqual(await inventory(workspace),beforeCancelled);assert.equal(await exists(workspace+'/cancel-batch'),false);assert.deepEqual(await inventory(external),externalBefore);record('cancel-before-publication-preserves-source-and-destination');
 await externalDrop([external+'/large.pdf',external+'/bundle'],'target',{name:'external-large-and-folder'});await until(()=>exists(workspace+'/target/bundle/empty'),'nested external copy');assert.equal(await sha(workspace+'/target/large.pdf'),await sha(external+'/large.pdf'));assert.equal(await fs.readFile(workspace+'/target/bundle/nested/leaf.txt','utf8'),'External nested bytes Ω\n');assert.deepEqual(await fs.readdir(workspace+'/target/bundle/empty'),[]);
 await externalDrop([external+'/a/same.txt',external+'/b/same.txt'],'target',{name:'external-same-basename'});await until(async()=>(await fs.readdir(workspace+'/target')).filter(n=>n.startsWith('same')).length===2,'two keep-both files');const duplicateNames=(await fs.readdir(workspace+'/target')).filter(n=>n.startsWith('same'));assert.deepEqual((await Promise.all(duplicateNames.map(n=>fs.readFile(workspace+'/target/'+n,'utf8')))).sort(),['First same name\n','Second same name\n'].sort());record('external-copies-keep-both-large-nested-empty',{duplicateNames});await drag(['source/second.md'],'empty-target',{name:'internal-after-external-drop'});await until(()=>exists(workspace+'/empty-target/second.md'),'internal drag after external copies');assert.equal(await fs.readFile(workspace+'/empty-target/second.md','utf8'),inputs['source/second.md']);record('external-to-internal-drag-backend-cleanup');
 const beforeOutside=await inventory(workspace),url=page.url();await externalDrop([external+'/outside.txt'],'',{name:'outside-tree',outside:true});await new Promise(r=>setTimeout(r,200));assert.equal(page.url(),url);assert.deepEqual(await inventory(workspace),beforeOutside);record('outside-tree-drop-does-not-navigate-or-copy');
 const visibility=page.getByRole('switch',{name:'Hide unavailable functions'});await visibility.click();await snapshotBounds('v5-implemented-only');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(390,760));await page.locator('.rfe-sidebar').waitFor({state:'hidden'});await button('Toggle file sidebar').click();await page.locator('.rfe-sidebar').waitFor();await snapshotBounds('v5-narrow');await externalDrop([external+'/outside.txt'],'',{name:'external-narrow-implemented-only'});await until(()=>exists(workspace+'/outside.txt'),'narrow implemented-only root copy');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,1000));
 assert.equal(git('rev-parse','HEAD'),events.find(e=>e.name==='head-before-drops').head);record('drops-do-not-create-commits');
 await button('Review saved changes…').click();const commit=page.locator('.rfe-commit-dialog[open]').filter({has:page.getByRole('heading',{name:'Commit changes',exact:true})});await commit.getByLabel('Commit message',{exact:true}).fill('Qualify one copied binary');await commit.getByLabel('Local author name',{exact:true}).fill('Drag Drop QA');await commit.getByLabel('Local author email',{exact:true}).fill('drag-drop-qa@example.invalid');for(const label of await commit.locator('.rfe-change-selection label').all()){const text=await label.locator('span').innerText();await label.locator('input').setChecked(text.startsWith('target/large.pdf '));}await commit.getByRole('button',{name:'Refresh review',exact:true}).click();await until(()=>commit.getByRole('button',{name:'Commit changes',exact:true}).isEnabled(),'selected copied binary reviewed');const beforeCommit=git('rev-parse','HEAD');await commit.getByRole('button',{name:'Commit changes',exact:true}).click();await until(()=>git('rev-parse','HEAD')!==beforeCommit,'explicit selected local commit');await commit.waitFor({state:'hidden'});const committed=git('rev-parse','HEAD');assert.equal(git('diff-tree','--no-commit-id','--name-only','-r',committed),'target/large.pdf');assert.equal(git('show','-s','--format=%an <%ae>',committed),'Drag Drop QA <drag-drop-qa@example.invalid>');assert.equal(git('show',committed+':README.md'),initial.trim());assert.equal(git('remote'),'');record('explicit-one-copied-binary-commit-excludes-other-copies-and-drafts',{head:committed,path:'target/large.pdf'});assert.deepEqual(await inventory(external),externalBefore);await close();await launch();await select();await files();await open('empty-target/note.md');await edit();assert.match(await page.locator('.cm-content').innerText(),/Private dragged draft/);assert.equal(await fs.readFile(workspace+'/empty-target/note.md','utf8'),inputs['source/note.md']);assert.equal(git('rev-parse','HEAD'),events.find(e=>e.name==='explicit-one-copied-binary-commit-excludes-other-copies-and-drafts').head);record('moved-private-draft-and-external-copies-survive-restart');
 // Empty tree: generated default repository only, with its README retained in Trash.
 await select('Workspace');await files();await button('More actions for README.md').click();await page.getByRole('menuitem',{name:'Move to Trash',exact:true}).click();await page.locator('.rfe-management-dialog').getByRole('button',{name:'Move to Trash',exact:true}).click();await until(()=>page.locator('.rex-empty').count(),'empty tree');await externalDrop([external+'/empty-tree.txt'],'',{name:'external-empty-tree'});await until(()=>exists(data+'/workspaces/asMagicBrain/Workspace/empty-tree.txt'),'empty-tree copied file');record('external-copy-into-empty-tree');
 await select();await files();await externalDrop([external+'/closing-batch'],'',{name:'close-during-copy',settle:false});const start=Date.now();let closed=false;const onClosed=()=>{closed=true;};app.once('close',onClosed);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close()).catch(e=>{if(!/closed|destroyed/i.test(String(e)))throw e;});await until(async()=>closed||await exists(workspace+'/closing-batch/file-79.bin'),'accepted copy close outcome',30000);if(!closed){await until(async()=>await page.locator('.rfe [inert]').count()===0,'copy complete before retry close',30000);await close();}else record('native-close-drained-accepted-copy',{elapsedMs:Date.now()-start});
 await launch();await select();await files();for(let i=0;i<80;i++)assert.equal(await sha(workspace+`/closing-batch/file-${i}.bin`),await sha(external+`/closing-batch/file-${i}.bin`));assert.deepEqual(await inventory(external),externalBefore);assert.equal(errors.length,0);assert.equal(consoleErrors.length,0);assert.equal(requests.length,0);record('accepted-external-copy-complete-after-native-close-restart');await close();
}catch(error){failure={message:error.message,stack:error.stack};console.error(error.stack);try{await screenshot('failure');await fs.writeFile(path.join(output,'failure-dom.txt'),await page.locator('body').innerText());await stopVideo();}catch{}try{if(app)await close();}catch{}process.exitCode=1;}
finally{await fs.writeFile(path.join(output,'receipt.json'),JSON.stringify({status:failure?'failed':'passed',failure,metadata,executable,data,events,errors,consoleErrors,requests,definitionSha256:await sha(fileURLToPath(import.meta.url))},null,2));console.log(JSON.stringify({status:failure?'failed':'passed',output}));}
