/** Targeted native parity check; all data stays in a fresh disposable Test root. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {appRoot,createDriver,testRoot,until,sha,nativeTarget} from './native-driver.mjs';
await fs.mkdir(testRoot,{recursive:true});const run=await fs.mkdtemp(path.join(testRoot,'import-modes-')),dataRoot=path.join(run,'data'),repo='Mode-Import-QA',workspacePath=path.join(dataRoot,'workspaces/asMagicBrain',repo);
const driver=await createDriver({...nativeTarget(dataRoot),output:run,workspacePath});
const fixture=path.join(run,'zip-source');await fs.mkdir(fixture);const content='# Implemented mode import\n';await fs.writeFile(path.join(fixture,'README.md'),content);const zip=path.join(run,'mode-import.zip');execFileSync('/usr/bin/zip',['-q',zip,'README.md'],{cwd:fixture});
const candidate=[];async function capture(relative){for(const entry of await fs.readdir(path.join(appRoot,relative),{withFileTypes:true})){if(entry.name.startsWith('.')||entry.name==='node_modules')continue;const name=path.posix.join(relative,entry.name);if(entry.isDirectory())await capture(name);else if(entry.isFile())candidate.push({path:name,sha256:sha(await fs.readFile(path.join(appRoot,name)))});}}for(const root of ['apps/native','apps/desktop/ui/shared','packages','ui-workshop/src'])await capture(root);await fs.writeFile(path.join(run,'candidate-source.json'),JSON.stringify({at:new Date().toISOString(),files:candidate},null,2));
const button=(page,name)=>page.getByRole('button',{name,exact:true});let page,failure;
try{
 page=await driver.launch();await button(page,'README.md').first().waitFor();const toggle=page.getByRole('switch',{name:'Hide unavailable functions'});assert.equal(await toggle.getAttribute('aria-checked'),'false');await button(page,'Create new options').click();const menu=page.locator('.ra-menu-create');await button(page,'Import repository').waitFor();assert.equal(await menu.getByRole('button',{name:'New repository',exact:true}).isVisible(),true);assert.equal(await menu.getByRole('button',{name:'New repository',exact:true}).isDisabled(),false);await driver.screenshot('01-full-mode-menu');await page.keyboard.press('Escape');
 await toggle.click();await until(async()=>await toggle.getAttribute('aria-checked')==='true');assert.equal(await button(page,'Create new options').isVisible(),true);assert.equal(await button(page,'Ask agent options').isVisible(),false);await button(page,'Create new options').click();assert.deepEqual(await menu.locator('button:visible').allTextContents(),['New repository','Import repository']);await driver.screenshot('02-implemented-mode-menu');await button(page,'Dismiss action menu').click({position:{x:20,y:200}});await menu.waitFor({state:'detached'});await button(page,'Create new options').click();await button(page,'Import repository').click();await page.getByLabel('ZIP archive',{exact:true}).setInputFiles(zip);await page.getByLabel('Repository name',{exact:true}).fill(repo);await page.locator('.zi-dialog').getByRole('button',{name:'Import repository',exact:true}).click();await page.locator('.zi-dialog').waitFor({state:'detached'});await until(async()=>await fs.readFile(path.join(workspacePath,'README.md'),'utf8')===content);driver.record('implemented-mode-import-remains-available-and-placeholders-hidden');await driver.screenshot('03-imported-implemented-mode');await driver.closeNormally();
 page=await driver.launch();await button(page,'README.md').first().waitFor();assert.equal(await page.getByRole('switch',{name:'Hide unavailable functions'}).getAttribute('aria-checked'),'true');await button(page,/^Switch local repository:/).click();await page.locator('.rh-list').getByRole('button',{name:new RegExp(repo)}).click();await until(async()=>await page.locator('.rh-repository-name').innerText()===repo);assert.equal(await fs.readFile(path.join(workspacePath,'README.md'),'utf8'),content);assert.equal(await button(page,'Create new options').isVisible(),true);assert.equal(await button(page,'Ask agent options').isVisible(),false);driver.record('import-registration-and-implemented-mode-survive-restart');await driver.screenshot('04-restarted-implemented-mode');assert.equal(driver.errors.length,0);await driver.closeNormally();
}catch(error){failure={message:error.message,stack:error.stack};try{await fs.writeFile(path.join(run,'failure-dom.txt'),await page.locator('body').innerText());await driver.screenshot('failure');}catch{}console.error(error.stack);try{await driver.closeNormally();}catch{}process.exitCode=1;}
finally{await driver.report({dataRoot,status:failure?'failed':'passed',failure});console.log(JSON.stringify({output:run,status:failure?'failed':'passed'}));}
