import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {_electron} from '../../../tools/playwright.mjs';
import {testRoot} from '../../../tools/development-paths.mjs';
import {readZipFiles,extractZip} from '../../../packages/desktop-host/src/zip-import/index.mjs';
import {createPackageExchange} from '../../../packages/desktop-host/src/package-exchange/index.mjs';
import {renderOffline} from '../dist-host/offline-reader.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url));
const input=process.env.ASMB_OFFLINE_FIXTURE,output=process.env.ASMB_OFFLINE_OUTPUT;
assert(input&&path.isAbsolute(input)&&output&&path.isAbsolute(output));assert(output.startsWith(testRoot+path.sep));assert.equal(fs.realpathSync(path.dirname(output)),path.dirname(output));
fs.mkdirSync(output,{mode:0o700});for(const name of ['tmp','source','private'])fs.mkdirSync(path.join(output,name),{mode:0o700});
const files=readZipFiles(fs.readFileSync(input)).files;
extractZip(fs.readFileSync(input),{destination:path.join(output,'source')});
fs.writeFileSync(path.join(output,'source','.env'),'ASMB_TEST_SECRET=synthetic-only\n');
fs.writeFileSync(path.join(output,'source','offline-link-check.md'),'# Link checks\n[External](https://example.invalid/never-request)\n![Missing](missing.png)\n[Local chapter](math.md)\n');
const manager=createPackageExchange({sourceRoot:path.join(output,'source'),privateRoot:path.join(output,'private'),renderOffline});
const plan=await manager.reviewExport({collectionId:'neutral-engineering',version:'1'}),portable=await manager.buildExport({planId:plan.planId,kind:'source'}),offline=await manager.buildExport({planId:plan.planId,kind:'offline'});
fs.writeFileSync(path.join(output,portable.filename),portable.bytes);fs.writeFileSync(path.join(output,offline.filename),offline.bytes);
const sourceFiles=new Map(readZipFiles(portable.bytes).files.map(file=>[file.path,file.bytes]));
for(const file of files)assert.deepEqual(sourceFiles.get(file.path),file.bytes,file.path);
assert(!sourceFiles.has('.env'));assert(plan.warnings.some(w=>w.code==='SUSPECTED_CREDENTIAL_EXCLUDED'));
const unpacked=path.join(output,'original-extraction');fs.mkdirSync(unpacked,{mode:0o700});extractZip(offline.bytes,{destination:unpacked});
const relocated=path.join(output,'relocated-reader with spaces');fs.renameSync(unpacked,relocated);
const harness=path.join(output,'reader-shell.cjs');fs.writeFileSync(harness,`const {app,BrowserWindow}=require('electron');app.commandLine.appendSwitch('headless');app.commandLine.appendSwitch('disable-background-networking');app.commandLine.appendSwitch('disable-gpu');app.setPath('userData',${JSON.stringify(path.join(output,'electron-profile'))});app.whenReady().then(()=>{const win=new BrowserWindow({show:false,width:1200,height:1000,webPreferences:{offscreen:true,nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}});win.loadFile(${JSON.stringify(path.join(relocated,'index.html'))});});app.on('window-all-closed',()=>app.quit());`);
const checks=[],requests=[],errors=[],consoleErrors=[];let app;
try{
 app=await _electron.launch({executablePath:path.join(root,'.tooling/electron-44.4.0-darwin-arm64/Electron.app/Contents/MacOS/Electron'),args:[harness],cwd:output,env:{...process.env,TMPDIR:path.join(output,'tmp'),TMP:path.join(output,'tmp'),TEMP:path.join(output,'tmp'),ELECTRON_RUN_AS_NODE:undefined},timeout:60000});
 const context=app.context();await context.route('**/*',route=>{const request=route.request();requests.push(request.url());return request.url().startsWith('file:')?route.continue():route.abort();});
 const page=await app.firstWindow();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
 const versions=await app.evaluate(()=>process.versions);await page.goto(pathToFileURL(path.join(relocated,'index.html')).href);
 assert.equal(await page.title(),'Offline collection');assert(await page.getByRole('heading',{name:'Reading notes'}).count());await page.screenshot({path:path.join(output,'01-contents.png'),fullPage:true});
 await page.getByRole('link',{name:'README.md',exact:true}).click();await page.getByRole('heading',{name:'Brain engineering-document reproduction'}).waitFor();
 const image=page.locator('main img').first();await image.scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('main img')].every(img=>img.complete&&img.naturalWidth>0));
 assert(await page.locator('math').count()>=2);const mathBox=await page.locator('math').first().boundingBox();assert(mathBox&&mathBox.width>30&&mathBox.height>10);
 assert.equal(await page.locator('iframe,script,input[type=range],canvas,button').count(),0);assert(await page.getByText('Mermaid diagram — source fallback',{exact:true}).count());
 await page.screenshot({path:path.join(output,'02-readme.png'),fullPage:true});checks.push({name:'relocated file URL preserves native MathML, PNG and labelled Mermaid fallback',mathBox,image:await image.evaluate(img=>({width:img.naturalWidth,height:img.naturalHeight}))});
 await page.getByRole('link',{name:'Expanded math cases'}).click();await page.getByRole('heading').first().waitFor();const equations=await page.locator('math').count();assert(equations>=4);const matrix=await page.locator('math mtable').first().evaluate(table=>({height:table.getBoundingClientRect().height,fenceHeight:table.previousElementSibling.getBoundingClientRect().height,font:getComputedStyle(table).fontFamily}));assert(matrix.fenceHeight>=matrix.height*0.75,JSON.stringify(matrix));checks.push({name:'MathML uses an installed local math font and stretches matrix fences',matrix});await page.screenshot({path:path.join(output,'03-math.png'),fullPage:true});checks.push({name:'relative chapter link and expanded equations',equations});
 await page.goBack();await page.getByRole('link',{name:'Open the local slider'}).click();assert(await page.getByText('Source view. Executable content is not run in the offline reader.',{exact:true}).count());assert.equal(await page.locator('input,script,iframe,canvas').count(),0);assert((await page.locator('pre').textContent()).includes('<script>'));await page.screenshot({path:path.join(output,'04-html-source.png'),fullPage:true});checks.push({name:'interactive HTML escaped; no slider or imported script activated'});
 await page.goto(pathToFileURL(path.join(relocated,'reader/offline-link-check.md.html')).href);assert.equal(await page.getByRole('link',{name:'External',exact:true}).count(),0);assert(await page.getByText('Missing — image unavailable in offline reading.',{exact:true}).count());await page.screenshot({path:path.join(output,'05-missing-external.png'),fullPage:true});checks.push({name:'external links inactive and missing images explicitly labelled'});
 assert.equal(requests.filter(url=>!url.startsWith('file:')).length,0);assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);
 const styles=await page.evaluate(()=>({fontFamily:getComputedStyle(document.body).fontFamily,scripts:document.scripts.length,styleSheets:[...document.styleSheets].map(sheet=>sheet.href)}));assert(styles.styleSheets.every(href=>href.startsWith('file:')));assert.equal(styles.scripts,0);
 const receipt={status:'passed',qualification:'Fresh hidden sandboxed Electron Chromium file:// reader, not Safari/Firefox or a packaged native app claim.',versions,sourceZipSha256:createHash('sha256').update(portable.bytes).digest('hex'),offlineZipSha256:createHash('sha256').update(offline.bytes).digest('hex'),exactOriginalFiles:files.length,excluded:plan.excluded,checks,styles,requests,errors,consoleErrors,warnings:plan.warnings};fs.writeFileSync(path.join(output,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({status:'passed',checks:checks.length,versions:receipt.versions.chrome,output}));
}finally{await app?.close();}
