/** Actual native acceptance. Synthetic fixtures and receipts only under sibling Test. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const {appRoot,createDriver,testRoot,until,sha,nativeTarget} = await import(process.platform==='linux'?'./linux-driver.mjs':'./native-driver.mjs');
await fs.mkdir(testRoot,{recursive:true});
const run=await fs.mkdtemp(path.join(testRoot,'acceptance-')),dataRoot=path.join(run,process.platform==='linux'?'home/asMagicBrain':'data');
const repo='Native-QA',workspacePath=path.join(dataRoot,'workspaces/asMagicBrain',repo);
const driver=await createDriver({...nativeTarget(dataRoot),output:run,workspacePath});
const button=(p,name)=>p.getByRole('button',{name,exact:true});
const exists=async relative=>fs.access(path.join(workspacePath,relative)).then(()=>true,()=>false);
const git=(...args)=>execFileSync('/usr/bin/git',['-C',workspacePath,...args],{env:{PATH:'/usr/bin:/bin',TMPDIR:path.join(run,'tmp'),GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'},encoding:'utf8'}).trim();
const fixture=path.join(run,'zip-source');await fs.mkdir(path.join(fixture,'notes/nested'),{recursive:true});await fs.mkdir(path.join(fixture,'destination'));
const initial='\ufeff# Native operations\r\n\r\nOriginal Ω\r\n';
await fs.writeFile(path.join(fixture,'README.md'),initial);await fs.writeFile(path.join(fixture,'notes/nested/draft.md'),'# Saved source\n');await fs.writeFile(path.join(fixture,'unselected.md'),'# Not selected\n');await fs.writeFile(path.join(fixture,'destination/keep.md'),'# Destination\n');
const binary=Buffer.alloc(5*1024*1024+17);let seed=123456789;for(let i=0;i<binary.length;i++){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;binary[i]=seed&255;}await fs.writeFile(path.join(fixture,'notes/nested/large.pdf'),binary);
const zip=path.join(run,'native-qa.zip');execFileSync('/usr/bin/zip',['-q','-r',zip,'.'],{cwd:fixture});const zipHash=sha(await fs.readFile(zip));
const candidate=[];async function snapshot(relative){for(const entry of await fs.readdir(path.join(appRoot,relative),{withFileTypes:true})){if(entry.name.startsWith('.')||entry.name==='node_modules')continue;const name=path.posix.join(relative,entry.name);if(entry.isDirectory())await snapshot(name);else if(entry.isFile())candidate.push({path:name,sha256:sha(await fs.readFile(path.join(appRoot,name)))});}}for(const root of ['apps/native','apps/desktop/ui/shared','packages','ui-workshop/src'])await snapshot(root);await fs.writeFile(path.join(run,'candidate-source.json'),JSON.stringify({at:new Date().toISOString(),files:candidate},null,2));
let page,failure;
async function selectRepo(){await button(page,/^Switch local repository:/).click();await page.locator('.rh-list').getByRole('button',{name:new RegExp(repo)}).click();await button(page,'README.md').first().waitFor();}
async function action(file,name){await button(page,file===null?'Repository file actions':`More actions for ${file}`).click();await page.getByRole('menuitem',{name,exact:true}).click();}
async function openTree(file){const parts=file.split('/');for(let i=1;i<parts.length;i++){const parent=parts.slice(0,i).join('/');await button(page,`More actions for ${parent}`).waitFor();const expand=button(page,`Expand ${parent}`);if(await expand.count())await expand.click();}await action(file,'Open');await until(async()=>await page.getByLabel('File path',{exact:true}).count()?(await page.getByLabel('File path',{exact:true}).inputValue())===file:(await page.locator('.rfe-file-name').innerText())===file.split('/').at(-1),{label:'active file '+file});}
async function enterEdit(){if(await button(page,'Edit this file').count())await button(page,'Edit this file').click();await page.locator('.cm-content[contenteditable=true]').waitFor();}
async function append(text){const editor=page.locator('.cm-content[contenteditable=true]');await editor.click();await editor.press(process.platform==='darwin'?'Meta+ArrowDown':'Control+End');await page.keyboard.insertText(text);}
async function openInitial(){await button(page,'README.md').first().click();await until(()=>button(page,'Edit this file').isEnabled());}
try{
 page=await driver.launch();await button(page,'README.md').first().waitFor();await button(page,'Create new options').click();await button(page,'Import repository').click();await page.getByLabel('ZIP archive',{exact:true}).setInputFiles(zip);await page.getByLabel('Repository name',{exact:true}).fill(repo);await page.locator('.zi-dialog').getByRole('button',{name:'Import repository',exact:true}).click();await until(()=>exists('notes/nested/large.pdf'),{timeout:30000,label:'ZIP published'});await page.locator('.zi-dialog').waitFor({state:'detached'});assert.equal(sha(await fs.readFile(path.join(workspacePath,'notes/nested/large.pdf'))),sha(binary));assert.equal(sha(await fs.readFile(zip)),zipHash);assert.equal(git('rev-list','--count','HEAD'),'1');assert.equal(git('remote'), '');driver.record('native-zip-import-exact-binary-fresh-local-history',{zipHash,binarySha:sha(binary)});await driver.screenshot('01-imported');await driver.closeNormally();
 page=await driver.launch();await selectRepo();driver.record('import-registration-survives-restart');await openInitial();await driver.screenshot('02-native-file-explorer');
 await action(null,'New folder');await page.getByLabel('Folder path',{exact:true}).fill('created');await button(page,'Create folder').click();await until(()=>exists('created'));
 await action(null,'New Markdown file');await page.getByLabel('File path',{exact:true}).fill('created/new.md');await append('# Created in native UI\n');await button(page,'Save').click();await until(()=>exists('created/new.md'));driver.record('native-create-folder-and-markdown');
 await action('created/new.md','Rename');await page.getByLabel('Rename created/new.md',{exact:true}).fill('renamed.md');await page.getByLabel('Rename created/new.md',{exact:true}).press('Enter');await until(()=>exists('created/renamed.md'));assert.equal(await exists('created/new.md'),false);driver.record('inline-rename');
 await action('created/renamed.md','Duplicate');await until(()=>exists('created/renamed copy.md'));driver.record('duplicate');
 await action('created/renamed.md','Copy');await action('destination','Paste');await until(()=>exists('destination/renamed.md'));driver.record('copy-paste');
 await action('created/renamed copy.md','Move to…');await page.getByLabel('Destination folder',{exact:true}).fill('destination');await page.locator('.rfe-management-dialog').getByRole('button',{name:'Move',exact:true}).click();await until(()=>exists('destination/renamed copy.md'));assert.equal(await exists('created/renamed copy.md'),false);driver.record('move-file');
 await openTree('notes/nested/draft.md');await enterEdit();await append('Private unsaved marker Ω');
 await action('notes','Move to Trash');await page.locator('.rfe-management-dialog').getByRole('button',{name:'Move to Trash',exact:true}).click();await until(async()=>!(await exists('notes')));driver.record('trash-recursive-folder-with-large-binary-and-draft');
 await action(null,'Restore from Trash…');await page.locator('.rfe-trash-list li').filter({hasText:'notes'}).getByRole('button',{name:'Restore',exact:true}).click();await until(()=>exists('notes/nested/large.pdf'));await page.locator('.rfe-management-dialog').getByRole('button',{name:'Close',exact:true}).click();assert.equal(sha(await fs.readFile(path.join(workspacePath,'notes/nested/large.pdf'))),sha(binary));
 await action('notes','Rename');await page.getByLabel('Rename notes',{exact:true}).fill('restored-notes');await page.getByLabel('Rename notes',{exact:true}).press('Enter');await until(()=>exists('restored-notes/nested/draft.md'));await openTree('restored-notes/nested/draft.md');await enterEdit();assert.match(await page.locator('.cm-content').innerText(),/Private unsaved marker Ω/);assert.equal(await page.getByLabel('File path',{exact:true}).inputValue(),'restored-notes/nested/draft.md');assert.equal(await fs.readFile(path.join(workspacePath,'restored-notes/nested/draft.md'),'utf8'),'# Saved source\n');driver.record('restore-and-rename-do-not-publish-private-draft');await button(page,'Save').click();await until(async()=> (await fs.readFile(path.join(workspacePath,'restored-notes/nested/draft.md'),'utf8')).includes('Private unsaved marker Ω'));driver.record('restore-then-rename-before-open-preserves-draft-and-path');await driver.screenshot('03-managed-draft');
 await action('restored-notes/nested/large.pdf','Move to Trash');await page.locator('.rfe-management-dialog').getByRole('button',{name:'Move to Trash',exact:true}).click();await until(async()=>!(await exists('restored-notes/nested/large.pdf')));await action(null,'Restore from Trash…');await page.locator('.rfe-trash-list li').filter({hasText:'restored-notes/nested/large.pdf'}).getByRole('button',{name:'Restore',exact:true}).click();await until(()=>exists('restored-notes/nested/large.pdf'));await page.locator('.rfe-management-dialog').getByRole('button',{name:'Close',exact:true}).click();assert.equal(sha(await fs.readFile(path.join(workspacePath,'restored-notes/nested/large.pdf'))),sha(binary));driver.record('standalone-large-binary-trash-and-restore-exact-bytes');
 await append(' Private draft excluded from commits');
 await openTree('unselected.md');await enterEdit();await append('Saved but unselected');await button(page,'Save').click();await until(async()=> (await fs.readFile(path.join(workspacePath,'unselected.md'),'utf8')).includes('Saved but unselected'));
 await button(page,'Account menu').click();await page.getByRole('menuitem',{name:'Settings',exact:true}).click();await page.getByRole('radio',{name:/asMagicBrain profile/}).check();await page.getByLabel('Author name',{exact:true}).fill('Native QA Writer');await page.getByLabel('Author email',{exact:true}).fill('native-qa@example.invalid');await button(page,'Save settings').click();await page.locator('.ac-settings').waitFor({state:'detached'});driver.record('synthetic-author-preference-saved-through-native-ui');
 await button(page,'Review saved changes…').click();const form=page.locator('.rfe-commit-dialog[open]').filter({has:page.getByRole('heading',{name:'Commit changes',exact:true})});await form.getByLabel('Commit message',{exact:true}).fill('Native selected files acceptance');assert.equal(await form.getByLabel('Local author name',{exact:true}).inputValue(),'Native QA Writer');assert.equal(await form.getByLabel('Local author email',{exact:true}).inputValue(),'native-qa@example.invalid');
 const selected=['created/renamed.md','destination/renamed.md','notes/nested/large.pdf','restored-notes/nested/large.pdf'];for(const label of await form.locator('.rfe-change-selection label').all()){const text=await label.locator('span').innerText();await label.locator('input').setChecked(selected.some(file=>text.startsWith(file+' ')));}await form.getByRole('button',{name:'Refresh review',exact:true}).click();await until(()=>form.getByRole('button',{name:'Commit changes',exact:true}).isEnabled());await driver.screenshot('04-selected-local-commit');const before=git('rev-parse','HEAD');await form.getByRole('button',{name:'Commit changes',exact:true}).click();await until(()=>git('rev-parse','HEAD')!==before);await form.waitFor({state:'hidden'});const after=git('rev-parse','HEAD');assert.deepEqual(git('diff-tree','--no-commit-id','--name-only','-r',after).split('\n').sort(),selected.sort());assert.equal(git('show','-s','--format=%an <%ae>',after),'Native QA Writer <native-qa@example.invalid>');assert.equal(git('show',after+':unselected.md'),'# Not selected');assert.equal(git('show',after+':notes/nested/draft.md'),'# Saved source');assert.equal(sha(execFileSync('/usr/bin/git',['-C',workspacePath,'show',after+':restored-notes/nested/large.pdf'],{maxBuffer:8*1024*1024})),sha(binary));assert.equal(git('remote'),'');driver.record('selected-local-commit-excludes-unselected-and-private-draft',{head:after,paths:selected,author:'Native QA Writer <native-qa@example.invalid>'});
 await driver.closeNormally();page=await driver.launch();await selectRepo();await openInitial();await openTree('restored-notes/nested/draft.md');await enterEdit();assert.match(await page.locator('.cm-content').innerText(),/Private draft excluded from commits/);assert.ok(!(await fs.readFile(path.join(workspacePath,'restored-notes/nested/draft.md'),'utf8')).includes('Private draft excluded from commits'));assert.equal(git('rev-parse','HEAD'),after);await button(page,'Account menu').click();await page.getByRole('menuitem',{name:'Settings',exact:true}).click();assert.equal(await page.getByLabel('Author name',{exact:true}).inputValue(),'Native QA Writer');assert.equal(await page.getByLabel('Author email',{exact:true}).inputValue(),'native-qa@example.invalid');await button(page,'Close settings').click();driver.record('restart-preserves-registration-author-head-and-private-draft');await driver.screenshot('05-restarted-private-draft');
 await button(page,'Account menu').click();await page.getByRole('menuitem',{name:'Settings',exact:true}).click();await page.getByRole('radio',{name:/Manual each commit/}).check();await button(page,'Save settings').click();await page.locator('.ac-settings').waitFor({state:'detached'});await openTree('unselected.md');await enterEdit();await button(page,'Commit changes…').click();const manual=page.locator('.rfe-commit-dialog[open]').filter({has:page.getByRole('heading',{name:'Commit changes',exact:true})});assert.equal(await manual.getByLabel('Local author name',{exact:true}).inputValue(),'');assert.equal(await manual.getByLabel('Local author email',{exact:true}).inputValue(),'');await manual.getByLabel('Commit message',{exact:true}).fill('Explicit manual author acceptance');await manual.getByRole('button',{name:'Commit changes',exact:true}).click();assert.equal(git('rev-parse','HEAD'),after);assert.ok(await manual.isVisible());assert.equal(await manual.getByLabel('Local author name',{exact:true}).evaluate(input=>input.validity.valueMissing),true);await manual.getByLabel('Local author name',{exact:true}).fill('Manual QA Writer');await manual.getByLabel('Local author email',{exact:true}).fill('manual-qa@example.invalid');await driver.screenshot('06-manual-author-required');await manual.getByRole('button',{name:'Commit changes',exact:true}).click();await until(()=>git('rev-parse','HEAD')!==after);await manual.waitFor({state:'hidden'});const manualHead=git('rev-parse','HEAD');assert.equal(git('show','-s','--format=%an <%ae>',manualHead),'Manual QA Writer <manual-qa@example.invalid>');assert.equal(git('diff-tree','--no-commit-id','--name-only','-r',manualHead),'unselected.md');assert.equal(git('rev-list','--count','HEAD'),'3');driver.record('manual-mode-requires-explicit-author-one-file-commit',{head:manualHead,author:'Manual QA Writer <manual-qa@example.invalid>'});await driver.closeNormally();page=await driver.launch();await selectRepo();await button(page,'Account menu').click();await page.getByRole('menuitem',{name:'Settings',exact:true}).click();assert.equal(await page.getByRole('radio',{name:/Manual each commit/}).isChecked(),true);await button(page,'Close settings').click();assert.equal(git('rev-parse','HEAD'),manualHead);driver.record('manual-author-mode-and-second-commit-survive-restart');assert.equal(driver.errors.length,0);await driver.closeNormally();
}catch(error){failure={message:error.message,stack:error.stack};try{await fs.writeFile(path.join(run,'failure-dom.txt'),await page.locator('body').innerText());await driver.screenshot('failure');}catch{}console.error(error.stack);try{await driver.closeNormally();}catch{}process.exitCode=1;}
finally{await driver.report({dataRoot,status:failure?'failed':'passed',failure,zipHash});console.log(JSON.stringify({output:run,status:failure?'failed':'passed'}));}
