import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createDriver,nativeTarget,testRoot,until} from './native-driver.mjs';
const run=testRoot;
const output=await fs.mkdtemp(path.join(run,'native-presentation-'));
const data=path.join(output,'data');await fs.mkdir(data,{mode:0o700});
const repo=path.join(data,'workspaces/asMagicBrain/Workspace');
const driver=await createDriver({...nativeTarget(data),output,workspacePath:repo});
try{
 let page=await driver.launch();await page.getByRole('heading',{name:'Workspace',exact:true}).first().waitFor();await driver.closeNormally();
 await fs.mkdir(path.join(repo,'classes'),{mode:0o700});
 await fs.writeFile(path.join(repo,'fixture.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a6nQAAAAASUVORK5CYII=','base64'));
 await fs.writeFile(path.join(repo,'README.md'),'# Presentation fixture\n\n## Introduction\n\nOpen [Class 01](classes/Class01.md). [Later](#later-section). [Missing](classes/missing.md).\n\n## Later section\n\n中文课程内容.\n\n'+Array.from({length:60},(_,n)=>`Paragraph ${n}. Course evidence and discussion.\n\n`).join(''));
 await fs.writeFile(path.join(repo,'classes/Class01.md'),'# Class 01\n\n## Activity\n\nStudent class fixture.\n\n![中文示意图](../fixture.png)\n\n$$\nx^2+y^2=1\n$$\n\n```mermaid\ngraph LR\n A[数据] --> B[模型]\n```\n');
 page=await driver.launch();await page.getByRole('button',{name:'README.md',exact:true}).first().click();await page.getByRole('button',{name:'Edit this file',exact:true}).click();
 await page.locator('.cm-content').first().waitFor();
 await page.locator('.cm-content').first().press('Meta+End');
 await page.keyboard.insertText('\n\n未保存的教学草稿.');
 await page.locator('.cm-content').first().press('Meta+Home');
 await page.getByRole('tab',{name:'Split',exact:true}).click();
 const original=await page.locator('.cm-content').first().evaluate(node=>({source:node.cmTile.root.view.state.doc.toString(),selection:node.cmTile.root.view.state.selection.toJSON()}));
 await page.getByRole('button',{name:'Present',exact:true}).click();await page.getByRole('dialog',{name:'Document presentation'}).waitFor();
 await until(()=>driver.app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(window=>!window.getParentWindow()).isFullScreen()),{label:'native presentation fullscreen'});
 assert.equal(await page.locator('.document-presentation header,.document-presentation footer').count(),0);
 await page.locator('.document-presentation-content').press('Meta+=');
 assert.equal(await page.locator('.document-presentation').evaluate(node=>node.style.getPropertyValue('--presentation-size')),'26px');
 await page.locator('.document-presentation-content').press('m');await page.locator('.document-presentation-content').press('m');await page.locator('.document-presentation-content').press('ArrowRight');
 await page.locator('.document-presentation').getByRole('heading',{name:'Introduction',exact:true}).waitFor();
 await page.locator('.document-presentation').getByRole('link',{name:'Missing',exact:true}).click();
 await page.locator('.document-presentation-notice').waitFor();
 await page.locator('.document-presentation').getByRole('heading',{name:'Introduction',exact:true}).waitFor();
 await page.locator('.document-presentation').getByRole('link',{name:'Later',exact:true}).click();
 await page.locator('.document-presentation').getByRole('heading',{name:'Later section',exact:true}).waitFor();
 await page.locator('.document-presentation-content').press('ArrowLeft');
 await page.locator('.document-presentation').getByRole('link',{name:'Class 01',exact:true}).click();await page.locator('.document-presentation').getByRole('heading',{name:'Class 01',exact:true}).waitFor();
 await page.locator('.document-presentation-content').press('ArrowRight');
 await page.locator('.document-presentation .katex').first().waitFor();
 await page.locator('.document-presentation [data-mermaid-diagram] svg').first().waitFor();
 await until(()=>page.locator('.document-presentation img').first().evaluate(node=>node.complete&&node.naturalWidth===1&&node.src.startsWith('blob:')),{label:'admitted local Chinese image decoded'});
 await driver.screenshot('presentation-class');
 await page.locator('.document-presentation-content').press('?');await page.getByRole('button',{name:'Back to previous document'}).click();await page.locator('.document-presentation').getByRole('heading',{name:'Introduction',exact:true}).waitFor();
 await page.getByRole('button',{name:'Use Pages',exact:true}).click();await page.getByRole('button',{name:'Use Document',exact:true}).click();
 await page.keyboard.press('Escape');
 await until(()=>page.locator('.document-presentation-content').evaluate(node=>node===document.activeElement),{label:'Escape restores focus from temporary controls'});
 await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Document presentation'}).waitFor({state:'detached'});
 await until(()=>driver.app.evaluate(({BrowserWindow})=>!BrowserWindow.getAllWindows().find(window=>!window.getParentWindow()).isFullScreen()),{label:'native original window restored'});
 const returned=await page.locator('.cm-content').first().evaluate(node=>({source:node.cmTile.root.view.state.doc.toString(),selection:node.cmTile.root.view.state.selection.toJSON()}));assert.deepEqual(returned,original);
 assert.equal(await page.getByRole('tab',{name:'Split',exact:true}).getAttribute('aria-selected'),'true');
 await page.locator('.cm-content').first().press('Meta+z');
 await until(async()=>!(await page.locator('.cm-content').first().evaluate(node=>node.cmTile.root.view.state.doc.toString())).includes('未保存的教学草稿.'),{label:'draft undo retained'});
 await page.locator('.cm-content').first().press('Meta+Shift+z');
 await until(async()=>(await page.locator('.cm-content').first().evaluate(node=>node.cmTile.root.view.state.doc.toString()))===original.source,{label:'draft redo retained'});
 for(const mode of ['Source','Visual']){
  await page.getByRole('tab',{name:'Edit',exact:true}).click();
  const controls=page.getByRole('group',{name:'Editor presentation',exact:true});
  await controls.getByRole('button',{name:mode,exact:true}).click();
  const before=await page.locator('.cm-content').first().evaluate(node=>({source:node.cmTile.root.view.state.doc.toString(),selection:node.cmTile.root.view.state.selection.toJSON()}));
  await page.getByRole('button',{name:'Present',exact:true}).click();
  await page.locator('.document-presentation-content').press('Escape');
  await page.getByRole('dialog',{name:'Document presentation'}).waitFor({state:'detached'});
  await until(async()=>JSON.stringify(await page.locator('.cm-content').first().evaluate(node=>({source:node.cmTile.root.view.state.doc.toString(),selection:node.cmTile.root.view.state.selection.toJSON()})))===JSON.stringify(before),{label:mode+' source and selection return'});
  assert.equal(await controls.getByRole('button',{name:mode,exact:true}).getAttribute('aria-pressed'),'true');
 }
 await page.getByRole('tab',{name:'Preview',exact:true}).click();
 await page.getByRole('button',{name:'Present',exact:true}).click();
 await page.locator('.document-presentation-content').press('Escape');
 await page.getByRole('dialog',{name:'Document presentation'}).waitFor({state:'detached'});
 assert.equal(await page.getByRole('tab',{name:'Preview',exact:true}).getAttribute('aria-selected'),'true');
 await driver.screenshot('editor-after-presentation');await driver.closeNormally();
 await driver.report({status:'passed',scope:'actual native presentation navigation/fullscreen/text-size/retained-document',limitations:'Media/layout, Linux and update qualification remain; package identity is recorded by the driver.'});console.log(output);
}catch(error){await driver.report({status:'failed',error:String(error)});try{await driver.closeNormally();}catch{}throw error;}
