import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
/** Records real parent-renderer frames in an isolated acceptance profile.
 * The detached encoding canvas changes no application UI or product bridge.
 * OS sheets and separate child renderers are outside this capture scope. */
export async function recordParentWindow(page,filename){
 const started=Date.now(),errors=[];let active=true,frames=0;
 await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=900;const stream=canvas.captureStream(4),mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm;codecs=vp8',recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1200000}),chunks=[];window.__stage4Capture={canvas,stream,recorder,chunks,mime};recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.start(1000);});
 const work=(async()=>{while(active){const begin=Date.now();try{const frame=await page.screenshot({type:'jpeg',quality:70,timeout:5000});await page.evaluate(async data=>{const v=window.__stage4Capture;if(!v)return;const image=new Image();image.src='data:image/jpeg;base64,'+data;await image.decode();const ctx=v.canvas.getContext('2d'),scale=Math.min(v.canvas.width/image.width,v.canvas.height/image.height);ctx.fillStyle='#111';ctx.fillRect(0,0,v.canvas.width,v.canvas.height);ctx.drawImage(image,0,0,image.width*scale,image.height*scale);},frame.toString('base64'));frames++;}catch(error){if(active)errors.push(String(error));}await new Promise(resolve=>setTimeout(resolve,Math.max(0,250-(Date.now()-begin))));}})();
 return async()=>{active=false;await work;const captured=await page.evaluate(async()=>{const v=window.__stage4Capture;await new Promise(resolve=>{v.recorder.onstop=resolve;v.recorder.stop();});v.stream.getTracks().forEach(track=>track.stop());const data=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(v.chunks,{type:v.mime}));});delete window.__stage4Capture;return{data,mime:v.mime};});const bytes=Buffer.from(captured.data,'base64');await fs.writeFile(filename,bytes,{flag:'wx'});return{file:filename,mime:captured.mime,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),durationMs:Date.now()-started,frames,errors,scope:'Actual parent-renderer frames; excludes native OS sheets and separate child renderers.'};};
}
