import {testRoot as developmentTestRoot} from '../../../tools/development-paths.mjs';
/** Actual packaged UI acceptance. All data is fresh/disposable below this Test run. */
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const appRoot=fileURLToPath(new URL('../../../',import.meta.url)),project=path.resolve(appRoot,'../..'),testRoot=developmentTestRoot,root=path.join(testRoot,'runs/native-sidebar-20260917'),executable=process.env.ASMB_PACKAGED_EXECUTABLE;
assert.deepEqual(process.argv.slice(2),['--run-isolated'],'Pass --run-isolated explicitly.');assert.ok(executable&&path.isAbsolute(executable)&&executable.includes('.app/Contents/MacOS/'),'Supply ASMB_PACKAGED_EXECUTABLE.');assert.ok(executable.startsWith(path.join(appRoot,'releases')+'/')||executable.startsWith(testRoot+'/runs/native-package/'),'Use a canonical release or prepared package candidate.');
await fs.mkdir(root,{recursive:true});
import {_electron} from '../../../tools/playwright.mjs';
const output=await fs.mkdtemp(root+'/acceptance-'),data=output+'/data',tmp=output+'/tmp',fixture=output+'/fixture';await fs.mkdir(tmp);await fs.mkdir(fixture);const initial='# Sidebar QA\n\nSaved source.\n',marker=' Private draft retained during repository rename.';await fs.writeFile(fixture+'/README.md',initial);await fs.writeFile(fixture+'/other.md','# Other file\n');const zip=output+'/fixture.zip';execFileSync('/usr/bin/zip',['-q','-r',zip,'.'],{cwd:fixture,env:{PATH:'/usr/bin:/bin',TMPDIR:tmp}});
const bundle=executable.slice(0,executable.indexOf('.app/Contents/MacOS/')+4),metadata=JSON.parse(await fs.readFile(bundle+'/Contents/Resources/app/native-package.json','utf8'));let repo='Sidebar-QA',app,page,failure;const events=[],errors=[],consoleErrors=[];const source=()=>data+'/workspaces/asMagicBrain/'+repo;const record=(name,detail={})=>events.push({name,at:new Date().toISOString(),...detail});const button=name=>page.getByRole('button',{name,exact:true});const exists=async file=>Boolean(await fs.stat(file).catch(()=>null));const git=(...args)=>execFileSync('/usr/bin/git',['-C',source(),...args],{encoding:'utf8'}).trim();
async function until(check,label,timeout=15000){const end=Date.now()+timeout;let last;do{try{last=await check();if(last)return last;}catch(error){last=error.message;}await new Promise(resolve=>setTimeout(resolve,60));}while(Date.now()<end);throw Error('Timeout '+label+': '+last);}
async function launch(){app=await _electron.launch({executablePath:executable,args:['--test-data-root='+data],cwd:output,env:{PATH:process.env.PATH,HOME:process.env.HOME,TMPDIR:tmp}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});await button('README.md').first().waitFor();const runtime=await app.evaluate(({app})=>({packaged:app.isPackaged,exe:process.execPath,profile:app.getPath('userData'),cwd:process.cwd()}));assert.equal(runtime.packaged,true);assert.equal(runtime.exe,executable);assert.equal(runtime.profile,data+'-electron-profile');assert.equal(runtime.cwd,output);record('packaged-launch',{runtime});}
async function close(){const exit=app.waitForEvent('close',{timeout:20000});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close()).catch(e=>{if(!/closed|destroyed/i.test(String(e)))throw e;});await exit;record('normal-close');}
async function shot(name){await page.screenshot({path:output+'/'+name+'.png'});record('screenshot',{name});}
async function select(name=repo){await button(/^Switch local repository:/).click();await page.locator('.rh-list').getByRole('button',{name:new RegExp('\\b'+name+'\\b')}).click();if(await button('Leave editor').isVisible())await button('Leave editor').click();await until(async()=>await page.locator('.rc-identity h1').innerText()===name,'selected repository');}
async function openReadme(){await button('README.md').first().click();await until(()=>button('Edit this file').isEnabled(),'reader ready');}
async function edit(){if(await button('Edit this file').count())await button('Edit this file').click();await page.locator('.cm-content[contenteditable=true]').waitFor();}
async function append(text){const cm=page.locator('.cm-content[contenteditable=true]');await cm.click();await cm.press('Meta+ArrowDown');await page.keyboard.insertText(text);}
async function sourceText(){const cm=page.locator('.cm-content[contenteditable=true]');await cm.click();await cm.press('Meta+ArrowDown');return cm.innerText();}
async function openExisting(){await button('More actions for README.md').click();await page.getByRole('menuitem',{name:'Open',exact:true}).click();await edit();}
async function action(name){await button('Repository file actions').click();await page.getByRole('menuitem',{name,exact:true}).click();}
async function layout(mode){const sw=page.getByRole('switch',{name:'Hide unavailable functions'});if((await sw.getAttribute('aria-checked')==='true')!==mode)await sw.click();await until(async()=>await page.locator('.fw-window').evaluate(e=>e.classList.contains('fw-hide-unavailable'))===mode,'availability mode');const geometry=await page.evaluate(()=>{const box=s=>{const r=document.querySelector(s)?.getBoundingClientRect();return r?{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom,right:r.right}:null;};return{title:box('.fw-titlebar'),tabs:box('.rt-bar'),rail:box('.fw-rail'),main:box('.rfe-main'),header:box('.rfe-sidebar>header'),search:box('.rfe-sidebar>header [aria-label="Search files"]'),branch:box('.fnc .rp-trigger'),more:box('.fnc [aria-label="Repository file actions"]')};});assert.equal(geometry.tabs,null,'Repository V3 strip removed');assert.equal(await page.locator('#repository-code-tab, #repository-code-panel, [aria-labelledby="repository-code-tab"]').count(),0);assert.ok(Math.abs(geometry.title.bottom-geometry.main.y)<2,'Document begins below titlebar without V3 gap');assert.ok(Math.abs(geometry.title.bottom-geometry.header.y)<2,'Sidebar begins below titlebar');assert.equal(await page.locator('.zi-import-status').count(),0);assert.equal(await page.locator('.fnc-new-folder').count(),0);assert.equal(await page.locator('.fnc-repository-search').count(),0);assert.equal(await page.locator('.rfe-sidebar>header strong').innerText(),repo);assert.ok(geometry.more.x>geometry.branch.x);assert.ok(Math.abs(geometry.more.y-geometry.branch.y)<8);const search=button('Search files');if(mode)assert.equal(await search.isVisible(),false);else{assert.equal(await search.isDisabled(),true);assert.ok(geometry.search.x>geometry.header.x+geometry.header.w/2);}
 await shot(mode?'implemented-mode':'full-mode');record('V4-layout-without-repository-strip',{mode,geometry});}
async function rename(name){await button('Rename repository').click();const dialog=page.getByRole('dialog',{name:'Rename repository',exact:true});await dialog.getByLabel('Repository name',{exact:true}).fill(name);await shot('rename-modal-'+name);await dialog.getByRole('button',{name:'Rename repository',exact:true}).click();return dialog;}
try{
 await launch();await button('Create new options').click();await button('Import repository').click();await page.getByLabel('ZIP archive',{exact:true}).setInputFiles(zip);await page.getByLabel('Repository name',{exact:true}).fill(repo);await page.locator('.zi-dialog').getByRole('button',{name:'Import repository',exact:true}).click();await page.locator('.zi-dialog').waitFor({state:'detached',timeout:60000});await select();await openReadme();await layout(false);await layout(true);await edit();await append(marker);await action('New Markdown file');await page.getByLabel('File path',{exact:true}).fill('pending.md');await append('# Unsaved new file retained');await openExisting();const before=git('rev-parse','HEAD'),tree=git('rev-parse','HEAD^{tree}'),inode=(await fs.stat(source())).ino;
 const toggle=page.locator('.fw-titlebar').getByRole('button',{name:/file sidebar/i});for(let i=0;i<2;i++){await toggle.click();await page.locator('.rfe-sidebar').waitFor({state:'hidden'});assert.match(await sourceText(),/Private draft retained/);await toggle.click();await page.locator('.rfe-sidebar').waitFor();}assert.equal(await fs.readFile(source()+'/README.md','utf8'),initial);const cmUndo=page.locator('.cm-content[contenteditable=true]');await cmUndo.press('Meta+z');assert.doesNotMatch(await sourceText(),/Private draft retained/);await cmUndo.press('Meta+Shift+z');assert.match(await sourceText(),/Private draft retained/);record('titlebar-toggle-keeps-draft-and-undo');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(390,760));await until(async()=>await page.locator('.rfe').evaluate(e=>e.classList.contains('rfe-narrow')),'narrow layout');await page.locator('.rfe-sidebar').waitFor({state:'hidden'});await toggle.click();await page.locator('.rfe-sidebar').waitFor();await shot('narrow-sidebar');await toggle.click();await page.locator('.rfe-sidebar').waitFor({state:'hidden'});await toggle.click();await page.locator('.rfe-sidebar').waitFor();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,1000));await until(async()=>!(await page.locator('.rfe').evaluate(e=>e.classList.contains('rfe-narrow'))),'wide restored');record('narrow-toggle-keeps-file');
 const filePath=page.getByLabel('File path',{exact:true});await filePath.fill('unsaved-name.md');const intentDialog=await rename('Blocked-Name');await intentDialog.getByRole('alert').waitFor();assert.match(await intentDialog.getByRole('alert').innerText(),/Save or revert filename/);assert.equal(await exists(data+'/workspaces/asMagicBrain/Blocked-Name'),false);assert.equal(await exists(source()),true);await intentDialog.getByRole('button',{name:'Cancel',exact:true}).click();await filePath.fill('README.md');
 await button('Rename repository').click();await page.getByRole('dialog',{name:'Rename repository',exact:true}).press('Escape');await until(async()=>await button('Rename repository').evaluate(e=>e===document.activeElement),'rename Escape returns focus');
 const old=source(),dialog=await rename('Sidebar-Renamed');await dialog.waitFor({state:'hidden'});repo='Sidebar-Renamed';await until(()=>exists(source()),'actual renamed folder');assert.equal(await exists(old),false);assert.equal((await fs.stat(source())).ino,inode);assert.equal(git('rev-parse','HEAD'),before);assert.equal(git('rev-parse','HEAD^{tree}'),tree);assert.equal(await fs.readFile(source()+'/README.md','utf8'),initial);await edit();assert.match(await sourceText(),/Private draft retained/);await shot('renamed-private-draft');record('actual-folder-rename-preserves-inode-git-and-private-draft');
 const collision=await rename('Workspace');await collision.getByRole('alert').waitFor();assert.equal(await collision.getByLabel('Repository name',{exact:true}).inputValue(),'Workspace');assert.ok(await exists(source()));assert.ok(await exists(data+'/workspaces/asMagicBrain/Workspace'));assert.equal(git('rev-parse','HEAD'),before);await collision.getByRole('button',{name:'Cancel',exact:true}).click();record('collision-preserves-repositories-and-dialog-input');await page.locator('.rfe-new-drafts').getByRole('button',{name:/pending.md/}).click();const activeNewRename=await rename('Sidebar-Final');await activeNewRename.waitFor({state:'hidden'});repo='Sidebar-Final';await page.locator('.rfe-directory-table').waitFor();await page.locator('.rfe-new-drafts').getByRole('button',{name:/pending.md/}).click();assert.match(await sourceText(),/Unsaved new file retained/);assert.equal(await exists(source()+'/pending.md'),false);assert.equal(git('rev-parse','HEAD'),before);record('rename-active-new-draft-routes-safely-and-retains-content');await close();
 await launch();await select();await openReadme();await edit();assert.match(await sourceText(),/Private draft retained/);assert.equal(await fs.readFile(source()+'/README.md','utf8'),initial);assert.equal(git('rev-parse','HEAD'),before);await page.locator('.rfe-new-drafts').getByRole('button',{name:/pending.md/}).click();assert.match(await sourceText(),/Unsaved new file retained/);assert.equal(await exists(source()+'/pending.md'),false);await openExisting();await button('Save').click();await until(async()=>await fs.readFile(source()+'/README.md','utf8')===initial+marker,'save uses new physical repository');await button('Commit changes…').click();const form=page.locator('.rfe-commit-dialog[open]');await form.getByLabel('Local author name',{exact:true}).fill('Sidebar QA');await form.getByLabel('Local author email',{exact:true}).fill('sidebar-qa@example.invalid');await form.getByLabel('Commit message',{exact:true}).fill('Verify renamed repository binding');await until(()=>form.getByRole('button',{name:'Commit changes',exact:true}).isEnabled(),'review ready');await form.getByRole('button',{name:'Commit changes',exact:true}).click();await until(()=>git('rev-parse','HEAD')!==before,'local commit after rename');assert.equal(git('diff-tree','--no-commit-id','--name-only','-r','HEAD'),'README.md');assert.equal(git('show','-s','--format=%an <%ae>'),'Sidebar QA <sidebar-qa@example.invalid>');record('rename-restart-save-selected-commit');
 await select('Workspace');await openReadme();const defaultDialog=await rename('Workspace-Renamed');await defaultDialog.waitFor({state:'hidden'});await until(()=>exists(data+'/workspaces/asMagicBrain/Workspace-Renamed'),'default renamed');assert.equal(await exists(data+'/workspaces/asMagicBrain/Workspace'),false);record('default-workspace-renamed');await close();await launch();assert.equal(await exists(data+'/workspaces/asMagicBrain/Workspace'),false);await select('Workspace-Renamed');record('renamed-default-persists-without-reseed');await button('Account menu').click();await page.getByRole('menuitem',{name:'Settings',exact:true}).click();await until(()=>page.getByRole('radio',{name:/asMagicBrain profile/}).isEnabled(),'global preferences after default rename');await page.getByRole('radio',{name:/asMagicBrain profile/}).check();await page.getByLabel('Author name',{exact:true}).fill('Renamed Default QA');await page.getByLabel('Author email',{exact:true}).fill('renamed-default@example.invalid');await button('Save settings').click();await page.locator('.ac-settings').waitFor({state:'detached'});record('global-author-preferences-after-default-rename');await select();await openReadme();await layout(false);await layout(true);assert.equal(errors.length,0);assert.equal(consoleErrors.length,0);await close();
}catch(error){failure={message:error.message,stack:error.stack};console.error(error.stack);try{await shot('failure');await fs.writeFile(output+'/failure-dom.txt',await page.locator('body').innerText());}catch{}try{if(app)await close();}catch{}process.exitCode=1;}
finally{await fs.writeFile(output+'/receipt.json',JSON.stringify({status:failure?'failed':'passed',failure,executable,metadata,data,events,errors,consoleErrors,definitionSha256:createHash('sha256').update(await fs.readFile(fileURLToPath(import.meta.url))).digest('hex')},null,2));console.log(JSON.stringify({status:failure?'failed':'passed',output}));}
