import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createDriver,nativeTarget,testRoot,until} from './native-driver.mjs';
const output=await fs.mkdtemp(path.join(await fs.mkdir(testRoot,{recursive:true}).then(()=>testRoot),'teach-'));
const data=path.join(output,'data'),driver=await createDriver({...nativeTarget(data),output,workspacePath:path.join(data,'workspaces/asMagicBrain/Workspace')});
const plugin=process.env.ASMB_TEACH_PACKAGE;assert.ok(plugin);let page,running=false,failure;
const button=name=>page.getByRole('button',{name,exact:true});
async function capture(name){
 await page.evaluate(()=>{for(const [selector,label] of [['.pws-breadcrumb','C0 · Navigation'],['.ths-heading','TH1 · Teacher defaults'],['.tcal-overview','TH3–TH4 · Combined calendar'],['.tcs-list','C1 · Courses'],['.tcal-course-calendar','T7 · Course calendar'],['.rfe-editor-frame','T3 · Shared CM6 editor']]){const target=document.querySelector(selector);if(!target||!target.getClientRects().length)continue;const r=target.getBoundingClientRect(),mark=document.createElement('div');mark.className='acceptance-overlay';Object.assign(mark.style,{position:'fixed',pointerEvents:'none',zIndex:'99999',left:r.left+'px',top:Math.max(0,r.top)+'px',width:r.width+'px',height:Math.min(r.height,innerHeight-r.top)+'px',outline:'2px solid #8250df',color:'#fff',fontSize:'12px'});const text=document.createElement('span');text.textContent=label;text.style.background='#8250df';mark.append(text);document.body.append(mark);}});
 await driver.screenshot(name);await page.evaluate(()=>document.querySelectorAll('.acceptance-overlay').forEach(e=>e.remove()));
}
const call=input=>page.evaluate(async value=>{const reply=await window.asMagicBrain.nativeTeachRequest(value);if(!reply.ok)throw Error(reply.error.message);return reply.value;},input);
try{
 page=await driver.launch();running=true;await button('Manage plugins').waitFor();assert.equal(await button('asTeach').count(),0);
 await driver.app.evaluate(({dialog},filename)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[filename]});},plugin);
 await button('Manage plugins').click();await button('Install plugin…').click();await button('Install plugin').click();await page.getByRole('switch',{name:'Enable asTeach',exact:true}).click();await button('asTeach').click();await page.getByRole('heading',{name:'Home',exact:true}).waitFor();
 await button('Edit office hours').click();await page.getByLabel('Office hours',{exact:true}).fill('Monday 14:00');await button('Save office hours').click();await until(async()=>(await call({operation:'defaults'})).value.office.hours==='Monday 14:00');
 await button('Edit teacher details').click();const profile=page.getByRole('dialog',{name:'Teacher details'});await profile.locator('[name=givenNames]').fill('Test');await profile.locator('[name=familyNames]').fill('Teacher');await button('Save teacher details').click();await until(async()=>(await call({operation:'defaults'})).value.teacher.givenNames==='Test');
 await capture('01-home-annotated');await button('Create a new course').click();const dialog=page.getByRole('dialog',{name:'New course'});
 await dialog.getByLabel('Course Code',{exact:true}).fill('ROB7103/8103');await dialog.getByLabel('Course Name',{exact:true}).fill('Robotics');await dialog.locator('[name=season]').selectOption('Autumn');await dialog.getByRole('button',{name:'Create course',exact:true}).click();
 await until(async()=> (await call({operation:'list'})).length===1,{label:'course saved'});await page.getByRole('heading',{name:'Courses',exact:true}).waitFor();await driver.screenshot('02-courses');
 const course=(await call({operation:'list'}))[0];assert.equal(course.course.code,'ROB7103/8103');assert.equal(course.settings[`${course.course.terms[0].year}-autumn`].value.teacherSnapshot.givenNames,'Test');
 await button('Open course ROB7103/8103').click();await button('Edit this file').waitFor();
 await button('Choose course page').click();assert.notEqual(await page.getByRole('menuitem',{name:'Student page',exact:true}).getAttribute('aria-disabled'),'true');await page.getByRole('menuitem',{name:'Course calendar',exact:true}).click();
 // Both pages must keep the same explorer and text edges at different window widths.
 for(const width of [1440,1100]){
  await driver.app.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows()[0].setSize(width,900),width);
  await button('Choose course page').click();await page.getByRole('menuitem',{name:'Instructor page',exact:true}).click();
  await page.locator('.rfe-preview article').waitFor();
  const edges=await page.locator('.rfe-preview article').evaluate(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return {left:r.left+parseFloat(s.paddingLeft),right:r.right-parseFloat(s.paddingRight)};});
  const sidebar=await page.locator('.rfe-sidebar').boundingBox();
  await button('Choose course page').click();await page.getByRole('menuitem',{name:'Course calendar',exact:true}).click();await page.locator('.native-teach-calendar').waitFor();
  const calendarEdges=await page.locator('.tcal-course-calendar').evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right};});
  assert.ok(Math.abs(edges.left-calendarEdges.left)<=1,JSON.stringify({width,edges,calendarEdges}));assert.ok(Math.abs(edges.right-calendarEdges.right)<=1,JSON.stringify({width,edges,calendarEdges}));
  assert.deepEqual(await page.locator('.rfe-sidebar').boundingBox(),sidebar);
  assert.equal(await page.locator('.rfe-document-panel').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 }
 await page.locator('.tcal-settings input[type=text]').fill('20260907');await page.getByLabel('Total number of weeks').fill('3');await page.locator('.tcal-settings').getByRole('button',{name:'Save',exact:true}).click();await until(async()=>(await call({operation:'list'}))[0].settings['2026-autumn'].value.calendar.totalWeeks===3);
 await button('Add class session').click();const session=page.getByRole('dialog',{name:'Add class session'});await session.getByLabel('Class name').fill('Lecture');await session.getByLabel('Start time').fill('10:00');await session.getByLabel('End time').fill('12:00');await session.getByRole('button',{name:'Add session'}).click();await until(async()=>(await call({operation:'list'}))[0].settings['2026-autumn'].value.calendar.sessions.length===1);await capture('02-calendar-annotated');
 await button('asTeach — Home').click();await page.locator('td[data-date="2026-09-07"] time').dblclick();const day=page.getByRole('dialog',{name:'Add no-class day'});await day.getByLabel('Description (optional)').fill('Holiday');await day.getByRole('button',{name:'Add no-class day'}).click();await until(async()=>(await call({operation:'defaults'})).value.noClassDays.length===1);
 await button('Courses — all courses').click();await button('Open course ROB7103/8103').click();
 await button('Choose course page').click();await page.getByRole('menuitem',{name:'Course calendar',exact:true}).click();
 for(const [weekday,room] of [['2','CR6'],['4','L12']]){await button('Add class session').click();const form=page.getByRole('dialog',{name:'Add class session'});await form.getByLabel('Class name').fill('Session');await form.locator('select').selectOption(weekday);await form.getByLabel('Start time').fill('09:00');await form.getByLabel('End time').fill('10:20');await form.getByLabel('Room or location (optional)').fill(room);await form.getByRole('button',{name:'Add session',exact:true}).click();await form.waitFor({state:'detached'});}
 await until(async()=>(await call({operation:'list'}))[0].settings['2026-autumn'].value.calendar.sessions.length===3);
 const savedBefore=await fs.readFile(path.join(data,'workspaces/asMagicBrain',course.repo,`${course.course.terms[0].year}-autumn/instructor.md`),'utf8');
 const previousClipboard=await driver.app.evaluate(({clipboard})=>clipboard.readText());
 await button('One-Page Course').click();await page.getByText('Schedule copied',{exact:true}).waitFor();
 const schedule=await driver.app.evaluate(({clipboard})=>clipboard.readText());assert.match(schedule,/Sep 07: Class 01<br>No Class\. Holiday/);assert.match(schedule,/Sep 14: Class 04<br>ClassContent/);assert.equal(await fs.readFile(path.join(data,'workspaces/asMagicBrain',course.repo,`${course.course.terms[0].year}-autumn/instructor.md`),'utf8'),savedBefore);await capture('05-schedule-copy-annotated');
 await button('Multi-Page Course').click();await page.getByText('Class pages saved. Schedule copied.',{exact:true}).waitFor();
 const linked=await driver.app.evaluate(({clipboard})=>clipboard.readText());assert.match(linked,/\[No Class\. Holiday\]\(classes\/Class01.md\)/);assert.match(linked,/\[ClassContent\]\(classes\/Class09.md\)/);
 const termRoot=path.join(data,'workspaces/asMagicBrain',course.repo,'2026-autumn/classes');
 const pageNames=(await fs.readdir(termRoot)).filter(name=>/^Class\d+\.md$/.test(name));assert.equal(pageNames.length,9);
 const pageBytes=await Promise.all(pageNames.map(name=>fs.readFile(path.join(termRoot,name),'utf8')));
 await button('Multi-Page Course').click();await page.getByText('Class pages saved. Schedule copied.',{exact:true}).waitFor();assert.deepEqual(await Promise.all(pageNames.map(name=>fs.readFile(path.join(termRoot,name),'utf8'))),pageBytes);
 const geometry=await page.locator('.tcal-settings').evaluate(el=>{const save=el.querySelector('button[type=submit]').getBoundingClientRect(),multi=[...el.querySelectorAll('button')].find(b=>b.textContent==='Multi-Page Course').getBoundingClientRect();return {sameRow:Math.abs(save.top-multi.top)<2,right:multi.left>save.right,weeksSameRow:Math.abs(el.querySelector('input[type=number]').getBoundingClientRect().bottom-save.bottom)<2};});assert.equal(geometry.sameRow,true);assert.equal(geometry.right,true);assert.equal(geometry.weeksSameRow,true);
 const feedback=await page.locator('.tcal-guidance-row').evaluate(el=>{const note=el.querySelector('.tcal-scope').getBoundingClientRect(),status=el.querySelector('.tcal-copy-status').getBoundingClientRect();return status.left>note.right&&Math.abs(status.top-note.top)<2;});assert.equal(feedback,true);
 await capture('07-multi-page-schedule-annotated');await page.locator('.rfe-sidebar').getByText('classes',{exact:true}).waitFor();
 await button('Choose course page').click();await page.getByRole('menuitem',{name:'Instructor page',exact:true}).click();await button('Edit this file').click();await page.locator('.cm-content[contenteditable=true]').click();await page.keyboard.press('Meta+End');await page.keyboard.insertText('\n\n## Teaching Schedule\n\n');await page.keyboard.press('Meta+v');await until(async()=>(await page.locator('.cm-content').innerText()).includes('Class 09<br>[ClassContent](classes/Class09.md)'));
 await driver.app.evaluate(({clipboard},{previous,schedule})=>{if(clipboard.readText()===schedule)clipboard.writeText(previous);},{previous:previousClipboard,schedule:linked});
 await page.keyboard.insertText('\n\nNative teaching acceptance.\n');await button('Save').click();
 await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.locator('.rfe-preview table').waitFor();assert.equal(await page.locator('.rfe-preview table tbody br').count(),9);
 for(const label of ['Wk','Notes'])assert.equal(await page.locator('.rfe-preview table th').filter({hasText:new RegExp('^'+label+'$')}).evaluate(el=>{const range=document.createRange();range.selectNodeContents(el);return range.getBoundingClientRect().height<=parseFloat(getComputedStyle(el).lineHeight)+1;}),true);
 await page.locator('.rfe-preview table').scrollIntoViewIfNeeded();await driver.screenshot('06-pasted-schedule');
 await until(async()=> (await fs.readFile(path.join(data,'workspaces/asMagicBrain',course.repo,`${course.course.terms[0].year}-autumn/instructor.md`),'utf8')).includes('Native teaching acceptance.'),{label:'saved Instructor source'});
 await page.locator('.rfe-preview table').getByRole('link',{name:'ClassContent',exact:true}).first().click();await until(()=>page.getByRole('textbox',{name:'File path',exact:true}).inputValue().then(text=>text==='2026-autumn/classes/Class02.md'));await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.locator('.rfe-preview').getByRole('heading',{name:'Class 02',exact:true}).waitFor();await driver.screenshot('08-linked-class-page');await button('Choose course page').click();await page.getByRole('menuitem',{name:'Instructor page',exact:true}).click();await until(()=>page.getByRole('textbox',{name:'File path',exact:true}).inputValue().then(text=>text==='2026-autumn/instructor.md'));await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.locator('.rfe-preview table').waitFor();
 await button('Commit changes…').click();const commit=page.getByRole('dialog',{name:'Commit changes',exact:true});await commit.getByLabel('Local author name').fill('Test Teacher');await commit.getByLabel('Local author email').fill('teacher@example.invalid');await commit.getByRole('button',{name:'Commit changes',exact:true}).click();await commit.waitFor({state:'hidden'});
 const tracked=execFileSync('/usr/bin/git',['-C',path.join(data,'workspaces/asMagicBrain',course.repo),'ls-tree','--name-only','-r','HEAD'],{encoding:'utf8',env:{PATH:'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'}}).trim();assert.equal(tracked,`${course.course.terms[0].year}-autumn/instructor.md`);
 await button('Edit this file').click();await page.getByRole('tab',{name:'Split',exact:true}).click();await capture('03-instructor-split-annotated');
 await page.locator('.cm-content[contenteditable=true]').click();await page.keyboard.press('Meta+End');await page.keyboard.insertText('\nRetained teaching draft.\n');await driver.closeNormally();running=false;
 page=await driver.launch();running=true;await button('asTeach').waitFor();await button('asTeach').click();await button('Courses — all courses').click();await button('Open course ROB7103/8103').click();await button('Edit this file').waitFor();await button('Edit this file').click();await page.locator('.cm-content[contenteditable=true]').click();await page.keyboard.press('Meta+End');await until(()=>page.locator('.cm-content').innerText().then(t=>t.includes('Retained teaching draft.')),{label:'retained draft after restart'});
 await driver.screenshot('04-restarted-draft');assert.equal((await call({operation:'defaults'})).value.office.hours,'Monday 14:00');assert.equal((await call({operation:'defaults'})).value.noClassDays.length,1);assert.equal((await call({operation:'list'}))[0].settings['2026-autumn'].value.calendar.sessions.length,3);
 await button('Manage plugins').click();await page.getByRole('switch',{name:'Enable asTeach',exact:true}).click();await until(()=>button('asTeach').count().then(n=>n===0));await page.getByRole('switch',{name:'Enable asTeach',exact:true}).click();await button('asTeach').waitFor();await button('asTeach').click();
 await page.evaluate(async()=>{for(const [method,args] of [['createRepository',{name:'LegacyTeaching',requestId:crypto.randomUUID()}],['request',{repo:'LegacyTeaching',operation:'create',args:{path:'README.md',text:'# Existing course\nOriginal bytes.\n'}}]]){const r=await window.asMagicBrain[method](args);if(!r.ok)throw Error(r.error.message);}});
 await button('Add existing course').click();const adopt=page.getByRole('dialog',{name:'Add existing course'});await adopt.getByRole('combobox',{name:'Repository',exact:true}).selectOption('LegacyTeaching');await adopt.getByRole('combobox',{name:'Instructor document',exact:true}).selectOption('README.md');await adopt.getByLabel('Course Code',{exact:true}).fill('LEGACY101');await adopt.getByLabel('Course Name',{exact:true}).fill('Existing course');await adopt.getByRole('button',{name:'Add course',exact:true}).click();await adopt.waitFor({state:'detached'});assert.equal((await call({operation:'list'})).length,2);assert.equal(await fs.readFile(path.join(data,'workspaces/asMagicBrain/LegacyTeaching/README.md'),'utf8'),'# Existing course\nOriginal bytes.\n');
 await button('Courses — all courses').click();await button('Choose term for ROB7103/8103').click();await page.getByRole('menuitem',{name:'Add term',exact:true}).click();const term=page.getByRole('dialog',{name:'Add term'});await term.locator('[name=season]').selectOption('Winter');await term.getByRole('button',{name:'Create term',exact:true}).click();await until(async()=>(await call({operation:'list'})).find(r=>r.repo==='ROB7103_8103_asTeach').course.terms.length===2);
 assert.deepEqual(driver.errors,[]);await driver.closeNormally();running=false;
}catch(e){failure=e;if(page)await fs.writeFile(path.join(output,'failure-aria.yml'),await page.locator('body').ariaSnapshot().catch(()=>''));}
finally{if(running)await driver.closeNormally().catch(()=>{});await driver.report({passed:!failure,failure:failure?.stack});}
if(failure)throw failure;console.log(JSON.stringify({passed:true,output}));
