import {testRoot as developmentTestRoot} from '../../../tools/development-paths.mjs';
/** Historical preview.6 V3-placement predecessor. Current builds use navigation-strip.mjs.
 * Original delivered definitions remain in immutable historical tags/evidence. */
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
assert.equal(process.env.ASMB_HISTORICAL_V3,'1','Historical V3 predecessor only; use navigation-strip.mjs for current builds.');
const appRoot=fileURLToPath(new URL('../../../',import.meta.url)),project=path.resolve(appRoot,'../..'),testRoot=developmentTestRoot,root=path.join(testRoot,'runs/native-v3-20260917'),executable=process.env.ASMB_PACKAGED_EXECUTABLE;
assert.deepEqual(process.argv.slice(2),['--run-isolated'],'Pass --run-isolated explicitly.');assert.ok(executable&&path.isAbsolute(executable)&&executable.includes('.app/Contents/MacOS/'),'Supply ASMB_PACKAGED_EXECUTABLE.');assert.ok(executable.startsWith(path.join(appRoot,'releases')+'/')||executable.startsWith(testRoot+'/runs/native-package/'),'Use a canonical release or prepared package candidate.');
await fs.mkdir(root,{recursive:true});
import {_electron} from '../../../tools/playwright.mjs';
const output=await fs.mkdtemp(root+'/acceptance-'),data=output+'/data',tmp=output+'/tmp',fixture=output+'/fixture';await fs.mkdir(tmp);await fs.mkdir(fixture);const initial='# V3 QA\n\nSaved source.\n',marker=' Private V3 draft retained.';await fs.writeFile(fixture+'/README.md',initial);await fs.writeFile(fixture+'/other.md','# Other file\n');await fs.mkdir(fixture+'/notes');await fs.writeFile(fixture+'/notes/nested.md','# Nested file\n');const zip=output+'/fixture.zip';execFileSync('/usr/bin/zip',['-q','-r',zip,'.'],{cwd:fixture,env:{PATH:'/usr/bin:/bin',TMPDIR:tmp}});
const bundle=executable.slice(0,executable.indexOf('.app/Contents/MacOS/')+4),metadata=JSON.parse(await fs.readFile(bundle+'/Contents/Resources/app/native-package.json','utf8'));let repo='V3-QA',app,page,failure;const events=[],errors=[],consoleErrors=[];const source=()=>data+'/workspaces/asMagicBrain/'+repo;const record=(name,detail={})=>events.push({name,at:new Date().toISOString(),...detail});const button=name=>page.getByRole('button',{name,exact:true});const exists=async file=>Boolean(await fs.stat(file).catch(()=>null));const git=(...args)=>execFileSync('/usr/bin/git',['-C',source(),...args],{encoding:'utf8'}).trim();
async function until(check,label,timeout=15000){const end=Date.now()+timeout;let last;do{try{last=await check();if(last)return last;}catch(error){last=error.message;}await new Promise(resolve=>setTimeout(resolve,60));}while(Date.now()<end);throw Error('Timeout '+label+': '+last);}
async function launch(){app=await _electron.launch({executablePath:executable,args:['--test-data-root='+data],cwd:output,env:{PATH:process.env.PATH,HOME:process.env.HOME,TMPDIR:tmp}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});await button('README.md').first().waitFor();const runtime=await app.evaluate(({app})=>({packaged:app.isPackaged,exe:process.execPath,profile:app.getPath('userData'),cwd:process.cwd()}));assert.equal(runtime.packaged,true);assert.equal(runtime.exe,executable);assert.equal(runtime.profile,data+'-electron-profile');assert.equal(runtime.cwd,output);record('packaged-launch',{runtime});}
let cdp,recorder;
async function startVideo(){
 await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=1000;const context=canvas.getContext('2d'),chunks=[],mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm;codecs=vp8';const stream=canvas.captureStream(12),recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1500000});window.__asmbQaVideo={canvas,context,chunks,recorder,stream,started:Date.now(),mime};recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start(1000);});
 recorder={started:Date.now(),frames:0,dropped:0,busy:false,listener:null};const state=recorder;
 state.listener=async event=>{void cdp.send('Page.screencastFrameAck',{sessionId:event.sessionId}).catch(()=>{});if(state.busy){state.dropped++;return;}state.busy=true;try{await page.evaluate(async jpeg=>{const v=window.__asmbQaVideo;if(!v)return;const img=new Image();img.src='data:image/jpeg;base64,'+jpeg;await img.decode();v.context.drawImage(img,0,0,v.canvas.width,v.canvas.height);},event.data);state.frames++;}catch(error){state.frameErrors??=[];state.frameErrors.push(String(error));}finally{state.busy=false;}};
 cdp.on('Page.screencastFrame',state.listener);await cdp.send('Page.startScreencast',{format:'jpeg',quality:75,maxWidth:1440,maxHeight:1000,everyNthFrame:1});
}
async function stopVideo(){if(!recorder)return;const state=recorder;await cdp.send('Page.stopScreencast');cdp.off('Page.screencastFrame',state.listener);await until(()=>!state.busy,'video frame drained');const result=await page.evaluate(async()=>{const v=window.__asmbQaVideo;await new Promise(resolve=>{v.recorder.onstop=resolve;v.recorder.stop();});v.stream.getTracks().forEach(t=>t.stop());const blob=new Blob(v.chunks,{type:v.mime}),base64=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(blob);});delete window.__asmbQaVideo;return{base64,mime:v.mime};});const filename='layout-walkthrough.webm';await fs.writeFile(path.join(output,filename),Buffer.from(result.base64,'base64'));record('real-gesture-recording',{file:filename,mime:result.mime,durationMs:Date.now()-state.started,capturedFrames:state.frames,droppedFrames:state.dropped,frameErrors:state.frameErrors??[],canvasRate:12,method:'Actual CDP screencast frames encoded through browser MediaRecorder; no reenactment.'});recorder=null;}

async function close(){await stopVideo();const exit=app.waitForEvent('close',{timeout:20000});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close()).catch(e=>{if(!/closed|destroyed/i.test(String(e)))throw e;});await exit;record('normal-close');}
async function shot(name){await page.screenshot({path:output+'/'+name+'.png'});record('screenshot',{name});}
async function select(name=repo){await button(/^Switch local repository:/).click();await page.locator('.rh-list').getByRole('button',{name:new RegExp('\\b'+name+'\\b')}).click();if(await button('Leave editor').isVisible())await button('Leave editor').click();await until(async()=>await page.locator('.rc-identity h1').innerText()===name,'selected repository');}
async function openReadme(){await button('README.md').first().click();await until(()=>button('Edit this file').isEnabled(),'reader ready');}
async function edit(){if(await button('Edit this file').count())await button('Edit this file').click();await page.locator('.cm-content[contenteditable=true]').waitFor();}
async function append(text){const cm=page.locator('.cm-content[contenteditable=true]');await cm.click();await cm.press('Meta+ArrowDown');await page.keyboard.insertText(text);}
async function sourceText(){const cm=page.locator('.cm-content[contenteditable=true]');await cm.click();await cm.press('Meta+ArrowDown');return cm.innerText();}
async function openExisting(){await button('More actions for README.md').click();await page.getByRole('menuitem',{name:'Open',exact:true}).click();await edit();}
async function action(name){await button('Repository file actions').click();await page.getByRole('menuitem',{name,exact:true}).click();}

const near=(a,b,label)=>assert.ok(Math.abs(a-b)<2,`${label}: ${a} versus ${b}`);
async function mode(value){const sw=page.getByRole('switch',{name:'Hide unavailable functions'});if((await sw.getAttribute('aria-checked')==='true')!==value)await sw.click();await until(async()=>await page.locator('.fw-window').evaluate(e=>e.classList.contains('fw-hide-unavailable'))===value,'availability');}
async function geometry(name,{overview=false,narrow=false}={}){
 await until(async()=>await page.locator('.rt-bar').count()===1,'single V3');
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const boxes=await page.evaluate(()=>{const box=s=>{const e=document.querySelector(s),r=e?.getBoundingClientRect();return r&&r.width&&r.height?{x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}:null;};return{title:box('.fw-titlebar'),tabs:box('.rt-bar'),rail:box('.fw-rail'),main:box('.rfe-main'),sidebar:box('.rfe-sidebar'),divider:box('.rfe-resizer'),shell:box('.fw-main'),compact:document.querySelector('.rt-bar')?.classList.contains('rt-compact')};});
 near(boxes.tabs.h,41,'V3 height');near(boxes.tabs.y,boxes.title.bottom,'V3 top');
 if(overview){near(boxes.tabs.x,boxes.rail.right,'overview starts at rail');near(boxes.tabs.right,boxes.shell.right,'overview right edge');}
 else{assert.ok(boxes.main);near(boxes.tabs.x,boxes.main.x,'V3 main left');near(boxes.tabs.right,boxes.main.right,'V3 main right');if(boxes.sidebar){near(boxes.sidebar.y,boxes.title.bottom,'sidebar directly below titlebar');if(!narrow)near(boxes.tabs.x,boxes.divider.right,'V3 after divider');}else near(boxes.tabs.x,boxes.rail.right,'collapsed main starts at rail');}
 assert.equal(await page.locator('#repository-code-tab').count(),1);assert.equal(await page.locator('#repository-code-panel').count(),1);
 const ids=await page.locator('#repository-code-tab').getAttribute('aria-controls');assert.equal(ids,'repository-code-panel');
 await shot(name);await fs.writeFile(output+'/'+name+'-bounds.json',JSON.stringify(boxes,null,2));record('V3 geometry',{name,boxes});if(name==='file-full'||name==='edit-full')await overlay(name,boxes);return boxes;
}
async function overlay(name,boxes){
 const areas=[['V1 titlebar',boxes.title],['V2 rail',boxes.rail],['V3 repository sections',boxes.tabs],['V4/V5 sidebar',boxes.sidebar],['Document pane',boxes.main]].filter(([,box])=>box);
 await page.evaluate(areas=>{const layer=document.createElement('div');layer.id='v3-qa-overlay';layer.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:2147483647';areas.forEach(([label,r],i)=>{const color=['#ffbf47','#b99cff','#39dfbf','#ff8cb7','#6ae3ff'][i],box=document.createElement('div');box.style.cssText=`position:fixed;box-sizing:border-box;left:${r.x}px;top:${r.y}px;width:${r.w}px;height:${r.h}px;border:2px solid ${color};background:${color}10`;const badge=document.createElement('span');badge.textContent=label;badge.style.cssText=`background:#15181e;color:${color};font:700 12px system-ui;padding:3px 5px`;box.append(badge);layer.append(box);});document.body.append(layer);},areas);
 try{await page.screenshot({path:output+'/'+name+'-overlay.png'});record('DOM overlay',{raw:name+'.png',overlay:name+'-overlay.png',bounds:name+'-bounds.json'});}finally{await page.evaluate(()=>document.getElementById('v3-qa-overlay')?.remove());}
}
async function openTreeFile(path){await button('More actions for '+path).click();await page.getByRole('menuitem',{name:'Open',exact:true}).click();}
try{
 await launch();cdp=await page.context().newCDPSession(page);await startVideo();await button('Create new options').click();await button('Import repository').click();await page.getByLabel('ZIP archive',{exact:true}).setInputFiles(zip);await page.getByLabel('Repository name',{exact:true}).fill(repo);await page.locator('.zi-dialog').getByRole('button',{name:'Import repository',exact:true}).click();await page.locator('.zi-dialog').waitFor({state:'detached',timeout:60000});await select();
 await mode(false);await geometry('overview-full',{overview:true});for(const kind of ['branches','tags']){await page.locator('.rp-trigger').click();if(kind==='tags')await page.getByRole('tab',{name:'Tags',exact:true}).click();await button('View all '+kind).click();await page.locator('.rl-page').waitFor();await geometry(kind+'-listing',{overview:true});await page.locator('#repository-code-tab').click();await page.locator('.rc-identity h1').waitFor();await geometry(kind+'-return',{overview:true});}await openReadme();await geometry('file-full');await mode(true);await geometry('file-implemented');await mode(false);await edit();await append(marker);await geometry('edit-full');
 const toggle=page.locator('.fw-titlebar').getByRole('button',{name:/file sidebar/i});
 await page.locator('.cm-content').evaluate(e=>{window.__v3OriginalEditor=e;});
 await toggle.click();await page.locator('.rfe-sidebar').waitFor({state:'hidden'});await geometry('edit-collapsed');assert.equal(await page.locator('.cm-content').evaluate(e=>e===window.__v3OriginalEditor),true);assert.match(await sourceText(),/Private V3 draft/);
 await toggle.click();await page.locator('.rfe-sidebar').waitFor();await geometry('edit-reopened');
 const resize=page.getByRole('separator',{name:'File sidebar width'});const oldWidth=Number(await resize.getAttribute('aria-valuenow'));await resize.focus();await resize.press('ArrowRight');await resize.press('ArrowRight');assert.equal(Number(await resize.getAttribute('aria-valuenow')),oldWidth+32);await geometry('edit-resized');
 const cm=page.locator('.cm-content[contenteditable=true]');await cm.click();await cm.press('Meta+z');assert.doesNotMatch(await sourceText(),/Private V3 draft/);await cm.press('Meta+Shift+z');assert.match(await sourceText(),/Private V3 draft/);record('sidebar-layout-preserves-CM6-node-draft-undo');
 await button('More actions for notes').click();await page.getByRole('menuitem',{name:'Open',exact:true}).click();await page.locator('.rfe-directory-table').waitFor();await geometry('directory-full');await openTreeFile('README.md');await edit();assert.match(await sourceText(),/Private V3 draft/);await cm.press('Meta+z');assert.doesNotMatch(await sourceText(),/Private V3 draft/);await cm.press('Meta+Shift+z');assert.match(await sourceText(),/Private V3 draft/);record('directory-transition-retains-draft-and-undo');
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(390,760));await until(async()=>await page.locator('.rfe').evaluate(e=>e.classList.contains('rfe-narrow')),'narrow');await page.locator('.rfe-sidebar').waitFor({state:'hidden'});const compact=await geometry('narrow-full',{narrow:true});assert.equal(compact.compact,true,'narrow full tabs compact');await toggle.click();await page.locator('.rfe-sidebar').waitFor();await geometry('narrow-drawer',{narrow:true});await toggle.click();await page.locator('.rfe-sidebar').waitFor({state:'hidden'});await mode(true);await geometry('narrow-implemented',{narrow:true});await toggle.click();await page.locator('.rfe-sidebar').waitFor();await geometry('narrow-implemented-drawer',{narrow:true});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1440,1000));await until(async()=>!await page.locator('.rfe').evaluate(e=>e.classList.contains('rfe-narrow')),'wide');assert.match(await sourceText(),/Private V3 draft/);assert.equal(await fs.readFile(source()+'/README.md','utf8'),initial);
 await page.locator('#repository-code-tab').click();if(await button('Leave editor').isVisible())await button('Leave editor').click();await page.locator('.rc-identity h1').waitFor();await geometry('overview-return',{overview:true});await openReadme();await edit();assert.match(await sourceText(),/Private V3 draft/);record('Code-home-navigation-retains-checkpointed-draft');await close();
 await launch();await select();await openReadme();await edit();assert.match(await sourceText(),/Private V3 draft/);assert.equal(await fs.readFile(source()+'/README.md','utf8'),initial);await geometry('restart-draft');record('restart-draft-source-preserved');assert.equal(errors.length,0);assert.equal(consoleErrors.length,0);await close();
}catch(error){failure={message:error.message,stack:error.stack};console.error(error.stack);try{await shot('failure');await fs.writeFile(output+'/failure-dom.txt',await page.locator('body').innerText());}catch{}try{if(app)await close();}catch{}process.exitCode=1;}
finally{await fs.writeFile(output+'/receipt.json',JSON.stringify({status:failure?'failed':'passed',failure,executable,metadata,data,events,errors,consoleErrors,definitionSha256:createHash('sha256').update(await fs.readFile(fileURLToPath(import.meta.url))).digest('hex')},null,2));console.log(JSON.stringify({status:failure?'failed':'passed',output}));}
