import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {validateAutomationFiles,AUTOMATION_VALIDATION_LIMITS} from './automation-validation.mjs';
import {analyzeReferences} from './automation-validation-parser.mjs';
const check=files=>validateAutomationFiles({files,analyzeReferences});
const hash=value=>createHash('sha256').update(value).digest('hex');
const fixture=()=>{const source='<html><body>Offline example</body></html>',fallback='# Fallback\n\nUse the source.';return[{path:'interactive/example.artifact.json',text:JSON.stringify({schemaVersion:1,id:'example',title:'Offline example',entryPath:'example.html',fallbackPath:'fallback.md',network:'none',assets:[{path:'example.html',role:'entry',bytes:Buffer.byteLength(source),sha256:hash(source)},{path:'fallback.md',role:'fallback',bytes:Buffer.byteLength(fallback),sha256:hash(fallback)}]})},{path:'interactive/example.html',text:source},{path:'interactive/fallback.md',text:fallback}];};
test('A05 capability distinctions never imply permission or activate imported code',()=>{const result=check([{path:'a.md',text:'# Notes\n\n$E=mc^2$\n\n```mermaid\ngraph LR\n A-->B\n```'},{path:'demo.html',text:'<script>throw Error("must not run")</script>'},{path:'plot.png',mime:'image/png'},{path:'video.mp4',mime:'video/mp4'},{path:'data.bin'}]);assert.equal(result.schemaVersion,1);assert.equal(result.executionPermitted,false);assert.equal(result.files[0].staticPreview,'markdown-with-math-and-diagram-support');assert.equal(result.files[1].staticPreview,'source');assert.equal(result.files[1].runtimeEligibility,'eligible-for-explicit-review');assert.equal(result.files[2].staticPreview,'image');assert.equal(result.files[3].staticPreview,'platform-dependent-media');assert.equal(result.files[4].staticPreview,'unavailable');assert.ok(result.files.every(file=>file.present&&file.importSupported&&!file.executionPermitted));});
test('Markdown links use existing encoded relative path, heading and image rules',()=>{const result=check([{path:'chapters/current.md',text:'# Current\n\n[Other](../reports/a%20b.md#result) ![Chart](../plot.png) [Missing](../none.md) [Missing heading](../reports/a%20b.md#absent)'},{path:'reports/a b.md',text:'# Title\n\n## Result\n\n30 Hz.'},{path:'plot.png',mime:'image/png'}]);assert.equal(result.issues.filter(issue=>issue.code==='MISSING_LOCAL_REFERENCE').length,1);assert.equal(result.issues.filter(issue=>issue.code==='MISSING_LOCAL_TARGET').length,1);assert.equal(result.issues.length,2);});
test('duplicate headings match the existing renderer suffix and unknown fragments do not guess',()=>{const result=check([{path:'a.md',text:'# Same\n\n# Same\n\n[First](#same) [Second](#same-1) [Absent](#same-2)'}]);assert.deepEqual(result.issues.map(issue=>[issue.code,issue.fragment]),[['MISSING_LOCAL_TARGET','same-2']]);});
test('external reference validation neither fetches nor returns URL secrets',()=>{const result=check([{path:'a.md',text:'[Remote](https://user:password@example.invalid/path?token=private-token) [Email](mailto:someone@example.invalid)'}]);assert.equal(result.issues.length,2);assert.ok(result.issues.every(issue=>issue.code==='EXTERNAL_REFERENCE'&&issue.networkChecked===false));assert.doesNotMatch(JSON.stringify(result),/password|private-token|someone/);});
test('fenced and inert HTML examples are not treated as live Markdown links',()=>{const result=check([{path:'a.md',text:'```md\n[Example](missing.md)\n```\n\n<a href="missing.md">HTML stays source</a>'}]);assert.deepEqual(result.issues,[]);});
test('artifact schema and matching admitted dependency bytes establish only review eligibility',()=>{const result=check(fixture());assert.equal(result.files[0].runtimeEligibility,'eligible-for-explicit-review');assert.equal(result.files[0].executionPermitted,false);assert.deepEqual(result.issues,[]);});
test('missing, changed or uninspected artifact assets cannot become execution permission',()=>{let files=fixture();files[1].text='changed';let result=check(files);assert.equal(result.files[0].runtimeEligibility,'manifest-valid-dependencies-unconfirmed');assert.ok(result.issues.some(issue=>issue.code==='ARTIFACT_DEPENDENCY_CHANGED'));files=fixture().filter(file=>!file.path.endsWith('example.html'));result=check(files);assert.ok(result.issues.some(issue=>issue.code==='MISSING_ARTIFACT_DEPENDENCY'));files=fixture();delete files[1].text;result=check(files);assert.ok(result.issues.some(issue=>issue.code==='DEPENDENCY_NOT_INSPECTED'));assert.equal(result.executionPermitted,false);});
test('unknown artifact schema remains source-readable and reports ineligible',()=>{const result=check([{path:'test.artifact.json',text:'{"schemaVersion":2}'}]);assert.equal(result.files[0].runtimeEligibility,'ineligible');assert.equal(result.files[0].staticPreview,'source');assert.equal(result.issues[0].code,'INVALID_ARTIFACT_MANIFEST');});
test('oversized text and file-count bounds are explicit and bounded',()=>{const result=check([{path:'large.md',text:'x'.repeat(65537)},...Array.from({length:300},(_,index)=>({path:`file${index}.md`,text:'# File'}))]);assert.equal(result.status,'truncated');assert.equal(result.files.length,AUTOMATION_VALIDATION_LIMITS.documents);assert.equal(result.files[0].validation,'limit-exceeded');assert.equal(result.issues[0].code,'LIMIT_EXCEEDED');});
test('a present target omitted from the bounded text set is uninspected rather than missing',()=>{const result=validateAutomationFiles({files:[{path:'a.md',text:'[Heading](b.md#title)'}],inventoryPaths:['a.md','b.md'],analyzeReferences});assert.equal(result.issues[0].code,'TARGET_NOT_INSPECTED');});
test('private/traversal/duplicate paths rejected; ordinary hidden source files admitted',()=>{for(const path of ['../x','/private/x','.git/config','.asmagicbrain/secrets','.asmb-state/x'])assert.throws(()=>check([{path,text:'x'}]),error=>error.code==='INVALID_REQUEST');assert.throws(()=>check([{path:'A.md',text:'x'},{path:'a.md',text:'x'}]));assert.equal(check([{path:'.gitignore',text:'node_modules\n'}]).files[0].staticPreview,'source');});

test('host-reported oversized text is truncated even when bytes were deliberately not read',()=>{const result=check([{path:'large.md',size:1024*1024}]);assert.equal(result.status,'truncated');assert.equal(result.files[0].validation,'limit-exceeded');assert.equal(result.issues[0].code,'LIMIT_EXCEEDED');});
