import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createGitHubUpdates} from '../../packages/desktop-host/src/local-git/github-updates.mjs';
import {createGitHubApply} from '../../packages/desktop-host/src/local-git/github-apply.mjs';

const env={...(process.env.TMPDIR?{TMPDIR:process.env.TMPDIR}:{}),PATH:'/usr/bin:/bin',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_COUNT:'0',GIT_TERMINAL_PROMPT:'0',GIT_AUTHOR_NAME:'Apply test',GIT_AUTHOR_EMAIL:'apply@example.invalid',GIT_COMMITTER_NAME:'Apply test',GIT_COMMITTER_EMAIL:'apply@example.invalid'};
const git=(root,...args)=>execFileSync('/usr/bin/git',['--no-pager','-c','core.hooksPath=/dev/null','-C',root,...args],{env,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();
const inventory=root=>{const result=Object.create(null);const walk=r=>{for(const n of fs.readdirSync(path.join(root,r)).sort()){const p=r?`${r}/${n}`:n,s=fs.lstatSync(path.join(root,p));if(s.isDirectory())walk(p);else result[p]={mode:s.mode&0o777,hash:createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')};}};walk('');return result;};
function commit(root,files){for(const [name,text] of Object.entries(files)){const p=path.join(root,name);if(text===null)fs.unlinkSync(p);else{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,text);}}git(root,'add','--all');git(root,'commit','-m','Change');return git(root,'rev-parse','HEAD');}
async function fixture(t,{hooks={}}={}){
 const parent=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'asmb-apply-')),remote=path.join(parent,'remote'),root=path.join(parent,'root'),state=path.join(parent,'state');for(const p of [remote,state])fs.mkdirSync(p,{mode:0o700});
 git(remote,'init','--initial-branch=main','--template=');const old=commit(remote,{'README.md':'# Old\r\n','remove.md':'Delete me\n','.gitignore':'ignored.txt\n'});git(remote,'tag','v1');git(parent,'clone','--no-hardlinks','--',remote,root);
 const remoteHead=commit(remote,{'README.md':'# New\r\n','remove.md':null,'nested/new.md':'New file\n','binary.bin':Buffer.from([0,255,1]),'exec.sh':'#!/bin/sh\n'});fs.chmodSync(path.join(remote,'exec.sh'),0o755);git(remote,'add','.');git(remote,'commit','-m','Executable');
 const updatesRoot=path.join(state,'updates'),applyRoot=path.join(state,'apply');fs.mkdirSync(updatesRoot,{mode:0o700});fs.mkdirSync(applyRoot,{mode:0o700});
 const updates=createGitHubUpdates({sourceRoot:root,privateRoot:updatesRoot,sourceUrl:'https://github.com/example/repo',branch:'main',hooks:{acquire:async({gitDir})=>{execFileSync('/usr/bin/git',[`--git-dir=${gitDir}`,'fetch','--no-tags','--no-write-fetch-head','--no-auto-maintenance','--',remote,'refs/heads/main:refs/asmb-check/remote'],{env,stdio:'pipe'});return git(remote,'rev-parse','HEAD');}}});
 const check=await updates.check({requestId:randomUUID(),localHead:old,localBranch:'main'});const options={sourceRoot:root,privateRoot:applyRoot,snapshots:updates,hooks},manager=createGitHubApply(options);
 t.after(()=>fs.rmSync(parent,{recursive:true,force:true}));return {parent,root,remote,old,remoteHead,check,manager,options,updates,applyRoot,updatesRoot};
}
test('offline clean fast-forward applies exact binary/text/mode/add/delete bytes, preserves remotes/tags and replays idempotently',async t=>{
 const f=await fixture(t),config=fs.readFileSync(path.join(f.root,'.git/config')),tags=git(f.root,'show-ref','--tags');const review=await f.manager.review({checkId:f.check.checkId});assert.equal(review.canApply,true,JSON.stringify(review));
 const request={checkId:f.check.checkId,reviewId:review.reviewId,requestId:randomUUID()};let admitted=0;const result=await f.manager.apply(request,{onAdmission:async()=>{admitted++;assert.equal(git(f.root,'rev-parse','HEAD'),f.old);assert.equal(fs.readFileSync(path.join(f.root,'README.md'),'utf8'),'# Old\r\n');}});
 assert.equal(result.status,'applied');assert.equal(admitted,1);assert.equal(result.head,git(f.remote,'rev-parse','HEAD'));assert.equal(git(f.root,'status','--porcelain'),'');assert.equal(fs.readFileSync(path.join(f.root,'README.md'),'utf8'),'# New\r\n');assert.deepEqual(fs.readFileSync(path.join(f.root,'binary.bin')),Buffer.from([0,255,1]));assert.equal(fs.statSync(path.join(f.root,'exec.sh')).mode&0o111,0o111);assert.equal(fs.existsSync(path.join(f.root,'remove.md')),false);assert.deepEqual(fs.readFileSync(path.join(f.root,'.git/config')),config);assert.equal(git(f.root,'show-ref','--tags'),tags);
 const before=inventory(f.root);assert.deepEqual(await f.manager.apply(request),result);assert.deepEqual(inventory(f.root),before);assert.deepEqual(await createGitHubApply(f.options).recover(),{status:'idle'});await assert.rejects(f.manager.apply({...request,reviewId:randomUUID()}),{code:'APPLY_REQUEST_REUSED'});
});
test('review refuses raw hidden edits, ignored/untracked files, empty directories, staged changes and private drafts without writes',async t=>{
 for(const kind of ['tracked','assume','skip','ignored','untracked','empty','staged','draft'])await t.test(kind,async t=>{const f=await fixture(t);if(kind==='assume')git(f.root,'update-index','--assume-unchanged','README.md');if(kind==='skip')git(f.root,'update-index','--skip-worktree','README.md');if(['tracked','assume','skip','staged'].includes(kind))fs.writeFileSync(path.join(f.root,'README.md'),'Local bytes');if(kind==='staged')git(f.root,'add','README.md');if(['ignored','untracked'].includes(kind))fs.writeFileSync(path.join(f.root,kind==='ignored'?'ignored.txt':'untracked.md'),'Own bytes');if(kind==='empty')fs.mkdirSync(path.join(f.root,'empty'));const before=inventory(f.root),review=await f.manager.review({checkId:f.check.checkId},{validateContext:async()=>({draftCount:kind==='draft'?1:0})});assert.equal(review.canApply,false);assert.equal(review.reason,kind==='draft'?'drafts':'saved-changes');assert.deepEqual(inventory(f.root),before);});
});
test('apply rechecks saved bytes, branch/index and drafts after review before admission',async t=>{
 for(const kind of ['bytes','branch','index','draft'])await t.test(kind,async t=>{const f=await fixture(t),review=await f.manager.review({checkId:f.check.checkId});if(kind==='bytes')fs.writeFileSync(path.join(f.root,'README.md'),'Changed after review');if(kind==='branch')git(f.root,'checkout','-b','other');if(kind==='index')git(f.root,'update-index','--assume-unchanged','README.md');const before=inventory(f.root);let admitted=false;await assert.rejects(f.manager.apply({checkId:f.check.checkId,reviewId:review.reviewId,requestId:randomUUID()},{validateContext:async()=>({draftCount:kind==='draft'?1:0}),onAdmission:async()=>{admitted=true;}}));assert.equal(admitted,false);assert.deepEqual(inventory(f.root),before);});
});
test('recognized interrupted publication rolls forward; unknown external bytes cause preserved recovery hold',async t=>{
 for(const point of ['apply-intent','apply-staged','apply-before-file','apply-after-file','apply-before-ref','apply-after-ref','apply-after-index','apply-complete'])await t.test(point,async t=>{let once=true;const f=await fixture(t,{hooks:{at:phase=>{if(once&&phase===point){once=false;throw Object.assign(new Error('interruption'),{code:'TEST_STOP'});}}}}),review=await f.manager.review({checkId:f.check.checkId});await assert.rejects(f.manager.apply({checkId:f.check.checkId,reviewId:review.reviewId,requestId:randomUUID()}),{code:'APPLY_RECOVERY_REQUIRED'});const reopened=createGitHubApply({...f.options,hooks:{}}),recovery=await reopened.recover();assert.equal(recovery.status,'recovered',JSON.stringify(recovery));assert.equal(git(f.root,'rev-parse','HEAD'),git(f.remote,'rev-parse','HEAD'));assert.equal(git(f.root,'status','--porcelain'),'');assert.equal(reopened.inspect().recoveryRequired,false);});
 const f=await fixture(t,{hooks:{at:phase=>{if(phase==='apply-after-file')throw new Error('stop');}}}),r=await f.manager.review({checkId:f.check.checkId});await assert.rejects(f.manager.apply({checkId:f.check.checkId,reviewId:r.reviewId,requestId:randomUUID()}));fs.writeFileSync(path.join(f.root,'README.md'),'External bytes must survive');const before=inventory(f.root),recovery=await createGitHubApply({...f.options,hooks:{}}).recover();assert.equal(recovery.status,'held');assert.deepEqual(inventory(f.root),before);
});

test('worker stops between retain/link/unlink preserve bytes and recover despite phase-marker lag',async t=>{
 for(const point of ['retain','link','unlink'])await t.test(point,async t=>{const f=await fixture(t,{hooks:{workerStopAfter:point}}),r=await f.manager.review({checkId:f.check.checkId});await assert.rejects(f.manager.apply({checkId:f.check.checkId,reviewId:r.reviewId,requestId:randomUUID()}),{code:'APPLY_RECOVERY_REQUIRED'});const recovery=await createGitHubApply({...f.options,hooks:{}}).recover();assert.equal(recovery.status,'recovered',JSON.stringify(recovery));assert.equal(git(f.root,'status','--porcelain'),'');assert.equal(git(f.root,'rev-parse','HEAD'),git(f.remote,'rev-parse','HEAD'));});
});

test('actual stopped host processes resume admitted updates before or after ref/index publication',async t=>{
 for(const point of ['apply-intent','apply-after-file','apply-after-ref','apply-after-index','apply-complete'])await t.test(point,async t=>{
  const f=await fixture(t),requestId=randomUUID();
  const script=`import {createGitHubUpdates} from ${JSON.stringify(new URL('../../packages/desktop-host/src/local-git/github-updates.mjs',import.meta.url).href)};import {createGitHubApply} from ${JSON.stringify(new URL('../../packages/desktop-host/src/local-git/github-apply.mjs',import.meta.url).href)};const updates=createGitHubUpdates({sourceRoot:${JSON.stringify(f.root)},privateRoot:${JSON.stringify(f.updatesRoot)},sourceUrl:'https://github.com/example/repo',branch:'main'});const manager=createGitHubApply({sourceRoot:${JSON.stringify(f.root)},privateRoot:${JSON.stringify(f.applyRoot)},snapshots:updates,hooks:{at:p=>{if(p===${JSON.stringify(point)})process.exit(86);}}});const review=await manager.review({checkId:${JSON.stringify(f.check.checkId)}});await manager.apply({checkId:${JSON.stringify(f.check.checkId)},reviewId:review.reviewId,requestId:${JSON.stringify(requestId)}});process.exit(87);`;
  assert.throws(()=>execFileSync(process.execPath,['--input-type=module','-e',script],{env:{...process.env,...(process.versions.electron?{ELECTRON_RUN_AS_NODE:'1'}:{})},stdio:'pipe'}),e=>e.status===86);
  const recovery=await createGitHubApply({...f.options,hooks:{}}).recover();assert.equal(recovery.status,'recovered');assert.equal(git(f.root,'status','--porcelain'),'');assert.equal(git(f.root,'rev-parse','HEAD'),git(f.remote,'rev-parse','HEAD'));
 });
});

async function refresh(f){return f.updates.check({requestId:randomUUID(),localHead:git(f.root,'rev-parse','HEAD'),localBranch:'main'});}
test('large binaries and prototype-like filenames remain real tracked entries; old empty directories retire cleanly',async t=>{
 const f=await fixture(t);commit(f.remote,Object.fromEntries([['__proto__','Prototype bytes'],['constructor','Constructor'],['toString','String'],['nested/__proto__','Nested'],['large.bin',Buffer.alloc(5*1024*1024,73)]]));let check=await refresh(f),review=await f.manager.review({checkId:check.checkId});assert.equal(review.canApply,true);await f.manager.apply({checkId:check.checkId,reviewId:review.reviewId,requestId:randomUUID()});assert.equal(fs.readFileSync(path.join(f.root,'__proto__'),'utf8'),'Prototype bytes');assert.equal(fs.statSync(path.join(f.root,'large.bin')).size,5*1024*1024);assert.equal(git(f.root,'status','--porcelain'),'');
 commit(f.remote,{'nested/new.md':null,'nested/__proto__':null,'README.md':'Next update'});check=await refresh(f);review=await f.manager.review({checkId:check.checkId});assert.equal(review.canApply,true);await f.manager.apply({checkId:check.checkId,reviewId:review.reviewId,requestId:randomUUID()});assert.equal(fs.existsSync(path.join(f.root,'nested')),false);commit(f.remote,{'README.md':'Another update'});check=await refresh(f);assert.equal((await f.manager.review({checkId:check.checkId})).canApply,true);
 fs.writeFileSync(path.join(f.root,'__proto__'),'Modified own bytes');const before=inventory(f.root);assert.equal((await f.manager.review({checkId:check.checkId})).reason,'saved-changes');assert.deepEqual(inventory(f.root),before);
});

test('unsupported transitions/types/names and partial comparisons are blocked before admission',async t=>{
 for(const kind of ['nonportable','symlink','gitlink','file-directory','partial'])await t.test(kind,async t=>{const f=await fixture(t);if(kind==='nonportable')commit(f.remote,{'a:b.md':'Existing Git name'});if(kind==='symlink'){fs.symlinkSync('README.md',path.join(f.remote,'link.md'));git(f.remote,'add','.');git(f.remote,'commit','-m','Link');}if(kind==='gitlink'){git(f.remote,'update-index','--add','--cacheinfo',`160000,${f.old},submodule`);git(f.remote,'commit','-m','Gitlink');}if(kind==='file-directory'){fs.unlinkSync(path.join(f.remote,'README.md'));commit(f.remote,{'README.md/inside.md':'Transition'});}if(kind==='partial'){const files={};for(let i=0;i<1001;i++)files[`many/${i}.md`]='new';commit(f.remote,files);}const check=await refresh(f),before=inventory(f.root),review=await f.manager.review({checkId:check.checkId});assert.equal(review.canApply,false);assert.equal(review.reason,kind==='partial'?'partial':'unsupported');assert.deepEqual(inventory(f.root),before);});
});

test('source hooks/filters/fsmonitor configuration cannot transform bytes or execute during apply',async t=>{
 const f=await fixture(t),sentinel=path.join(f.parent,'executed'),script=path.join(f.parent,'hook.sh');fs.writeFileSync(script,`#!/bin/sh\ntouch '${sentinel}'\ncat\n`,{mode:0o755});git(f.root,'config','core.hooksPath',f.parent);git(f.root,'config','core.fsmonitor',script);git(f.root,'config','filter.danger.smudge',script);git(f.root,'config','filter.danger.clean',script);fs.copyFileSync(script,path.join(f.parent,'reference-transaction'));fs.chmodSync(path.join(f.parent,'reference-transaction'),0o755);commit(f.remote,{'.gitattributes':'*.md filter=danger\n','README.md':'Untransformed bytes'});const check=await refresh(f),review=await f.manager.review({checkId:check.checkId});assert.equal(review.canApply,true);await f.manager.apply({checkId:check.checkId,reviewId:review.reviewId,requestId:randomUUID()});assert.equal(fs.existsSync(sentinel),false);assert.equal(fs.readFileSync(path.join(f.root,'README.md'),'utf8'),'Untransformed bytes');
});

test('external branch/index/untouched bytes at final publication boundary hold without overwriting that change',async t=>{
 for(const kind of ['branch','index','untouched'])await t.test(kind,async t=>{
  let root;const f=await fixture(t,{hooks:{at:phase=>{if(phase!=='apply-before-ref')return;if(kind==='branch')git(root,'symbolic-ref','HEAD','refs/heads/other');if(kind==='index')fs.appendFileSync(path.join(root,'.git/index'),'external');if(kind==='untouched')fs.writeFileSync(path.join(root,'.gitignore'),'External ignore bytes');}}});root=f.root;const review=await f.manager.review({checkId:f.check.checkId});await assert.rejects(f.manager.apply({checkId:f.check.checkId,reviewId:review.reviewId,requestId:randomUUID()}),{code:'APPLY_RECOVERY_REQUIRED'});assert.equal(git(root,'rev-parse','refs/heads/main'),f.old);const before=inventory(root);assert.equal((await createGitHubApply({...f.options,hooks:{}}).recover()).status,'held');assert.deepEqual(inventory(root),before);
 });
});

test('successive identical-tree incoming commit recovers after index publication with no remaining lock',async t=>{
 const f=await fixture(t);let review=await f.manager.review({checkId:f.check.checkId});await f.manager.apply({checkId:f.check.checkId,reviewId:review.reviewId,requestId:randomUUID()});
 // Do not run git status here: a stat-cache refresh would obscure the identical
 // read-tree indexes exercised by an empty incoming commit.
 git(f.remote,'commit','--allow-empty','-m','Incoming history-only change');const check=await refresh(f);assert.equal(check.totalFiles,0);assert.equal(check.behind,1);
 const manager=createGitHubApply({...f.options,hooks:{at:phase=>{if(phase==='apply-after-index')throw new Error('stop');}}});review=await manager.review({checkId:check.checkId});assert.equal(review.canApply,true);
 await assert.rejects(manager.apply({checkId:check.checkId,reviewId:review.reviewId,requestId:randomUUID()}),{code:'APPLY_RECOVERY_REQUIRED'});assert.equal(fs.existsSync(path.join(f.root,'.git/index.lock')),false);
 const recovery=await createGitHubApply({...f.options,hooks:{}}).recover();assert.equal(recovery.status,'recovered');assert.equal(git(f.root,'rev-parse','HEAD'),git(f.remote,'rev-parse','HEAD'));assert.equal(git(f.root,'status','--porcelain'),'');
});
