import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createNativeService} from './host-service.mjs';
async function fixture(t,hooks={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'teach-pipeline-'));let service=await createNativeService({dataRoot:path.join(root,'profile'),hooks});t.after(async()=>{await service.close();fs.rmSync(root,{recursive:true,force:true});});const course=await service.teachRequest({operation:'create',requestId:randomUUID(),code:'TEST101',name:'Pipeline',year:2026,season:'autumn'});await service.createRepository({name:'Assistants',requestId:randomUUID()});return {root,course,get service(){return service;},restart:async()=>{await service.close();service=await createNativeService({dataRoot:path.join(root,'profile'),hooks});}};}
const teach=(f,value)=>f.service.teachRequest(value);
test('project sibling repositories are local, restart-safe and independent of course roles',async t=>{
 const f=await fixture(t);await bind(f);
 const review=await teach(f,{operation:'reviewProjectCreation',repo:f.course.repo,year:2026,season:'autumn',count:8});
 assert.equal(review.teams.length,8);
 await teach(f,{operation:'applyProjectCreation',planId:review.planId});
 const before=await teach(f,{operation:'projectSettings',repo:f.course.repo});
 assert.equal(before.projects.length,8);
 assert.equal(new Set(before.projects.map(p=>p.bindingId)).size,8);
 const team=before.projects[0];
 assert.match((await f.service.request({repo:team.name,operation:'open',args:{path:'SUBMISSION.md'}})).text,/A push is not a submission/);
 await f.restart();
 const after=await teach(f,{operation:'projectSettings',repo:f.course.repo});
 assert.deepEqual(after.projects.map(p=>p.id),before.projects.map(p=>p.id));
 assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).roles.length,3);
 assert.equal((await teach(f,{operation:'reviewProjectCreation',repo:f.course.repo,year:2026,season:'autumn',count:8})).planId,null);
});
test('Assistant contributions preserve authoritative Instructor pages',async t=>{
 const f=await fixture(t);await bind(f);await populate(f);
 await teach(f,{operation:'applyPromotion',planId:(await teach(f,request(f))).planId});
 const before=(await f.service.request({repo:f.course.repo,operation:'open',args:{path:'2026-autumn/student.md'}})).text;
 const review=await teach(f,{...request(f),fromRole:'assistants',toRole:'instructors',destination:f.course.repo});
 assert.ok(review.files.every(v=>v.path.startsWith('2026-autumn/contributions/assistants/')));
 await teach(f,{operation:'applyPromotion',planId:review.planId});
 assert.equal((await f.service.request({repo:f.course.repo,operation:'open',args:{path:'2026-autumn/student.md'}})).text,before);
 assert.equal((await f.service.request({repo:f.course.repo,operation:'open',args:{path:'2026-autumn/contributions/assistants/student.md'}})).text,before);
});
async function bind(f){const settings=await teach(f,{operation:'pipelineSettings',repo:f.course.repo});const preview=await teach(f,{operation:'reviewRepositoryGraph',repo:f.course.repo,assistantId:settings.repositories.find(e=>e.name==='Assistants').stableId});assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).migrated,false);return teach(f,{operation:'applyRepositoryGraph',planId:preview.planId});}
async function file(f,repo,p,text){return f.service.request({repo,operation:'create',args:{path:p,text}});}
const request=f=>({operation:'reviewPromotion',repo:f.course.repo,year:2026,season:'autumn',fromRole:'instructors',toRole:'assistants',destination:'Assistants',paths:['2026-autumn/student.md','2026-autumn/run.py','2026-autumn/model.xml','2026-autumn/LICENSE']});
async function populate(f){await file(f,f.course.repo,'2026-autumn/student.md','# Student\n\n[Code](run.py)\n');await file(f,f.course.repo,'2026-autumn/run.py','print("no execution during publication")\n');await file(f,f.course.repo,'2026-autumn/model.xml','<mujoco/>\n');await file(f,f.course.repo,'2026-autumn/LICENSE','Example license\n');}
test('graph preview does not migrate; explicit binding survives restart and rename, preserving course bytes/calendar',async t=>{const f=await fixture(t),before=fs.readFileSync(path.join(f.root,'profile/workspaces/asMagicBrain',f.course.repo,'.asteach/course.json'));const settings=await bind(f);assert.equal(settings.roles[1].name,'Assistants');assert.equal(settings.roles[1].observedVisibility,null);await f.restart();assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).revision,1);await f.service.renameRepository({repository:'Assistants',name:'Support'});assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).roles[1].name,'Support');assert.deepEqual(fs.readFileSync(path.join(f.root,'profile/workspaces/asMagicBrain',f.course.repo,'.asteach/course.json')),before);assert.equal((await teach(f,{operation:'list'})).length,1);assert.deepEqual((await teach(f,{operation:'list'}))[0].settings,f.course.settings);});
test('stale migration and cross-course binding refuse without modifying pair',async t=>{const f=await fixture(t),settings=await teach(f,{operation:'pipelineSettings',repo:f.course.repo}),preview=await teach(f,{operation:'reviewRepositoryGraph',repo:f.course.repo,assistantId:settings.repositories.find(e=>e.name==='Assistants').stableId});await f.service.renameRepository({repository:'Assistants',name:'Support'});await assert.rejects(teach(f,{operation:'applyRepositoryGraph',planId:preview.planId}),{code:'CONFLICT'});await assert.rejects(teach(f,{operation:'reviewRepositoryGraph',repo:f.course.repo,assistantId:settings.roles[2].repositoryId}),{code:'TEACH_GRAPH_INVALID'});assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).migrated,false);});
test('runnable manifest promotion is local, repeatable, preserves unselected additions, and rejects changed destinations',async t=>{const f=await fixture(t);await bind(f);await populate(f);let review=await teach(f,request(f));assert.equal(review.files.length,4);const result=await teach(f,{operation:'applyPromotion',planId:review.planId});assert.equal(result.localOnly,true);assert.equal(result.sourceCommit,null);assert.equal((await f.service.request({repo:'Assistants',operation:'open',args:{path:'2026-autumn/run.py'}})).text,'print("no execution during publication")\n');await f.restart();await file(f,'Assistants','2026-autumn/notes.md','Independent\n');review=await teach(f,{...request(f),paths:['2026-autumn/run.py']});await teach(f,{operation:'applyPromotion',planId:review.planId});assert.equal((await f.service.request({repo:'Assistants',operation:'open',args:{path:'2026-autumn/run.py'}})).text,'print("no execution during publication")\n');review=await teach(f,request(f));const current=await f.service.request({repo:'Assistants',operation:'open',args:{path:'2026-autumn/run.py'}});await f.service.request({repo:'Assistants',operation:'save',args:{path:current.path,baseHash:current.sourceHash,text:'local edit\n'}});await assert.rejects(teach(f,{operation:'applyPromotion',planId:review.planId}));assert.equal((await f.service.request({repo:'Assistants',operation:'open',args:{path:'2026-autumn/notes.md'}})).text,'Independent\n');assert.equal((await f.service.read({repo:'Assistants'})).commitCount,0);});
test('source changes, drafts, missing dependency and private/credential files refuse',async t=>{const f=await fixture(t);await bind(f);await populate(f);await file(f,f.course.repo,'2026-autumn/private.md','private');await assert.rejects(teach(f,{...request(f),paths:['2026-autumn/private.md']}),{code:'PROMOTION_PRIVATE_FILE'});await assert.rejects(teach(f,{...request(f),paths:['2026-autumn/student.md']}),{code:'PROMOTION_DEPENDENCY'});await file(f,f.course.repo,'2026-autumn/key.txt','-----BEGIN PRIVATE KEY-----\n');await assert.rejects(teach(f,{...request(f),paths:['2026-autumn/key.txt']}),{code:'PROMOTION_SECRET'});const review=await teach(f,request(f));const current=await f.service.request({repo:f.course.repo,operation:'open',args:{path:'2026-autumn/run.py'}});await f.service.request({repo:f.course.repo,operation:'save',args:{path:current.path,baseHash:current.sourceHash,text:'changed\n'}});await assert.rejects(teach(f,{operation:'applyPromotion',planId:review.planId}),{code:'CONFLICT'});await f.service.request({repo:f.course.repo,operation:'checkpoint',args:{path:current.path,baseHash:(await f.service.request({repo:f.course.repo,operation:'open',args:{path:current.path}})).sourceHash,text:'draft\n'}});await assert.rejects(teach(f,request(f)),{code:'DRAFT_CONFLICT'});});

test('interrupted journaled copy recovers explicitly and retains source provenance across restart',async t=>{
 let interrupt=true;const f=await fixture(t,{packageAt:phase=>{if(interrupt&&phase==='exchange-after-step'){interrupt=false;throw Error('injected interruption');}}});await bind(f);await populate(f);const review=await teach(f,request(f));await assert.rejects(teach(f,{operation:'applyPromotion',planId:review.planId}));await f.restart();const pending=(await f.service.packageStatus({repo:'Assistants'})).pending;assert.ok(pending);await f.service.recoverPackageUpdate({repo:'Assistants',operationId:pending.operationId,direction:'resume'});await teach(f,{operation:'resolvePromotion',repo:f.course.repo,direction:'complete'});const settings=await teach(f,{operation:'pipelineSettings',repo:f.course.repo});assert.equal(settings.provenance.pending,null);assert.equal(settings.provenance.last.files.length,4);await f.restart();assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).provenance.last.sourceRole,'instructors');
});
test('Assistant promotion to Students preserves independent Git history and adds GitBook navigation',async t=>{const f=await fixture(t);await bind(f);await populate(f);let review=await teach(f,request(f));await teach(f,{operation:'applyPromotion',planId:review.planId});review=await teach(f,{...request(f),fromRole:'assistants',toRole:'students',destination:'TEST101_Students'});assert.equal(review.files.length,6);await teach(f,{operation:'applyPromotion',planId:review.planId});assert.match((await f.service.request({repo:'TEST101_Students',operation:'open',args:{path:'2026-autumn/SUMMARY.md'}})).text,/student.md/);await assert.rejects(teach(f,{...request(f),fromRole:'instructors',toRole:'students',destination:'TEST101_Students',paths:['2026-autumn/instructor.md']}),{code:'PROMOTION_PRIVATE_FILE'});assert.equal((await f.service.read({repo:'TEST101_Students'})).commitCount,0);});

test('local staff roster persists in private state and account pause/resume is honored',async t=>{const f=await fixture(t);await bind(f);assert.equal((await teach(f,{operation:'pipelineSettings',repo:f.course.repo})).staff.roster.revision,0);await f.service.pauseTeachGitHub();await assert.rejects(teach(f,{operation:'saveCourseStaff',repo:f.course.repo,entries:[{login:'as-wanfang',role:'assistant'}],revision:0}),{code:'GITHUB_BUSY'});f.service.resumeTeachGitHub();await teach(f,{operation:'saveCourseStaff',repo:f.course.repo,entries:[{login:'ancorasir',role:'instructor'},{login:'as-wanfang',role:'assistant'}],revision:0});await f.restart();const settings=await teach(f,{operation:'pipelineSettings',repo:f.course.repo});assert.equal(settings.staff.roster.revision,1);assert.equal(settings.staff.roster.entries[1].login,'as-wanfang');await assert.rejects(teach(f,{operation:'saveCourseStaff',repo:f.course.repo,entries:[],revision:0}),{code:'CONFLICT'});assert.equal(fs.existsSync(path.join(f.root,'profile/workspaces/asMagicBrain',f.course.repo,'.asmb-teach-staff')),false);});
