import {spawn} from 'node:child_process';
import {testRoot} from '../../tools/development-paths.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {resolveBuildConfiguration} from './build-channel.mjs';
import {nativeProfilePaths} from './profile-paths.mjs';
import {runtimeSpec} from './native-runtime.mjs';
const appRoot = fileURLToPath(new URL('../../', import.meta.url));
const runtime = runtimeSpec();
const args = process.argv.slice(2);
if (args.some(arg => !arg.startsWith('--channel=') && !arg.startsWith('--test-user-home='))) throw Error('Use launch.mjs [--channel=development|preview] [--test-user-home=/absolute/Test/home].');
const configuration = resolveBuildConfiguration({args});
const homeArguments = args.filter(arg => arg.startsWith('--test-user-home='));
if (configuration.channel === 'development' && homeArguments.length) throw Error('The development launcher retains its isolated native-preview Test data.');
if (configuration.channel === 'preview' && homeArguments.length !== 1) throw Error('Source preview validation requires an explicit --test-user-home inside asMagicBrain-Test.');
const profileArguments = configuration.channel === 'development' ? [`--test-data-root=${path.join(testRoot, 'native-preview', 'data')}`] : homeArguments;
nativeProfilePaths({args: profileArguments, testRoot, packaged: false, appData: '/unused', channel: configuration.channel});
if (process.platform !== runtime.platform || process.arch !== runtime.arch) throw Error('Use the Electron runtime prepared for this operating system and processor.');
const executable = path.join(appRoot, runtime.executable);
if (!fs.existsSync(executable)) throw Error('Prepare the pinned Electron runtime first: npm run native:runtime.');
if (!fs.existsSync(new URL('./dist/index.html', import.meta.url))) throw Error('Build the native renderer first: npm run native:build.');
const temporary = path.join(testRoot, ...(configuration.channel === 'development' ? ['native-preview', 'tmp'] : ['runs', 'native-preview-validation', 'launcher-tmp']));
fs.mkdirSync(temporary, {recursive: true, mode: 0o700});
const env = {...process.env, TMPDIR: temporary};
for (const key of ['NODE_OPTIONS', 'NODE_PATH', 'ELECTRON_RUN_AS_NODE']) delete env[key];
const child = spawn(executable, [fileURLToPath(new URL('./main.mjs', import.meta.url)), `--channel=${configuration.channel}`, ...profileArguments], {cwd: appRoot, env, stdio: 'inherit'});
child.on('error', error => {console.error(error.message); process.exitCode = 1;});
child.on('exit', code => {process.exitCode = code ?? 1;});
// Quit from the native window/menu so pending drafts can be preserved.
