import path from 'node:path';
import fs from 'node:fs';
import {buildConfiguration} from './build-channel.mjs';

function profileError(code, message) {return Object.assign(new Error(message), {code});}
function lstatOrNull(filename) {
  try {return fs.lstatSync(filename);} catch (error) {if (error.code === 'ENOENT') return null; throw error;}
}
function within(parent, child) {return child.startsWith(parent + path.sep);}

/** Inspect all existing ancestors without creating or following a linked directory. */
function physicalDirectoryState(directory) {
  const parent = path.dirname(directory);
  if (parent !== directory) physicalDirectoryState(parent);
  const stat = lstatOrNull(directory);
  if (stat && (!stat.isDirectory() || stat.isSymbolicLink() || fs.realpathSync(directory) !== directory)) {
    throw profileError('ASMB_PROFILE_PATH', 'A physical application directory is required. Linked paths and files are preserved.');
  }
  return stat;
}

/** Validate every existing parent before creating a profile child. */
export function ensurePhysicalDirectory(directory) {
  const absolute = path.resolve(directory), parent = path.dirname(absolute);
  if (parent !== absolute) ensurePhysicalDirectory(parent);
  try {fs.mkdirSync(absolute, {mode: 0o700});} catch (error) {if (error.code !== 'EEXIST') throw error;}
  physicalDirectoryState(absolute);
  return absolute;
}

/** Development package metadata is generated by the packager, outside renderer control. */
export function packagedTestRoot(metadata) {
  if (metadata?.schemaVersion !== 1 || typeof metadata.testRoot !== 'string' ||
      !path.isAbsolute(metadata.testRoot) || path.dirname(path.resolve(metadata.testRoot)) === path.resolve(metadata.testRoot)) {
    throw Error('This development package has invalid test-directory metadata.');
  }
  return path.resolve(metadata.testRoot);
}

/** Callers supply OS paths; installed preview keeps its Electron profile separate. */
export function installedProfilePaths({home, appData, channel = 'development'}) {
  buildConfiguration(channel);
  if (![home, appData].every(value => typeof value === 'string' && path.isAbsolute(value))) {
    throw profileError('ASMB_PROFILE_PATH', 'Absolute user home and application-data paths are required.');
  }
  const dataRoot = path.join(home, 'asMagicBrain');
  const profileRoot = path.join(appData, channel === 'preview' ? 'asMagicBrain Preview' : 'asMagicBrain');
  return {dataRoot, profileRoot, temporaryRoot: path.join(profileRoot, 'tmp')};
}

function testOverride(args, testRoot) {
  const matches = args.filter(arg => arg.startsWith('--test-data-root=') || arg.startsWith('--test-user-home='));
  if (matches.length > 1) throw profileError('ASMB_PROFILE_ARGUMENT', 'Use one native test data root or test user home.');
  if (!matches.length) return null;
  const requested = matches[0].slice(matches[0].indexOf('=') + 1);
  if (typeof testRoot !== 'string' || !path.isAbsolute(testRoot) || !path.isAbsolute(requested) || !within(path.resolve(testRoot), path.resolve(requested))) {
    throw profileError('ASMB_PROFILE_ARGUMENT', 'Native test data must be inside the explicitly approved asMagicBrain-Test directory.');
  }
  return {home: matches[0].startsWith('--test-user-home='), root: path.resolve(requested)};
}

export function nativeProfilePaths({args = [], testRoot, packaged, home, appData, platform = process.platform, channel = 'development'}) {
  buildConfiguration(channel);
  const override = testOverride(args, testRoot);
  if (channel === 'preview' && ((!packaged && !override) || (override && !override.home))) {
    throw profileError('ASMB_PROFILE_ARGUMENT', 'Preview source and test launches require an explicit --test-user-home inside the approved asMagicBrain-Test directory.');
  }
  if (override?.home) {
    if (channel === 'preview' && ['native-preview', 'packaged-preview'].some(name => override.root === path.join(testRoot, name) || within(path.join(testRoot, name), override.root))) {
      throw profileError('ASMB_PROFILE_ARGUMENT', 'Preview cannot use an existing development profile location.');
    }
    const relativeAppData = platform === 'darwin' ? 'Library/Application Support' : platform === 'win32' ? 'AppData/Roaming' : '.config';
    return installedProfilePaths({home: override.root, appData: path.join(override.root, relativeAppData), channel});
  }
  if (channel === 'preview') return installedProfilePaths({home, appData, channel});
  let dataRoot, profileRoot;
  if (override) {
    dataRoot = override.root;
    profileRoot = dataRoot + '-electron-profile';
  } else if (packaged) {
    if (typeof testRoot !== 'string' || !path.isAbsolute(testRoot)) throw profileError('ASMB_PROFILE_ARGUMENT', 'The development package requires its recorded Test directory.');
    dataRoot = path.join(testRoot, 'packaged-preview', 'data');
    profileRoot = dataRoot + '-electron-profile';
  } else {
    profileRoot = path.join(appData, 'asMagicBrain Native Preview');
    dataRoot = path.join(profileRoot, 'managed-data');
  }
  return {dataRoot, profileRoot, temporaryRoot: path.join(profileRoot, 'tmp')};
}

const ownershipFilename = '.asmagicbrain-channel.json';
function readOwnership(directory) {
  const filename = path.join(directory, ownershipFilename), stat = lstatOrNull(filename);
  if (!stat) return null;
  if (!stat.isFile() || stat.isSymbolicLink() || stat.nlink !== 1 || fs.realpathSync(filename) !== filename) {
    throw profileError('ASMB_PROFILE_OWNERSHIP', 'A physical native channel ownership record is required. Existing data is preserved.');
  }
  if (stat.size > 4096) throw profileError('ASMB_PROFILE_OWNERSHIP', 'The native ownership record is too large. Existing data is preserved.');
  const content = fs.readFileSync(filename, 'utf8');
  let value;
  try {value = JSON.parse(content);} catch {
    throw profileError('ASMB_PROFILE_OWNERSHIP', 'The native ownership record is incomplete or invalid. Existing data is preserved; inspect this directory before retrying.');
  }
  const keys = Object.keys(value ?? {}).sort().join(',');
  if (!(value?.schemaVersion === 1 && keys === 'channel,schemaVersion') &&
      !(value?.schemaVersion === 2 && keys === 'channel,dataRoot,profileRoot,role,schemaVersion' &&
        value.channel === 'preview' && ['data', 'profile'].includes(value.role) &&
        [value.dataRoot, value.profileRoot].every(name => typeof name === 'string' && path.isAbsolute(name)))) {
    throw profileError('ASMB_PROFILE_OWNERSHIP', 'Invalid native channel ownership record. Existing data is preserved.');
  }
  buildConfiguration(value.channel);
  return value;
}

function writeOwnership(directory, value) {
  physicalDirectoryState(directory);
  const filename = path.join(directory, ownershipFilename);
  // Exclusive creation never repairs or replaces an incomplete record. An interrupted
  // mkdir/write must remain a closed admission failure, not become permission to adopt data.
  const fd = fs.openSync(filename, fs.constants.O_WRONLY | fs.constants.O_CREAT | fs.constants.O_EXCL | fs.constants.O_NOFOLLOW, 0o600);
  try {fs.writeFileSync(fd, JSON.stringify(value) + '\n'); fs.fsyncSync(fd);} finally {fs.closeSync(fd);}
  const directoryFd = fs.openSync(directory, fs.constants.O_RDONLY);
  try {fs.fsyncSync(directoryFd);} finally {fs.closeSync(directoryFd);}
}

function rejectForeignOwner(owner, channel) {
  if (owner && owner.channel !== channel) throw profileError('ASMB_PROFILE_OWNERSHIP', 'This directory belongs to another native build channel. Existing data is preserved.');
}

function matchesPreviewOwner(owner, role, paths) {
  return owner?.schemaVersion === 2 && owner.channel === 'preview' && owner.role === role &&
    owner.dataRoot === paths.dataRoot && owner.profileRoot === paths.profileRoot;
}

/** Read-only proof for host first-run initialization. Only this exact marker may
 * be excluded from an otherwise empty root; arbitrary files remain existing data.
 */
export function hasPreviewDataOwnership(dataRoot) {
  if (typeof dataRoot !== 'string' || !path.isAbsolute(dataRoot) || path.resolve(dataRoot) !== dataRoot) throw profileError('ASMB_PROFILE_PATH', 'An absolute physical managed-data directory is required.');
  physicalDirectoryState(dataRoot);
  const owner = readOwnership(dataRoot);
  if (!owner) return false;
  const paths = {dataRoot, profileRoot: owner.profileRoot};
  if (!matchesPreviewOwner(owner, 'data', paths) || path.resolve(paths.profileRoot) !== paths.profileRoot ||
      paths.profileRoot === dataRoot || within(dataRoot, paths.profileRoot) || within(paths.profileRoot, dataRoot)) {
    throw profileError('ASMB_PROFILE_OWNERSHIP', 'The managed-data ownership record does not match this preview. Existing data is preserved.');
  }
  physicalDirectoryState(paths.profileRoot);
  if (!matchesPreviewOwner(readOwnership(paths.profileRoot), 'profile', paths)) {
    throw profileError('ASMB_PROFILE_OWNERSHIP', 'The paired preview profile ownership record is missing or mismatched. Existing data is preserved.');
  }
  return true;
}

/** Admit preview-owned roots before Electron or the host can write settings or data.
 * No default development path is marked or migrated. Legacy preview ownership is
 * recognized only in an explicit Test home; installed unmarked roots are never adopted.
 */
export function admitNativeProfile({args = [], testRoot, channel = 'development', paths}) {
  buildConfiguration(channel);
  const override = testOverride(args, testRoot);
  if (channel === 'development' && !override) return;
  for (const directory of [paths.dataRoot, paths.profileRoot]) {
    if (typeof directory !== 'string' || !path.isAbsolute(directory) || path.resolve(directory) !== directory) {
      throw profileError('ASMB_PROFILE_PATH', 'Absolute physical application paths are required.');
    }
    physicalDirectoryState(directory);
  }
  let legacyPreviewHome = false;
  if (override) {
    physicalDirectoryState(override.root);
    for (let directory = override.root; directory !== path.resolve(testRoot); directory = path.dirname(directory)) {
      rejectForeignOwner(readOwnership(directory), channel);
    }
    const homeOwner = readOwnership(override.root);
    if (override.home) {
      if (paths.dataRoot !== path.join(override.root, 'asMagicBrain') || !within(override.root, paths.profileRoot)) throw profileError('ASMB_PROFILE_PATH', 'The supplied test-home paths do not match their approved home.');
      rejectForeignOwner(readOwnership(paths.dataRoot), channel);
      legacyPreviewHome = channel === 'preview' && homeOwner?.schemaVersion === 1 && homeOwner.channel === 'preview';
    }
    if (channel === 'development') {
      if (!override.home || homeOwner) return;
      ensurePhysicalDirectory(override.root);
      writeOwnership(override.root, {schemaVersion: 1, channel});
      return;
    }
    if (!override.home) throw profileError('ASMB_PROFILE_ARGUMENT', 'Preview requires an approved test user home.');
  }
  if (paths.dataRoot === paths.profileRoot || within(paths.dataRoot, paths.profileRoot) || within(paths.profileRoot, paths.dataRoot)) throw profileError('ASMB_PROFILE_PATH', 'Managed data and the Electron profile require separate directories.');
  const roots = [['data', paths.dataRoot], ['profile', paths.profileRoot]].map(([role, directory]) => {
    const exists = physicalDirectoryState(directory), owner = readOwnership(directory);
    rejectForeignOwner(owner, channel);
    if (owner && !matchesPreviewOwner(owner, role, paths)) {
      throw profileError('ASMB_PROFILE_OWNERSHIP', 'The ownership record does not match these preview directories. Existing data is preserved.');
    }
    if (exists && !owner && !legacyPreviewHome) {
      throw profileError('ASMB_PROFILE_UNOWNED', 'An existing preview directory has no ownership record. It may contain earlier data or an interrupted first run. Existing data is preserved; inspect this directory before retrying.');
    }
    return {role, directory, exists};
  });
  // Preflight both roots before creating either. mkdir is exclusive: a directory
  // appearing after inspection is rejected, including an empty directory.
  for (const {role, directory, exists} of roots) {
    if (exists) continue;
    ensurePhysicalDirectory(path.dirname(directory));
    fs.mkdirSync(directory, {mode: 0o700});
    writeOwnership(directory, {schemaVersion: 2, channel, role, dataRoot: paths.dataRoot, profileRoot: paths.profileRoot});
  }
}
