import test from 'node:test';
import assert from 'node:assert/strict';
import {createTeachGitHubSetup} from './teach-github-setup.mjs';
import {createTeachGitHubProvider} from './teach-github-provider.mjs';
function fixture(){let saved=null,remote=null,creates=0,interrupt=false,accountId=1;const connections=[];const ctx={courseId:'00000000-0000-4000-8000-000000000001',role:'students',bindingId:'1'.repeat(64),branch:'main',migrated:true,terms:['2026-autumn'],url:null};
 const store={scan:()=>({events:saved?[{payload:structuredClone(saved)}]:[],tailRecords:0,coveredFiles:[]}),ensureDurable:v=>v,append:(_s,_k,v)=>{saved=structuredClone(v);}};
 const provider={session:async()=>({account:{id:accountId,login:'teacher'},capability:async()=>({allRepositories:true}),inspect:async()=>structuredClone(remote),projectIsolation:async r=>r.isolation,create:async input=>{creates++;remote={id:5,owner:'teacher',ownerId:1,name:'course',url:'https://github.com/teacher/course.git',visibility:input.visibility,description:'asMagicBrain setup '+input.marker,permissions:{read:true,write:true,admin:true},collaborators:[],invitations:[],accessComplete:true,verifiedAt:1,account:{id:1,login:'teacher'}};if(interrupt)throw Object.assign(Error(),{code:'GITHUB_OUTCOME_UNKNOWN'});return structuredClone(remote);}})};
 const create=(options={})=>createTeachGitHubSetup({...options,store,provider,context:async(_repo,role)=>({...ctx,role}),connect:async(c,r)=>{connections.push(r.id);ctx.url=r.url;}});
 return {get manager(){return create();},create,ctx,connections,get creates(){return creates;},set interrupt(v){interrupt=v;},set account(v){accountId=v;},set remote(v){remote=v;},get remote(){return remote;},get saved(){return saved;}};
}
const input={repo:'Course',role:'students',mode:'create',owner:'teacher',repository:'course',visibility:'public'};
test('review is read-only; creation connects empty repository and pins identity',async()=>{const f=fixture(),m=f.manager,p=await m.review(input);assert.equal(f.creates,0);assert.equal(f.saved,null);await m.apply(p.planId);assert.equal(f.creates,1);assert.equal(m.status('00000000-0000-4000-8000-000000000001').roles.students.remote.id,5);assert.equal(f.connections.length,1);await assert.rejects(m.apply(p.planId),{code:'STALE_PLAN'});});
test('unknown creation outcome survives restart; recheck completes without another POST',async()=>{const f=fixture(),m=f.manager;{const p=await m.review(input);f.interrupt=true;await assert.rejects(m.apply(p.planId),{code:'GITHUB_OUTCOME_UNKNOWN'});}assert.ok(f.saved.pending);const restarted=f.manager;await restarted.recover({repo:'Course',direction:'complete'});assert.equal(f.creates,1);assert.equal(restarted.status('00000000-0000-4000-8000-000000000001').pending,null);});
test('account change, role/branch change and remote collisions refuse before creation',async()=>{const f=fixture(),m=f.manager,p=await m.review(input);f.account=2;await assert.rejects(m.apply(p.planId),{code:'GITHUB_ACCOUNT_CHANGED'});assert.equal(f.creates,0);f.account=1;const next=await m.review(input);f.ctx.branch='other';await assert.rejects(m.apply(next.planId),{code:'CONFLICT'});assert.equal(f.creates,0);});
test('recover refuses unrelated remote and cannot clear existing repository',async()=>{const f=fixture(),m=f.manager,p=await m.review(input);f.interrupt=true;await assert.rejects(m.apply(p.planId));f.remote.description='unrelated repository';await assert.rejects(f.manager.recover({repo:'Course',direction:'complete'}),{code:'GITHUB_SETUP_RECOVERY_REQUIRED'});await assert.rejects(f.manager.recover({repo:'Course',direction:'cancel'}),{code:'GITHUB_SETUP_RECOVERY_REQUIRED'});assert.equal(f.creates,1);});
test('verification detects replacement identity; mapping never claims GitBook sync',async()=>{const f=fixture(),m=f.manager,p=await m.review(input);await m.apply(p.planId);await m.mapping({repo:'Course',url:'https://app.gitbook.com/o/test/s/test/',root:'2026-autumn'});assert.equal(m.status('00000000-0000-4000-8000-000000000001').roles.students.mapping.syncVerified,false);f.remote.id=6;await assert.rejects(m.verify({repo:'Course',role:'students'}),{code:'GITHUB_REPOSITORY_CHANGED'});});
test('private role cannot bind public repository and access changes require fresh review',async()=>{const f=fixture(),m=f.manager,p=await m.review(input);await m.apply(p.planId);await assert.rejects(m.review({...input,mode:'bind',role:'instructors',visibility:'private'}),{code:'PRIVATE_ROLE_PUBLIC'});const r=await m.review({...input,mode:'bind'});f.remote.collaborators=[{login:'new-writer',role:'write'}];await assert.rejects(m.apply(r.planId),{code:'GITHUB_ACCESS_CHANGED'});});
test('provider rejects missing Administration permission and keeps credentials out of observations',async()=>{const calls=[],fetch=async(url,options)=>{calls.push({url,method:options.method});const pathname=new URL(url).pathname;const data=pathname==='/user'?{id:1,login:'teacher'}:pathname==='/users/teacher'?{id:1,login:'teacher',type:'User'}:pathname==='/user/installations'?{installations:[{account:{id:1},permissions:{contents:'write'},repository_selection:'all'}]}:null;return new Response(JSON.stringify(data),{status:data?200:404,headers:{'Content-Type':'application/json'}});};const p=createTeachGitHubProvider({fetch,getCredential:async()=>({token:'synthetic-only'})});const s=await p.session();await assert.rejects(s.capability('teacher'),{code:'GITHUB_ADMIN_PERMISSION'});assert.equal(calls.filter(c=>c.method==='POST').length,0);assert.deepEqual(s.account,{id:1,login:'teacher'});});

test('access observation records drift while managed private-role Push refuses it',async()=>{const f=fixture(),m=f.manager,p=await m.review({...input,role:'instructors',visibility:'private'});await m.apply(p.planId);f.remote.visibility='public';await m.verify({repo:'Course',role:'instructors'});assert.equal(m.status(f.ctx.courseId).roles.instructors.remote.visibility,'public');await assert.rejects(m.guardPush(f.ctx.bindingId),{code:'PRIVATE_ROLE_PUBLIC'});f.remote.visibility='private';f.remote.permissions.write=false;await assert.rejects(m.guardPush(f.ctx.bindingId),{code:'GITHUB_WRITE_REQUIRED'});});

test('organization capability checks exact active owner membership and refuses missing permission',async()=>{let role='admin',id=2,state='active',status=200;const fetch=async url=>{const p=new URL(url).pathname;const data=p==='/user'?{id:1,login:'teacher'}:p==='/users/school'?{id:2,login:'school',type:'Organization'}:p==='/user/memberships/orgs/school'?{organization:{id,login:'school'},role,state}:p==='/user/installations'?{installations:[{account:{id:2},permissions:{administration:'write'},repository_selection:'all'}]}:null;return new Response(JSON.stringify(data),{status:p==='/user/memberships/orgs/school'?status:data?200:404,headers:{'Content-Type':'application/json'}});};const session=await createTeachGitHubProvider({fetch,getCredential:async()=>({token:'synthetic-only'})}).session();assert.equal((await session.capability('school')).allRepositories,true);role='member';await assert.rejects(session.capability('school'),{code:'GITHUB_OWNER_ADMIN_REQUIRED'});role='admin';id=3;await assert.rejects(session.capability('school'),{code:'GITHUB_OWNER_ADMIN_REQUIRED'});id=2;state='pending';await assert.rejects(session.capability('school'),{code:'GITHUB_OWNER_ADMIN_REQUIRED'});state='active';status=403;await assert.rejects(session.capability('school'),{code:'GITHUB_PERMISSION_REQUIRED'});});

test('project setup and Push refuse incomplete or drifted isolation',async()=>{const f=fixture(),m=f.manager;await m.apply((await m.review({...input,role:'instructors',visibility:'private'})).planId);const project=f.create({requireIsolation:true});f.remote.isolation={complete:false,basePermission:'read'};await assert.rejects(project.review({...input,role:'instructors',mode:'bind',visibility:'private'}),{code:'GITHUB_PROJECT_ISOLATION_UNVERIFIED'});f.remote.isolation={complete:true,basePermission:'none'};await project.apply((await project.review({...input,role:'instructors',mode:'bind',visibility:'private'})).planId);f.remote.isolation.complete=false;await assert.rejects(project.guardPush(f.ctx.bindingId),{code:'GITHUB_PROJECT_ISOLATION_UNVERIFIED'});});
