import test from 'node:test';
import assert from 'node:assert/strict';
import {createTeachWorkflow} from './teach-workflow.mjs';
function fixture(){
 let saved=null,interruption=null;
 const ctx={courseId:'00000000-0000-4000-8000-000000000001',bound:true,terms:['2026-autumn'],roles:[{role:'instructors',available:true,repositoryId:'1'.repeat(64),name:'Teacher'},{role:'assistants',available:false,repositoryId:null,name:null},{role:'students',available:true,repositoryId:'2'.repeat(64),name:'Students'}],roleHomes:{instructors:{'2026-autumn':'2026-autumn/instructor.md'},assistants:{}},studentCandidates:{'2026-autumn':['2026-autumn/student.md','2026-autumn/students/中文.md']},legacyCandidates:{'2026-autumn':[{path:'2026-autumn/student.md',sha256:'a'.repeat(64)}]},files:[{role:'students',path:'2026-autumn/student.md',sha256:'b'.repeat(64)}],drafts:[],blocked:false,projects:Array.from({length:8},(_,i)=>({id:String(i),term:'2026-autumn',label:'Team0'+(i+1)}))};
 const store={scan:()=>({events:saved?[{payload:structuredClone(saved)}]:[],tailRecords:0,coveredFiles:[]}),ensureDurable:v=>v,append:(_s,_t,v)=>{saved=structuredClone(v);}};
 const open=()=>createTeachWorkflow({store,snapshot:async()=>structuredClone(ctx),at:p=>{if(p===interruption){interruption=null;throw Error('Interrupted');}}});
 return {ctx,open,interrupt:p=>{interruption=p;},get saved(){return saved;},replace:v=>{saved=v;}};
}
const homes={'2026-autumn':'2026-autumn/student.md'};
test('fresh creation intent is private, durable and fingerprint-bound',()=>{const f=fixture(),w=f.open();assert.equal(w.creation(f.ctx.courseId),null);w.startCreation(f.ctx.courseId,'a'.repeat(64));assert.equal(f.open().creation(f.ctx.courseId),'a'.repeat(64));w.startCreation(f.ctx.courseId,'a'.repeat(64));assert.throws(()=>w.startCreation(f.ctx.courseId,'b'.repeat(64)),{code:'REQUEST_CONFLICT'});assert.equal(w.get(f.ctx.courseId),null);});
test('M02/M03 inventory is read-only, explicit authored home wins, repeated application is idempotent',async()=>{const f=fixture(),w=f.open();assert.equal((await w.inventory('Teacher')).workflow,null);assert.equal(f.saved,null);const p=await w.review('Teacher',{'2026-autumn':'2026-autumn/students/中文.md'});assert.equal(f.saved,null);const after=await w.apply(p.planId);assert.equal(after.workflow.mode,'direct-students');assert.equal(after.roles[2].homePath,'2026-autumn/students/中文.md');assert.equal(after.roles[1].available,false);assert.equal(after.projects.length,8);assert.deepEqual((await f.open().descriptor('Teacher')).workflow,after.workflow);assert.equal((await w.review('Teacher',after.workflow.homes)).planId,null);});
test('M05 fingerprint, draft and blocked-tree changes refuse without activation',async()=>{for(const mutate of [c=>c.files[0].sha256='c'.repeat(64),c=>c.drafts.push({path:'new.md'}),c=>c.blocked=true,c=>c.roles[2].repositoryId='3'.repeat(64)]){const f=fixture(),w=f.open(),p=await w.review('Teacher',homes);mutate(f.ctx);await assert.rejects(w.apply(p.planId),{code:'CONFLICT'});assert.equal(w.get(f.ctx.courseId),null);}const f=fixture();f.ctx.drafts.push({path:'draft.md'});await assert.rejects(f.open().review('Teacher',homes),{code:'DRAFT_CONFLICT'});});
test('M06 missing Students and invalid term/home selection hold; Assistant stays unavailable',async()=>{const f=fixture(),w=f.open();await assert.rejects(w.review('Teacher',{}),{code:'TEACH_HOME_SELECTION_REQUIRED'});await assert.rejects(w.review('Teacher',{'2026-autumn':'2026-autumn/missing.md'}),{code:'TEACH_STUDENT_PAGE_MISSING'});f.ctx.roles[2].available=false;await assert.rejects(w.review('Teacher',homes),{code:'TEACH_GRAPH_REQUIRED'});await assert.rejects(w.descriptor('Teacher','2027-spring'),{code:'INVALID_TERM'});});
test('M08 each durable interruption resumes on restart or rolls back without repository writes',async()=>{for(const phase of ['workflow-prepared','workflow-activated','workflow-complete']){for(const direction of ['resume','rollback']){const f=fixture(),w=f.open(),before=structuredClone(f.ctx),p=await w.review('Teacher',homes);f.interrupt(phase);await assert.rejects(w.apply(p.planId),/Interrupted/);const reopened=f.open();if(direction==='resume'&&phase==='workflow-complete')assert.equal((await reopened.descriptor('Teacher')).workflow.mode,'direct-students');else await reopened.recover('Teacher',direction);assert.equal((await reopened.descriptor('Teacher')).workflow.mode,direction==='rollback'?'legacy-preparation':'direct-students');assert.deepEqual(f.ctx,before);}}});
test('M09 rollback refuses later content edits and subsequent workflow revision, cancel is inert',async()=>{const f=fixture(),w=f.open(),p=await w.review('Teacher',homes);await w.apply(p.planId);f.ctx.files[0].sha256='c'.repeat(64);await assert.rejects(w.recover('Teacher','rollback'),{code:'CONFLICT'});assert.equal(w.get(f.ctx.courseId).mode,'direct-students');const c=await w.review('Teacher',{'2026-autumn':'2026-autumn/students/中文.md'});w.cancel(c.planId);await assert.rejects(w.apply(c.planId),{code:'STALE_PLAN'});});
test('M10 malformed paths and unknown durable schemas refuse',async()=>{const f=fixture(),w=f.open();for(const home of ['/tmp/x.md','2026-autumn/../x.md','2026-autumn/.private/x.md','2026-autumn/code.py'])await assert.rejects(w.review('Teacher',{'2026-autumn':home}),{code:'TEACH_WORKFLOW_INVALID'});f.replace({schemaVersion:2,courses:{},pending:null,last:{}});assert.throws(()=>w.get(f.ctx.courseId),{code:'RECOVERY_REQUIRED'});});

test('descriptor defaults to selected term; damaged transaction preimage refuses recovery',async()=>{const f=fixture(),w=f.open(),p=await w.review('Teacher',homes);await w.apply(p.planId);f.ctx.terms.push('2027-spring');assert.equal((await w.descriptor('Teacher')).projects.length,0);assert.equal((await w.descriptor('Teacher','2026-autumn')).projects.length,8);const state=structuredClone(f.saved);state.last[f.ctx.courseId].before=false;f.replace(state);assert.throws(()=>f.open().get(f.ctx.courseId));});
test('multi-term home selection is idempotent regardless of object key order',async()=>{const f=fixture(),w=f.open();f.ctx.terms.push('2027-spring');f.ctx.studentCandidates['2027-spring']=['2027-spring/student.md'];const first={'2027-spring':'2027-spring/student.md',...homes};await w.apply((await w.review('Teacher',first)).planId);assert.equal((await w.review('Teacher',{...homes,'2027-spring':'2027-spring/student.md'})).alreadyApplied,true);});
