import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createNativeService} from './host-service.mjs';
import {buildStudentPublication,createTeachPublication} from './teach-publication.mjs';
import {pinDirectory} from '../../packages/desktop-host/src/physical-roots.mjs';
async function setup(t){const root=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'publication-'));let service=await createNativeService({dataRoot:path.join(root,'data')});t.after(async()=>{await service.close();fs.rmSync(root,{recursive:true,force:true});});const course=await service.teachRequest({operation:'create',requestId:randomUUID(),code:'TEST101',name:'Synthetic',year:2026,season:'autumn'});await service.createRepository({name:'Student',requestId:randomUUID()});const request=(operation,args)=>service.request({repo:course.repo,operation,args});await request('create',{path:'2026-autumn/student.md',text:'# Course\n\n[Class](classes/Class01.md)\n'});await request('create',{path:'2026-autumn/classes/Class01.md',text:'# Class\n\n![Image](plot.png)\n'});const repoRoot=path.join(root,'data/workspaces/asMagicBrain',course.repo);fs.writeFileSync(path.join(repoRoot,'2026-autumn/classes/plot.png'),Buffer.from([137,80,78,71]));const input={operation:'reviewPublication',repo:course.repo,year:2026,season:'autumn',destination:'Student',selectedPages:['2026-autumn/classes/Class01.md']};return {root,repoRoot,course,input,request,get service(){return service;},restart:async()=>{await service.close();service=await createNativeService({dataRoot:path.join(root,'data')});}};}
test('reviewed term copy preserves student/class/binary bytes, excludes instructor and Git, survives restart and never duplicates',async t=>{const f=await setup(t);const plan=await f.service.teachRequest(f.input);assert.deepEqual(plan.files.map(f=>f.path),['2026-autumn/student.md','2026-autumn/classes/Class01.md','2026-autumn/classes/plot.png','2026-autumn/SUMMARY.md','2026-autumn/.gitbook.yaml']);const result=await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});assert.equal(result.path,'2026-autumn/student.md');const dest=path.join(f.root,'data/workspaces/asMagicBrain/Student');assert.deepEqual(fs.readFileSync(path.join(dest,'2026-autumn/classes/plot.png')),Buffer.from([137,80,78,71]));assert.equal(fs.existsSync(path.join(dest,'2026-autumn/instructor.md')),false);await f.restart();assert.match((await f.service.read({repo:'Student',path:'2026-autumn/student.md'})).content,/Class/);const again=await f.service.teachRequest(f.input);await f.service.teachRequest({operation:'copyPublication',planId:again.planId});assert.equal(fs.existsSync(path.join(dest,'2026-autumn copy')),false);});
test('changed saved dependencies invalidate review; review is one-use and restart invalidates it',async t=>{const f=await setup(t);const plan=await f.service.teachRequest(f.input);const file=await f.request('open',{path:'2026-autumn/classes/Class01.md'});await f.request('save',{path:file.path,baseHash:file.sourceHash,text:'# Revised\n'});await assert.rejects(f.service.teachRequest({operation:'copyPublication',planId:plan.planId}),{code:'CONFLICT'});await assert.rejects(f.service.teachRequest({operation:'copyPublication',planId:plan.planId}),{code:'PUBLICATION_EXPIRED'});const next=await f.service.teachRequest(f.input);await f.restart();await assert.rejects(f.service.teachRequest({operation:'copyPublication',planId:next.planId}),{code:'PUBLICATION_EXPIRED'});});
test('instructor and cross-term links, missing dependencies, symlinks and drafts block output',async t=>{const f=await setup(t);let file=await f.request('open',{path:'2026-autumn/student.md'});for(const [target,code] of [['instructor.md','PUBLICATION_PRIVATE_LINK'],['../2025-autumn/student.md','PUBLICATION_PRIVATE_LINK'],['missing.md','PUBLICATION_PAGE_NOT_SELECTED']]){file=await f.request('save',{path:file.path,baseHash:file.sourceHash,text:`[link](${target})\n`});await assert.rejects(f.service.teachRequest(f.input),{code});}file=await f.request('save',{path:file.path,baseHash:file.sourceHash,text:'[link](linked.md)\n'});fs.symlinkSync('instructor.md',path.join(f.repoRoot,'2026-autumn/linked.md'));await assert.rejects(f.service.teachRequest(f.input));fs.unlinkSync(path.join(f.repoRoot,'2026-autumn/linked.md'));file=await f.request('save',{path:file.path,baseHash:file.sourceHash,text:'# Ready\n'});await f.request('checkpoint',{path:file.path,baseHash:file.sourceHash,text:'# Draft'});await assert.rejects(f.service.teachRequest(f.input),{code:'DRAFT_CONFLICT'});});
test('destination instructor repository is inadmissible; unrelated destination content is preserved',async t=>{const f=await setup(t);await assert.rejects(f.service.teachRequest({...f.input,destination:f.course.repo}),{code:'PUBLICATION_DESTINATION'});await f.service.request({repo:'Student',operation:'create',args:{path:'keep.md',text:'Preserve'}});const plan=await f.service.teachRequest(f.input);await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});assert.equal((await f.service.request({repo:'Student',operation:'open',args:{path:'keep.md'}})).text,'Preserve');});
test('ZIP uses same reviewed bytes; comments remain explicit; references in code fences do not copy secrets',async t=>{const f=await setup(t);const file=await f.request('open',{path:'2026-autumn/student.md'});await f.request('save',{path:file.path,baseHash:file.sourceHash,text:'# Student\n<!-- review this -->\n```md\n[private](instructor.md)\n```\n'});const context=()=>({root:pinDirectory(f.repoRoot),identity:'source',recordHash:'record',term:{year:2026,season:'autumn'},studentPath:'2026-autumn/student.md',forbidden:['2026-autumn/instructor.md']});const output=buildStudentPublication(context());assert.equal(output.files.length,3);assert.match(output.warnings.join(' '),/comments/);const manager=createTeachPublication({context,destinations:()=>[],copy:()=>assert.fail()});const plan=await manager.review({destination:null});const zip=await manager.finish(plan.planId,'zip');assert.equal(zip.bytes.readUInt32LE(0),0x04034b50);assert.equal(zip.filename,'2026-autumn-student.zip');});
test('target draft reserves the term; existing terms, source bytes and author history remain untouched',async t=>{const f=await setup(t);const before=fs.readFileSync(path.join(f.repoRoot,'2026-autumn/instructor.md'));await f.service.request({repo:'Student',operation:'checkpointNew',args:{draftId:'reserved',path:'2026-autumn/proposed.md',text:'private unsaved draft'}});const plan=await f.service.teachRequest(f.input);await assert.rejects(f.service.teachRequest({operation:'copyPublication',planId:plan.planId}),{code:'PUBLICATION_DESTINATION_EXISTS'});assert.deepEqual(fs.readFileSync(path.join(f.repoRoot,'2026-autumn/instructor.md')),before);assert.equal(fs.existsSync(path.join(f.root,'data/workspaces/asMagicBrain/Student/2026-autumn')),false);});

test('page selection is explicit, includes unlinked selected pages, and blocks unselected page dependencies',async t=>{const f=await setup(t);await assert.rejects(f.service.teachRequest({...f.input,selectedPages:[]}),{code:'PUBLICATION_PAGE_NOT_SELECTED'});await f.request('create',{path:'2026-autumn/resources/Reading.md',text:'# Reading'});const plan=await f.service.teachRequest({...f.input,selectedPages:[...f.input.selectedPages,'2026-autumn/resources/Reading.md']});assert.ok(plan.files.some(file=>file.path.endsWith('Reading.md')));});
test('updates detect manual student edits and preserve other terms and unrelated files',async t=>{const f=await setup(t);let plan=await f.service.teachRequest(f.input);await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});await f.service.request({repo:'Student',operation:'create',args:{path:'2025-autumn/keep.md',text:'Other term'}});let file=await f.request('open',{path:'2026-autumn/classes/Class01.md'});await f.request('save',{path:file.path,baseHash:file.sourceHash,text:'# Revised'});plan=await f.service.teachRequest(f.input);assert.equal(plan.comparison.rows.find(r=>r.path===file.path).action,'update');await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});assert.equal((await f.service.request({repo:'Student',operation:'open',args:{path:file.path}})).text,'# Revised');await f.restart();const listing=await f.service.teachRequest({operation:'courseFiles',repo:f.course.repo,year:2026,season:'autumn'});assert.equal(listing.students[0].repo,'Student');const edited=await f.service.request({repo:'Student',operation:'open',args:{path:file.path}});await f.service.request({repo:'Student',operation:'save',args:{path:file.path,baseHash:edited.sourceHash,text:'Manual edit'}});file=await f.request('open',{path:file.path});await f.request('save',{path:file.path,baseHash:file.sourceHash,text:'# Next'});plan=await f.service.teachRequest(f.input);assert.ok(plan.comparison.rows.some(r=>r.conflict));await assert.rejects(f.service.teachRequest({operation:'copyPublication',planId:plan.planId}),{code:'PUBLICATION_UPDATE_CONFLICT'});assert.equal((await f.service.request({repo:'Student',operation:'open',args:{path:file.path}})).text,'Manual edit');assert.equal((await f.service.request({repo:'Student',operation:'open',args:{path:'2025-autumn/keep.md'}})).text,'Other term');});
test('shared assets become term-local with source-preserving Markdown link rewriting',async t=>{
 const f=await setup(t);fs.mkdirSync(path.join(f.repoRoot,'shared/assets'),{recursive:true});fs.writeFileSync(path.join(f.repoRoot,'shared/assets/diagram.png'),'synthetic');
 const file=await f.request('open',{path:'2026-autumn/classes/Class01.md'}),text='# Class\n\n![Diagram](../../shared/assets/diagram.png)\n\n[Download][asset]\n\n[asset]: ../../shared/assets/diagram.png\n\n```md\n![Example](../../shared/assets/diagram.png)\n```\n';
 await f.request('save',{path:file.path,baseHash:file.sourceHash,text});const plan=await f.service.teachRequest(f.input);assert.ok(plan.files.some(file=>file.path==='2026-autumn/assets/shared/diagram.png'));const preview=plan.files.find(file=>file.path==='2026-autumn/classes/Class01.md').preview;assert.match(preview,/!\[Diagram\]\(\.\.\/assets\/shared\/diagram.png\)/);assert.match(preview,/\[asset\]: ..\/assets\/shared\/diagram.png/);assert.match(preview,/!\[Example\]\(\.\.\/\.\.\/shared\/assets\/diagram.png\)/);await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});assert.equal(fs.readFileSync(path.join(f.repoRoot,file.path),'utf8'),text);
});

test('reviewed in-memory Student home writes only destination and rejects stale Instructor source',async t=>{
 const f=await setup(t);const legacy=fs.readFileSync(path.join(f.repoRoot,'2026-autumn/student.md'),'utf8');
 const review=await f.service.teachRequest({operation:'studentReview',repo:f.course.repo,year:2026,season:'autumn'});
 const input={...f.input,studentText:'# Reviewed Student\n\n[Class](classes/Class01.md)\n',sourceHash:review.instructor.sourceHash};
 let plan=await f.service.teachRequest(input);await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});
 assert.equal(fs.readFileSync(path.join(f.repoRoot,'2026-autumn/student.md'),'utf8'),legacy);
 fs.unlinkSync(path.join(f.repoRoot,'2026-autumn/student.md'));
 plan=await f.service.teachRequest(input);await f.service.teachRequest({operation:'copyPublication',planId:plan.planId});
 assert.equal(fs.existsSync(path.join(f.repoRoot,'2026-autumn/student.md')),false);
 assert.equal((await f.service.read({repo:'Student',path:'2026-autumn/student.md'})).content,input.studentText);
 plan=await f.service.teachRequest(input);await f.request('save',{path:review.sourcePath,baseHash:review.instructor.sourceHash,text:'# Changed Instructor'});
 await assert.rejects(f.service.teachRequest({operation:'copyPublication',planId:plan.planId}),{code:'CONFLICT'});
 await assert.rejects(f.service.teachRequest({operation:'saveStudent',repo:f.course.repo,year:2026,season:'autumn',sourceHash:input.sourceHash,studentHash:null,text:input.studentText}),{code:'STUDENT_DESTINATION_REQUIRED'});
});
