import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pinDirectory} from '../../packages/desktop-host/src/physical-roots.mjs';
import {buildStudentPublication} from './teach-publication.mjs';
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'audience-publication-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const put=(p,text)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),text);};put('2026-autumn/students/README.md','# Student\n\n[Class](classes/class06/lesson.md)\n');put('2026-autumn/students/classes/class06/lesson.md','# Class\n\n[Code](code/play.py)\n');put('2026-autumn/students/classes/class06/code/play.py','print("synthetic")\n');put('2026-autumn/instructors/classes/class06/delivery.md','Private');return {root,put,build:()=>buildStudentPublication({root:pinDirectory(root),term:{year:2026,season:'autumn'},studentPath:'2026-autumn/students/README.md',forbidden:[]})};}
test('complete student-root package strips audience prefix, preserves code paths, source and private exclusion',t=>{const f=fixture(t),out=f.build();assert.equal(out.homePath,'2026-autumn/README.md');assert.ok(out.files.some(x=>x.path==='2026-autumn/classes/class06/code/play.py'));assert.ok(!out.files.some(x=>x.path.includes('instructors')));assert.match(out.files.find(x=>x.path.endsWith('.gitbook.yaml')).bytes.toString(),/readme: README.md/);assert.equal(fs.readFileSync(path.join(f.root,'2026-autumn/instructors/classes/class06/delivery.md'),'utf8'),'Private');});
test('private links, missing dependencies, symlink escape and unsupported assets fail the complete review',t=>{const f=fixture(t);f.put('2026-autumn/students/classes/class06/lesson.md','[Private](../../../instructors/classes/class06/delivery.md)');assert.throws(f.build,{code:'PUBLICATION_PRIVATE_LINK'});f.put('2026-autumn/students/classes/class06/lesson.md','[Missing](missing.csv)');assert.throws(f.build,{code:'PUBLICATION_MISSING_LINK'});f.put('2026-autumn/students/classes/class06/lesson.md','# Lesson');f.put('2026-autumn/students/unsupported.exe','synthetic');assert.throws(f.build,{code:'PUBLICATION_UNSUPPORTED_ASSET'});fs.unlinkSync(path.join(f.root,'2026-autumn/students/unsupported.exe'));fs.symlinkSync(path.join(f.root,'2026-autumn/instructors'),path.join(f.root,'2026-autumn/students/escape'));assert.throws(f.build,{code:'PUBLICATION_PATH'});});
test('cache inclusion is rejected instead of silently discarded',t=>{const f=fixture(t);f.put('2026-autumn/students/classes/class06/code/__pycache__/private.pyc','synthetic');assert.throws(f.build,{code:'PUBLICATION_PRIVATE_LINK'});});

test('role promotion requires complete candidate-root selection and refuses private preparation',async t=>{const {buildRolePromotion}=await import('./teach-promotion.mjs');const f=fixture(t),paths=['2026-autumn/students/README.md','2026-autumn/students/classes/class06/lesson.md','2026-autumn/students/classes/class06/code/play.py'];const input={root:pinDirectory(f.root),folder:'2026-autumn',sourceAudienceRoot:'2026-autumn/students',paths,toRole:'students'};assert.ok(buildRolePromotion(input).files.some(f=>f.path.endsWith('/code/play.py')));assert.throws(()=>buildRolePromotion({...input,paths:paths.slice(0,2)}),{code:'PUBLICATION_PACKAGE_INCOMPLETE'});assert.throws(()=>buildRolePromotion({...input,paths:['2026-autumn/instructors/classes/class06/delivery.md']}),{code:'PROMOTION_PRIVATE_FILE'});});
test('package manifests, model dependencies and secret-like code require explicit repair before delivery',t=>{const f=fixture(t);f.put('2026-autumn/students/classes/class06/package-manifest.json',JSON.stringify({files:{'lesson.md':'0'.repeat(64)}}));assert.throws(f.build,{code:'PUBLICATION_MANIFEST_STALE'});f.put('2026-autumn/students/classes/class06/package-manifest.json',JSON.stringify({schemaVersion:1,files:['lesson.md','code/play.py']}));f.put('2026-autumn/students/classes/class06/code/play.py','model="missing.xml"');assert.throws(f.build,{code:'PROMOTION_DEPENDENCY'});f.put('2026-autumn/students/classes/class06/code/play.py','token="ghp_'+ 'a'.repeat(30)+'"');assert.throws(f.build,{code:'PROMOTION_SECRET'});f.put('2026-autumn/students/classes/class06/code/play.py','print("synthetic")');f.put('2026-autumn/students/classes/class06/code/.gitignore','__pycache__/\n');assert.ok(f.build().files.some(x=>x.path.endsWith('/.gitignore')));});

test('complete package preserves Chinese UTF-8 BOM and CRLF bytes under declared hashes',async t=>{const {createHash}=await import('node:crypto');const f=fixture(t),text='\uFEFF# 中文课程\r\n\r\n';f.put('2026-autumn/students/classes/class06/lesson.md',text);f.put('2026-autumn/students/classes/class06/package-manifest.json',JSON.stringify({files:{'lesson.md':createHash('sha256').update(Buffer.from(text)).digest('hex')}}));assert.deepEqual(f.build().files.find(f=>f.path.endsWith('/lesson.md')).bytes,Buffer.from(text));});
