import test from 'node:test';
import assert from 'node:assert/strict';
import {createTeachStaffAccess} from './teach-staff-access.mjs';
import {createTeachGitHubProvider} from './teach-github-provider.mjs';
function fixture(){let saved=null,grants=0,accountId=1,userId=2,interrupt=false,applyGrant=true;const ctx={courseId:'00000000-0000-4000-8000-000000000001',role:'students',bindingId:'1'.repeat(64),branch:'main',migrated:true,revision:1,url:'https://github.com/school/course.git'};const remote={id:5,ownerId:6,ownerType:'Organization',owner:'school',name:'course',url:ctx.url,visibility:'public',permissions:{admin:true},archived:false,accessComplete:true,collaborators:[],invitations:[]};const pinned=structuredClone(remote);
 const store={scan:()=>({events:saved?[{payload:structuredClone(saved)}]:[],tailRecords:0,coveredFiles:[]}),ensureDurable:v=>v,append:(_s,_k,v)=>{saved=structuredClone(v);}};
 const provider={session:async()=>({account:{id:accountId,login:'teacher'},resolveUser:async login=>({id:userId,login}),inspect:async()=>structuredClone(remote),grant:async v=>{grants++;if(applyGrant)remote.invitations=[{login:v.login,role:v.permission}];if(interrupt)throw Object.assign(Error(),{code:'GITHUB_OUTCOME_UNKNOWN'});}})};
 const create=()=>createTeachStaffAccess({store,provider,context:async(_repo,role)=>({...ctx,role}),setupStatus:()=>({pending:null,roles:{students:{bindingId:ctx.bindingId,branch:'main',remote:pinned},instructors:{bindingId:ctx.bindingId,branch:'main',remote:{...pinned,visibility:'private'}}}})});
 return {manager:create(),create,ctx,remote,get grants(){return grants;},get saved(){return saved;},set account(v){accountId=v;},set user(v){userId=v;},set interrupt(v){interrupt=v;},set applyGrant(v){applyGrant=v;}};
}
const input={repo:'Course',role:'students',login:'assistant',permission:'write'};
async function roster(f){await f.manager.saveRoster({repo:'Course',entries:[{login:'assistant',role:'assistant'}],revision:0});}
test('local roster remains local; reviewed invite is one grant with pending acceptance',async()=>{const f=fixture();await roster(f);assert.equal(f.grants,0);const p=await f.manager.review(input);assert.equal(f.grants,0);const result=await f.manager.apply(p.planId);assert.equal(f.grants,1);assert.match(result.status,/recipient must accept/);assert.equal(f.manager.status(f.ctx.courseId).pending,null);await assert.rejects(f.manager.apply(p.planId),{code:'STALE_PLAN'});});
test('existing admin and pending invitation never receive duplicate or lower grant',async()=>{const f=fixture();await roster(f);f.remote.collaborators=[{login:'assistant',role:'admin'}];const p=await f.manager.review(input);assert.equal(p.action,'none');await f.manager.apply(p.planId);assert.equal(f.grants,0);f.remote.collaborators=[];f.remote.invitations=[{login:'assistant',role:'read'}];const next=await f.manager.review(input);assert.match(next.status,/already pending/);await f.manager.apply(next.planId);assert.equal(f.grants,0);});
test('uncertain grant survives restart and GET-only recovery never repeats it',async()=>{const f=fixture();await roster(f);const p=await f.manager.review(input);f.interrupt=true;await assert.rejects(f.manager.apply(p.planId),{code:'GITHUB_OUTCOME_UNKNOWN'});assert.ok(f.saved.pending);const restarted=f.create();await assert.rejects(restarted.review(input),{code:'GITHUB_STAFF_RECOVERY_REQUIRED'});await restarted.recover({repo:'Course',direction:'complete'});assert.equal(f.grants,1);assert.equal(restarted.status(f.ctx.courseId).pending,null);});
test('missing uncertain result needs verified clear before a fresh review',async()=>{const f=fixture();await roster(f);f.interrupt=true;f.applyGrant=false;const p=await f.manager.review(input);await assert.rejects(f.manager.apply(p.planId));await assert.rejects(f.manager.recover({repo:'Course',direction:'complete'}),{code:'GITHUB_STAFF_RECOVERY_REQUIRED'});await f.manager.recover({repo:'Course',direction:'clear'});assert.equal(f.grants,1);assert.equal(f.saved.pending,null);});
test('stale account, identity, local revision and access refuse before any PUT',async()=>{for(const [mutate,code] of [[f=>{f.account=3;},'GITHUB_ACCOUNT_CHANGED'],[f=>{f.user=9;},'GITHUB_USER_CHANGED'],[f=>{f.ctx.revision++;},'CONFLICT'],[f=>{f.remote.collaborators=[{login:'other',role:'write'}];},'GITHUB_ACCESS_CHANGED'],[f=>{f.remote.id=7;},'GITHUB_REPOSITORY_CHANGED']]){const f=fixture();await roster(f);const p=await f.manager.review(input);mutate(f);await assert.rejects(f.manager.apply(p.planId),{code});assert.equal(f.grants,0);}});
test('roster validates bounds, duplicate identity, revision and saved recipient',async()=>{const f=fixture();await assert.rejects(f.manager.saveRoster({repo:'Course',entries:[{login:'a',role:'assistant'},{login:'A',role:'instructor'}],revision:0}),{code:'INVALID_REQUEST'});await assert.rejects(f.manager.saveRoster({repo:'Course',entries:Array.from({length:33},(_,i)=>({login:'a'+i,role:'assistant'})),revision:0}),{code:'INVALID_REQUEST'});await assert.rejects(f.manager.review(input),{code:'GITHUB_STAFF_NOT_LISTED'});await roster(f);await assert.rejects(f.manager.saveRoster({repo:'Course',entries:[],revision:0}),{code:'CONFLICT'});await f.manager.saveRoster({repo:'Course',entries:[],revision:1});assert.equal(f.grants,0);});
test('incomplete/adminless/public private-role review and paused operations fail closed',async()=>{const f=fixture();await roster(f);f.remote.accessComplete=false;await assert.rejects(f.manager.review(input),{code:'GITHUB_ACCESS_INCOMPLETE'});f.remote.accessComplete=true;f.remote.permissions.admin=false;await assert.rejects(f.manager.review(input),{code:'GITHUB_ADMIN_REQUIRED'});f.remote.permissions.admin=true;await assert.rejects(f.manager.review({...input,role:'instructors'}),{code:'GITHUB_VISIBILITY_CHANGED'});f.manager.pause();await assert.rejects(f.manager.review(input),{code:'GITHUB_BUSY'});assert.equal(f.grants,0);});
test('provider admits only personal identities and read/write PUT; accepts empty 204',async()=>{const calls=[];let type='User',status=204;const provider=createTeachGitHubProvider({getCredential:async()=>({token:'synthetic-only'}),fetch:async(url,options)=>{calls.push({url,method:options.method,body:options.body});const p=new URL(url).pathname;if(options.method==='PUT')return new Response(status===204?null:JSON.stringify({id:1}),{status});return new Response(JSON.stringify(p==='/user'?{id:1,login:'teacher'}:{id:2,login:'assistant',type}),{status:200});}});const s=await provider.session();assert.equal((await s.resolveUser('assistant')).id,2);await s.grant({owner:'school',repository:'course',login:'assistant',permission:'write',ownerType:'Organization'});assert.equal(JSON.parse(calls.at(-1).body).permission,'push');status=201;assert.equal((await s.grant({owner:'school',repository:'course',login:'assistant',permission:'read',ownerType:'Organization'})).invited,true);await assert.rejects(s.grant({owner:'school',repository:'course',login:'assistant',permission:'admin'}),{code:'INVALID_REQUEST'});type='Organization';await assert.rejects(s.resolveUser('assistant'),{code:'GITHUB_USER_UNAVAILABLE'});});

test('pause clears a review and resume admits fresh work without applying old consent',async()=>{const f=fixture();await roster(f);const p=await f.manager.review(input);f.manager.pause();await assert.rejects(f.manager.apply(p.planId),{code:'GITHUB_BUSY'});f.manager.resume();await assert.rejects(f.manager.apply(p.planId),{code:'STALE_PLAN'});assert.equal((await f.manager.review(input)).action,'grant');assert.equal(f.grants,0);});

test('personal Read review refuses without a grant or pending intent; existing access remains an observation',async()=>{const f=fixture();await roster(f);f.remote.ownerType='User';await assert.rejects(f.manager.review({...input,permission:'read'}),{code:'GITHUB_PERSONAL_READ_UNSUPPORTED'});assert.equal(f.grants,0);assert.equal(f.saved.pending,null);f.remote.collaborators=[{login:'assistant',role:'write'}];assert.equal((await f.manager.review({...input,permission:'read'})).action,'none');});
test('project isolation drift blocks a reviewed grant before PUT',async()=>{const f=fixture();await roster(f);f.remote.isolation={complete:true,basePermission:'none',owners:['teacher'],teams:[]};const review=await f.manager.review(input);f.remote.isolation={complete:false,basePermission:'read',owners:['teacher'],teams:[]};await assert.rejects(f.manager.apply(review.planId),{code:'GITHUB_PROJECT_ISOLATION_UNVERIFIED'});assert.equal(f.grants,0);});
test('personal Write omits organization permission body; personal Read never sends PUT',async()=>{const calls=[];const provider=createTeachGitHubProvider({getCredential:async()=>({token:'synthetic-only'}),fetch:async(url,options)=>{calls.push({url,...options});return options.method==='PUT'?new Response(JSON.stringify({id:1}),{status:201}):new Response(JSON.stringify({id:1,login:'teacher'}));}});const s=await provider.session();await assert.rejects(s.grant({owner:'teacher',repository:'course',login:'assistant',permission:'read',ownerType:'User'}),{code:'GITHUB_PERSONAL_READ_UNSUPPORTED'});assert.equal(calls.filter(c=>c.method==='PUT').length,0);await s.grant({owner:'teacher',repository:'course',login:'assistant',permission:'write',ownerType:'User'});assert.equal(calls.at(-1).body,undefined);assert.equal(calls.at(-1).headers['Content-Length'],'0');});
test('collaborator validation rejection is distinct from repository name conflict and retains safe recovery intent',async()=>{const provider=createTeachGitHubProvider({getCredential:async()=>({token:'synthetic-only'}),fetch:async(_url,options)=>options.method==='PUT'?new Response('{}',{status:422}):new Response(JSON.stringify({id:1,login:'teacher'}))});const s=await provider.session();await assert.rejects(s.grant({owner:'school',repository:'course',login:'assistant',permission:'read',ownerType:'Organization'}),{code:'GITHUB_GRANT_REJECTED'});});


test('contact directories persist UTF-8 privately and retain legacy staff entries',async()=>{const f=fixture();const entries=[{login:'assistant',role:'assistant'},{login:'',role:'assistant',firstName:'小明',lastName:'王',email:'ta@example.test'},{login:'learner',role:'student',firstName:'Mei',lastName:'陈',email:'student@example.test'}];await f.manager.saveRoster({repo:'Course',entries,revision:0});assert.deepEqual(f.create().status(f.ctx.courseId).roster.entries,entries);assert.equal(f.grants,0);});
test('directory bounds, invalid contact fields and unknown keys are refused',async()=>{const f=fixture();for(const entry of [{login:'',role:'student'},{login:'',role:'student',email:'wrong'},{login:'a',role:'student',firstName:'bad\nname'},{login:'a',role:'student',privateToken:'x'}])await assert.rejects(f.manager.saveRoster({repo:'Course',entries:[entry],revision:0}),{code:'INVALID_REQUEST'});await assert.rejects(f.manager.saveRoster({repo:'Course',entries:Array.from({length:501},(_,i)=>({login:'student'+i,role:'student'})),revision:0}),{code:'INVALID_REQUEST'});});
test('students can only review Read on Students and never receive staff rights',async()=>{const f=fixture();await f.manager.saveRoster({repo:'Course',entries:[{login:'learner',role:'student'}],revision:0});for(const [role,permission] of [['instructors','read'],['assistants','write'],['students','write']])await assert.rejects(f.manager.review({...input,login:'learner',role,permission}),{code:'GITHUB_STUDENT_ACCESS_SCOPE'});const p=await f.manager.review({...input,login:'learner',permission:'read'});await f.manager.apply(p.planId);assert.equal(f.grants,1);const again=await f.manager.review({...input,login:'learner',permission:'read'});assert.equal(again.action,'none');});
test('directory revision changes invalidate reviewed access before any grant',async()=>{const f=fixture();await roster(f);const p=await f.manager.review(input);await f.manager.saveRoster({repo:'Course',entries:[{login:'assistant',role:'student',firstName:'Changed role'}],revision:1});await assert.rejects(f.manager.apply(p.planId),{code:'STALE_PLAN'});assert.equal(f.grants,0);});
