import test from 'node:test';import assert from 'node:assert/strict';import {createTeachAccessBatch} from './teach-access-batch.mjs';
function fixture(){let revision=1,drift=false;const writes=[];const b=createTeachAccessBatch({context:async()=>({revision}),review:async i=>({planId:i.login,user:{login:i.login,id:drift?99:i.login==='alice'?1:2},account:{id:1},remote:{id:3,ownerId:4,visibility:'private'},action:'grant'}),cancel:async()=>{},apply:async(_,id)=>{writes.push(id);if(id==='bob')throw Object.assign(Error(),{code:'GITHUB_OUTCOME_UNKNOWN'});return {status:'Invited',changed:true};}});return {b,writes,rev:()=>revision++,drift:()=>drift=true};}
test('review performs no writes; unknown outcome stops remaining recipients',async()=>{const f=fixture(),r=await f.b.review({logins:['alice','bob','carol'],permission:'write'});assert.deepEqual(f.writes,[]);const a=await f.b.apply(r.planId);assert.equal(a.complete,false);assert.deepEqual(f.writes,['alice','bob']);assert.equal(a.results[2].status,'Not attempted');await assert.rejects(f.b.apply(r.planId));});
test('local changes invalidate batch consent',async()=>{const f=fixture(),r=await f.b.review({logins:['alice'],permission:'write'});f.rev();await assert.rejects(f.b.apply(r.planId),{code:'CONFLICT'});assert.deepEqual(f.writes,[]);});
test('numeric identity drift prevents grants',async()=>{const f=fixture(),r=await f.b.review({logins:['alice'],permission:'write'});f.drift();const a=await f.b.apply(r.planId);assert.equal(a.results[0].error,'GITHUB_USER_CHANGED');assert.deepEqual(f.writes,[]);});
test('case-insensitive duplicates are rejected',async()=>{const f=fixture();await assert.rejects(f.b.review({logins:['alice','ALICE'],permission:'read'}),{code:'INVALID_REQUEST'});});

test('expired review is retired before any recipient request',async()=>{let clock=0,writes=0;const b=createTeachAccessBatch({now:()=>clock,context:async()=>({}),review:async()=>({planId:'r',user:{id:1,login:'alice'},account:{id:2},remote:{id:3,ownerId:4,visibility:'private'},action:'grant'}),cancel:async()=>{},apply:async()=>{writes++;}});const p=await b.review({logins:['alice'],permission:'write'});clock=300001;await assert.rejects(b.apply(p.planId),{code:'STALE_PLAN'});assert.equal(writes,0);});
for(const failed of ['alice','bob'])test(`failure at ${failed} preserves partial outcomes and safe error details`,async()=>{const writes=[],b=createTeachAccessBatch({context:async()=>({}),review:async i=>({planId:i.login,user:{id:i.login==='alice'?1:2,login:i.login},account:{id:4},remote:{id:5,ownerId:6,visibility:'private'},action:'grant'}),cancel:async()=>{},apply:async(_,login)=>{writes.push(login);if(login===failed)throw Object.assign(Error('private raw message'),{code:'GITHUB_PERMISSION_REQUIRED',diagnostic:{httpStatus:403,requestId:'ABCD:1234',outcome:'rejected'}});return {status:'Invited',changed:true};}});const p=await b.review({logins:['alice','bob','carol'],permission:'write'}),r=await b.apply(p.planId);const index=failed==='alice'?0:1;assert.equal(r.results[index].diagnostic.httpStatus,403);assert.equal(r.results[index].diagnostic.outcome,'rejected');assert.equal(r.results[index].error,'GITHUB_PERMISSION_REQUIRED');assert.ok(!JSON.stringify(r).includes('private raw message'));assert.equal(r.results[index+1].status,'Not attempted');assert.deepEqual(writes,failed==='alice'?['alice']:['alice','bob']);});
