import test from 'node:test';
import assert from 'node:assert/strict';
import {ReadingHistory,readingLocation,preserveBeforeNavigation} from '../src/reading-navigation.mjs';
const location=(path,extra={})=>({schemaVersion:1,repoId:'repo:stable-a',repo:'Example',ref:'',path,type:'file',mode:'preview',editing:false,fragment:'',selection:{anchor:0,head:0},scroll:{main:0,source:0,preview:0},...extra});
test('N01 successful visits restore full source, visual, split positions without source bytes',()=>{
 const history=new ReadingHistory();history.visit(location('current.md'));history.checkpoint(location('current.md',{mode:'split',editing:true,selection:{anchor:125,head:151},scroll:{main:350,source:860,preview:420}}));history.visit(location('evidence/report-v1.md',{fragment:'result'}));const ticket=history.peek(-1);assert.equal(ticket.location.mode,'split');assert.deepEqual(ticket.location.scroll,{main:350,source:860,preview:420});assert.deepEqual(ticket.location.selection,{anchor:125,head:151});history.complete(ticket.token,ticket.location);assert.equal(history.state().forward,true);const next=history.peek(1);assert.equal(next.location.path,'evidence/report-v1.md');history.complete(next.token,next.location);assert.equal(history.state().forward,false);
});
test('failed navigation consumes no entry or cursor; canceled tickets cannot later commit',()=>{const h=new ReadingHistory();h.visit(location('a.md'));h.visit(location('b.md'));const t=h.peek(-1);h.cancel(t.token);assert.equal(h.current().path,'b.md');assert.equal(h.state().count,2);assert.throws(()=>h.complete(t.token,t.location),/stale/);});
test('new destination prunes forward history; pending async results become stale',()=>{const h=new ReadingHistory();h.visit(location('a.md'));h.visit(location('b.md'));const t=h.peek(-1);h.visit(location('c.md'));assert.throws(()=>h.complete(t.token,t.location),/stale/);const back=h.peek(-1);h.complete(back.token,back.location);h.visit(location('d.md'));assert.equal(h.state().forward,false);assert.equal(h.state().count,3);});
test('history is bounded and does not expose mutable internal locations',()=>{const h=new ReadingHistory(3);for(let i=0;i<9;i++)h.visit(location(`${i}.md`));assert.equal(h.state().count,3);const t=h.peek(-1);t.location.path='forged.md';assert.throws(()=>h.complete(t.token,t.location),/stale/);assert.equal(h.current().path,'8.md');});
test('repository removal prunes history, managed rename updates only matching identity',()=>{const h=new ReadingHistory();h.visit(location('folder/a.md'));h.visit(location('other.md',{repoId:'repo:b'}));h.renamePaths('repo:stable-a',[{from:'folder',to:'renamed'}]);assert.equal(h.peek(-1).location.path,'renamed/a.md');h.removeRepository('repo:stable-a');assert.equal(h.state().count,1);assert.equal(h.current().repoId,'repo:b');h.removeRepository('repo:b');assert.equal(h.current(),null);});
test('ref changes are distinct reading locations and same target checkpoints do not grow history',()=>{const h=new ReadingHistory();h.visit(location('a.md'));h.visit(location('a.md',{mode:'visual'}));assert.equal(h.state().count,1);h.visit(location('a.md',{ref:'0123456789abcdef'}));assert.equal(h.state().count,2);assert.equal(h.peek(-1).location.ref,'');});
test('locations reject absolute/traversal paths, invalid positions and unsupported versions',()=>{for(const path of ['/Users/name/file','../file','folder/../file','C:\\file'])assert.throws(()=>readingLocation(location(path)));assert.throws(()=>readingLocation(location('a.md',{schemaVersion:2})));assert.throws(()=>readingLocation(location('a.md',{scroll:{main:NaN,source:0,preview:0}})));});

test('long supported refs and fragments remain reading positions; optional history cannot block retained drafts',async()=>{
 const value=location('a.md',{ref:'refs/heads/'+ 'a'.repeat(600),fragment:'heading-'+ 'b'.repeat(1500)});assert.deepEqual(readingLocation(value).ref,value.ref);
 const events=[];const result=await preserveBeforeNavigation(async()=>{events.push('retained');},async()=>{events.push('history');readingLocation({...value,fragment:'x'.repeat(3000)});});assert.deepEqual(events,['retained','history']);assert.equal(result.historyUnavailable,true);assert.equal(result.historyState,null);
 let visited=false;const failure=new Error('Draft write failed');await assert.rejects(preserveBeforeNavigation(async()=>{throw failure;},async()=>{visited=true;}),failure);assert.equal(visited,false,'Draft failures still prevent leaving');
});
