import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {parseCollectionMetadata,resolvePortableReference,evidenceContext,portableReference,sourceTargetSelection,assertResolvedRepository} from '../src/reading-reference.mjs';
const sha=text=>createHash('sha256').update(text).digest('hex');
const historic='# Result\n\nMeasured 30 Hz.\n',planning='# Result\n\nTarget 60 Hz, not measured.\n';
const manifest=()=>({schemaVersion:1,collectionId:'demo.collection',documents:[{id:'demo.rate.v1',path:'evidence/report-v1.md',evidence:{observationDate:'2026-09-20',build:'demo-1',kind:'measured',scope:'one synthetic demonstration workload',supersedes:''},targets:[{id:'rate',kind:'heading',sourceHash:sha(historic),from:0,to:8}]},{id:'demo.rate.v2',path:'evidence/report-v2.md',evidence:{observationDate:'2026-09-22',build:'demo-2',kind:'target',validation:'not measured',supersedes:'demo.rate.v1'}}]});
const candidate=(repo='Renamed fixture')=>({repoId:'stable:1',repo,metadata:parseCollectionMetadata(JSON.stringify(manifest()))});
const reference=(extra={})=>({schemaVersion:1,collectionId:'demo.collection',documentId:'demo.rate.v1',...extra});
const readDocument=async(_candidate,path)=>{const text=path==='evidence/report-v1.md'||path==='renamed/report-v1.md'?historic:planning;return{text,sourceHash:sha(text)};};
test('N02 measured and target declarations remain distinct without generated verification',()=>{const data=candidate().metadata,a=evidenceContext(data,'evidence/report-v1.md'),b=evidenceContext(data,'evidence/report-v2.md');assert.equal(a.evidence.kind,'measured');assert.equal(b.evidence.kind,'target');assert.equal(b.evidence.validation,'not measured');assert.match(a.message,/not independently verified/);assert.equal('validated' in a,false);});
test('N03 portable identities resolve after repository name and physical location changes',async()=>{for(const repo of ['Original','Imported elsewhere']){const result=await resolvePortableReference({reference:reference(),candidates:[candidate(repo)],readDocument});assert.equal(result.status,'resolved');assert.equal(result.repo,repo);assert.equal(result.path,'evidence/report-v1.md');assert.equal('absolutePath' in result,false);}});
test('N03 duplicate installed collection IDs require explicit repository choice',async()=>{let read=false;const result=await resolvePortableReference({reference:reference(),candidates:[candidate(),{...candidate('Copy'),repoId:'stable:2'}],readDocument:async()=>{read=true;}});assert.equal(result.status,'ambiguous');assert.equal(read,false);assert.equal(result.candidates.length,2);});
test('N04 managed rename resolves declared document through host mapping; external rename stays missing',async()=>{const redirects=[{repoId:'stable:1',from:'evidence/report-v1.md',to:'renamed/report-v1.md',documentId:'demo.rate.v1'}];const reader=async(c,p)=>{if(p.startsWith('evidence'))throw new Error('missing');return readDocument(c,p);};assert.equal((await resolvePortableReference({reference:reference(),candidates:[candidate()],readDocument:reader})).status,'missing');const result=await resolvePortableReference({reference:reference(),candidates:[candidate()],readDocument:reader,redirects});assert.equal(result.status,'resolved');assert.equal(result.redirected,true);assert.equal(result.path,'renamed/report-v1.md');});
test('N04 exact target requires source hash and refuses changed heading instead of nearby fallback',async()=>{const result=await resolvePortableReference({reference:reference({targetId:'rate'}),candidates:[candidate()],readDocument});assert.equal(result.status,'resolved');assert.equal(result.target.kind,'heading');const changed=await resolvePortableReference({reference:reference({targetId:'rate'}),candidates:[candidate()],readDocument:async()=>({text:'# Renamed result\n\nMeasured 30 Hz.',sourceHash:sha('changed')})});assert.equal(changed.status,'changed');assert.equal((await resolvePortableReference({reference:reference({targetId:'absent'}),candidates:[candidate()],readDocument})).status,'missing');});
test('N04 duplicate document and target IDs refuse metadata rather than first match',()=>{const a=manifest();a.documents.push({...a.documents[0],path:'another.md'});assert.equal(parseCollectionMetadata(JSON.stringify(a)).status,'ambiguous');const b=manifest();b.documents[0].targets.push({...b.documents[0].targets[0]});assert.equal(parseCollectionMetadata(JSON.stringify(b)).status,'ambiguous');});
test('N05 pinned hash and immutable revision never silently show new working bytes',async()=>{const candidates=[candidate()];const a=await resolvePortableReference({reference:reference({sourceHash:sha(historic)}),candidates,readDocument});assert.equal(a.status,'resolved');const b=await resolvePortableReference({reference:reference({sourceHash:sha(historic)}),candidates,readDocument:async()=>({text:planning,sourceHash:sha(planning)})});assert.equal(b.status,'changed');const c=await resolvePortableReference({reference:reference({revision:'0123456789abcdef0123456789abcdef01234567',sourceHash:sha(historic)}),candidates,readDocument});assert.equal(c.status,'version-unavailable');const d=await resolvePortableReference({reference:reference({revision:'0123456789abcdef0123456789abcdef01234567',sourceHash:sha(historic)}),candidates,readDocument,readRevision:readDocument});assert.equal(d.status,'resolved');assert.equal(d.revision,'0123456789abcdef0123456789abcdef01234567');});
test('N06 missing, malformed, oversized and unknown metadata are nonthrowing readable fallbacks',()=>{for(const [input,status] of [[undefined,'missing'],['{','invalid'],[' '.repeat(65537),'invalid'],[JSON.stringify({schemaVersion:99}),'unsupported']])assert.equal(parseCollectionMetadata(input).status,status);const evil=manifest();evil.documents[0].path='../escape';assert.equal(parseCollectionMetadata(JSON.stringify(evil)).status,'invalid');});
test('reference schema admits no path, executable payload or unsupported revision guess',()=>{assert.throws(()=>portableReference({schemaVersion:2}));const ref=portableReference({...reference(),path:'/private/x',execute:'javascript:alert(1)'});assert.equal('path' in ref,false);assert.equal('execute' in ref,false);});

test('target ranges convert raw BOM/CRLF to CM6 coordinates without guessing Unicode boundaries',()=>{const raw='\ufeff# Heading\r\nText 😀';assert.deepEqual(sourceTargetSelection(raw,{from:1,to:10}),{from:0,to:9});assert.equal(sourceTargetSelection(raw,{from:10,to:11}),null);assert.equal(sourceTargetSelection(raw,{from:18,to:19}),null);});

test('pinned revisions accept immutable full OIDs and refuse branch/tag names',()=>{for(const revision of ['main','refs/heads/main','refs/tags/v1','HEAD','123abcd'])assert.throws(()=>portableReference(reference({revision})));assert.equal(portableReference(reference({revision:'a'.repeat(40)})).revision,'a'.repeat(40));assert.equal(portableReference(reference({revision:'b'.repeat(64)})).revision,'b'.repeat(64));});

test('resolved local repository identity must still match after asynchronous navigation',()=>{
 const resolved={status:'resolved',repoId:'stable:original',repo:'Same-name'};assertResolvedRepository(resolved,'stable:original');for(const identity of ['stable:replacement',undefined,''])assert.throws(()=>assertResolvedRepository(resolved,identity),/repository changed/);assert.throws(()=>assertResolvedRepository({...resolved,status:'ambiguous'},'stable:original'));
});
