const fail=()=>{throw Object.assign(Error('INVALID_TEACH_SETTINGS'),{code:'INVALID_TEACH_SETTINGS'});};
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v,keys)=>object(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const text=(v,max=2000)=>typeof v==='string'&&v.isWellFormed()&&!v.includes('\0')&&v.length<=max;
const array=(v,check)=>Array.isArray(v)&&v.length<=128&&v.every(check);
export function validTeacher(v){return exact(v,['givenNames','familyNames','publishedName','orcidId','alsoKnownAs','biography','emails','websites','keywords','countries','employment'])&&['givenNames','familyNames','publishedName','orcidId','biography'].every(k=>text(v[k],k==='biography'?5000:2000))&&['alsoKnownAs','emails','keywords','countries'].every(k=>array(v[k],x=>text(x)))&&array(v.websites,w=>exact(w,['description','url'])&&text(w.description)&&text(w.url))&&array(v.employment,e=>exact(e,['organization','city','region','country','department','roleTitle','startDate','endDate','link'])&&['organization','city','region','country','department','roleTitle','link'].every(k=>text(e[k]))&&['startDate','endDate'].every(k=>exact(e[k],['year','month','day'])&&Object.values(e[k]).every(x=>text(x,4))));}
export const emptyTeacher=()=>({givenNames:'',familyNames:'',publishedName:'',orcidId:'',alsoKnownAs:[],biography:'',emails:[],websites:[],keywords:[],countries:[],employment:[]});
const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
export function validCalendar(v){return exact(v,['monday','totalWeeks','sessions'])&&(v.monday===''||date(v.monday)&&new Date(v.monday+'T00:00:00Z').getUTCDay()===1)&&Number.isInteger(v.totalWeeks)&&v.totalWeeks>=1&&v.totalWeeks<=53&&array(v.sessions,s=>exact(s,['id','title','weekday','start','end','location','weekFrom','weekTo'])&&text(s.id,80)&&text(s.title,120)&&text(s.location,160)&&Number.isInteger(s.weekday)&&s.weekday>=0&&s.weekday<=6&&/^([01]\d|2[0-3]):[0-5]\d$/.test(s.start)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(s.end)&&s.start<s.end&&Number.isInteger(s.weekFrom)&&Number.isInteger(s.weekTo)&&s.weekFrom>=1&&s.weekTo>=s.weekFrom&&s.weekTo<=v.totalWeeks)&&new Set(v.sessions.map(s=>s.id)).size===v.sessions.length;}
export const defaultCalendar=()=>({monday:'',totalWeeks:14,sessions:[]});
export function validateDefaults(v){if(!exact(v,['teacher','office','noClassDays'])||!validTeacher(v.teacher)||!exact(v.office,['hours','weekdays','location'])||!Object.values(v.office).every(s=>text(s,160))||!array(v.noClassDays,d=>exact(d,['id','date','description'])&&text(d.id,80)&&date(d.date)&&text(d.description,200))||new Set(v.noClassDays.map(d=>d.date)).size!==v.noClassDays.length||JSON.stringify(v).length>65536)fail();return structuredClone(v);}
export const emptyDefaults=()=>({teacher:emptyTeacher(),office:{hours:'',weekdays:'',location:''},noClassDays:[]});
export function validateTermSettings(v){if(!exact(v,['schemaVersion','teacherSnapshot','calendar'])||v.schemaVersion!==1||!validTeacher(v.teacherSnapshot)||!validCalendar(v.calendar)||JSON.stringify(v).length>65536)fail();return structuredClone(v);}
