import React,{useEffect,useRef,useState} from 'react';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
import type {WorkspaceAdoptionReview} from './native-types';
export function ApplicationInfoDialog({onClose}:{onClose():void}){
 const dialog=useRef<HTMLDialogElement>(null),[info,setInfo]=useState<{version:string;buildNumber:number;channel:string;dataRoot:string}|null>(null),[locations,setLocations]=useState<{previousRoot:string|null;pending:string|null;candidates:{root:string;repositories:string[]}[]}|null>(null),[error,setError]=useState(''),[review,setReview]=useState<WorkspaceAdoptionReview|null>(null),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[closing,setClosing]=useState(false),[phase,setPhase]=useState('Preserving drafts…');
 useEffect(()=>{dialog.current?.showModal();let active=true;const bridge=getNativeBridge();if(bridge)void Promise.all([nativeOperation(()=>bridge.getApplicationInfo()),nativeOperation(()=>bridge.getWorkspaceLocations())]).then(([value,where])=>{if(active){setInfo(value);setLocations(where);}}).catch(reason=>{if(active)setError((reason as Error).message);});return()=>{active=false;dialog.current?.close();};},[]);
 useEffect(()=>getNativeBridge()?.onWorkspaceProgress?.(message=>setPhase(({locked:'Verifying current workspace backup…','current-backed-up':'Verifying selected workspace backup…','target-backed-up':'Checking selected private state…',validated:'Recording workspace selection…',selected:'Workspace selected. Finishing…',complete:'Workspace switch ready.'} as Record<string,string>)[message.phase]??'Preparing workspace switch…')),[]);
 useEffect(()=>getNativeBridge()?.onPrepareClose?.(message=>{if(message.cancelled){setClosing(false);setBusy(false);setReview(null);setError(message.error??'Closing was cancelled. Review the workspace again before switching.');}}),[]);
 const choose=async(action:'choose'|'previous'|'resume')=>{const bridge=getNativeBridge();if(!bridge)return;setBusy(true);setError('');setApproved(false);try{setReview(await nativeOperation(()=>bridge.reviewWorkspaceAdoption({action})));}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
 const confirm=async()=>{const bridge=getNativeBridge();if(!bridge||!review||!approved)return;setBusy(true);setError('');try{await nativeOperation(()=>bridge.confirmWorkspaceAdoption({reviewId:review.reviewId,approved:true}));setClosing(true);}catch(reason){setError((reason as Error).message);setBusy(false);}};
 return <dialog ref={dialog} className="ac-settings workspace-info" aria-labelledby="application-info-title" onCancel={event=>{event.preventDefault();if(!busy)onClose();}}><header><h2 id="application-info-title">About asMagicBrain</h2><button disabled={busy} onClick={onClose} aria-label="Close application information">×</button></header>{error&&<p role="alert">{error}</p>}{info?<><p>Version {info.version} · Build {info.buildNumber}</p><p>Channel: {info.channel}</p><h3>Active workspace location</h3><p className="workspace-path">{info.dataRoot}</p><p>Installing or enabling asTeach does not move courses between workspaces.</p></>:<p role="status">Loading application information…</p>}
 {closing?<p role="status">{phase} Keep this application open until it finishes. A native dialog will report the result.</p>:review?<section aria-labelledby="workspace-review-title"><h3 id="workspace-review-title">Review workspace switch</h3><p>Use the selected folder in place. Both folders receive verified backups. Their courses and private state are kept separate; no files are merged or overwritten.</p><dl><dt>Current folder</dt><dd className="workspace-path">{review.currentRoot}</dd><dt>Selected folder</dt><dd className="workspace-path">{review.targetRoot}</dd><dt>Selected contents</dt><dd>{review.target.repositories.length} repositories · {review.target.fileCount.toLocaleString()} files · {(review.target.bytes/1024/1024).toFixed(1)} MB · {review.target.links} symbolic links retained without following their targets</dd></dl><p>Repositories: {review.target.repositories.join(', ')||'None'}</p>{review.overlappingRepositories.length>0&&<p>Names present in both folders: {review.overlappingRepositories.join(', ')}. Switching chooses one complete workspace; it does not reconcile these copies. Edit only the active copy.</p>}<p>Git history, drafts, Trash, installed plugins and course state stay with the selected folder. Account credentials are not copied; sign in again. Local automation must be authorized again. Backup copies retain recovery evidence and are not directly usable as rebound profiles.</p><label><input type="checkbox" checked={approved} disabled={busy} onChange={event=>setApproved(event.target.checked)}/> I reviewed the folders and want to back up both, close this session and use the selected workspace when I reopen.</label><footer><button disabled={busy} onClick={()=>setReview(null)}>Cancel review</button><button disabled={busy||!approved} onClick={()=>void confirm()}>Back up and switch</button></footer></section>:<section><h3>Locate previous courses</h3>{locations?.candidates.map(candidate=><p key={candidate.root} className="workspace-path">Known folder: {candidate.root}<br/>{candidate.repositories.length} repositories. Choose it through the folder picker to review.</p>)}<p>Select the complete managed-data folder containing <code>workspaces</code> and <code>state</code>. Large repositories keep their Git history; no ZIP import is required. Existing folders remain recoverable.</p><div className="workspace-actions"><button disabled={busy} onClick={()=>void choose('choose')}>Locate previous courses</button>{locations?.previousRoot&&<button disabled={busy} onClick={()=>void choose('previous')}>Review return to previous workspace</button>}{locations?.pending&&<button disabled={busy} onClick={()=>void choose('resume')}>Resume workspace review</button>}</div></section>}
 {!closing&&<footer><button disabled={busy} onClick={onClose}>Done</button>{busy&&<span role="status">Checking workspace…</span>}</footer>}</dialog>;
}
