import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
import type {AutomationStatus,AutomationScope} from './native-types';
import type {RepositoryCatalogEntry} from './repository-catalog';
import './package-exchange.css';
export function LocalAutomationDialog({repositories,onClose,beforeApprove,onChanged}:{repositories:RepositoryCatalogEntry[];onClose():void;beforeApprove():Promise<void>;onChanged():void}){
 const dialog=useRef<HTMLDialogElement>(null),[status,setStatus]=useState<AutomationStatus|null>(null),[grants,setGrants]=useState<Record<string,AutomationScope[]>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const bridge=getNativeBridge()!;
 const refresh=async()=>{const value=await nativeOperation(()=>bridge.getAutomationStatus());setStatus(value);return value;};
 const run=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await nativeOperation(fn);await refresh();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
 useLayoutEffect(()=>{dialog.current!.showModal();void refresh().then(value=>setGrants(Object.fromEntries(value.grants.map(grant=>[grant.repoId,grant.scopes])))).catch(reason=>setError(reason.message));return()=>dialog.current?.close();},[]);
 useEffect(()=>{if(!status?.enabled)return;const timer=setInterval(()=>{if(!busy)void refresh().catch(reason=>setError(reason.message));},1500);return()=>clearInterval(timer);},[status?.enabled,busy]);
 const configure=(enabled:boolean)=>run(()=>bridge.configureAutomation({enabled,grants:Object.entries(grants).filter(([,scopes])=>scopes.length).map(([repoId,scopes])=>({repoId,scopes}))}));
 const toggle=(id:string,scope:AutomationScope,checked:boolean)=>setGrants(value=>({...value,[id]:checked?[...new Set([...(value[id]??[]),scope])]:(value[id]??[]).filter(item=>item!==scope)}));
 return <dialog className="package-dialog" ref={dialog} aria-labelledby="automation-heading" onCancel={event=>{event.preventDefault();if(!busy)onClose();}}><header><h2 id="automation-heading">Local automation</h2><button disabled={busy} aria-label="Close local automation" onClick={onClose}>×</button></header>
 <p>Connect a local tool to this running app. Access lasts for this session. Every write, import and export waits for your review here.</p>
 <p>Automation cannot delete files, create commits, push, access account credentials, or run interactive content.</p>
 <table><caption>Repository permissions</caption><thead><tr><th>Repository</th>{(['read','write','import','export'] as const).map(scope=><th key={scope}>{scope==='read'?'Read / search':scope[0].toUpperCase()+scope.slice(1)}</th>)}</tr></thead><tbody>{repositories.filter(entry=>entry.stableId).map(entry=><tr key={entry.stableId}><th scope="row">{entry.name}</th>{(['read','write','import','export'] as const).map(scope=><td key={scope}><input type="checkbox" aria-label={`${scope} ${entry.name}`} disabled={busy||entry.readOnly&&['write','import'].includes(scope)} checked={grants[entry.stableId!]?.includes(scope)??false} onChange={event=>toggle(entry.stableId!,scope,event.target.checked)}/></td>)}</tr>)}</tbody></table>
 <footer><button disabled={busy} onClick={()=>void configure(true)}>{status?.enabled?'Apply permissions':'Enable for this session'}</button>{status?.enabled&&<button disabled={busy} onClick={()=>void configure(false)}>Disconnect tools</button>}</footer>
 {status?.connectionFile&&<section><h3>Connection</h3><p>Use this private connection file with the bundled CLI. It stops working when you disconnect or quit.</p><code>{status.connectionFile}</code><p><button onClick={()=>void navigator.clipboard.writeText(status.connectionFile!)}>Copy connection path</button></p></section>}
 <section><h3>Requests</h3>{!status?.operations.length?<p>No requests yet.</p>:status.operations.slice().reverse().map(operation=><details key={operation.operationId} open={operation.status==='review'}><summary>{operation.kind} · {operation.status} · {operation.requestId}</summary><p>Review fingerprint: <code>{operation.digest}</code></p><pre className="automation-plan">{JSON.stringify(operation.plan,null,2)}</pre>{operation.error&&<p role="alert">{operation.error.message}</p>}{operation.status==='review'&&<footer><button disabled={busy} onClick={()=>void run(()=>bridge.cancelAutomation({operationId:operation.operationId}))}>Cancel request</button><button disabled={busy||!status.enabled} onClick={()=>void run(async()=>{await beforeApprove();await bridge.approveAutomation({operationId:operation.operationId,digest:operation.digest});onChanged();})}>Approve this request</button></footer>}</details>)}</section>{error&&<p role="alert" className="rfe-error">{error}</p>}{busy&&<p role="status">Working…</p>}
 </dialog>;
}
