import React,{useEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
import './teach-publish-dialog.css';
type Props={destinationRepo?:string;proposal:{studentText:string;sourceHash:string};repo:string;year:number;season:string;onClose():void;onSaved(repo:string,path:string):void};
const messages:Record<string,string>={PUBLICATION_UNSUPPORTED_HTML:'This HTML block cannot be converted safely. Replace unsupported or active markup, or use Markdown before exporting.',PUBLICATION_REWRITE_REQUIRED:'A shared asset link could not be safely rewritten. Use a term-local copy for this link.',PUBLICATION_PAGE_NOT_SELECTED:'A selected page links to another Markdown page that is not selected. Select that page or revise the link.',PUBLICATION_COLLECTION_CONFLICT:'This repository is already registered to another publication. Choose a separate student repository.',PUBLICATION_UPDATE_CONFLICT:'Student files were edited independently. Resolve the differences before updating.',PUBLICATION_DESTINATION_EXISTS:'This term already exists in the destination. Existing files are preserved. Choose another repository.',PUBLICATION_PRIVATE_LINK:'A link leaves this term or points to Instructor/private or unsupported content. Revise the Student links before exporting.',PUBLICATION_MISSING_LINK:'A linked local file is missing. Repair the link before exporting.',PUBLICATION_HTML_LINK:'A local HTML link needs conversion to a Markdown link before export.',PUBLICATION_UNSUPPORTED_ASSET:'A candidate file type is unsupported. Nothing was silently omitted. Move it outside the candidate root or use an explicitly versioned external asset.',PUBLICATION_LAYOUT:'This export requires student.md directly inside the year-season folder.',PUBLICATION_EXPIRED:'This review expired. Review the files again.',DRAFT_CONFLICT:'Save or resolve course drafts before exporting.',CONFLICT:'The source or destination changed. Review again.',PUBLICATION_STUDENT_REQUIRED:'Save a reviewed Student page first.'};
function ReviewFile({file}:{file:any}){const [open,setOpen]=useState(false);return <li><details onToggle={e=>setOpen(e.currentTarget.open)}><summary>{file.path} · {file.bytes} bytes{file.generated?' · generated':''}</summary>{open&&<p>Source: {file.sourcePath} → {file.path}<br/>SHA-256: {file.sha256}</p>}{open&&(file.preview!==null?<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{file.preview}{file.bytes>16000?'\n[Preview limited; review the original file too.]':''}</pre>:<p>Binary asset. Review this file in the source repository before copying.</p>)}</details></li>;}
export function NativeTeachPublishDialog({destinationRepo,proposal,repo,year,season,onClose,onSaved}:Props){
 const [structured,setStructured]=useState(false);
 const [publishedPages,setPublishedPages]=useState<Record<string,string[]>>({});
 const [convertGitBook,setConvertGitBook]=useState(false);
 const [pages,setPages]=useState<string[]>([]),[selectedPages,setSelectedPages]=useState<string[]>([]);
 const [destinations,setDestinations]=useState<any[]>([]),[destination,setDestination]=useState(destinationRepo??''),[review,setReview]=useState<any>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const pending=useRef(false),current=useRef<any>(null);
 const call=(input:Record<string,unknown>)=>nativeOperation(()=>getNativeBridge()!.nativeTeachRequest(input));
 useEffect(()=>{let active=true;void call({operation:'courseFiles',repo,year,season}).then(result=>{if(active){setStructured(Boolean(result.audiences));const available=result.entries.filter((e:any)=>e.type==='file'&&e.path.startsWith(result.audiences?result.audiences.students.root+'/':result.folder+'/')&&/\.(md|markdown)$/i.test(e.path)&&e.path!==result.instructor&&!/(^|\/)(?:private|teacher)(?:\/|\.)/i.test(e.path)&&!/(^|\/)(?:student|SUMMARY|instructor(?:-template)?)\.md$/i.test(e.path)).map((e:any)=>e.path);setPages(available);if(result.audiences)setSelectedPages(available);else if(destinationRepo)setSelectedPages(available.filter((p:string)=>result.students.find((student:any)=>student.repo===destinationRepo)?.publishedPaths.includes(p)));setPublishedPages(Object.fromEntries(result.students.map((student:any)=>[student.repo,available.filter((p:string)=>student.publishedPaths.includes(p))])));}}).catch(e=>{if(active)setError(e.message);});void call({operation:'publicationDestinations'}).then(items=>{if(active)setDestinations(items);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;if(current.current)void call({operation:'cancelPublication',planId:current.current.planId}).catch(()=>{});};},[]);
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await action();}catch(e){setError(messages[(e as any).code]??(e as Error).message);setReview(null);current.current=null;}finally{pending.current=false;setBusy(false);}};
 const reset=()=>{if(current.current)void call({operation:'cancelPublication',planId:current.current.planId}).catch(()=>{});current.current=null;setReview(null);setAck(false);setNotice('');};
 return <CourseDialog title="Prepare Student output" onClose={()=>{if(!busy)onClose();}}><div className="teach-publish teach-native-output" aria-busy={busy} data-teach-area="T10">
 <p>{structured?'Review the complete Student candidate root, including class lessons, code and media. Candidate paths become term-relative paths in the released Students repository.':'Choose whole pages to accompany the reviewed Student home. Links to other pages require selection; linked assets are included automatically.'} Instructor files and Git history are excluded. Saving output does not commit or push it.</p>
 <label>Destination<select disabled={busy||Boolean(destinationRepo)} value={destination} onChange={e=>{reset();setDestination(e.target.value);setSelectedPages(publishedPages[e.target.value]??[]);}}><option value={destinationRepo??''}>{destinationRepo??'GitBook-ready ZIP'}</option>{destinations.filter(d=>d.name!==repo&&d.name!==destinationRepo).map(d=><option key={d.name} value={d.name}>{d.name}{d.sourceUrl?' · GitHub clone':' · local repository'}</option>)}</select></label>
 <p>Each term stays in its own {year}-{season} folder. Previously published files are compared before updating; independent edits require resolution. For GitBook Git Sync, select this term as the project directory.</p>
 {!review&&<label className="teach-output-ack"><input type="checkbox" disabled={busy} checked={convertGitBook} onChange={e=>setConvertGitBook(e.target.checked)}/> Convert GitBook HTML in Student output. Originals stay unchanged; review the converted files.</label>}
 {!review&&!structured&&<fieldset disabled={busy}><legend>Student pages</legend><p>The Student home is always included. Private materials stay excluded.</p>{pages.length?pages.map(page=><label className="teach-output-ack" key={page}><input type="checkbox" checked={selectedPages.includes(page)} onChange={e=>setSelectedPages(previous=>e.target.checked?[...previous,page]:previous.filter(p=>p!==page))}/>{page}</label>):<p>No additional Markdown pages.</p>}</fieldset>}
 {!review&&<button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const next=await call({operation:'reviewPublication',repo,year,season,destination:destination||null,selectedPages,convertGitBook,...proposal});current.current=next;setReview(next);setAck(false);setNotice('');})}>Review output</button>}
 {review&&<><h3>Review files ({review.files.length})</h3><p><strong>{review.destination?.name??'ZIP export'}</strong> / {review.folder}{review.destination?.sourceUrl&&<><br/>{review.destination.sourceUrl} · {review.destination.branch}</>}</p>
 {review.comparison?.kind==='update'&&<section><h3>Changes to Student edition</h3><ul>{review.comparison.rows.map((row:any)=><li key={row.path}><details><summary>{row.path} · {row.action}{row.protectedDraft?' · unsaved draft':''}</summary>{row.current!==undefined&&<><h4>Current Student file</h4><pre>{row.current??'(absent)'}</pre><h4>Proposed file</h4><pre>{row.incoming??'(remove)'}</pre></>}</details></li>)}</ul>{(review.comparison.rows.some((row:any)=>row.conflict||row.protectedDraft)||review.comparison.warnings.length>0)&&<p role="alert">Resolve edited Student files or drafts before updating. No files will be overwritten.</p>}</section>}
 <div className="teach-publish-review"><section><ul>{review.files.map((file:any)=><ReviewFile key={file.path} file={file}/>)}</ul></section></div>
 <p>Only listed files are copied. SUMMARY.md and .gitbook.yaml provide navigation; shared asset links are adjusted in the output without changing authoring files.</p>{review.conversions?.length>0&&<section><h3>GitBook conversion ({review.conversions.length} files)</h3>{review.conversions.map((item:any)=><details key={item.path}><summary>{item.path}</summary><ul>{item.changes.map((change:string)=><li key={change}>{change}</li>)}</ul><h4>Original source</h4><pre style={{whiteSpace:'pre-wrap'}}>{item.original}</pre><p>Compare with the proposed file above. Long source previews are limited to 16,000 characters.</p></details>)}</section>}{review.warnings.map((warning:string)=><p key={warning}>{warning}</p>)}
 <label className="teach-output-ack"><input type="checkbox" disabled={busy} checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed all listed files, including comments and attachments, for student sharing.</label>
 <div className="teach-publish-settings"><button className="pws-button" disabled={busy} onClick={reset}>Back</button><button className="pws-button" disabled={!ack||busy||Boolean(review.comparison?.rows.some((row:any)=>row.conflict||row.protectedDraft))||Boolean(review.comparison?.warnings?.length)} onClick={()=>void run(async()=>{const planId=review.planId;current.current=null;setNotice('Saving reviewed Student files… Keep the app open.');if(destination){const result=await call({operation:'copyPublication',planId});onSaved(result.repository,result.path);onClose();}else{const result=await nativeOperation(()=>getNativeBridge()!.saveTeachPublication({planId}));setNotice(result.saved?'Student ZIP saved.':'Export cancelled. Review again to choose another destination.');}})}>{destination?'Save to student repository':'Save ZIP…'}</button></div></>}
 {busy&&<p role="status">{notice||'Preparing reviewed output…'}</p>}
 {error&&<p role="alert">{error}</p>}{notice&&!busy&&<p role="status">{notice}</p>}
 </div></CourseDialog>;
}
