import React,{useEffect,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
export function NativeTeachAdoptDialog({onClose,onAdopt}:{onClose():void;onAdopt(value:Record<string,unknown>):Promise<void>}){
 const [repos,setRepos]=useState<string[]>([]),[repo,setRepo]=useState(''),[paths,setPaths]=useState<string[]>([]),[source,setSource]=useState('');
 const [code,setCode]=useState(''),[name,setName]=useState(''),[year,setYear]=useState(String(new Date().getFullYear())),[season,setSeason]=useState('autumn'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void nativeOperation(()=>getNativeBridge()!.catalog()).then(c=>setRepos(c.repositories.map(r=>r.name).filter(n=>!['asMagicBrain-Docs','asMagicBrain-DevDocs'].includes(n)))).catch(e=>setError(e.message));},[]);
 useEffect(()=>{setPaths([]);setSource('');if(!repo)return;let current=true;void nativeOperation(()=>getNativeBridge()!.request({repo,operation:'discover',args:{}})).then((result:any)=>{if(current){if(result.truncated)throw Error('Repository file list is incomplete.');setPaths(result.entries.filter((e:any)=>e.type==='file'&&/\.md$/i.test(e.path)).map((e:any)=>e.path));}}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[repo]);
 return <CourseDialog title="Add existing course" onClose={onClose}><form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void onAdopt({operation:'adopt',repo,course:{schemaVersion:1,courseId:crypto.randomUUID(),code,name,terms:[{year:Number(year),season,source:{kind:'document',paths:[source]}}]}}).then(onClose).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><p>Choose an imported local repository and its Instructor Markdown document. The original document stays unchanged.</p><fieldset disabled={busy} style={{border:0,padding:0}}><label>Repository<select required value={repo} onChange={e=>setRepo(e.target.value)}><option value="">Choose repository</option>{repos.map(r=><option key={r}>{r}</option>)}</select></label><label>Instructor document<select required value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose Markdown file</option>{paths.map(p=><option key={p}>{p}</option>)}</select></label><label>Course Code<input required maxLength={32} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Course Name<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Year<input required type="number" min={1949} max={2100} value={year} onChange={e=>setYear(e.target.value)}/></label><label>Season<select value={season} onChange={e=>setSeason(e.target.value)}>{['spring','summer','autumn','winter'].map(s=><option key={s}>{s}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancel</button><button type="submit">Add course</button></footer></fieldset></form></CourseDialog>;
}
