import React,{useEffect,useRef,useState} from 'react';
import {RepositoryFileEditor} from './RepositoryFileEditor';
import {WorkspaceSearch} from './WorkspaceSearch';
import {IntegratedDocumentOutline} from './IntegratedDocumentOutline';
import {PanelResizeHandle} from './PanelResizeHandle';
import {getNativeBridge,nativeOperation,readRepository} from './native-bridge.mjs';
import {isTypingTarget} from './workspace-navigation';
import type {NavigationRequest,OutlineState,SearchRequest} from './workspace-navigation';
import './native-course-workspace.css';

type Root={repositoryId:string;name:string;available:boolean;homePath:string|null;role?:string;label?:string};
type Slot={root:Root;ref:string;snapshot:any;initialPath:string};
type Props={descriptor:any;page:string;visible:boolean;calendar?:React.ReactNode;sidebar:boolean;outline:boolean;onSidebarClose():void;filesRevision:number;onCalendar():void;onActiveRoot(role:string):void;onSettings():void;onOutlineClose():void;targetPath?:string;onClose():void;onRefresh():Promise<void>;registerBeforeLeave(fn:(reason?:'close')=>Promise<void>):void;studentActions?:React.ComponentProps<typeof RepositoryFileEditor>['studentActions']};
/** Retain visited stable root/ref editors. The explorer is the editor's own surface,
 * portalled into the shared column; mutations never use a second file controller. */
export function NativeCourseWorkspace(props:Props){
 const [outlineWidth,setOutlineWidth]=useState(240);
 const [contentHeights,setContentHeights]=useState<Record<string,number>>({});
 const [treeHeights,setTreeHeights]=useState<Record<string,number>>({}),[availableHeight,setAvailableHeight]=useState(480);
 const [narrow,setNarrow]=useState(false);
 const [slots,setSlots]=useState<Record<string,Slot>>({}),[active,setActive]=useState(''),[expanded,setExpanded]=useState<Record<string,boolean>>({instructors:true,students:true,Projects:false}),[hosts,setHosts]=useState<Record<string,HTMLElement|null>>({}),[nav,setNav]=useState<NavigationRequest|null>(null),[search,setSearch]=useState<SearchRequest|null>(null),[error,setError]=useState(''),[width,setWidth]=useState(280),[outlines,setOutlines]=useState<Record<string,OutlineState|null>>({});
 const flushes=useRef(new Map<string,(reason?:'close')=>Promise<void>>()),sequence=useRef(0),surface=useRef<HTMLDivElement>(null),activeRef=useRef(active),slotsRef=useRef(slots),opening=useRef(false),hostRefs=useRef(new Map<string,(element:HTMLDivElement|null)=>void>()),rootTerms=useRef(new Map<string,string>());
 activeRef.current=active;slotsRef.current=slots;
 const roots:Root[]=props.descriptor?[...props.descriptor.roles,...props.descriptor.projects]:[];
 const key=(root:Root,ref='')=>root.repositoryId+':'+ref;
 const label=(root:Root)=>root.label??({instructors:'Instructors',assistants:'Assistants',students:'Students'} as Record<string,string>)[root.role!]??root.name;
 const flush=async(reason?:'close')=>{for(const fn of flushes.current.values())await fn(reason);};
 useEffect(()=>{props.registerBeforeLeave(flush);return()=>props.registerBeforeLeave(async()=>{});},[props.registerBeforeLeave]);
 useEffect(()=>{const node=surface.current;if(!node)return;const observer=new ResizeObserver(entries=>{if(entries[0].contentRect.width)setNarrow(entries[0].contentRect.width<760);setAvailableHeight(Math.max(160,entries[0].contentRect.height-160));});observer.observe(node);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!props.visible)return;const keydown=(event:KeyboardEvent)=>{if(event.defaultPrevented||event.isComposing||document.querySelector('dialog[open],.document-presentation'))return;const slot=slotsRef.current[activeRef.current];if((event.metaKey||event.ctrlKey)&&!event.altKey&&event.key.toLowerCase()==='p'&&slot){event.preventDefault();setSearch({mode:'files',repo:slot.root.name,ref:slot.ref,finder:true});}else if(event.key==='Escape'&&narrow&&props.sidebar){event.preventDefault();props.onSidebarClose();}else if(event.key==='/'&&!isTypingTarget(event.target)&&slot){event.preventDefault();setSearch({mode:'content',repo:slot.root.name});}};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);},[props.visible,props.sidebar,narrow]);
 const load=async(root:Root,ref='',path?:string)=>{const id=key(root,ref);if(slotsRef.current[id])return id;const initialPath=path??root.homePath??'',snapshot=await readRepository({repo:root.name,path:initialPath,ref});setSlots(old=>({...old,[id]:{root,ref,snapshot,initialPath}}));return id;};
 const activate=async(root:Root,ref='',path?:string,type:'file'|'directory'='file',request?:any)=>{if(opening.current)throw Error('Wait for the repository to finish opening.');opening.current=true;setError('');try{if(activeRef.current!==key(root,ref))await flushes.current.get(activeRef.current)?.();const id=await load(root,ref,path);setExpanded(old=>({...old,[root.role??root.repositoryId]:true}));setActive(id);if(props.descriptor)rootTerms.current.set(root.repositoryId,props.descriptor.courseId+':'+props.descriptor.term);props.onActiveRoot(root.role??'project');if(path!==undefined)setNav({...request,id:++sequence.current,repo:root.name,path,type,ref});}catch(reason){setError((reason as Error).message);throw reason;}finally{opening.current=false;}};
 // Loading a descriptor is cheap; mount only selected or expanded roots.
 useEffect(()=>{let alive=true;const target=props.page==='project'?undefined:roots.find(r=>r.role===(props.page==='student'?'students':props.page==='assistant'?'assistants':'instructors'));
 if(target?.available&&props.visible&&props.page!=='calendar'){const termKey=props.descriptor.courseId+':'+props.descriptor.term,changed=rootTerms.current.get(target.repositoryId)!==termKey;const path=props.targetPath??(changed||!slotsRef.current[key(target)]?target.homePath??'':undefined);void activate(target,'',path,path? 'file':'directory').catch(()=>{});}
 for(const root of roots)if(root.available&&expanded[root.role??root.repositoryId])void load(root).catch(reason=>{if(alive)setError(reason.message);});return()=>{alive=false;};
 },[props.descriptor,props.page,props.visible,props.targetPath]);
 // Stable IDs survive repository rename; refresh routing without replacing sessions.
 useEffect(()=>{setSlots(old=>Object.fromEntries(Object.entries(old).map(([id,slot])=>{const root=roots.find(r=>r.repositoryId===slot.root.repositoryId);return [id,root?{...slot,root}:slot];})));},[props.descriptor]);
 const toggle=async(root:Root)=>{const id=root.role??root.repositoryId,next=!expanded[id];setExpanded(old=>({...old,[id]:next}));if(next&&root.available)try{await load(root);}catch(reason){setError((reason as Error).message);}};
 const hostRef=(id:string)=>{if(!hostRefs.current.has(id))hostRefs.current.set(id,element=>setHosts(old=>old[id]===element?old:{...old,[id]:element}));return hostRefs.current.get(id)!;};
 const group=(root:Root)=>{const id=root.role??root.repositoryId,slotId=key(root),open=!!expanded[id];return <section key={root.repositoryId??id} className="ncw-root" aria-label={`${label(root)} repository`} data-repository={root.name} style={{'--ncw-tree-height':`${treeHeights[id]??contentHeights[id]??availableHeight}px`} as React.CSSProperties}><div ref={hostRef(slotId)}/>{open&&root.available&&<div className="ncw-height-handle" role="separator" tabIndex={0} title="Drag to resize; double-click to fit all files" aria-orientation="horizontal" aria-label={`${label(root)} explorer height`} aria-valuemin={64} aria-valuemax={Math.max(availableHeight*2,120)} aria-valuenow={treeHeights[id]??contentHeights[id]??availableHeight} onDoubleClick={()=>setTreeHeights(old=>{const next={...old};delete next[id];return next;})} onKeyDown={event=>{if(!['ArrowUp','ArrowDown','Home'].includes(event.key))return;event.preventDefault();setTreeHeights(old=>{if(event.key==='Home'){const next={...old};delete next[id];return next;}return {...old,[id]:Math.max(64,Math.min(availableHeight*2,(old[id]??contentHeights[id]??availableHeight)+(event.key==='ArrowUp'?-24:24)))};});}} onPointerDown={event=>{event.preventDefault();const node=event.currentTarget,start=event.clientY,height=treeHeights[id]??contentHeights[id]??availableHeight;node.setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>setTreeHeights(old=>({...old,[id]:Math.max(64,Math.min(availableHeight*2,height+e.clientY-start))}));const finish=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',finish);node.removeEventListener('pointercancel',finish);};node.addEventListener('pointermove',move);node.addEventListener('pointerup',finish);node.addEventListener('pointercancel',finish);}}/>}{!slots[slotId]&&<header className="rfe-sidebar-header"><button className="rfe-icon" aria-expanded={open} aria-label={`${open?'Collapse':'Expand'} ${label(root)} repository`} disabled={!root.available} onClick={()=>void toggle(root)}>{open?'▾':'▸'}</button><strong>{label(root)}</strong>{root.available?<button className="rfe-icon" aria-label={`Open ${label(root)}`} onClick={()=>void activate(root,'',root.homePath??'',root.homePath?'file':'directory').catch(()=>{})}>↗</button>:<span className="ncw-unavailable">Unavailable</span>}</header>}</section>;};
 useEffect(()=>{if(!props.visible||!props.sidebar)return;const slot=slots[active];if(slot)hosts[key(slot.root)]?.closest('.ncw-root')?.scrollIntoView({block:'start'});},[active,props.visible,props.sidebar,hosts]);
 const closeSearch=()=>setSearch(null);
 return <div className={`ncw ${narrow?'ncw-narrow':''}`} ref={surface} hidden={!props.visible}>
 {props.sidebar&&<aside className="ncw-sidebar" style={{width}} aria-label="Course repositories"><nav><button className="rfe-tree-row ncw-calendar" aria-current={props.page==='calendar'?'page':undefined} onClick={props.onCalendar}>Course calendar</button>{roots.filter(r=>r.role).map(group)}<section className="ncw-root"><header className="rfe-sidebar-header"><button className="rfe-icon" aria-label={`${expanded.Projects?'Collapse':'Expand'} Projects`} aria-expanded={!!expanded.Projects} onClick={()=>{setExpanded(old=>({...old,Projects:!old.Projects}));}}>{expanded.Projects?'▾':'▸'}</button><strong>Projects</strong></header><div hidden={!expanded.Projects} className="ncw-projects">{roots.filter(r=>!r.role).map(group)}</div></section></nav><PanelResizeHandle width={width} defaultWidth={280} minWidth={180} maxWidth={480} onResize={setWidth} onCollapse={()=>setWidth(180)} label="Course sidebar width"/></aside>}
 {narrow&&props.sidebar&&<button className="ncw-backdrop" aria-label="Close course sidebar" onClick={props.onSidebarClose}/>}<div className="ncw-content" inert={narrow&&props.sidebar}>{error&&<p role="alert" className="rfe-error">{error}</p>}{props.page==='calendar'&&props.calendar}{Object.entries(slots).map(([id,slot])=><div key={id} hidden={active!==id||props.page==='calendar'} className="ncw-editor"><RepositoryFileEditor active={active===id&&props.visible&&props.page!=='calendar'} presentInModes repository={slot.root.name} repositoryIdentity={slot.root.repositoryId} initialPath={slot.initialPath} initialDirectory={slot.snapshot.type==='directory'?slot.initialPath:undefined} initialSource={slot.snapshot.content??''} revision={slot.ref} branch={slot.snapshot.branch} branches={slot.snapshot.branches??[]} tags={slot.snapshot.tags??[]} fileSidebarOpen={false} explorerHost={(active.startsWith(slot.root.repositoryId+':')?active===id:!slot.ref)?hosts[key(slot.root)]:undefined} explorerLabel={label(slot.root)} explorerExpanded={!!expanded[slot.root.role??slot.root.repositoryId]} onExplorerContentHeight={height=>setContentHeights(old=>old[slot.root.role??slot.root.repositoryId]===height?old:{...old,[slot.root.role??slot.root.repositoryId]:height})} onExplorerToggle={()=>void toggle(slot.root)} beforeExplorerAction={async()=>{await activate(slot.root,slot.ref);}} filesRevision={props.filesRevision} studentActions={slot.root.role==='students'?props.studentActions:undefined} onClose={props.onClose} registerBeforeLeave={fn=>{flushes.current.set(id,fn);}} navigationRequest={nav?.repo===slot.root.name&&nav.ref===slot.ref?nav:null} onNavigationHandled={n=>setNav(old=>old?.id===n?null:old)} onOutlineChange={value=>setOutlines(old=>({...old,[id]:value}))} onSearch={setSearch} onRevisionChange={async(ref,path)=>{await activate(slot.root,ref,path);}} onRenameRepository={async(name)=>{for(const [other,fn] of flushes.current)if(other!==id)await fn();await nativeOperation(()=>getNativeBridge()!.renameRepository({repository:slot.root.name,name}));await props.onRefresh();}}/></div>)}</div>
 {props.outline&&props.page!=='calendar'&&<IntegratedDocumentOutline mainWindow={surface} outline={outlines[active]??null} width={outlineWidth} onResize={setOutlineWidth} onClose={props.onOutlineClose} onReturnToDocument={()=>surface.current?.querySelector<HTMLElement>('.ncw-editor:not([hidden]) .cm-content')?.focus()} onReady={()=>{}}/>}
 {search&&<WorkspaceSearch request={search} repositories={roots.filter(r=>r.available).map(r=>({name:r.name,privateRepo:r.role!=='students',stableId:r.repositoryId}))} returnFocus={null} onClose={closeSearch} onOpen={value=>{const root=roots.find(r=>r.name===value.repo);if(root){closeSearch();void activate(root,value.ref??'',value.path,value.type,value).catch(()=>{});}}}/>}
 </div>;
}
