import {TeachPipelineSettings} from './TeachPipelineSettings';
import {TeachStudentExport} from './TeachStudentTools';
import {CourseDialog} from './TeachCoursesStudy';
import {NativeTeachPublishDialog} from './NativeTeachPublishDialog';
import {TeachStudentReviewDialog} from './TeachStudentReviewDialog';
import {NativeTeachAdoptDialog} from './NativeTeachAdoptDialog';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {usePluginState} from './NativePluginHost';
import {isTrustedTeachPackage} from '../../packages/asteach-plugin/binding.mjs';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
import {TeachHomeStudy} from './TeachHomeStudy';
import {TeachCoursesStudy,NewCourseDialog} from './TeachCoursesStudy';
import {TeachCourseCalendarStudy,defaultTeachTermCalendar,type TeachCalendarState} from './TeachCalendarStudy';
import {TeachBreadcrumb} from './TeachBreadcrumb';
import {emptyTeacherProfile} from './teach-teacher-profile';
import {selectCurrentTeachTerm} from './teach-course-groups';
import type {TeachStudyCourse} from './teach-plugin-fixture';
import type {WorkspaceStudy} from './FocusedWriting';
import './plugin-workspace-study.css';

export function useNativeTeach({navigate,onDocument}:{navigate(action:()=>void):void;onDocument(repo:string,path:string,reload?:boolean):void}){
 const host=usePluginState(),enabled=Boolean(host?.getPackages().some(entry=>isTrustedTeachPackage(entry)&&entry.enabled));
 const [view,setView]=useState<'home'|'courses'|'calendar'|'student'|'document'|'settings'|null>(null),[records,setRecords]=useState<any[]>([]),[defaults,setDefaults]=useState<any>(null),[selected,setSelected]=useState<string>(),[addTerm,setAddTerm]=useState<string>();
 const [documentPage,setDocumentPage]=useState('home');
 const [publishing,setPublishing]=useState(false),[proposal,setProposal]=useState<{studentText:string;sourceHash:string}|null>(null);
 const [pairOptions,setPairOptions]=useState<string[]>([]);
 const [studentRepo,setStudentRepo]=useState(''),[reviewChoice,setReviewChoice]=useState(false),[exporting,setExporting]=useState(false),[studentText,setStudentText]=useState('');
 const [studentReview,setStudentReview]=useState<any>(null),[reviewing,setReviewing]=useState(false);const reviewButton=useRef<HTMLButtonElement>(null);
 const [adopting,setAdopting]=useState(false),[filesRevision,setFilesRevision]=useState(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const pending=useRef(false),navigation=useRef(0);
 const call=useCallback((value:Record<string,unknown>)=>nativeOperation(()=>getNativeBridge()!.nativeTeachRequest(value)),[]);
 const [graphInfo,setGraphInfo]=useState<any>(null);
 const pipelineCall=useCallback(async(value:Record<string,unknown>)=>{const result=await call(value);if(value.operation==='pipelineSettings')setGraphInfo(result);return result;},[call]);
 const refresh=async()=>{const [next,settings]=await Promise.all([call({operation:'list'}),call({operation:'defaults'})]);setRecords(next);setDefaults(settings);};
 useEffect(()=>{if(!enabled){setView(null);return;}void refresh().catch(e=>setError(e.message));},[enabled]);
 const courses:TeachStudyCourse[]=records.flatMap(record=>record.course.terms.map((term:any)=>({id:`${record.course.courseId}:${term.year}-${term.season}`,code:record.course.code,title:record.course.name,year:String(term.year),season:term.season[0].toUpperCase()+term.season.slice(1),description:'',repository:record.repo,sections:[]})));
 const course=courses.find(c=>c.id===selected);
 useEffect(()=>{let active=true;setGraphInfo(null);if(!course?.repository){setGraphInfo(null);return;}void call({operation:'pipelineSettings',repo:course.repository}).then(value=>{if(active)setGraphInfo(value);}).catch(()=>{if(active)setGraphInfo(null);});return()=>{active=false;};},[course?.repository,call]);
 const calendar:TeachCalendarState={terms:Object.fromEntries(courses.map(c=>{const r=records.find(r=>r.repo===c.repository);return [c.id,r.settings[`${c.year}-${c.season.toLowerCase()}`]?.value.calendar??defaultTeachTermCalendar()];})),noClassDays:defaults?.value.noClassDays??[]};
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await action();await refresh();}catch(e){const messages:Record<string,string>={DRAFT_CONFLICT:'Save or resolve the existing Instructor, Student or template draft, then try again.',CONFLICT:'The saved files changed. Close this review and review the latest saved content.',TEACH_PAIR_AMBIGUOUS:'Several Student destinations exist for this course. Keep them intact and resolve the course pairing before continuing.',TEACH_STUDENT_PAGE_MISSING:'The Student home was removed. Restore student.md from Trash or create it again in the Student term folder.',TEACH_STUDENT_UNAVAILABLE:'The paired Student repository is unavailable. Restore it from Trash before continuing.',TEACH_PAIR_CONFLICT:'The paired repository identity changed. Existing files have been preserved.',STUDENT_SINGLE_DOCUMENT_REQUIRED:'Combine the legacy Instructor sections into one document before creating a Student page.'};setError(messages[(e as any).code]??(e as Error).message);}finally{pending.current=false;setBusy(false);}};
 const leaveReview=()=>{navigation.current++;setReviewChoice(false);setReviewing(false);setPublishing(false);setExporting(false);};
 const show=(next:typeof view)=>navigate(()=>{leaveReview();setView(next);});
 const openStudent=(repo:string,path:string,reload=false)=>navigate(()=>{setStudentRepo(repo);setDocumentPage('student');setView('document');onDocument(repo,path,reload);});
 const open=(id:string,page='home')=>{if(pending.current)return;const target=courses.find(c=>c.id===id);if(!target)return;const record=records.find(r=>r.repo===target.repository),term=record.course.terms.find((t:any)=>String(t.year)===target.year&&t.season===target.season.toLowerCase());navigate(()=>{leaveReview();const epoch=navigation.current;setSelected(id);setDocumentPage(page==='student'?'student':'home');setView(page==='settings'?'settings':page==='calendar'?'calendar':page==='student'?'student':'document');setStudentReview(null);setReviewing(false);setPublishing(false);setProposal(null);setPairOptions([]);
 if(page==='student')void run(async()=>{try{const pair=await call({operation:'ensureStudent',repo:target.repository});setFilesRevision(v=>v+1);if(epoch!==navigation.current)return;openStudent(pair.repo,`${target.year}-${target.season.toLowerCase()}/student.md`);}catch(e){if((e as any).code!=='TEACH_PAIR_AMBIGUOUS')throw e;const files=await call({operation:'courseFiles',repo:target.repository,year:Number(target.year),season:target.season.toLowerCase()});if(epoch!==navigation.current)return;setPairOptions(files.students.map((item:any)=>item.repo));}});
 else if(page==='settings'){}
 else if(page==='assistant')void run(async()=>{const settings=await pipelineCall({operation:'pipelineSettings',repo:target.repository});const role=settings.roles.find((r:any)=>r.role==='assistants');if(!role?.available)throw Error('Bind an Assistant repository in Course settings first.');const files:any=await nativeOperation(()=>getNativeBridge()!.request({repo:role.name,operation:'discover',args:{}}));if(epoch!==navigation.current)return;setDocumentPage('assistant');const folder=`${target.year}-${target.season.toLowerCase()}`;const candidate=[folder+'/instructor.md',folder+'/student.md','README.md'].find(p=>files.entries.some((e:any)=>e.path===p&&e.type==='file'));if(!candidate)throw Error('Add a Markdown page to the Assistant repository first.');onDocument(role.name,candidate);});
 else {setDocumentPage('home');onDocument(target.repository,term.source.paths[0]);}});};
 const create=(c:TeachStudyCourse)=>{void run(async()=>{const record=records.find(r=>r.course.code.toLowerCase()===c.code.toLowerCase());await call(record?{operation:'addTerm',repo:record.repo,expectedHash:record.hash,year:Number(c.year),season:c.season.toLowerCase()}:{operation:'create',requestId:crypto.randomUUID(),code:c.code,name:c.title,year:Number(c.year),season:c.season.toLowerCase()});setAddTerm(undefined);setView('courses');});};
 const saveDefaults=(value:any)=>{void run(async()=>{await call({operation:'setDefaults',expectedRevision:defaults.revision,value});});};
 const updateCalendar:React.Dispatch<React.SetStateAction<TeachCalendarState>>=update=>{const next=typeof update==='function'?update(calendar):update;void run(async()=>{for(const c of courses){if(JSON.stringify(next.terms[c.id])===JSON.stringify(calendar.terms[c.id]))continue;const r=records.find(r=>r.repo===c.repository),id=`${c.year}-${c.season.toLowerCase()}`;await call({operation:'setCalendar',repo:c.repository,year:Number(c.year),season:c.season.toLowerCase(),expectedHash:r.settings[id]?.hash??null,calendar:next.terms[c.id]});}if(JSON.stringify(next.noClassDays)!==JSON.stringify(calendar.noClassDays))await call({operation:'setDefaults',expectedRevision:defaults.revision,value:{...defaults.value,noClassDays:next.noClassDays}});});};
 const generateMultiPage=async()=>{
  if(!course||pending.current)throw Error('Wait for the calendar to finish saving.');
  pending.current=true;setBusy(true);setError('');
  try{const record=records.find(r=>r.repo===course.repository),id=`${course.year}-${course.season.toLowerCase()}`;
   const result=await call({operation:'generateClassPages',repo:course.repository,year:Number(course.year),season:course.season.toLowerCase(),expectedHash:record.settings[id]?.hash??null});
   await refresh();setFilesRevision(value=>value+1);return result.markdown as string;
  }catch(error){const messages:Record<string,string>={CLASS_PAGES_INCOMPLETE:'Some class pages are missing. Restore them, or remove all generated class pages before generating a new set.',CLASS_PAGES_SCHEDULE_CHANGED:'Class dates or times have changed. Keep the existing pages, or remove all generated class pages before generating a new set.',CLASS_PAGES_COLLISION:'A Class file already exists. Move it to another folder before generating.',CLASS_PAGES_RECORD_INVALID:'The class-page record could not be read. Your files have been preserved.',CLASS_PAGES_LIMIT:'Multi-page generation supports up to 255 scheduled classes.',TRASH_PATH_RESERVED:'Previous class files are still in Trash. Restore them, or permanently empty their Trash entries before generating a new set.'};throw Error(messages[(error as any).code]??(error as Error).message);}
  finally{pending.current=false;setBusy(false);}
 };
 const current=(code:string)=>{const c=selectCurrentTeachTerm(courses.filter(c=>c.code===code),calendar.terms);if(c)open(c.id);};
 const rail=enabled?<button type="button" className="fw-icon pws-rail-button" aria-label="asTeach" title="asTeach" aria-current={view?'page':undefined} onClick={()=>show('home')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="m2 8 10-5 10 5-10 5Z M6 10v6c4 3 8 3 12 0v-6M22 8v7"/></svg></button>:null;
 const content=view==='settings'&&course?<TeachPipelineSettings repo={course.repository} year={Number(course.year)} season={course.season.toLowerCase()} call={pipelineCall} onOpenRole={role=>open(course.id,role==='instructors'?'home':role==='assistants'?'assistant':'student')} onCreateAssistant={async()=>{await nativeOperation(()=>getNativeBridge()!.createRepository({name:course.code.replaceAll('/','_')+'_Assistants',requestId:crypto.randomUUID()}));setFilesRevision(v=>v+1);}}/>:(view==='home'||view==='courses')?<div className="pws-surface" style={{flexDirection:"column"}} aria-busy={busy}>{error&&<p role="alert">{error} <button onClick={()=>void run(async()=>{})}>Retry</button></p>}{!defaults?<p role="status">Loading courses…</p>:<fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0,minHeight:0,flex:1,display:"flex",flexDirection:"column"}}>
 {view==='home'&&<TeachHomeStudy nativeMode onAddExisting={()=>setAdopting(true)} office={defaults.value.office} onOfficeChange={office=>saveDefaults({...defaults.value,office})} courses={courses} recent={[]} teacherProfile={defaults.value.teacher??emptyTeacherProfile()} calendarState={calendar} onCalendarChange={updateCalendar} onSaveProfile={teacher=>saveDefaults({...defaults.value,teacher})} onOpenDocument={item=>open(item.courseId,item.sectionId)} onOpenTerm={id=>open(id,'calendar')} onCreate={create} onReturnToRepository={()=>show(null)}/>}
 {view==='courses'&&<TeachCoursesStudy nativeMode onAddExisting={()=>setAdopting(true)} courses={courses} calendarState={calendar} summaries={{}} teacherProfile={defaults.value.teacher} onOpen={id=>open(id)} onCourse={current} onAddTerm={code=>setAddTerm(code)} onCreate={create} onReturnToRepository={()=>show(null)}/>}
 {adopting&&<NativeTeachAdoptDialog onClose={()=>setAdopting(false)} onAdopt={async value=>{await call(value);await refresh();}}/>}
 {addTerm&&<NewCourseDialog nativeMode courses={courses} courseCode={addTerm} teacherProfile={defaults.value.teacher} onClose={()=>setAddTerm(undefined)} onCreate={create}/>}
 </fieldset>}</div>:null;
 const study:WorkspaceStudy|undefined=view?{active:view==='home'||view==='courses'||view==='settings',rail:null,content,headerContext:<TeachBreadcrumb onSettings={()=>{if(course)open(course.id,'settings');}} assistantAvailable={Boolean(graphInfo?.roles.find((r:any)=>r.role==='assistants')?.available)} studentAvailable studentView={documentPage==='student'} courses={courses} homeActive={view==='home'} activeCourse={view==='settings'||view==='calendar'||view==='student'||view==='document'?course:undefined} calendarState={calendar} summaries={course?{[course.id]:{sectionId:view==='settings'?'settings':view==='calendar'?'calendar':view==='student'?'student':documentPage,sectionTitle:view==='settings'?'Course settings':view==='calendar'?'Course calendar':documentPage==='assistant'?'Assistant page':view==='student'||documentPage==='student'?'Student page':documentPage==='template'?'Instructor template':'Instructor page',dirtyCount:0,readySectionIds:['home','calendar']}}:{}} onHome={()=>show('home')} onCourses={()=>show('courses')} onCourse={current} onAddTerm={code=>{show('courses');setAddTerm(code);}} onTerm={id=>open(id,documentPage==='student'?'student':documentPage==='assistant'?'assistant':'home')} onPage={page=>{if(course)open(course.id,page);}}/>,headerContextReplacesOwner:true,onExit:()=>show(null)}:undefined;
 const startReview=()=>{if(!course||!studentRepo)return;navigate(()=>{const epoch=navigation.current;void run(async()=>{const source=await call({operation:'studentReview',repo:course.repository,year:Number(course.year),season:course.season.toLowerCase()});const current:any=await nativeOperation(()=>getNativeBridge()!.request({repo:studentRepo,operation:'open',args:{path:`${course.year}-${course.season.toLowerCase()}/student.md`}}));if(current.draft)throw Error('Save or resolve the Student draft before reviewing.');if(epoch!==navigation.current)return;setStudentReview(source);setStudentText(current.text);setReviewChoice(true);});});};
 const dialogs=course?<>{error&&view==='document'&&<CourseDialog title="Course action needs attention" onClose={()=>setError('')}><p role="alert">{error}</p></CourseDialog>}{reviewChoice&&<CourseDialog title="Review Instructor changes" onClose={()=>setReviewChoice(false)}><p>Choose what to update in the Student repository. Saved Student edits are compared before applying changes.</p><div className="teach-publish-settings"><button className="pws-button" onClick={()=>{setReviewChoice(false);setReviewing(true);}}>Main page sections</button><button className="pws-button" onClick={()=>{setReviewChoice(false);setProposal({studentText,sourceHash:studentReview.instructor.sourceHash});setPublishing(true);}}>Course pages and assets</button></div></CourseDialog>}{reviewing&&studentReview&&<TeachStudentReviewDialog nativeMode error={error} source={studentReview.instructor.text} currentSource={studentReview.instructor.text} path={studentReview.sourcePath} hasDraft={false} reference={false} returnFocusRef={reviewButton} previous={{number:1,source:studentText,instructorSource:'',includedSectionIds:[]}} onCancel={()=>setReviewing(false)} onConfirm={edition=>{setProposal({studentText:edition.source,sourceHash:studentReview.instructor.sourceHash});setReviewing(false);setPublishing(true);}}/>}{publishing&&proposal&&<NativeTeachPublishDialog proposal={proposal} destinationRepo={studentRepo} repo={course.repository} year={Number(course.year)} season={course.season.toLowerCase()} onClose={()=>setPublishing(false)} onSaved={(repo,path)=>{setFilesRevision(v=>v+1);openStudent(repo,path,true);}}/>}{exporting&&<TeachStudentExport repo={studentRepo} onClose={()=>setExporting(false)}/>}</>:null;
 const studentActions=view==='document'&&documentPage==='student'&&studentRepo?{onReview:startReview,onExport:()=>navigate(()=>setExporting(true))}:undefined;
 const documentPanel=view==='student'&&course?<section className="native-teach-calendar" aria-label="Opening Student repository"><h1>{pairOptions.length?'Choose Student repository':'Opening Student repository'}</h1>{pairOptions.map(destination=><button className="pws-button" key={destination} disabled={busy} onClick={()=>void run(async()=>{const epoch=navigation.current;const pair=await call({operation:'ensureStudent',repo:course.repository,destination});if(epoch!==navigation.current)return;openStudent(pair.repo,`${course.year}-${course.season.toLowerCase()}/student.md`);})}>{destination}</button>)}{error?<><p role="alert">{error}</p><button className="pws-button" disabled={busy} onClick={()=>open(course.id,'student')}>Retry</button></>:!pairOptions.length&&<p role="status">Preparing the paired repository…</p>}</section>:view==='calendar'&&course?<fieldset className="native-teach-calendar" disabled={busy} aria-busy={busy}>{error&&<p role="alert">{error}</p>}<TeachCourseCalendarStudy nativeMode course={course} state={calendar} onChange={updateCalendar} onGenerateMultiPage={generateMultiPage}/></fieldset>:undefined;

 return {rail,study,dialogs,studentActions,documentPanel,filesRevision,dismissPanel:()=>{if(view==='calendar'||view==='student'){leaveReview();setView('document');}},close:()=>{leaveReview();setView(null);}};
}
