import React,{useLayoutEffect,useRef,useState} from 'react';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
import type {PackageReview,ExchangeStatus,ExchangeResult,PackageChoice} from '../../packages/desktop-host/src/package-exchange/index.mjs';
import './package-exchange.css';
export function PackageExchangeDialog({repo,onClose,onChanged}:{repo:string;onClose():void;onChanged():void}){
 const dialog=useRef<HTMLDialogElement>(null),[status,setStatus]=useState<ExchangeStatus|null>(null),[review,setReview]=useState<PackageReview|null>(null),[choices,setChoices]=useState<Record<string,PackageChoice>>({}),[file,setFile]=useState<File|null>(null),[collectionId,setCollection]=useState(repo),[version,setVersion]=useState('1'),[semantics,setSemantics]=useState<'snapshot'|'patch'>('patch'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const bridge=getNativeBridge()!;
 const execute=async<T,>(fn:()=>Promise<T>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{return await nativeOperation(fn);}catch(reason){setError((reason as Error).message);}finally{try{setStatus(await nativeOperation(()=>bridge.packageStatus({repo})));}catch(reason){setError((reason as Error).message);}setBusy(false);}};
 useLayoutEffect(()=>{dialog.current!.showModal();void execute(()=>bridge.packageStatus({repo})).then(value=>{if(value){setStatus(value);if(value.registration){setCollection(value.registration.collectionId);setVersion(value.registration.version);}}});return()=>dialog.current?.close();},[]);
 const receive=(value:PackageReview|undefined)=>{if(value){setReview(value);setChoices({});}};
 const archive=async()=>{if(!file)throw Error('Choose a ZIP file.');if(file.size>256*1024*1024)throw Error('Choose a ZIP smaller than 256 MiB.');return file.arrayBuffer();};
 const close=async()=>{if(busy)return;if(review)await execute(()=>bridge.cancelPackagePlan({repo,planId:review.planId}));onClose();};
 const apply=async()=>{const result=await execute<ExchangeStatus|ExchangeResult>(()=>review!.kind==='register'?bridge.registerPackageBase({repo,planId:review!.planId}):bridge.applyPackageUpdate({repo,planId:review!.planId,choices:Object.entries(choices).map(([path,choice])=>({path,choice}))}));if(result){setReview(null);setNotice(review!.kind==='register'?'Original package recorded.':'Package update saved.');onChanged();}};
 const actionable=review?.rows.filter(row=>row.choices?.length)??[];
 return <dialog className="package-dialog" ref={dialog} aria-labelledby="package-heading" onCancel={event=>{event.preventDefault();void close();}}><header><h2 id="package-heading">Packages · {repo}</h2><button aria-label="Close packages" disabled={busy} onClick={()=>void close()}>×</button></header>
 <p>Review updates to saved files, or export a portable copy. Your drafts and Git history stay separate.</p>
 {status?.recoveryRequired?<section><h3>Finish interrupted update</h3><p>{status.pending?.completed} of {status.pending?.total} files completed. Ordinary file changes are paused for this repository.</p><button disabled={busy||!status.pending} onClick={()=>void execute(()=>bridge.recoverPackageUpdate({repo,operationId:status.pending!.operationId,direction:'resume'})).then(value=>{if(value){setReview(null);setChoices({});onChanged();setNotice(value.status==='rolled-back'?'Update rolled back.':'Update completed.');}})}>Resume update</button> <button disabled={busy||!status.pending} onClick={()=>void execute(()=>bridge.recoverPackageUpdate({repo,operationId:status.pending!.operationId,direction:'rollback'})).then(value=>{if(value){setReview(null);setChoices({});onChanged();setNotice('Update rolled back.');}})}>Roll back</button></section>:!review?<>
 <section><h3>{status?.registration?'Update from package':'Record original package'}</h3><p>{status?.registration?`Recorded collection: ${status.registration.collectionId} · ${status.registration.version}`:'Choose the original ZIP whose files still match this repository. Only its listed files become package-owned.'}</p><label>Package ZIP<input type="file" accept=".zip,application/zip" disabled={busy} onChange={event=>setFile(event.target.files?.[0]??null)}/></label><div className="package-fields"><label>Collection ID<input value={collectionId} disabled={busy||Boolean(status?.registration)} onChange={event=>setCollection(event.target.value)}/></label><label>{status?.registration?'Incoming version':'Original version'}<input value={version} disabled={busy} onChange={event=>setVersion(event.target.value)}/></label>{status?.registration&&<label>Package contents<select value={semantics} disabled={busy} onChange={event=>setSemantics(event.target.value as typeof semantics)}><option value="patch">Patch — missing files stay</option><option value="snapshot">Full snapshot — review removals</option></select></label>}</div><button disabled={busy||!file} onClick={()=>void execute(async()=>status?.registration?bridge.reviewPackageUpdate({repo,bytes:await archive(),semantics,version}):bridge.reviewPackageBase({repo,bytes:await archive(),collectionId,version})).then(receive)}>Review package</button></section>
 <section><h3>Export saved files</h3><p>Source ZIP keeps portable files and assets. Offline reader includes a static reading copy; interactive code does not run.</p><button disabled={busy} onClick={()=>void execute(()=>bridge.reviewPackageExport({repo,collectionId,version})).then(receive)}>Review export</button></section>
 {status?.operations.some(value=>value.canRollback)&&<section><h3>Recent updates</h3>{status.operations.filter(value=>value.canRollback).map(value=><div key={value.operationId}>{value.version} · {value.paths.length} changed files <button disabled={busy} onClick={()=>void execute(()=>bridge.rollbackPackageUpdate({repo,operationId:value.operationId})).then(result=>{if(result){onChanged();setNotice('Update rolled back.');}})}>Roll back update</button></div>)}</section>}
 </>:<section><h3>{review.kind==='export'?'Review export':review.kind==='register'?'Review original package':'Review changes'}</h3><p>{review.collectionId} · {review.version}{review.semantics&&` · ${review.semantics}`} · Review expires in 10 minutes.</p>
 {review.drafts.length>0&&<p>Private drafts excluded and protected: {review.drafts.join(', ')}</p>}
 {review.warnings.map((warning,index)=><p key={index} className="package-warning">{warning.path?`${warning.path}: `:''}{warning.message}</p>)}
 <p className="package-limits">Up to {review.limits.changedFiles} changed files; changed file limit {review.limits.updateMemberBytes/1024/1024} MiB. Larger unchanged assets can be exported.</p>
 <div className="package-rows">{review.rows.map(row=><details key={row.path}><summary><strong>{row.path}</strong> · {row.action??'saved file'} {row.protectedDraft?'· protected draft':''}</summary>{row.currentHash&&<p>Current SHA-256: <code>{row.currentHash}</code></p>}{row.incomingHash&&<p>Incoming SHA-256: <code>{row.incomingHash}</code></p>}{row.current!==undefined&&<div className="package-diff"><div><h4>Original package</h4><pre>{row.base??'(absent)'}</pre></div><div><h4>Current</h4><pre>{row.current??'(absent)'}</pre></div><div><h4>Incoming</h4><pre>{row.incoming??'(absent)'}</pre></div></div>}{row.choices?.length&&<label>Resolution<select aria-label={`Resolution for ${row.path}`} disabled={busy} value={choices[row.path]??''} onChange={event=>setChoices(value=>({...value,[row.path]:event.target.value as PackageChoice}))}><option value="" disabled>Choose…</option>{row.choices.map(choice=><option key={choice} value={choice}>{({'keep-current':'Keep current','use-incoming':'Use incoming','keep-both':'Keep both'})[choice]}</option>)}</select></label>}</details>)}</div>
 <footer><button disabled={busy} onClick={()=>void execute(()=>bridge.cancelPackagePlan({repo,planId:review.planId})).then(()=>setReview(null))}>Back</button>{review.kind==='export'?<><button disabled={busy} onClick={()=>void execute(()=>bridge.savePackageExport({repo,planId:review.planId,kind:'source'})).then(value=>{if(value?.saved)setNotice(`Saved ${value.filename}`);})}>Save source ZIP…</button><button disabled={busy} onClick={()=>void execute(()=>bridge.savePackageExport({repo,planId:review.planId,kind:'offline'})).then(value=>{if(value?.saved)setNotice(`Saved ${value.filename}`);})}>Save offline reader…</button></>:<button disabled={busy||actionable.some(row=>!choices[row.path])} onClick={()=>void apply()}>{review.kind==='register'?'Record original package':'Apply reviewed changes'}</button>}</footer>
 </section>}
 {busy&&<p role="status">Working…</p>}{error&&<p role="alert" className="rfe-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </dialog>;
}
