import React,{useEffect,useMemo,useState} from 'react';
import {RepositoryFileEditor} from './RepositoryFileEditor';
import {NativePluginProvider,usePluginHost} from './NativePluginHost';
import {proEditorManifest} from './pro-editor/manifest';
import type {LocalWorkspaceClient,WorkspaceDocument} from './local-workspace-client';
import {parseCollectionMetadata,evidenceContext} from './reading-reference.mjs';
import type {ReadingEvidence} from './ReadingEvidenceContext';
import themes from './github-themes/themes.json';
import './focused-writing.css';
import './pro-editor/pro-editor.css';
const origin='# Current capability — synthetic example\n\n'+Array.from({length:18},(_,index)=>`## Background ${index+1}\n\nThis fictional paragraph makes the originating reading position visible.\n\n`).join('')+'## Rate status\n\nThe old demo measured **30 Hz**. The new **60 Hz target is not measured**.\n\n- [Measured old result](evidence/report-v1.md#result)\n- [New target, not measured](evidence/report-v2.md#result)\n- [Missing report](evidence/missing.md)\n\n$$E = mc^2$$\n\nEnd of current summary.\n';
function fixture(){
 const files=new Map([['current.md',origin],['evidence/report-v1.md','# Synthetic report v1\n\n## Result\n\nMeasured **30 Hz** under one fictional workload.\n\n[Current summary](../current.md#rate-status)\n'],['evidence/report-v2.md','# Synthetic report v2\n\n## Result\n\nTarget **60 Hz**, **not measured**.\n\n[Current summary](../current.md#rate-status)\n']]),drafts=new Map<string,string>();
 const hash=async(text:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),byte=>byte.toString(16).padStart(2,'0')).join('');
 const entries=[{path:'evidence',name:'evidence',type:'directory' as const},...Array.from(files.keys(),path=>({path,name:path.split('/').at(-1)!,type:'file' as const}))];
 const open=async(path:string):Promise<WorkspaceDocument>=>{const text=files.get(path);if(text===undefined)throw new Error('This sample file is unavailable.');const sourceHash=await hash(text);return{path,documentId:`reading-study:${path}`,sourceHash,text,readOnly:false,draft:drafts.has(path)?{text:drafts.get(path)!,baseHash:sourceHash}:null};};
 const workspace:LocalWorkspaceClient={bootstrap:async()=>({local:true,newDrafts:[]}),async request<T>(operation:string,args:Record<string,unknown>={}){let value:unknown;const path=String(args.path??'');if(operation==='open')value=await open(path);else if(operation==='discover')value={entries};else if(operation==='runtimeStatus')value={recoveryRequired:false};else if(operation==='checkpoint'){drafts.set(path,String(args.text));value={};}else if(operation==='save'){const previous=files.get(path);if(previous===undefined||await hash(previous)!==args.baseHash)throw new Error('This sample changed.');files.set(path,String(args.text));drafts.delete(path);value=await open(path);}else if(operation==='gitStatus')value={initialized:false,files:[]};else throw new Error('This action is unavailable in the reading study.');return value as T;}};
 const readSnapshot=async(path:string)=>{if(!path||path==='evidence')return{type:'directory' as const,content:null,entries:entries.filter(entry=>entry.path.split('/').slice(0,-1).join('/')===path)};const document=await open(path);return{type:'file' as const,content:document.text,entries:[]};};
 const metadata=parseCollectionMetadata(JSON.stringify({schemaVersion:1,collectionId:'reading-study',documents:[{id:'current',path:'current.md',evidence:{kind:'summary',validation:'Author declaration; no independent verification'}},{id:'demo.rate.v1',path:'evidence/report-v1.md',evidence:{kind:'synthetic measured result',observationDate:'2026-09-20',build:'demo-1',scope:'one demonstration workload'}},{id:'demo.rate.v2',path:'evidence/report-v2.md',evidence:{kind:'planned target',observationDate:'2026-09-22',build:'demo-2',validation:'not measured',supersedes:'demo.rate.v1'}}]}));
 return{workspace,readSnapshot,loadEvidenceContext:async({path}:{repo:string;path:string;ref:string})=>evidenceContext(metadata,path) as ReadingEvidence};
}
function Study(){const host=usePluginHost(),[data]=useState(fixture),[dark,setDark]=useState(false),[pro,setPro]=useState(true);const theme=themes.find(item=>item.id===(dark?'dark-default':'light-default'))!;const style=useMemo(()=>({...theme.variables,...Object.fromEntries(Object.entries(theme.variables).map(([key,value])=>[key.replace('--ws-','--fw-'),value])),colorScheme:theme.appearance}) as React.CSSProperties,[theme]);useEffect(()=>{void host?.registry.enable(proEditorManifest.id);},[host]);return <div className="fw-window pro-study" style={style}><header className="fw-titlebar"><strong>Reading navigation</strong><span className="fw-spacer"/><button onClick={()=>{const next=!pro;setPro(next);void(next?host?.registry.enable(proEditorManifest.id):host?.registry.disable(proEditorManifest.id));}}>{pro?'Disable Pro Editor':'Enable Pro Editor'}</button><button onClick={()=>setDark(value=>!value)}>{dark?'Light theme':'Dark theme'}</button></header><div className="pro-study-notice">In-memory study · Follow each evidence link, then use Back. Saved sample content is fictional.</div><div className="fw-body"><main className="fw-main"><div className="pro-study-document"><RepositoryFileEditor repository="Reading-Study" initialPath="current.md" initialSource={origin} revision="" branch="main" branches={['main']} tags={[]} {...data} onClose={()=>{}}/></div></main></div></div>;}
export function ReadingNavigationStudy(){return <NativePluginProvider><Study/></NativePluginProvider>;}
