import React,{useLayoutEffect,useRef,useState} from 'react';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
import {portableReference} from './reading-reference.mjs';
import type {PortableReadingReference,ResolvedReadingReference} from './native-types';
export function ReadingReferenceDialog({onOpen,onClose}:{onOpen(value:ResolvedReadingReference):Promise<void>;onClose():void}){
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLTextAreaElement>(null),live=useRef(true),sequence=useRef(0);
 const [text,setText]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<ResolvedReadingReference|null>(null),[error,setError]=useState('');
 const admitted=useRef<PortableReadingReference|null>(null);
 useLayoutEffect(()=>{const previous=document.activeElement;dialog.current?.showModal();input.current?.focus();return()=>{live.current=false;sequence.current++;dialog.current?.close();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};},[]);
 const resolve=async(repoId?:string)=>{const bridge=getNativeBridge();if(!bridge?.resolveReadingReference||busy)return;const own=++sequence.current;setBusy(true);setError('');try{if(!repoId){if(text.length>8192)throw new Error('This reference is too large.');admitted.current=portableReference(JSON.parse(text)) as PortableReadingReference;}if(!admitted.current)throw new Error('Paste a supported reading reference.');const value=await nativeOperation(()=>bridge.resolveReadingReference({reference:admitted.current!,...(repoId?{repoId}:{})}));if(!live.current||own!==sequence.current)return;setResult(value);if(value.status==='resolved'){await onOpen(value);if(live.current&&own===sequence.current)onClose();}}catch(reason){if(live.current&&own===sequence.current)setError((reason as Error).message);}finally{if(live.current&&own===sequence.current)setBusy(false);}};
 return <dialog ref={dialog} className="rfe-reference-dialog" aria-labelledby="reading-reference-title" onCancel={event=>{event.preventDefault();if(!busy)onClose();}}><h2 id="reading-reference-title">Open reading reference</h2><p>A portable reference identifies a saved document. It does not grant access to another repository or verify an author's claim.</p><form onSubmit={event=>{event.preventDefault();void resolve();}}><label htmlFor="reading-reference-input">Reference</label><textarea ref={input} id="reading-reference-input" value={text} disabled={busy} maxLength={8192} onChange={event=>{setText(event.target.value);setResult(null);admitted.current=null;setError('');}} spellCheck={false} rows={6}/>{result&&<p role="status">{result.message}</p>}{result?.status==='ambiguous'&&result.candidates?.map(candidate=><button type="button" key={candidate.repoId} disabled={busy} onClick={()=>void resolve(candidate.repoId)}>Use {candidate.repo}</button>)}{error&&<p role="alert" className="rfe-error">{error}</p>}<footer><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button disabled={busy||!text.trim()}>{busy?'Resolving…':'Open reference'}</button></footer></form></dialog>;
}
