import {readRepository} from './native-bridge.mjs';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { renderSourcePreview } from '../../apps/desktop/ui/markdown-preview.mjs';
import './repository-code-page.css';
import { RevisionPicker } from './RevisionPicker';
import { RevisionListing } from './RevisionListing';
import { RepositoryDocument, isRepositoryMedia } from './RepositoryDocument';
import { RepositoryFileEditor } from './RepositoryFileEditor';
import type {ReadingHistoryAdapter, ReadingHistoryTicket} from './reading-navigation.mjs';
import type {ReadingEvidence} from './ReadingEvidenceContext';
import type {ResolvedReadingReference} from './native-types';
import {buildDocumentOutline} from './outline-model';
import type {NavigationRequest,OutlineState,SearchRequest} from './workspace-navigation';
type Entry={name:string;path:string;type:'file'|'directory';message?:string;date?:string};
type Snapshot={type:'file'|'directory';readmePath:string|null;licensePath:string|null;name:string;branch:string;branches:string[];tags:string[];commitCount:number;commit:{author:string;message:string;sha:string;date:string}|null;entries:Entry[];readme:string|null;license:string|null;content:string|null;contributors:string[];languages:{name:string;percent:number}[]};
const paths:Record<string,string>={file:'M5 2h9l5 5v15H5ZM14 2v6h5M8 12h8M8 16h8',folder:'M2 5h8l2 3h10v13H2Z',branch:'M6 6v12m0-9c12 0 12 0 12-5M8 4a2 2 0 1 1-4 0 2 2 0 0 1 4 0M8 20a2 2 0 1 1-4 0 2 2 0 0 1 4 0M20 3a2 2 0 1 1-4 0 2 2 0 0 1 4 0',tag:'M3 3h8l10 10-8 8L3 11ZM7 7h.1',book:'M12 5c-3-2-6-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-4-1-7-1-10 1Zm0 0v15',star:'m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z',eye:'M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12Zm14 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0',history:'M3 5v6h6M3 11a9 9 0 1 1 2 7M12 6v6l4 2',search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0m-2 4 7 7',code:'m8 5-7 7 7 7m8-14 7 7-7 7',people:'M15 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0M5 22v-4a7 7 0 0 1 14 0v4',gear:'M12 3v4m0 10v4M3 12h4m10 0h4M6 6l3 3m6 6 3 3M6 18l3-3m6-6 3-3M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',scale:'M12 2v19M6 22h12M3 7h18M5 7l-4 8h8Zm14 0-4 8h8Z'};
function Icon({name}:{name:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>}
function Unavailable({children,icon}:{children:React.ReactNode;icon?:string}){return <button disabled data-unavailable title="Not implemented yet" className="rc-button">{icon&&<Icon name={icon}/ >}{children}</button>}
type RepositoryLocation={path:string;directory:boolean};
type RepositoryCodePageProps={referenceReturn?:ResolvedReadingReference;repositoryIdentity?:string;readingHistory?:ReadingHistoryAdapter;historyReturn?:ReadingHistoryTicket;onHistoryNavigate?(ticket:ReadingHistoryTicket):Promise<void>;loadEvidenceContext?(value:{repo:string;path:string;ref:string}):Promise<ReadingEvidence>;onResolvedReference?(value:ResolvedReadingReference):Promise<void>;readOnly?:boolean;navigationRequest?:NavigationRequest|null;onNavigationHandled?(id:number):void;onOutlineChange?(outline:OutlineState|null):void;onDocumentContextChange?(value:{repo:string;path:string;ref:string}):void;onSearch?(value:SearchRequest):void;repository:string;initialEdit?:boolean;initialCreate?:boolean;initialFile?:string;initialDirectory?:string;panelResizePreview?:boolean;centeredOverview?:boolean;fileSidebarOpen?:boolean;onFileSidebarOpenChange?:(open:boolean)=>void;onFileViewChange?:(active:boolean)=>void;onRenameRepository?:(name:string,location:RepositoryLocation)=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void;registerBeforeLeave?:(fn:(reason?:'close')=>Promise<void>)=>void};
export function RepositoryCodePage({referenceReturn,repositoryIdentity,readingHistory,historyReturn,onHistoryNavigate,loadEvidenceContext,onResolvedReference,readOnly=false,navigationRequest,onNavigationHandled,onOutlineChange,onDocumentContextChange,onSearch,repository,initialEdit=false,initialCreate=false,initialFile,initialDirectory,fileSidebarOpen,onFileSidebarOpenChange,onFileViewChange,onRenameRepository,onDirtyChange,registerBeforeLeave}:RepositoryCodePageProps){
 const [editing,setEditing]=useState(initialEdit);
 const [creating,setCreating]=useState(initialCreate&&!readOnly),[refresh,setRefresh]=useState(0);
 const [fragment,setFragment]=useState(historyReturn?.location.fragment??'');
 const [revision,setRevision]=useState(historyReturn?.location.ref??referenceReturn?.revision??'');
 const [listing,setListing]=useState<'branches'|'tags'|null>(null);
 const [path,setPath]=useState(historyReturn?.location.path??referenceReturn?.path??initialFile??initialDirectory??''),[directoryView,setDirectoryView]=useState(historyReturn?historyReturn.location.type==='directory':initialDirectory!==undefined),[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[documentTab,setDocumentTab]=useState<'readme'|'license'>('readme');
 const revisionRequest=useRef<AbortController|null>(null),preloadedRoute=useRef<string|null>(null);
 useEffect(()=>()=>{revisionRequest.current?.abort();preloadedRoute.current=null;},[repository]);
 useEffect(()=>{const route=JSON.stringify([repository,path,revision]);if(preloadedRoute.current===route){preloadedRoute.current=null;return;}revisionRequest.current?.abort();const controller=new AbortController();setData(null);setError('');readRepository({repo:repository,path,ref:revision},controller.signal).then(snapshot=>{if(!controller.signal.aborted)setData(snapshot);}).catch(reason=>{if(!controller.signal.aborted)setError(reason.message);});return ()=>controller.abort();},[repository,path,revision,refresh]);
 const changeFileRevision=async(ref:string,filePath:string)=>{
  if(ref===revision)return;
  revisionRequest.current?.abort();const controller=new AbortController();revisionRequest.current=controller;
  const label=ref.replace(/^refs\/(heads|tags)\//,'')||data?.branch||'the current branch';
  try{
   const snapshot:Snapshot=await readRepository({repo:repository,path:filePath,ref},controller.signal);
   if(controller.signal.aborted)return;
   if(snapshot.type==='file'&&typeof snapshot.content!=='string'&&!isRepositoryMedia(filePath))throw new Error(`${filePath} cannot be displayed as a text file on ${label}. Your current file is still open.`);
   preloadedRoute.current=JSON.stringify([repository,filePath,ref]);
   setRevision(ref);setPath(filePath);setData(snapshot);setError('');setQuery('');setEditing(snapshot.type==='file');setDirectoryView(snapshot.type==='directory');setListing(null);
  }finally{if(revisionRequest.current===controller)revisionRequest.current=null;}
 };
 const licenseLabel=data?.license?.trimStart().startsWith('MIT License')?'MIT license':'License';
 const source=data?.content??(documentTab==='license'?data?.license:data?.readme)??'';
 const sourcePath=data?.type==='file'?path:(documentTab==='license'?data?.licensePath:data?.readmePath)||'README.md';
 const rendered=useMemo(()=>renderSourcePreview(source,sourcePath,{externalLinks:true,technical:true}),[source,sourcePath]);
 const navigate=(next:string,hash='')=>{setFragment(hash);setPath(next);setQuery('');setDocumentTab('readme');};
 const isFile=data?.type==='file';
 const isDirectoryView=data?.type==='directory'&&(Boolean(path)||directoryView)&&!creating&&!editing;
 const sourceAvailable=(isFile&&isRepositoryMedia(path))||typeof (isFile?data?.content:documentTab==='license'?data?.license:data?.readme)==='string';
 const fileView=Boolean((creating||editing||isFile||isDirectoryView)&&data&&(creating||isDirectoryView||sourceAvailable));
 useEffect(()=>{onFileViewChange?.(fileView);return()=>onFileViewChange?.(false);},[fileView,onFileViewChange]);
 const overviewOutline=useMemo(()=>!fileView&&!listing&&sourceAvailable&&/\.(md|markdown)$/i.test(sourcePath)?buildDocumentOutline(source):[],[fileView,listing,sourceAvailable,sourcePath,source]);
 useEffect(()=>{if(fileView)return;onDocumentContextChange?.({repo:repository,path:sourcePath,ref:revision});onOutlineChange?.({documentName:sourcePath,entries:overviewOutline,onSelect:entry=>{const target=document.querySelector<HTMLElement>(`.rc-document [id="${entry.id}"]`);if(target){target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView({block:'start'});}else if(rendered.limited){setEditing(true);setFragment(entry.id);}}});},[fileView,sourcePath,repository,revision,overviewOutline,onOutlineChange,onDocumentContextChange,rendered.limited]);
 const appliedNavigation=useRef(0);
 useEffect(()=>{const target=navigationRequest;if(!target||target.repo!==repository||target.id===appliedNavigation.current)return;
  if((target.ref??'')!==revision){appliedNavigation.current=target.id;setRevision(target.ref??'');setData(null);setPath(target.path);setDirectoryView(target.type==='directory');setEditing(target.type!=='directory');setCreating(false);setListing(null);return;}
  if(fileView){appliedNavigation.current=target.id;return;}
  appliedNavigation.current=target.id;setData(null);setPath(target.path);setDirectoryView(target.type==='directory');setEditing(target.type!=='directory');setCreating(false);setListing(null);
 },[navigationRequest,repository,revision,fileView]);

 if(fileView&&data)return <RepositoryFileEditor referenceReturn={referenceReturn} repositoryIdentity={repositoryIdentity} readingHistory={readingHistory} historyReturn={historyReturn} onHistoryNavigate={onHistoryNavigate} loadEvidenceContext={loadEvidenceContext} onResolvedReference={onResolvedReference} readOnly={readOnly} key={`${repository}:${revision}:${creating?'new':'file'}`} repository={repository} navigationRequest={navigationRequest} onNavigationHandled={onNavigationHandled} onOutlineChange={onOutlineChange} onDocumentContextChange={onDocumentContextChange} onSearch={onSearch} fileSidebarOpen={fileSidebarOpen} onFileSidebarOpenChange={onFileSidebarOpenChange} onRenameRepository={onRenameRepository} initialCreate={creating} initialDirectory={isDirectoryView?path:undefined} initialPath={creating?(path?`${path}/untitled.md`:'untitled.md'):sourcePath} initialFragment={fragment} initialSource={creating?'':source} commit={data.commit} revision={revision} branch={data.branch} branches={data.branches} tags={data.tags} onRevisionChange={changeFileRevision} onDirtyChange={onDirtyChange} registerBeforeLeave={registerBeforeLeave} onClose={()=>{setEditing(false);setCreating(false);setDirectoryView(false);setRefresh(value=>value+1);navigate('');}}/>;
 if(listing&&data)return <div className="rc-scroll rc-centered-overview"><RevisionListing kind={listing} repository={repository} branch={data.branch} branches={data.branches} tags={data.tags} onBack={()=>setListing(null)} onSelect={ref=>{setRevision(ref===`refs/heads/${data.branch}`?'':ref);navigate('');setListing(null);}}/></div>;
 return <div className="rc-scroll rc-centered-overview"><div className="rc-page">
 <header className="rc-identity" aria-label="Repository identity and social actions"><div><span className="rc-avatar">as</span><h1>{repository}</h1><span className="rc-badge">{readOnly?'Documentation':repository==='asTeach-App'?'Public':'Private'}</span></div><div className="rc-social"><Unavailable icon="tag">Pin</Unavailable><Unavailable icon="eye">Watch <span>—</span>⌄</Unavailable><Unavailable icon="branch">Fork <span>—</span>⌄</Unavailable><Unavailable icon="star">Star <span>—</span>⌄</Unavailable></div></header>
 {error?<div role="alert"><p>{error}</p><button onClick={()=>navigate('')}>Back to repository</button></div>:!data?<p role="status">Loading {repository}…</p>:<div className="rc-columns"><section className="rc-primary" aria-label="Repository code">
 <div className="rc-toolbar"><RevisionPicker branch={data.branch} branches={data.branches} tags={data.tags} value={revision} onList={setListing} onChange={ref=>{setRevision(ref);navigate('');}}/><div className="rc-file-actions"><button className="rc-button rc-search" disabled={!onSearch} aria-label="Go to file" onClick={()=>onSearch?.({mode:'files',repo:repository,ref:revision,finder:true})}><Icon name="search"/>Go to file <kbd>T</kbd></button><button className="rc-button" disabled={readOnly||Boolean(revision)} title={readOnly?'Bundled documentation is read only':revision?"Open the working branch to create files":"Create a new Markdown file"} onClick={()=>setCreating(true)}>Add file +</button><Unavailable icon="code">Code ⌄</Unavailable></div></div>
 {path&&<nav className="rc-breadcrumb" aria-label="Repository file path"><button onClick={()=>navigate('')}>{repository}</button>{path.split('/').map((part,index)=><React.Fragment key={index}><span>/</span><button onClick={()=>navigate(path.split('/').slice(0,index+1).join('/'))}>{part}</button></React.Fragment>)}</nav>}
 <div className="rc-filebox"><div className="rc-commit" aria-label="Current revision summary"><span className="rc-avatar">{data.commit?.author.slice(0,1)||'as'}</span><strong>{data.commit?.author||repository}</strong><span className="rc-message">{data.commit?.message||'No commits yet'}</span><small>{data.commit?.sha.slice(0,7)} {data.commit?.date?.slice(0,10)}</small><Unavailable icon="history">{data.commitCount} Commits</Unavailable></div>
 {isFile?<div className="rc-source-label"><Icon name="file"/>{path}{data.content===null&&<span className="rc-muted">Preview unavailable for this file</span>}<button className="rc-button" disabled={readOnly||data.content===null} onClick={()=>setEditing(true)}>Edit file</button></div>:<div role="table" aria-label="Directory contents">{path&&<div className="rc-row"><button onClick={()=>navigate(path.split('/').slice(0,-1).join('/'))}>..</button></div>}{data.entries.filter(item=>item.name.toLowerCase().includes(query.toLowerCase())).map(item=><div className="rc-row" role="row" key={item.path}><div role="cell"><button onClick={()=>navigate(item.path)}><Icon name={item.type==='directory'?'folder':'file'}/>{item.name}</button></div><span role="cell" className="rc-message">{item.message||'—'}</span><small role="cell">{item.date?.slice(0,10)||'—'}</small></div>)}{!data.entries.some(item=>item.name.toLowerCase().includes(query.toLowerCase()))&&<p className="rc-empty">{query?'No matching files':'This repository is empty.'}</p>}</div>}</div>
 {(isFile&&data.content!==null||source||data.readme||data.license)&&<section className="rc-document" aria-label="Repository document"><nav aria-label="Repository documents">{isFile?<strong>{path.split('/').at(-1)}</strong>:<><button aria-pressed={documentTab==='readme'} disabled={!data.readme} onClick={()=>setDocumentTab('readme')}><Icon name="book"/>README</button><button aria-pressed={documentTab==='license'} disabled={!data.license} onClick={()=>setDocumentTab('license')}><Icon name="scale"/>{licenseLabel}</button></>}<button className="rc-button rc-edit" disabled={readOnly} aria-label={`Edit ${sourcePath}`} title={`Edit ${sourcePath}`} onClick={()=>setEditing(true)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m15 4 5 5M3 21l5-1L21 7a2 2 0 0 0-5-5L3 16Z"/></svg></button></nav>{rendered.limited?<p className="rc-empty">This file is too large for the rendered preview.</p>:(!isFile&&documentTab==='license'&&!/\.(md|markdown)$/i.test(sourcePath))||isFile&&!/\.(md|markdown)$/i.test(path)?<pre className="rc-plain-document">{source}</pre>:<RepositoryDocument repository={repository} revision={revision} sourcePath={sourcePath} rendered={rendered} fragment={fragment} onNavigate={navigate}/>}</section>}
 </section></div>}
 </div></div>;
}
