import React,{useId,useLayoutEffect,useRef,useState} from 'react';
import './revision-picker.css';
type Props={branch:string;branches:string[];tags:string[];value:string;onChange:(ref:string)=>void;onList:(kind:'branches'|'tags')=>void;compact?:boolean;disabled?:boolean};
export function RevisionPicker({branch,branches,tags,value,onChange,onList,compact=false,disabled=false}:Props){
 const [open,setOpen]=useState(false),[tab,setTab]=useState<'branches'|'tags'>('branches'),[query,setQuery]=useState('');
 const id=useId();
 const trigger=useRef<HTMLButtonElement>(null);
 const [position,setPosition]=useState({left:0,top:0,width:320,maxHeight:400});
 const selected=value||`refs/heads/${branch}`;
 const name=value?value.replace(/^refs\/(heads|tags)\//,''):branch;
 const kind=selected.startsWith('refs/tags/')?'tags':'branches';
 const show=(next:'branches'|'tags')=>{setTab(next);setQuery('');setOpen(true);};
 const close=()=>{setOpen(false);trigger.current?.focus();};
 useLayoutEffect(()=>{if(!open)return;const place=()=>{const box=trigger.current!.getBoundingClientRect(),frame=trigger.current!.closest('.fw-window')!.getBoundingClientRect();const left=Math.max(8,frame.left+8),right=Math.min(window.innerWidth-8,frame.right-8),width=Math.min(320,right-left);setPosition({left:Math.max(left,Math.min(box.left,right-width)),top:box.bottom+4,width,maxHeight:Math.max(0,Math.min(window.innerHeight,frame.bottom)-box.bottom-12)});};place();window.addEventListener('resize',place);window.addEventListener('scroll',place,true);const observer=new ResizeObserver(place);observer.observe(trigger.current!.closest('.fw-window')!);return ()=>{observer.disconnect();window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};},[open]);
 const items=(tab==='branches'?branches:tags).filter(item=>item.toLowerCase().includes(query.toLowerCase()));
 const icon=(tag:boolean)=><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{tag?<path d="M3 3h8l10 10-8 8L3 11ZM7 7h.1"/>:<path d="M6 6v12m0-9c12 0 12 0 12-5M8 4a2 2 0 1 1-4 0 2 2 0 0 1 4 0M8 20a2 2 0 1 1-4 0 2 2 0 0 1 4 0M20 3a2 2 0 1 1-4 0 2 2 0 0 1 4 0"/>}</svg>;
 return <div className={`rp-controls${compact?' rp-compact':''}`} onKeyDown={event=>{if(event.key==='Escape'&&open){event.stopPropagation();close();}}}>
 <button ref={trigger} className="rp-trigger" disabled={disabled} aria-label={`Switch branches/tags: ${name}`} aria-expanded={open} aria-controls={open?`${id}-popup`:undefined} onClick={()=>open?close():show(kind)}>{icon((open?tab:kind)==='tags')}<span>{name}</span><svg className="rp-chevron" viewBox="0 0 16 16" aria-hidden="true"><path d="m4 6 4 4 4-4Z" fill="currentColor"/></svg></button>
 {!compact&&<><button className="rp-count" disabled={disabled} onClick={()=>onList('branches')}>{icon(false)}<strong>{branches.length}</strong> {branches.length===1?'Branch':'Branches'}</button><button className="rp-count" disabled={disabled} onClick={()=>onList('tags')}>{icon(true)}<strong>{tags.length}</strong> {tags.length===1?'Tag':'Tags'}</button></>}
 {open&&<><button className="rp-backdrop" aria-label="Dismiss branch and tag picker" tabIndex={-1} onClick={close}/><section id={`${id}-popup`} className="rp-popup" style={position} aria-label="Switch branches/tags"><header><strong>Switch branches/tags</strong><button aria-label="Close branch and tag picker" onClick={close}>×</button></header><div className="rp-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></svg><input autoFocus aria-label={tab==='branches'?'Find a branch':'Find a tag'} type="search" placeholder={tab==='branches'?'Find a branch…':'Search tags…'} value={query} onChange={event=>setQuery(event.target.value)}/></div><div className="rp-tabs" role="tablist" aria-label="Ref type" onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?'branches':event.key==='End'?'tags':tab==='branches'?'tags':'branches';setTab(next);setQuery('');(event.currentTarget.querySelectorAll('button')[next==='branches'?0:1] as HTMLButtonElement).focus();}}}><button role="tab" id={`${id}-branches-tab`} aria-controls={`${id}-options`} tabIndex={tab==='branches'?0:-1} aria-selected={tab==='branches'} onClick={()=>{setTab('branches');setQuery('');}}>Branches</button><button role="tab" id={`${id}-tags-tab`} aria-controls={`${id}-options`} tabIndex={tab==='tags'?0:-1} aria-selected={tab==='tags'} onClick={()=>{setTab('tags');setQuery('');}}>Tags</button></div><div className="rp-list" id={`${id}-options`} role="tabpanel" aria-labelledby={`${id}-${tab}-tab`}>{items.map(item=>{const ref=`refs/${tab==='branches'?'heads':'tags'}/${item}`;return <button key={ref} aria-current={selected===ref?'true':undefined} onClick={()=>{onChange(ref===`refs/heads/${branch}`?'':ref);close();}}><span className="rp-check">{selected===ref?'✓':''}</span><span>{item}</span>{tab==='branches'&&item===branch&&<small>default</small>}</button>;})}{!items.length&&<p>{query?'No matching '+tab:'No local '+tab}</p>}</div><footer><button onClick={()=>{setOpen(false);onList(tab);}}>View all {tab}</button></footer></section></>}
 </div>;
}
