import React,{useEffect,useState,useRef} from 'react';
import {staffAccessMessages} from './TeachStaffSettings';
import {CourseDialog} from './TeachCoursesStudy';
import {TeachProjectSettings} from './TeachProjectSettings';
import type {PipelineCall} from './TeachPipelineSettings';
import {reviewPeopleImport,assignCoursePeople,personAccess,validCoursePeople} from '../../packages/asteach-plugin/course-people.mjs';
export function TeachPeopleSettings({repo,year,season,settings,call,refresh}:{repo:string;year:number;season:string;settings:any;call:PipelineCall;refresh:()=>Promise<void>}){
 const [person,setPerson]=useState<any>(null),[editing,setEditing]=useState<number|null>(null);
 const pending=useRef(false);
 const roster=settings.staff?.roster??{entries:[],revision:0};
 const [selected,setSelected]=useState<number[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[text,setText]=useState(''),[projects,setProjects]=useState<any[]>([]),[target,setTarget]=useState('students'),[permission,setPermission]=useState('read'),[courseRole,setCourseRole]=useState('student'),[review,setReview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ack,setAck]=useState(false),[batchResults,setBatchResults]=useState<any[]>([]);
 const loadProjects=async()=>{const p=await call({operation:'projectSettings',repo});setProjects(p.projects??[]);};
 useEffect(()=>{if(settings.migrated)void loadProjects().catch(e=>setError(e.message));},[repo,settings.revision,roster.revision]);
 useEffect(()=>{setSelected([]);},[repo]);
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await action();await refresh();await loadProjects();}catch(e){if(review?.kind==='github'){setReview(null);setAck(false);}setError(staffAccessMessages[(e as any).code]??staffAccessMessages[(e as Error).message]??((e as Error).message==='GITHUB_ASSIGNMENT_REQUIRED'?'Save the selected repository assignments before reviewing GitHub access.':(e as Error).message));try{await refresh();await loadProjects();}catch{}}finally{pending.current=false;setBusy(false);}};
 useEffect(()=>()=>{if(review?.kind==='github')void call({operation:'cancelPeopleAccessBatch',planId:review.planId}).catch(()=>{});},[call,review?.planId]);
 const entries=roster.entries;
 const visible=entries.map((entry:any,index:number)=>({entry,index})).filter(({entry}:any)=>(filter==='all'||entry.role===filter||projects.some(p=>'team:'+p.id===filter&&p.policy?.members?.some((m:string)=>m.toLowerCase()===entry.login.toLowerCase())))&&[entry.firstName,entry.lastName,entry.email,entry.login].join(' ').toLowerCase().includes(query.toLowerCase()));
 const close=()=>{if(busy)return;if(review?.kind==='github')void call({operation:'cancelPeopleAccessBatch',planId:review.planId}).catch(()=>{});setReview(null);setAck(false);};
 const prepare=(action:()=>any)=>{try{setError('');const next=action();if(next.entries&&!next.changes)next.changes=next.entries.map((after:any,index:number)=>({row:index+1,after,action:entries[index]?'update':'add'})).filter((c:any)=>JSON.stringify(c.after)!==JSON.stringify(entries[c.row-1]));if(next.kind==='team')next.people=selected.map(i=>entries[i].login);setReview({...next,rosterRevision:roster.revision});setAck(false);}catch(e){setError((e as Error).message);}};
 const role=settings.roles.find((r:any)=>r.role===target),team=projects.find(p=>'project:'+p.id===target);
 const save=async(next:any[],revision:number)=>{await call({operation:'saveCourseStaff',repo,revision,entries:next});setNotice('People and assignments saved locally. GitHub access unchanged.');};
 return <section><h2 tabIndex={-1}>People</h2><p>Manage instructors, assistants, students and teams together. Contacts remain private and local. Assignments describe intended access; dated GitHub observations show actual listed access.</p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy||!settings.migrated}>
 <button className="pws-button" onClick={()=>{setEditing(null);setPerson({firstName:'',lastName:'',email:'',login:'',role:'student'});}}>Add person</button>
 {person&&<div className="teach-directory-form">{[['firstName','First name'],['lastName','Last name'],['email','Email'],['login','GitHub username']].map(([key,label])=><label key={key}>{label}<input value={person[key]??''} onChange={e=>setPerson({...person,[key]:e.target.value})}/></label>)}<label>Course role<select value={person.role} onChange={e=>setPerson({...person,role:e.target.value,assignments:e.target.value==='student'?person.assignments?.filter((a:any)=>a.role==='students'&&a.permission==='read'):person.assignments})}><option value="instructor">Instructor</option><option value="assistant">Assistant</option><option value="student">Student</option></select></label><button className="pws-button" onClick={()=>prepare(()=>{const next=editing===null?[...entries,person]:entries.map((e:any,i:number)=>i===editing?person:e);if(!validCoursePeople(next))throw Error('Check contact details, unique GitHub usernames and directory limits.');return {kind:'local',entries:next,description:'Save this person in the private local directory.'};})}>Review person</button><button className="pws-button" onClick={()=>setPerson(null)}>Cancel editing</button></div>}
 <details><summary>Import or update people</summary><p>CSV or TSV: first_name,last_name,email,github,role. Match by email or GitHub account. Blank cells preserve existing values; ambiguous matches stop the import.</p><input aria-label="Import people file" type="file" accept=".csv,.tsv,.txt" onChange={e=>void run(async()=>{const f=e.target.files?.[0];if(!f)return;if(f.size>524288)throw Error('Maximum import size: 512 KiB.');setText(new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer()));})}/><label className="teach-directory-search">Paste CSV or TSV<textarea aria-label="Paste CSV or TSV" rows={6} value={text} onChange={e=>setText(e.target.value)}/></label><button className="pws-button" disabled={!text.trim()} onClick={()=>prepare(()=>({...reviewPeopleImport(entries,text),kind:'import'}))}>Review import</button></details>
 <div className="teach-pipeline-actions"><label>People filter<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Everyone</option><option value="instructor">Instructors</option><option value="assistant">Assistants</option><option value="student">Students</option>{projects.map(p=><option key={p.id} value={'team:'+p.id}>{p.label||p.name} · {p.term}</option>)}</select></label><label>Search people<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="pws-button" onClick={()=>setSelected(visible.map((v:any)=>v.index))}>Select filtered people</button><button className="pws-button" onClick={()=>setSelected([])}>Clear selection</button><span>{selected.length} selected</span></div>
 <h3>Assign selected people</h3><div className="teach-pipeline-actions"><label>Course role<select value={courseRole} onChange={e=>setCourseRole(e.target.value)}><option value="instructor">Instructor</option><option value="assistant">Assistant</option><option value="student">Student</option></select></label><button className="pws-button" disabled={!selected.length} onClick={()=>prepare(()=>({kind:'local',entries:assignCoursePeople(entries,selected,{courseRole}),description:`Set ${selected.length} people to ${courseRole}.`}))}>Review role assignment</button></div>
 <div className="teach-pipeline-actions"><label>Repository<select value={target} onChange={e=>{setTarget(e.target.value);setPermission(e.target.value.startsWith('project:')?'write':'read');}}>{settings.roles.filter((r:any)=>r.available).map((r:any)=><option key={r.role} value={r.role}>{r.name}</option>)}{projects.map(p=><option key={p.id} value={'project:'+p.id}>{p.label||p.name}</option>)}</select></label><label>Permission<select value={permission} onChange={e=>setPermission(e.target.value)}><option value="read" disabled={Boolean(team)}>Read</option><option value="write">Write</option></select></label><button className="pws-button" disabled={!selected.length} onClick={()=>prepare(()=>{if(team){const logins=selected.map(i=>entries[i].login);if(logins.some(v=>!v))throw Error('Team membership requires a GitHub username.');const members=[...new Set([...team.policy.members,...logins])];if(members.length>32)throw Error('Maximum 32 members per team.');return {kind:'team',team,policy:{...team.policy,members},description:`Add ${logins.join(', ')} to ${team.label||team.name}. Existing members are retained.`};}return {kind:'local',entries:assignCoursePeople(entries,selected,{role:target,permission,repositoryId:role.repositoryId}),description:`Assign ${selected.length} people ${permission} on ${role.name}.`};})}>Review repository assignment</button><button className="pws-button" disabled={!selected.length} onClick={()=>void run(async()=>{const p=await call({operation:'reviewPeopleAccessBatch',repo,target,permission,logins:selected.map(i=>entries[i].login)});setReview({...p,kind:'github'});setAck(false);})}>Review GitHub batch</button><button className="pws-button" onClick={()=>void run(async()=>{await call(team?{operation:'verifyProjectGitHub',repo,projectId:team.id}:{operation:'verifyGitHubAccess',repo,role:target});})}>Recheck repository access</button></div><p>Removing or changing local assignments never revokes existing GitHub permissions. Organization owners and inherited team access may also apply.</p>
 <div className="teach-pipeline-table"><table><thead><tr><th>Select</th><th>Name</th><th>Email</th><th>GitHub</th><th>Course role</th><th>Teams</th><th>Repositories and access</th><th>Actions</th></tr></thead><tbody>{visible.map(({entry:e,index}:any)=><tr key={index}><td><input type="checkbox" aria-label={`Select ${e.login||e.email||e.firstName}`} checked={selected.includes(index)} onChange={event=>setSelected(prior=>event.target.checked?[...prior,index]:prior.filter(i=>i!==index))}/></td><td>{[e.firstName,e.lastName].filter(Boolean).join(' ')||'—'}</td><td>{e.email||'—'}</td><td>{e.login||'Not set'}</td><td>{e.role}</td><td>{projects.filter(p=>p.policy?.members?.some((m:string)=>m.toLowerCase()===e.login.toLowerCase())).map(p=>p.label||p.name).join(', ')||'—'}</td><td>{settings.roles.filter((r:any)=>r.available).map((r:any)=>{const a=e.assignments?.find((a:any)=>a.role===r.role),remote=settings.github?.roles?.[r.role]?.remote;return <div key={r.role}><strong>{r.name}</strong>: {a?(a.repositoryId===r.repositoryId?`Assigned ${a.permission}`:'Assignment needs rebinding'):'Not assigned'} · {personAccess(remote,e.login)}{remote?.verifiedAt&&<small> · checked {new Date(remote.verifiedAt).toLocaleString()}</small>}</div>;})}{projects.filter(p=>p.policy?.members?.some((m:string)=>m.toLowerCase()===e.login.toLowerCase())).map(p=><div key={p.id}>{p.label||p.name}: Assigned Write · {personAccess(p.github?.roles?.instructors?.remote,e.login)}</div>)}</td><td><button className="pws-button" onClick={()=>{setEditing(index);setPerson(structuredClone(e));}}>Edit</button></td></tr>)}</tbody></table>{!visible.length&&<p>No matching people. Import a directory to begin.</p>}</div>

 </fieldset>{settings.staff?.pending&&<section aria-label="Pending staff access change"><p>Pending access change for {settings.staff.pending.user.login}: {settings.staff.pending.permission} on {settings.staff.pending.remote.owner}/{settings.staff.pending.remote.name}. No request will be resent during recovery.</p>{settings.staff.pending.diagnostic&&<p>{settings.staff.pending.diagnostic.code}: {settings.staff.pending.diagnostic.message}{settings.staff.pending.diagnostic.httpStatus&&` · HTTP ${settings.staff.pending.diagnostic.httpStatus}`}{settings.staff.pending.diagnostic.requestId&&` · Request ${settings.staff.pending.diagnostic.requestId}`}</p>}<button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{await call({operation:'recoverStaffAccess',repo,direction:'complete'});})}>Recheck pending access change</button><button className="pws-button" disabled={busy} onClick={()=>{setReview({kind:'clear',recipient:settings.staff.pending.user.login,repository:settings.staff.pending.remote.owner+'/'+settings.staff.pending.remote.name});setAck(false);}}>Verify no grant and clear intent…</button></section>}{projects.filter(p=>p.staff?.pending).map(p=><section key={p.id} aria-label="Pending project access change"><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{await call({operation:'recoverProjectAccess',repo,projectId:p.id,direction:'complete'});})}>Recheck pending {p.label||p.name} access</button><button className="pws-button" disabled={busy} onClick={()=>{setReview({kind:'clear',projectId:p.id,recipient:p.staff.pending.user.login,repository:p.staff.pending.remote.owner+'/'+p.staff.pending.remote.name});setAck(false);}}>Verify no grant and clear intent…</button></section>)}<p role="status">{notice}</p>{batchResults.length>0&&<section aria-label="GitHub batch results"><h3>GitHub batch results</h3><ul>{batchResults.map(r=><li key={r.login}><strong>{r.login}</strong>: {r.status}{r.diagnostic&&<p role="alert">{r.error}: {r.diagnostic.message}{r.diagnostic.noGrantVerified&&' · No grant observed; local intent cleared. Review again only after resolving this failure.'}{r.diagnostic.apiMessage&&` · ${r.diagnostic.apiMessage}`}{r.diagnostic.httpStatus&&` · HTTP ${r.diagnostic.httpStatus}`}{r.diagnostic.requestId&&` · Request ${r.diagnostic.requestId}`}</p>}</li>)}</ul></section>}{settings.migrated&&<details onToggle={e=>{if(e.currentTarget.open)void loadProjects().catch(()=>{});}}><summary>Team repositories and submissions</summary><TeachProjectSettings repo={repo} year={year} season={season} call={call} onChanged={loadProjects}/></details>}
 {review&&<CourseDialog title={review.kind==='github'?'Review GitHub batch':review.kind==='clear'?'Review pending access recovery':'Review People changes'} onClose={close}>{error&&<p role="alert">{error}</p>}{review.kind==='clear'&&<><p>Verify current access for {review.recipient} on {review.repository}, then clear this local intent only if the requested access or invitation is not observed.</p><p>This sends no invitation, removes no GitHub access, and preserves your course files. A fresh review is required before any new request. If GitHub cannot be checked conclusively, the intent remains pending.</p></>}{review.description&&<p>{review.description}</p>}{review.people&&<p>{review.people.join(', ')}</p>}{review.changes&&<ul>{review.changes.map((c:any)=><li key={c.row}>Row {c.row}: {c.action} · {[c.after.firstName,c.after.lastName].filter(Boolean).join(' ')||'Unnamed'} · {c.after.email||'No email'} · {c.after.login||'No GitHub account'} · {c.after.role}</li>)}</ul>}{review.rows&&<ul>{review.rows.map((r:any)=><li key={r.user.id}>{r.user.login} (ID {r.user.id}) · {r.remote.owner}/{r.remote.name} (ID {r.remote.id}, {r.remote.visibility}) · {r.permission} · {r.status} · Signed in as {r.account.login}</li>)}</ul>}<p>{review.kind==='github'?'GitHub may send invitations. The batch stops on the first failure; successful earlier changes remain.':'These changes stay local. No invitation is sent.'}</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed the selected people and assignments.</label><button className="pws-button" disabled={busy||!ack} onClick={()=>void run(async()=>{if(review.kind==='github'){const result=await call({operation:'applyPeopleAccessBatch',planId:review.planId});setBatchResults(result.results);setNotice(result.complete?'GitHub batch completed.':'GitHub batch stopped. Review each recipient below and reconcile pending access before retrying.');}else if(review.kind==='clear'){const result=await call({operation:review.projectId?'recoverProjectAccess':'recoverStaffAccess',repo,...(review.projectId?{projectId:review.projectId}:{}),direction:'clear'});setNotice(result.status);}else if(review.kind==='team'){await call({operation:'saveProjectPolicy',repo,projectId:review.team.id,revision:review.team.revision,policy:review.policy});setNotice('Team membership saved locally.');}else await save(review.entries,review.rosterRevision);setReview(null);setPerson(null);setAck(false);})}>Confirm reviewed changes</button></CourseDialog>}
 </section>;
}
