import React,{useEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import type {PipelineCall} from './TeachPipelineSettings';
const dubai=(date:string)=>new Date(date).toLocaleString('en-GB',{timeZone:'Asia/Dubai',dateStyle:'medium',timeStyle:'short'});
const errors:Record<string,string>={GITHUB_PROJECT_ISOLATION_UNVERIFIED:'Project isolation could not be verified. Organization base access must be None, repository team grants must be absent, and owner/access inspection complete. Use personal private repositories or reconcile GitHub permissions before retrying.',GITHUB_PROJECT_ACCESS_DRIFT:'GitHub lists accounts outside this team policy and owner exceptions. Reconcile access on GitHub before granting more access.',SUBMISSION_MISSING:'No published release exists for this milestone and sequence. A push alone does not submit.',SUBMISSION_MANIFEST:'Check submission.json paths, hashes and sizes. At least one tracked deliverable is required.',SUBMISSION_HASH_MISMATCH:'Declared hashes or sizes do not match the exact tagged files. No receipt was recorded.',SUBMISSION_TAG_REUSED:'This tag was already receipted with different content. Publish a new sequence; the earlier receipt is preserved.',SUBMISSION_CHANGED:'The account, policy, tag or files changed after review. Review again.',SUBMISSION_ACCESS:'The private repository is unavailable or access/visibility changed. No receipt was recorded.',SUBMISSION_ARTIFACT:'A declared release asset could not be verified and archived. No receipt was recorded.',SUBMISSION_LIMIT:'Submission exceeds the supported snapshot limits: 128 files of 4 MiB each, eight release assets of 64 MiB each, 240 MiB total.',GITHUB_RECONNECT_REQUIRED:'Connect GitHub using the account menu.',GITHUB_SETUP_RECOVERY_REQUIRED:'Recheck the pending repository setup first.',GITHUB_STAFF_RECOVERY_REQUIRED:'Recheck the pending access change first.',CONFLICT:'Local settings changed. Reload and review again.',STALE_PLAN:'This review expired. Prepare a new review.'};
export function TeachProjectDetail({repo,team,call,refresh}:{repo:string;team:any;call:PipelineCall;refresh:()=>Promise<void>}){
 const [members,setMembers]=useState(''),[milestones,setMilestones]=useState<{id:string;deadline:string|null}[]>([]),[owner,setOwner]=useState(''),[remoteName,setRemoteName]=useState(team.localName),[mode,setMode]=useState('create'),[person,setPerson]=useState(''),[milestone,setMilestone]=useState(''),[sequence,setSequence]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[review,setReview]=useState<any>(null),[ack,setAck]=useState(false);
 const pending=useRef(false),plan=useRef<{planId:string;cancel:string;apply:string}|null>(null);
 const remote=team.github?.roles?.instructors?.remote;
 useEffect(()=>{setMembers(team.policy.members.join(', '));setMilestones(team.policy.milestones);},[team.id,team.revision]);
 useEffect(()=>()=>{if(plan.current)void call({operation:plan.current.cancel,planId:plan.current.planId}).catch(()=>{});},[team.id,call]);
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await action();await refresh();}catch(e){setError(errors[(e as any).code]??(e as Error).message);setReview(null);setAck(false);if(plan.current)void call({operation:plan.current.cancel,planId:plan.current.planId}).catch(()=>{});plan.current=null;await refresh().catch(()=>{});}finally{pending.current=false;setBusy(false);}};
 const prepare=async(operation:string,input:Record<string,unknown>,cancel:string,apply:string)=>{const result=await call({operation,repo,projectId:team.id,...input});if(!result.planId){setNotice(result.status);return;}plan.current={planId:result.planId,cancel,apply};setReview({...result,kind:operation});setAck(false);};
 const close=()=>{if(busy)return;if(plan.current)void call({operation:plan.current.cancel,planId:plan.current.planId}).catch(()=>{});plan.current=null;setReview(null);setAck(false);};
 const normalized=members.split(',').map(v=>v.trim()).filter(Boolean);
 const dirty=JSON.stringify({members:normalized,milestones})!==JSON.stringify(team.policy);
 return <section aria-label={`${team.label} project settings`}>
  <h3>{team.label} · {team.name??'Unavailable'}</h3>{error&&<p role="alert">{error}</p>}
  <fieldset disabled={busy}>
   <label>GitHub accounts allowed Write access (team and selected staff)<input value={members} onChange={e=>setMembers(e.target.value)} placeholder="username1, username2"/></label>
   <p>Saving this list does not change GitHub access. Removing an account locally does not revoke existing access or downloaded copies; inspect and reconcile GitHub access separately.</p>
   <h4>Milestones and extensions</h4><p>Enter deadlines in UTC. Each team can have its own extension. No deadlines are inferred from course dates.</p>
   {milestones.map((m,i)=><div className="teach-pipeline-actions" key={i}><label>Milestone ID<input value={m.id} onChange={e=>setMilestones(milestones.map((v,n)=>n===i?{...v,id:e.target.value}:v))}/></label><label>Deadline UTC (optional)<input type="datetime-local" step="1" value={m.deadline?.replace(/Z$/,'')??''} onChange={e=>setMilestones(milestones.map((v,n)=>n===i?{...v,deadline:e.target.value?new Date(e.target.value+'Z').toISOString().replace('.000Z','Z'):null}:v))}/></label>{m.deadline&&<span>Dubai: {dubai(m.deadline)}</span>}<button className="pws-button" onClick={()=>setMilestones(milestones.filter((_,n)=>n!==i))}>Remove milestone locally</button></div>)}
   <div className="teach-pipeline-actions"><button className="pws-button" disabled={milestones.length>=32} onClick={()=>setMilestones([...milestones,{id:'',deadline:null}])}>Add milestone</button><button className="pws-button" disabled={!dirty||Boolean(team.staff?.pending)} onClick={()=>void run(async()=>{await call({operation:'saveProjectPolicy',repo,projectId:team.id,revision:team.revision,policy:{members:normalized,milestones}});setNotice('Team policy saved locally; GitHub permissions unchanged.');})}>Save team policy</button></div>
   <h4>Private GitHub repository</h4><p>{remote?`${remote.owner}/${remote.name} · ${remote.visibility} · observed ${dubai(new Date(remote.verifiedAt).toISOString())}`:'Not connected'}</p>
   {team.github?.pending?<><p>Creation pending. Recheck without creating another repository.</p><button className="pws-button" onClick={()=>void run(async()=>{await call({operation:'recoverProjectGitHub',repo,projectId:team.id,direction:'complete'});setNotice('Repository verified and connected.');})}>Recheck project creation</button><button className="pws-button" onClick={()=>void run(async()=>{await call({operation:'recoverProjectGitHub',repo,projectId:team.id,direction:'cancel'});setNotice('Verified absence; intent cleared.');})}>Verify absence and clear project intent</button></>:<div className="teach-pipeline-actions"><label>Project setup action<select value={mode} onChange={e=>setMode(e.target.value)}><option value="create">Create empty</option><option value="bind">Bind existing</option></select></label><label>Project GitHub owner<input value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Project GitHub repository<input value={remoteName} onChange={e=>setRemoteName(e.target.value)}/></label><button className="pws-button" disabled={!owner||!remoteName||!team.available} onClick={()=>void run(()=>prepare('reviewProjectGitHub',{mode,owner,repository:remoteName},'cancelProjectGitHub','applyProjectGitHub'))}>Review private project setup</button></div>}
   <button className="pws-button" disabled={!remote} onClick={()=>void run(async()=>{await call({operation:'verifyProjectGitHub',repo,projectId:team.id});setNotice('Project access observation refreshed.');})}>Recheck project access</button>
   {remote&&<details><summary>Observed access and drift</summary><p>{remote.inheritanceWarning} Isolation {remote.isolation?.complete?'verified for observed base/team access':'not verified'}; organization owners retain access. Base access: {remote.isolation?.basePermission??'unknown'}. Listed access {remote.accessComplete?'inspected':'incomplete'}. A local roster does not enforce GitHub isolation.</p><ul>{remote.collaborators.map((v:any)=><li key={v.login}>{v.login}: {v.role}{team.policy.members.some((m:string)=>m.toLowerCase()===v.login.toLowerCase())?' · listed in policy':' · outside local policy; review inherited/owner access'}</li>)}</ul><ul>{remote.invitations.map((v:any,i:number)=><li key={i}>{v.login??'Unknown recipient'} · invitation pending · {v.role}</li>)}</ul></details>}
   <div className="teach-pipeline-actions"><label>Project account<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose saved account</option>{team.policy.members.map((v:string)=><option key={v} value={v}>{v}</option>)}</select></label><button className="pws-button" disabled={!person||dirty||!remote||Boolean(team.staff?.pending)} onClick={()=>void run(()=>prepare('reviewProjectAccess',{login:person},'cancelProjectAccess','applyProjectAccess'))}>Review project Write access</button></div>
   {team.staff?.pending&&<><p>Pending access change for {team.staff.pending.user.login}. Recovery never repeats the invitation.</p><button className="pws-button" onClick={()=>void run(async()=>{const r=await call({operation:'recoverProjectAccess',repo,projectId:team.id,direction:'complete'});setNotice(r.status);})}>Recheck project invitation</button><button className="pws-button" onClick={()=>void run(async()=>{const r=await call({operation:'recoverProjectAccess',repo,projectId:team.id,direction:'clear'});setNotice(r.status);})}>Verify no project grant and clear intent</button></>}
   <h4>Submissions</h4><p>Publish a GitHub release with tag <code>asmb-submit/&lt;milestone&gt;/&lt;sequence&gt;</code> and a committed submission.json manifest. Push alone is not submission.</p>
   <div className="teach-pipeline-actions"><label>Submission milestone<select value={milestone} onChange={e=>setMilestone(e.target.value)}><option value="">Choose milestone</option>{team.policy.milestones.map((m:any)=><option key={m.id} value={m.id}>{m.id}</option>)}</select></label><label>Submission sequence<input type="number" min="1" max="9999" value={sequence} onChange={e=>setSequence(Number(e.target.value))}/></label><button className="pws-button" disabled={!milestone||!remote||dirty} onClick={()=>void run(()=>prepare('reviewSubmission',{milestone,sequence},'cancelSubmission','applySubmission'))}>Verify submission</button></div>
   <ul>{team.submissions?.checks.map((c:any)=><li key={c.milestone}>{c.milestone}: {c.status}{c.observedAt?` · Dubai ${dubai(c.observedAt)}`:''}</li>)}</ul>
   {team.policy.milestones.filter((m:any)=>!team.submissions?.receipts.some((r:any)=>r.milestone===m.id)).map((m:any)=><p key={m.id}>{m.id}: no receipt retained{m.deadline?` · deadline Dubai ${dubai(m.deadline)}`:''}. Verify the release to distinguish missing submission from access failure.</p>)}
   <ul>{team.submissions?.receipts.map((r:any)=><li key={r.id}>{r.milestone} #{r.sequence} · {r.deadlineStatus} · Dubai {dubai(r.observedAt)} · <code>{r.commit}</code><details><summary>Immutable receipt</summary><p>Submitter {r.submitter.login}. Manifest SHA-256 {r.manifestHash}. Snapshot SHA-256 {r.snapshotHash}. {r.validation}</p><p>GitHub published {dubai(r.publishedAt)}. Deadline status uses server-observed verification time.</p></details><button className="pws-button" onClick={()=>void run(async()=>{const result=await call({operation:'openSubmission',repo,projectId:team.id,receiptId:r.id});setNotice(`Review copy opened as repository ${result.repo}. The retained archive is unchanged.`);})}>Create snapshot review copy</button></li>)}</ul>
  </fieldset><p role="status">{notice}</p>
  {review&&<CourseDialog title="Review project action" onClose={close}>
   {review.kind==='reviewProjectGitHub'?<><p>{review.mode==='create'?'Create empty':'Bind existing'} {review.owner}/{review.repository} · private</p><p>Signed in as {review.account.login}. Branch {review.branch}.</p><ul>{review.changes.map((v:string)=><li key={v}>{v}</li>)}</ul></>:review.kind==='reviewProjectAccess'?<><p>{review.user.login} · numeric user {review.user.id} · Write on {review.remote.owner}/{review.remote.name} · private</p><p>Account {review.account.login}. {review.status}. GitHub may notify the recipient; pending invitations require acceptance.</p></>:<><p>{review.team} · {review.tag}</p><p>Commit <code>{review.commit}</code>. Submitter {review.submitter.login}.</p><p>Server verification Dubai {dubai(review.observedAt)}. Deadline {review.deadline?dubai(review.deadline):'not set'}.</p><ul>{review.files.map((f:any)=><li key={f.path}>{f.path} · {f.size} bytes · SHA-256 {f.sha256}</li>)}{review.artifacts.map((a:any)=><li key={a.assetId}>Release asset {a.name} · {a.size} bytes · SHA-256 {a.sha256}</li>)}</ul></>}
   {review.warnings?.map((v:string)=><p key={v}>{v}</p>)}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed this exact project action.</label><button className="pws-button" disabled={busy||!ack} onClick={()=>void run(async()=>{const current=plan.current!;const result=await call({operation:current.apply,planId:current.planId});plan.current=null;setReview(null);setAck(false);setNotice(result.status??(result.receipt?'Immutable submission receipt retained.':'Private project repository connected; no files uploaded.'));})}>Confirm reviewed project action</button>
  </CourseDialog>}
 </section>;
}
