import {TeachProjectSettings} from './TeachProjectSettings';
import {TeachPeopleSettings} from './TeachPeopleSettings';
import {PanelResizeHandle} from './PanelResizeHandle';
import {TeachGitHubSettings} from './TeachGitHubSettings';
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import './teach-pipeline.css';
export type PipelineCall=(input:Record<string,unknown>)=>Promise<any>;
const labels:Record<string,string>={instructors:'Instructors',assistants:'Assistants',students:'Students'};
const messages:Record<string,string>={PROMOTION_RECOVERY_REQUIRED:'A previous copy needs recovery. Recheck it in Course settings before copying again.',TEACH_GRAPH_REQUIRED:'Review and save repository bindings first.',TEACH_GRAPH_BINDING:'The selected repository is unavailable or belongs to another course role.',PROMOTION_PRIVATE_FILE:'Select supported term files. Private files, course metadata and Instructor pages cannot be copied to Students.',PROMOTION_DEPENDENCY:'A selected file links to an unselected, missing or private dependency. Select the required safe files or repair the link.',PROMOTION_SECRET:'A file contains a suspected credential. Remove it before preparing output.',PROMOTION_LIMIT:'This local copy supports up to 128 files, 4 MiB per file and 32 MiB total. Large artifacts need separate delivery.',DRAFT_CONFLICT:'Save or resolve the source and destination drafts before copying.',CONFLICT:'The course, repository bindings or selected files changed. Review again.',STALE_PLAN:'The destination changed or the review expired. Review again.',PUBLICATION_UPDATE_CONFLICT:'Destination edits or drafts conflict with this copy. Existing files have been preserved.'};
export function TeachPipelineSettings({repo,year,season,call,onOpenRole,onCreateAssistant,authoring,sidebarOpen=true,onSidebarClose}:{repo:string;year:number;season:string;call:PipelineCall;onOpenRole?(role:string):void;onCreateAssistant?():Promise<void>;authoring?:React.ReactNode;sidebarOpen?:boolean;onSidebarClose?():void}){
 const [sidebarWidth,setSidebarWidth]=useState(280);
 const [page,setPage]=useState('repositories'),pageRoot=useRef<HTMLElement>(null),navigate=useRef(false);
 useLayoutEffect(()=>{if(!navigate.current)return;navigate.current=false;const pane=pageRoot.current?.querySelector<HTMLElement>(`[data-settings-section="${page}"]`);pane?.querySelector<HTMLElement>('h2')?.focus();pane?.scrollIntoView({block:'start'});},[page]);
 const [settings,setSettings]=useState<any>(null),[assistant,setAssistant]=useState(''),[migration,setMigration]=useState<any>(null),[fromRole,setFrom]=useState('instructors'),[toRole,setTo]=useState('assistants'),[inventory,setInventory]=useState<any>(null),[paths,setPaths]=useState<string[]>([]),[review,setReview]=useState<any>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const pending=useRef(false),plan=useRef<{operation:string;planId:string}|null>(null),errorRef=useRef<HTMLParagraphElement>(null);
 const refresh=async()=>{const next=await call({operation:'pipelineSettings',repo});setSettings(next);setAssistant(next.roles.find((r:any)=>r.role==='assistants')?.repositoryId??'');};
 useEffect(()=>{let active=true;void call({operation:'pipelineSettings',repo}).then(next=>{if(active){setSettings(next);setAssistant(next.roles.find((r:any)=>r.role==='assistants')?.repositoryId??'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;const current=plan.current;if(current)void call(current).catch(()=>{});};},[repo,call]);
 useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
 const reset=()=>{if(plan.current)void call(plan.current).catch(()=>{});plan.current=null;setMigration(null);setReview(null);setAck(false);setNotice('');};
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await action();}catch(e){setError(messages[(e as any).code]??(e as Error).message);reset();}finally{pending.current=false;setBusy(false);}};
 const options=settings?.repositories.filter((e:any)=>!settings.roles.some((r:any)=>r.role!=='assistants'&&r.repositoryId===e.stableId))??[];
 const blocked=review?.comparison?.rows.some((r:any)=>r.conflict||r.protectedDraft)||review?.comparison?.warnings?.length;
 return <div className="teach-settings-shell">{sidebarOpen&&<aside className="ncw-sidebar teach-settings-sidebar" style={{'--panel-resize-width':`${sidebarWidth}px`} as React.CSSProperties}><nav aria-label="Course settings pages">{[['repositories','Repositories'],['people','People'],['delivery','Delivery']].map(([id,title])=><button className="rfe-tree-row" key={id} aria-current={page===id?'page':undefined} onClick={()=>{navigate.current=true;setPage(id);}}>{title}</button>)}</nav><PanelResizeHandle width={sidebarWidth} defaultWidth={280} minWidth={180} maxWidth={480} onResize={setSidebarWidth} onCollapse={()=>onSidebarClose?.()} label="Resize Course settings sidebar"/></aside>}<section ref={pageRoot} className="teach-pipeline" aria-labelledby="teach-pipeline-title" aria-busy={busy} data-teach-area="TP1">
  <header><div><h1 id="teach-pipeline-title">Course settings</h1><p>{year} {season} · Set up repositories, manage people and teams, then connect delivery.</p></div></header>
  {error&&<p role="alert" tabIndex={-1} ref={errorRef}>{error}</p>}
  {!settings?<p role="status">Loading repository bindings…</p>:<fieldset disabled={busy}>
   <div className="teach-settings-layout"><div className="teach-settings-pages">
   <div hidden={page!=='repositories'}>
   <section className="teach-settings-section" data-settings-section="repositories" aria-labelledby="teach-repositories-title"><h2 id="teach-repositories-title" tabIndex={-1}>Repositories</h2><p>Your course content stays in separate local repositories. Open a role to edit its files.</p><div className="teach-pipeline-table"><table><thead><tr><th>Role</th><th>Local repository</th><th>Intended visibility</th><th>GitHub connection</th><th><span className="fw-sr-only">Open repository</span></th></tr></thead><tbody>{settings.roles.map((role:any)=><tr key={role.role}><th scope="row">{labels[role.role]}</th><td>{role.name??'Not bound'}{role.repositoryId&&!role.available&&' · unavailable'}</td><td>{role.intendedVisibility}</td><td>{role.sourceUrl?<><span>{role.sourceUrl.replace('https://github.com/','')}</span><br/></>:null}{!role.sourceUrl&&'Not connected'}</td><td><button className="pws-button" disabled={!role.available||!onOpenRole} onClick={()=>onOpenRole?.(role.role)}>Open {labels[role.role]}</button></td></tr>)}</tbody></table></div>
   <p className="teach-settings-note">Visibility here is intended. GitHub connection and access checks are in Delivery.</p><h3>Assistant repository</h3><p>Choose an existing repository or create one, then review and save the binding.</p>
   <div className="teach-pipeline-actions" data-teach-area="TP2"><label>Assistant repository<select aria-label="Assistant repository" value={assistant} onChange={e=>{reset();setAssistant(e.target.value);}}><option value="">No Assistant repository</option>{options.map((e:any)=><option key={e.stableId} value={e.stableId}>{e.name}</option>)}</select></label>{onCreateAssistant&&<button className="pws-button" onClick={()=>void run(async()=>{reset();await onCreateAssistant();await refresh();})}>Create local Assistant repository</button>}<button className="pws-button" onClick={()=>void run(async()=>{reset();const result=await call({operation:'reviewRepositoryGraph',repo,assistantId:assistant||null});plan.current={operation:'cancelRepositoryGraph',planId:result.planId};setMigration(result);})}>Review repository bindings</button></div>
   {!settings.migrated&&<p>The existing Instructor/Students pair has not been registered as a role graph. Review the bindings to continue.</p>}
   {settings.provenance?.pending&&<section><h2>Interrupted local copy</h2><p>Recheck the destination after resolving any package recovery. Your files are preserved.</p><button className="pws-button" onClick={()=>void run(async()=>{await call({operation:'resolvePromotion',repo,direction:'complete'});await refresh();})}>Verify completed copy</button><button className="pws-button" onClick={()=>void run(async()=>{await call({operation:'resolvePromotion',repo,direction:'cancel'});await refresh();})}>Verify unchanged destination</button></section>}
   {authoring}</section>
   <details className="teach-settings-optional"><summary>Copy files between repositories <span>Optional</span></summary><p>Use this when sharing selected saved content between roles. Direct editing does not require a copy.</p>
   {settings.provenance?.last&&<p>Last local copy: {labels[settings.provenance.last.sourceRole]} → {labels[settings.provenance.last.toRole]} · {settings.provenance.last.files.length} files. Source {settings.provenance.last.sourceCommit??'saved files without a matching commit'}.</p>}
   <section data-teach-area="TP3"><h3>Prepare a local copy</h3><p>Select saved pages, code, assets and licenses. Git history is excluded. This does not commit or push files.</p><div className="teach-pipeline-actions"><label>From<select aria-label="From" value={fromRole} onChange={e=>{reset();setInventory(null);setPaths([]);setFrom(e.target.value);if(e.target.value==='assistants')setTo('students');}}><option value="instructors">Instructors</option><option value="assistants">Assistants</option></select></label><label>To<select aria-label="To" value={toRole} onChange={e=>{reset();setInventory(null);setPaths([]);setTo(e.target.value);}}>{fromRole==='instructors'&&<option value="assistants">Assistants</option>}{fromRole==='assistants'&&<option value="instructors">Instructors · contribution folder</option>}<option value="students">Students</option></select></label><button className="pws-button" disabled={!settings.migrated} onClick={()=>void run(async()=>{reset();setPaths([]);setInventory(await call({operation:'pipelineFiles',repo,year,season,fromRole,toRole}));})}>Choose files</button></div>
   {inventory&&<><p>{inventory.source} → {inventory.destination}. Limit: {inventory.limits?.files??128} files, {(inventory.limits?.fileBytes??4194304)/1048576} MiB per file, {(inventory.limits?.totalBytes??33554432)/1048576} MiB total.</p>{!inventory.sourceCommit&&<p>Source has no commit yet. This copy records saved file hashes; it is not a committed release.</p>}{inventory.candidateRoot&&<><p>Student candidates: {inventory.candidateRoot}. A complete package is required; private preparation stays separate.</p><button className="pws-button" onClick={()=>{reset();setPaths(inventory.entries.filter((f:any)=>f.path.startsWith(inventory.candidateRoot+'/')).map((f:any)=>f.path));}}>Select complete Student package</button></>}<div className="teach-pipeline-files">{inventory.entries.length?inventory.entries.map((file:any)=><label key={file.path}><input type="checkbox" checked={paths.includes(file.path)} onChange={e=>{reset();setPaths(p=>e.target.checked?[...p,file.path]:p.filter(v=>v!==file.path));}}/>{file.path}</label>):<p>No files in this term. Open the source repository to prepare them.</p>}</div><button className="pws-button" disabled={!paths.length} onClick={()=>void run(async()=>{reset();const result=await call({operation:'reviewPromotion',repo,year,season,fromRole,toRole,destination:inventory.destination,paths});plan.current={operation:'cancelPromotion',planId:result.planId};setReview(result);})}>Review local copy</button></>}
   </section></details></div><div hidden={page!=='people'} className="teach-settings-section" data-settings-section="people"><TeachPeopleSettings repo={repo} year={year} season={season} settings={settings} call={call} refresh={refresh}/></div><div hidden={page!=='delivery'} className="teach-settings-section" data-settings-section="delivery"><TeachGitHubSettings repo={repo} term={`${year}-${season}`} settings={settings} call={call} refresh={refresh}/></div>{notice&&<p role="status">{notice}</p>}</div></div>
  </fieldset>}
  {migration&&<CourseDialog title="Review repository bindings" onClose={reset}><p>Register these local identities without moving or rewriting course files.</p><ul>{migration.after.roles.map((r:any)=><li key={r.role}>{labels[r.role]}: {r.name??'Not bound'}</li>)}</ul><h3>Preserved</h3><ul>{migration.preserves.map((text:string)=><li key={text}>{text}</li>)}</ul><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{await call({operation:'applyRepositoryGraph',planId:migration.planId});plan.current=null;setMigration(null);await refresh();setNotice('Repository bindings saved.');})}>Save repository bindings</button></CourseDialog>}
  {review&&<CourseDialog title="Review local copy" onClose={()=>{if(!busy)reset();}}><p>{inventory.source} → {inventory.destination}</p>{review.warnings.map((w:string)=><p key={w}>{w}</p>)}<ul className="teach-pipeline-review">{review.files.map((f:any)=><li key={f.path}><details><summary>{f.path} · {f.bytes} bytes</summary><code>SHA-256: {f.sha256}</code>{f.preview!==null&&<pre>{f.preview}</pre>}</details></li>)}</ul><h3>Destination comparison</h3><ul>{review.comparison.rows.map((r:any)=><li key={r.path}>{r.path} · {r.action}{r.conflict?' · conflict':''}{r.protectedDraft?' · unsaved draft':''}</li>)}</ul>{blocked&&<p role="alert">Resolve destination edits or drafts before copying. No files will be overwritten.</p>}<label className="teach-output-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed these files, dependencies, licenses and destination changes.</label><button className="pws-button" disabled={busy||!ack||Boolean(blocked)} onClick={()=>void run(async()=>{const result=await call({operation:'applyPromotion',planId:review.planId});plan.current=null;setReview(null);await refresh();setNotice(`${result.files} files copied locally. Commit and Push remain separate.`);})}>Copy reviewed files</button></CourseDialog>}
 </section></div>;
}
