import React,{useState,useRef,useEffect} from 'react';
import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import {CourseDialog} from './TeachCoursesStudy';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
export type TeachStudentActions={candidate?:boolean;hideReview?:boolean;reviewLabel?:string;onDelivery?():void;onPrepare?():void;onReview():void;onExport():void};
export function TeachStudentTools({actions,onGitHub,disabled}:{actions:TeachStudentActions;onGitHub():void;disabled:boolean}){
 const root=useRef<HTMLDivElement>(null);
 if(actions.candidate)return <div className="teach-student-tools"><button disabled={disabled} onClick={actions.onReview}>Review Student package</button><button disabled={disabled} onClick={actions.onExport}>Prepare Student ZIP…</button></div>;
 return <div ref={root} className="teach-student-tools">{!actions.hideReview&&<button disabled={disabled} onClick={actions.onReview}>{actions.reviewLabel??'Review Instructor changes'}</button>}<DropdownMenu.Root><DropdownMenu.Trigger asChild><button disabled={disabled} aria-label="Sync to GitHub">Sync to GitHub <span aria-hidden="true">▾</span></button></DropdownMenu.Trigger><DropdownMenu.Portal container={root.current?.closest('.fw-window')??undefined}><DropdownMenu.Content className="rex-menu" align="end" sideOffset={4}>{actions.onPrepare&&<DropdownMenu.Item className="rex-menu-item" onSelect={actions.onPrepare}>Prepare GitBook delivery…</DropdownMenu.Item>}<DropdownMenu.Item className="rex-menu-item" onSelect={actions.onDelivery??onGitHub}>Connect to GitHub…</DropdownMenu.Item><DropdownMenu.Item className="rex-menu-item" onSelect={actions.onDelivery??onGitHub}>Review GitHub status and Push…</DropdownMenu.Item><DropdownMenu.Item className="rex-menu-item" onSelect={actions.onExport}>Prepare Student ZIP…</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root></div>;
}
export function TeachStudentExport({repo,onClose}:{repo:string;onClose():void}){
 const [review,setReview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ack,setAck]=useState(false);const pending=useRef(false),plan=useRef<string|null>(null);const bridge=getNativeBridge()!;
 const run=async(fn:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{pending.current=false;setBusy(false);}};
 useEffect(()=>()=>{if(plan.current)void bridge.cancelPackagePlan({repo,planId:plan.current});},[repo]);
 return <CourseDialog title="Prepare Student ZIP" onClose={()=>{if(!busy)onClose();}}><div className="teach-publish"><p>Export saved files from {repo}, including all terms. Instructor files from the other repository are not included. Unsaved edits are excluded.</p>{!review&&<button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const result=await nativeOperation(()=>bridge.reviewPackageExport({repo,collectionId:repo,version:'1'}));setReview(result);plan.current=result.planId;})}>Review Student files</button>}{review&&<><ul>{review.rows.map((r:any)=><li key={r.path}>{r.path}</li>)}</ul>{review.warnings.map((w:any,i:number)=><p key={i}>{w.message}</p>)}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed these files for student sharing.</label><button className="pws-button" disabled={busy||!ack} onClick={()=>void run(async()=>{const result=await nativeOperation(()=>bridge.savePackageExport({repo,planId:review.planId,kind:'source'}));setNotice(result.saved?'Student ZIP saved.':'Export cancelled.');})}>Save ZIP…</button></>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div></CourseDialog>;
}
