import React,{useEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import {getNativeBridge,nativeOperation} from './native-bridge.mjs';
export function TeachDirectDelivery({repo,studentRepo,year,season,kind,onClose,onPrepared}:{repo:string;studentRepo:string;year:number;season:string;kind:'zip'|'prepare';onClose():void;onPrepared():void}){
 const [review,setReview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ack,setAck]=useState(false),[convert,setConvert]=useState(false);const pending=useRef(false),plan=useRef<string|null>(null),bridge=getNativeBridge()!;
 const call=(value:Record<string,unknown>)=>nativeOperation(()=>bridge.nativeTeachRequest(value));
 const cancel=()=>{if(plan.current)void call({operation:'cancelDirectDelivery',planId:plan.current});plan.current=null;};useEffect(()=>cancel,[]);
 const run=async(fn:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);cancel();setReview(null);setAck(false);}finally{pending.current=false;setBusy(false);}};
 return <CourseDialog title={kind==='zip'?'Prepare Student ZIP':'Prepare GitBook delivery'} onClose={()=>{if(!busy)onClose();}}><div className="teach-publish"><p>Review saved {year}-{season} files in {studentRepo}. Local links, model dependencies and private-path checks must pass. Other repositories and terms are excluded.</p><p>{kind==='zip'?'The ZIP includes reviewed navigation and GitBook configuration; authored files stay unchanged.':'Only reviewed navigation/configuration will be saved in Students. Commit selected files and review Push separately.'}</p>{kind==='zip'&&!review&&<label><input type="checkbox" checked={convert} onChange={e=>setConvert(e.target.checked)}/> Convert supported GitBook markup in the ZIP only</label>}{!review&&<button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const next=await call({operation:'reviewDirectDelivery',repo,year,season,convertGitBook:convert});plan.current=next.planId;setReview(next);})}>Review delivery files</button>}{review&&<><ul>{review.files.map((file:any)=><li key={file.path}>{file.path}{file.generated?' — proposed delivery update':''}{file.generated&&file.preview&&<details><summary>Review generated content</summary>{file.before!==null&&<><p>Current content</p><pre>{file.before}</pre><p>Proposed content</p></>}<pre>{file.preview}</pre></details>}</li>)}</ul>{review.warnings.map((w:string)=><p key={w}>{w}</p>)}{review.conversions.map((c:any)=><details key={c.path}><summary>Output conversion: {c.path}</summary><pre>{c.original}</pre></details>)}<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed these files and warnings for student delivery.</label><button className="pws-button" disabled={busy||!ack} onClick={()=>void run(async()=>{const id=review.planId;plan.current=null;if(kind==='zip'){const result=await nativeOperation(()=>bridge.saveTeachPublication({planId:id,direct:true}));setNotice(result.saved?'Student ZIP saved.':'Export cancelled.');}else{await call({operation:'prepareDirectDelivery',planId:id});onPrepared();setNotice('GitBook delivery files saved. Commit selected files, then review Push.');}setReview(null);setAck(false);})}>{kind==='zip'?'Save ZIP…':'Save delivery files'}</button></>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div></CourseDialog>;
}
