import React,{useMemo,useRef,useState} from 'react';
import {FocusedWriting} from './FocusedWriting';
import {FileNavigationControls} from './FileNavigationControls';
import {RepositoryExplorer} from './RepositoryExplorer';
import type {NavigationRequest} from './workspace-navigation';
import {RepositoryFileEditor} from './RepositoryFileEditor';
import {NativePluginProvider} from './NativePluginHost';
import {FrameIcon} from '../../apps/desktop/ui/shared/editor-frame';
import {TeachCourseCalendarStudy,type TeachCalendarState} from './TeachCalendarStudy';
import {TeachHomeStudy} from './TeachHomeStudy';
import {TeachCoursesStudy,CourseDialog} from './TeachCoursesStudy';
import {IntegratedDocumentOutline} from './IntegratedDocumentOutline';
import type {OutlineState} from './workspace-navigation';
import {emptyTeacherProfile} from './teach-teacher-profile';
import type {TeachStudyCourse} from './teach-plugin-fixture';
import {createTeachSpacesMemory} from './teach-spaces-memory';
import './plugin-workspace-study.css';
import './teach-spaces-study.css';
import './teach-spaces-typography.css';
type Space='Instructors'|'Assistants'|'Students'|'Projects';
const spaces:Space[]=['Instructors','Assistants','Students','Projects'];
const course:TeachStudyCourse={id:'four-spaces-sample',code:'TEST101',title:'Robotics Systems',year:'2026',season:'Autumn',description:'Robotics systems, experiments and evidence.',repository:'TEST101_Instructors',sections:[]};
const lesson='# Class 01 · Introduction and evidence\n\n## Learning goals\n\nConnect a claim to an experiment and measurable evidence.\n\n## Experiment\n\n| Measurement | Unit | Purpose |\n| --- | --- | --- |\n| Joint angle | rad | Compare model prediction |\n| Time | s | Align observations |\n\n### Model\n\n$$\\tau = I\\ddot{\\theta} + b\\dot{\\theta}$$\n\n## Next class\n\n[Class 02](Class02.md)\n';
function fixtures(space:Space):Record<string,string>{
 if(space==='Students')return {'README.md':'# Robotics Systems\n\n## Course lessons\n\n- [Class 01 · Introduction and evidence](classes/Class01.md)\n- [Class 02 · Design an experiment](classes/Class02.md)\n\n## Materials\n\nLessons, media, generating code and inputs live in this shared repository.\n','classes/Class01.md':lesson,'classes/Class02.md':'# Class 02 · Design an experiment\n\n## Design\n\nDefine your input, measurement and acceptance criteria.\n','figure-sources/README.md':'# Figure sources\n\nKeep generating code, inputs and commands here.\n','code/example.py':'# Synthetic teaching example\nprint("Model comparison")\n'};
 if(space==='Projects')return {'README.md':'# Team project\n\n## Brief\n\nDefine a claim, build an experiment and present evidence.\n\n## Submission\n\nStaff record an assessed commit/tag and submission receipt.\n','worksheets/claim.md':'# Claim\n\nDefine the intended result.\n','results/README.md':'# Results\n\nRecord conditions and limitations.\n'};
 return {'README.md':space==='Instructors'?'# Instructor overview\n\n## Course delivery\n\nPrivate teaching notes, solutions and preparation.\n\n## Student lessons\n\nEdit lessons directly in the shared Students repository.\n':'# Staff preparation\n\n## Rehearsal\n\nPrivate discussions and teaching preparation.\n\n## Student lessons\n\nEdit lessons directly in the shared Students repository.\n','preparation/notes.md':'# Preparation notes\n\nPrivate preparation for the next class.\n'};
}
export function TeachSpacesStudy(){return <NativePluginProvider><TeachSpacesContent/></NativePluginProvider>;}
function TeachSpacesContent(){
 const [space,setSpace]=useState<Space>('Students'),[team,setTeam]=useState('Team01'),[persona]=useState('Instructor'),[view,setView]=useState<'course'|'calendar'|'courses'|'home'>('course'),[sidebar,setSidebar]=useState(true),[outlineOpen,setOutlineOpen]=useState(false),[outlineWidth,setOutlineWidth]=useState(240),[dialog,setDialog]=useState<'review'|'delivery'|'migration'|null>(null),[approved,setApproved]=useState(false),[notice,setNotice]=useState('');
 const [profile,setProfile]=useState(emptyTeacherProfile),[sampleCourses,setSampleCourses]=useState<readonly TeachStudyCourse[]>([course]);
 const [calendar,setCalendar]=useState<TeachCalendarState>({terms:{[course.id]:{monday:'2026-10-19',totalWeeks:7,sessions:[{id:'lecture',title:'Lecture',weekday:1,start:'09:00',end:'10:20',location:'CR6',weekFrom:1,weekTo:7},{id:'lab',title:'Lab',weekday:4,start:'09:00',end:'10:50',location:'L12',weekFrom:1,weekTo:7}]}},noClassDays:[]});
 const adapters=useMemo(()=>Object.fromEntries(['Instructors','Assistants','Students','Team01','Team02','Team03'].map(key=>[key,createTeachSpacesMemory(fixtures(key.startsWith('Team')?'Projects':key as Space))])),[]);
 const [mounted,setMounted]=useState(['Students']),[outlines,setOutlines]=useState<Record<string,OutlineState|null>>({}),[dirty,setDirty]=useState<Record<string,boolean>>({});
 const surface=useRef<HTMLDivElement>(null);const key=space==='Projects'?team:space;
 const open=(next:Space,nextTeam=team)=>{const id=next==='Projects'?nextTeam:next;setMounted(old=>old.includes(id)?old:[...old,id]);setSpace(next);setTeam(nextTeam);setView('course');setNotice('');};
 const available=persona==='Instructor'?spaces:spaces.filter(s=>s!=='Instructors');
 const [expanded,setExpanded]=useState<Record<string,boolean>>({Instructors:true,Students:true}),[navRequest,setNavRequest]=useState<NavigationRequest|null>(null),[activePaths,setActivePaths]=useState<Record<string,string>>({Students:'README.md'});
 const [rootActions,setRootActions]=useState<Record<string,HTMLElement|null>>({});
 const rootRefs=useMemo(()=>Object.fromEntries(['Instructors','Assistants','Students','Team01','Team02','Team03'].map(id=>[id,(element:HTMLDivElement|null)=>setRootActions(old=>old[id]===element?old:{...old,[id]:element})])),[]);
 const [folderOpen,setFolderOpen]=useState<Record<string,boolean>>({});
 const treeHeight=(id:string)=>{const paths=Object.keys(fixtures(id.startsWith('Team')?'Projects':id as Space));const nodes=new Set<string>();for(const path of paths){const parts=path.split('/');for(let n=1;n<=parts.length;n++)nodes.add(parts.slice(0,n).join('/'));}return [...nodes].filter(path=>{const parts=path.split('/');return parts.slice(0,-1).every((_,n)=>folderOpen[id+':'+parts.slice(0,n+1).join('/')]);}).length*32;};
 const toggle=(id:string)=>setExpanded(old=>({...old,[id]:!old[id]}));
 const repoGroup=(id:string,label=id)=><section key={id} className="tss-repo-group"><header className={`rfe-sidebar-header ${key===id&&view==='course'?'is-active':''}`}><button className="rfe-icon" aria-label={`${expanded[id]?'Collapse':'Expand'} ${label} repository`} aria-expanded={!!expanded[id]} onClick={()=>toggle(id)}>{expanded[id]?'▾':'▸'}</button><strong title={`TEST101_${id}`}><button className="tss-existing-title" onClick={()=>open(id.startsWith('Team')?'Projects':id as Space,id.startsWith('Team')?id:team)}>{label}</button></strong><button className="rfe-icon" aria-label={`Refresh ${label} files`} title="Refresh files" onClick={()=>setNotice('Files refreshed.')}>↻</button><button className="rfe-icon rfe-sidebar-search" aria-label={`Search ${label} files`} disabled><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.3"><path d="M11 6a5 5 0 1 1-10 0 5 5 0 0 1 10 0m-1 4 5 5"/></svg></button></header>{expanded[id]&&<><FileNavigationControls repository={`TEST101_${id}`} branch="main" branches={['main']} tags={[]} revision="" onRevisionChange={()=>{}} rootActionsRef={rootRefs[id]}/>
<div style={{height:treeHeight(id)}}><RepositoryExplorer rootActionsContainer={rootActions[id]??null} onToggle={(path,open)=>setFolderOpen(old=>({...old,[id+':'+path]:open}))} entries={Object.keys(fixtures(id.startsWith('Team')?'Projects':id as Space)).map(path=>({path,type:'file' as const}))} activePath={view==='course'&&key===id?activePaths[id]??'README.md':null} readOnly onOpen={(path,type)=>{open(id.startsWith('Team')?'Projects':id as Space,id.startsWith('Team')?id:team);setActivePaths(old=>({...old,[id]:path}));setNavRequest({id:Date.now(),repo:`TEST101_${id}`,path,type});}} onCommand={()=>{}} onRename={async()=>{}} onMove={async()=>{}}/></div></>}</section>;
 const navigation=<nav className="tss-unified" aria-label="Course repositories"><button className="rfe-tree-row tss-calendar-link" aria-current={view==='calendar'?'page':undefined} onClick={()=>setView('calendar')}><span>Course calendar</span></button>{available.filter(s=>s!=='Projects').map(s=>repoGroup(s))}<section className="tss-repo-group"><header className="rfe-sidebar-header tss-project-header"><button className="rfe-icon" aria-label={`${expanded.Projects?'Collapse':'Expand'} Projects`} aria-expanded={!!expanded.Projects} onClick={()=>toggle('Projects')}>{expanded.Projects?'▾':'▸'}</button><strong>Projects</strong></header>{expanded.Projects&&<div className="tss-project-roots">{['Team01','Team02','Team03'].map(t=>repoGroup(t))}</div>}</section></nav>;
 const common={courses:sampleCourses,calendarState:calendar,teacherProfile:profile,onCreate:(c:TeachStudyCourse)=>{setSampleCourses(old=>[...old,c]);setNotice('Course created.');},onReturnToRepository:()=>setView('course')};
 const editor=<div ref={surface} className="tss-shared-workspace"><div className="tss-shared-panes">{sidebar&&(view==='course'||view==='calendar')&&<aside className="rfe-sidebar tss-unified-sidebar">{navigation}</aside>}{mounted.map(id=><div key={id} hidden={id!==key||view!=='course'} className="tss-shared-editor"><RepositoryFileEditor presentInModes repository={`TEST101_${id}`} initialPath="README.md" initialSource={fixtures(id.startsWith('Team')?'Projects':id as Space)['README.md']!} revision="" branch="main" branches={['main']} tags={[]} workspace={adapters[id].client} readSnapshot={adapters[id].readSnapshot} navigationRequest={navRequest?.repo===`TEST101_${id}`?navRequest:null} onNavigationHandled={()=>setNavRequest(null)} fileSidebarOpen={false} onFileSidebarOpenChange={setSidebar} onClose={()=>setView('courses')} onDirtyChange={value=>setDirty(old=>({...old,[id]:value}))} onDocumentContextChange={value=>setActivePaths(old=>({...old,[id]:value.path}))} onOutlineChange={value=>setOutlines(old=>({...old,[id]:value}))} studentActions={id==='Students'?{hideReview:true,reviewLabel:'Review student content',onReview:()=>setDialog('review'),onPrepare:()=>setDialog('delivery'),onExport:()=>{setDialog('delivery');},onDelivery:()=>setDialog('delivery')}:undefined}/></div>)}{view==='calendar'&&<div className="tss-shared-calendar"><div className="tss-calendar-content"><TeachCourseCalendarStudy course={course} state={calendar} onChange={setCalendar} onOpenSchedule={()=>open('Students')}/></div></div>}{view==='home'&&<TeachHomeStudy {...common} recent={[]} onCalendarChange={setCalendar} onSaveProfile={setProfile} onOpenDocument={()=>open('Students')} onOpenTerm={()=>open('Students')}/>} {view==='courses'&&<TeachCoursesStudy {...common} summaries={{}} onOpen={()=>open('Students')} onCourse={()=>open('Students')} onAddTerm={()=>setNotice('Select a year and season to add a term.')}/>} {outlineOpen&&view==='course'&&<IntegratedDocumentOutline mainWindow={surface} outline={outlines[key]??null} width={outlineWidth} onResize={setOutlineWidth} onClose={()=>setOutlineOpen(false)} onReturnToDocument={()=>surface.current?.querySelector<HTMLElement>('.tss-shared-editor:not([hidden]) .cm-content')?.focus()} onReady={()=>{}}/>}</div>{notice&&<p className="tss-feedback" role="status">{notice}</p>}</div>;
 const rail=<button className="fw-icon pws-rail-button is-active" aria-label="asTeach Home" title="asTeach" onClick={()=>setView('home')}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m2 8 10-5 10 5-10 5Z M6 10v6c4 3 8 3 12 0v-6"/></svg></button>;
 return <><FocusedWriting repositoryHeader repositoryCode initialTheme="light-default" workspaceStudy={{active:true,rail,onExit:()=>setView('courses'),sidebar:{open:sidebar,onToggle:()=>setSidebar(v=>!v)},outline:{open:outlineOpen,onToggle:()=>setOutlineOpen(v=>!v)},headerContext:<nav className="pws-breadcrumb tss-breadcrumb" aria-label="asTeach breadcrumb"><button onClick={()=>setView('home')}>asTeach</button> / <button onClick={()=>setView('courses')}>Courses</button> / <button onClick={()=>setView('course')}>TEST101</button> / 2026 Autumn / {view==='calendar'?'Calendar':view==='home'?'Home':view==='courses'?'Courses':space}</nav>,headerContextReplacesOwner:true,content:editor}}/>{dialog&&<CourseDialog title={dialog==='review'?'Review student content':dialog==='delivery'?'GitHub delivery':'One-time migration proposal'} onClose={()=>setDialog(null)}><div className="tss-dialog-body">{dialog==='review'?<><p>Review changes in <strong>TEST101_Students</strong>: lesson-revision → main.</p><ul><li>classes/Class01.md — lesson changes</li><li>figure-sources/README.md — figure instructions</li></ul><p>{dirty.Students?'Save your edits before reviewing the branch.':'Saved changes are reviewed within the same Students repository.'}</p><p>Public branches and pull requests are public. Private discussions remain in Instructors or Assistants.</p>{persona==='Instructor'?<button className="pws-button" disabled={dirty.Students} onClick={()=>{setApproved(true);setNotice('Review approved.');}}>Approve review</button>:<p>Assistants propose changes; an instructor gives final approval.</p>}<p>{approved?'Approval recorded.':'Final instructor approval is required before merging to the GitBook-connected main branch.'}</p></>:dialog==='delivery'?<><p>{space==='Students'?'Students main → GitBook. Private repository content is never included automatically.':`Connect TEST101_${key} to GitHub and review repository status before pushing.`}</p></>:<><p>Bind independent Instructors, Assistants, Students and per-team Projects repositories.</p><ol><li>Inventory legacy student candidates and destination edits.</li><li>Adopt the chosen authored Students home; preserve its bytes.</li><li>Keep private notes in private spaces, preserving rollback evidence.</li></ol><p>Course identity, overview, saved files, drafts, calendars and bindings remain preserved. This dialog performs no migration.</p></>}<footer><button className="pws-button" onClick={()=>setDialog(null)}>Close</button></footer></div></CourseDialog>}</>;
}
