import React,{useEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import type {PipelineCall} from './TeachPipelineSettings';
type Entry={login:string;role:string};
const messages:Record<string,string>={GITHUB_PERSONAL_READ_UNSUPPORTED:'GitHub personal repositories do not support a Read-only collaborator invitation. Public content can already be read without an invitation. Use an organization repository for Read access, or explicitly review Write access.',GITHUB_GRANT_REJECTED:'GitHub rejected the access request. Recheck the pending change before preparing a new review.',GITHUB_BUSY:'Account changes are still completing. Wait, then try again.',INVALID_REQUEST:'Use unique GitHub usernames (up to 32 staff entries).',CONFLICT:'The course or roster changed. Reload settings and review again.',GITHUB_STAFF_NOT_LISTED:'Save this username in the course roster first.',GITHUB_VERIFY_FIRST:'Connect and verify this repository role first.',GITHUB_ADMIN_REQUIRED:'Your GitHub account needs repository administration access.',GITHUB_ACCESS_INCOMPLETE:'GitHub access inspection is incomplete. No access change can be reviewed.',GITHUB_USER_UNAVAILABLE:'GitHub did not resolve this personal account.',GITHUB_USER_CHANGED:'The GitHub identity changed. Prepare a fresh review.',GITHUB_ACCOUNT_CHANGED:'The signed-in account changed. Review again.',GITHUB_REPOSITORY_CHANGED:'The repository identity changed. Existing bindings are preserved.',GITHUB_ACCESS_CHANGED:'Repository access changed after review. Review again.',GITHUB_VISIBILITY_CHANGED:'Repository visibility changed. Verify it before reviewing again.',PRIVATE_ROLE_PUBLIC:'Instructor and Assistant repositories must be private.',GITHUB_OUTCOME_UNKNOWN:'The result is uncertain. Recheck the pending change before trying again.',GITHUB_STAFF_RECOVERY_REQUIRED:'A pending access change requires rechecking. No duplicate request will be sent.',GITHUB_PERMISSION_REQUIRED:'GitHub refused this request. Check Administration write and your repository access.',GITHUB_RECONNECT_REQUIRED:'Reconnect GitHub from the account menu.',STALE_PLAN:'This review expired. Prepare a fresh review.'};
export function TeachStaffSettings({repo,settings,call,refresh}:{repo:string;settings:any;call:PipelineCall;refresh:()=>Promise<void>}){
 const [entries,setEntries]=useState<Entry[]>([]),[login,setLogin]=useState(''),[staffRole,setStaffRole]=useState('assistant'),[target,setTarget]=useState('students'),[person,setPerson]=useState(''),[permission,setPermission]=useState('read'),[review,setReview]=useState<any>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const pending=useRef(false),plan=useRef<string|null>(null);
 const roster=settings.staff?.roster??{entries:[],revision:0},recovery=settings.staff?.pending;
 useEffect(()=>{setEntries(roster.entries);},[repo,roster.revision]);
 useEffect(()=>()=>{if(plan.current)void call({operation:'cancelStaffAccess',planId:plan.current}).catch(()=>{});},[repo,call]);
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await action();await refresh();}catch(e){setError(messages[(e as any).code]??'The request did not complete. Recheck settings before retrying.');setReview(null);plan.current=null;setAck(false);try{await refresh();}catch{}}finally{pending.current=false;setBusy(false);}};
 const close=()=>{if(busy)return;if(plan.current)void call({operation:'cancelStaffAccess',planId:plan.current}).catch(()=>{});plan.current=null;setReview(null);setAck(false);};
 const dirty=JSON.stringify(entries)!==JSON.stringify(roster.entries);
 return <section data-teach-area="TP7"><h2>Course staff</h2><p>Save Instructor and Assistant usernames locally. Saving or removing a roster entry does not invite anyone or change GitHub access.</p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy||Boolean(recovery)}><div className="teach-pipeline-actions"><label>Staff GitHub username<input value={login} autoCapitalize="none" spellCheck={false} onChange={e=>setLogin(e.target.value)}/></label><label>Course staff role<select aria-label="Course staff role" value={staffRole} onChange={e=>setStaffRole(e.target.value)}><option value="instructor">Instructor</option><option value="assistant">Assistant</option></select></label><button className="pws-button" disabled={!login.trim()||entries.length>=32||entries.some(e=>e.login.toLowerCase()===login.trim().toLowerCase())} onClick={()=>{setEntries([...entries,{login:login.trim(),role:staffRole}]);setLogin('');}}>Add staff locally</button></div><ul>{entries.map(e=><li key={e.login}>{e.login} · {e.role==='instructor'?'Instructor':'Assistant'} <button className="pws-button" aria-label={`Remove ${e.login} from local roster`} onClick={()=>setEntries(entries.filter(v=>v.login!==e.login))}>Remove locally</button></li>)}</ul><button className="pws-button" disabled={!dirty||!settings.migrated} onClick={()=>void run(async()=>{await call({operation:'saveCourseStaff',repo,entries,revision:roster.revision});setNotice('Staff roster saved locally. GitHub access unchanged.');})}>Save staff roster</button>
 <h3>Reviewed repository access</h3><p>Grant Read or Write to one saved staff account on one connected repository. Existing higher or inherited rights are preserved. This does not restrict student access or revoke former staff access.</p><div className="teach-pipeline-actions"><label>Saved staff account<select aria-label="Saved staff account" value={person} onChange={e=>{close();setPerson(e.target.value);}}><option value="">Choose staff</option>{roster.entries.map((e:Entry)=><option key={e.login} value={e.login}>{e.login}</option>)}</select></label><label>Staff access repository<select aria-label="Staff access repository" value={target} onChange={e=>{close();setTarget(e.target.value);}}>{settings.roles.filter((r:any)=>r.available).map((r:any)=><option key={r.role} value={r.role}>{r.role==='students'?'Students':r.role==='instructors'?'Instructors':'Assistants'}</option>)}</select></label><label>Requested access<select aria-label="Requested access" value={permission} onChange={e=>{close();setPermission(e.target.value);}}><option value="read">Read</option><option value="write">Write</option></select></label><button className="pws-button" disabled={!person||dirty} onClick={()=>void run(async()=>{const p=await call({operation:'reviewStaffAccess',repo,role:target,login:person,permission});plan.current=p.planId;setReview(p);setAck(false);})}>Review staff access</button></div></fieldset>
 {recovery&&<div><h3>Pending access change</h3><p>{recovery.user.login} · {recovery.permission} · {recovery.remote.owner}/{recovery.remote.name}. Rechecking only reads GitHub; it never repeats the grant.</p><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const result=await call({operation:'recoverStaffAccess',repo,direction:'complete'});setNotice(result.status);})}>Recheck access change</button><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const result=await call({operation:'recoverStaffAccess',repo,direction:'clear'});setNotice(result.status);})}>Verify no grant and clear intent</button></div>}<p role="status">{notice}</p>
 {review&&<CourseDialog title="Review staff repository access" onClose={close}><p>{review.user.login} · GitHub user ID {review.user.id}</p><p>{review.remote.owner}/{review.remote.name} · {review.remote.visibility} · repository ID {review.remote.id}</p><p>Signed in as {review.account.login}. Current access: {review.current}. Requested: {review.permission}.</p><p>{review.status}</p>{review.remote.ownerType==='User'&&review.action==='grant'&&<p>Personal repository collaborator access includes writing changes. This invitation grants Write access.</p>}<p>Organization owners and inherited access remain. GitHub may notify the recipient; a pending invitation must be accepted. No organization membership or other repository access is changed.</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed this account, repository and requested access.</label><button className="pws-button" disabled={busy||!ack} onClick={()=>void run(async()=>{const result=await call({operation:'applyStaffAccess',planId:review.planId});plan.current=null;setReview(null);setAck(false);setNotice(result.status);})}>{review.action==='none'?'Confirm access observation':'Confirm repository access'}</button></CourseDialog>}</section>;
}
