import React,{useEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import type {PipelineCall} from './TeachPipelineSettings';
type Entry={login:string;role:string;firstName?:string;lastName?:string;email?:string};
export const staffAccessMessages:Record<string,string>={GITHUB_SEAT_LIMIT:'GitHub has no available organization seat for this collaborator. Ask an organization owner to resolve the seat limit before a fresh review.',GITHUB_STUDENT_ACCESS_SCOPE:'Student invitations are limited to Read access on the Students repository.',GITHUB_PERSONAL_READ_UNSUPPORTED:'GitHub personal repositories do not support a Read-only collaborator invitation. Public content can already be read without an invitation. Use an organization repository for Read access, or explicitly review Write access.',GITHUB_GRANT_REJECTED:'GitHub rejected the access request. Recheck the pending change before preparing a new review.',GITHUB_BUSY:'Account changes are still completing. Wait, then try again.',INVALID_REQUEST:'Use valid emails and unique GitHub usernames. Maximum: 32 staff and 500 students.',CONFLICT:'The course or roster changed. Reload settings and review again.',GITHUB_STAFF_NOT_LISTED:'Save this username in the course roster first.',GITHUB_VERIFY_FIRST:'Connect and verify this repository role first.',GITHUB_ADMIN_REQUIRED:'Your GitHub account needs repository administration access.',GITHUB_ACCESS_INCOMPLETE:'GitHub access inspection is incomplete. No access change can be reviewed.',GITHUB_USER_UNAVAILABLE:'GitHub did not resolve this personal account.',GITHUB_USER_CHANGED:'The GitHub identity changed. Prepare a fresh review.',GITHUB_ACCOUNT_CHANGED:'The signed-in account changed. Review again.',GITHUB_REPOSITORY_CHANGED:'The repository identity changed. Existing bindings are preserved.',GITHUB_ACCESS_CHANGED:'Repository access changed after review. Review again.',GITHUB_VISIBILITY_CHANGED:'Repository visibility changed. Verify it before reviewing again.',PRIVATE_ROLE_PUBLIC:'Instructor and Assistant repositories must be private.',GITHUB_OUTCOME_UNKNOWN:'The result is uncertain. Recheck the pending change before trying again.',GITHUB_STAFF_RECOVERY_REQUIRED:'A pending access change requires rechecking. No duplicate request will be sent.',GITHUB_PERMISSION_REQUIRED:'GitHub refused this request. Check repository access, organization policy and app authorization.',GITHUB_RECONNECT_REQUIRED:'Reconnect GitHub from the account menu.',STALE_PLAN:'This review expired. Prepare a fresh review.'};
export function TeachStaffSettings({repo,settings,call,refresh,audience='staff'}:{repo:string;settings:any;call:PipelineCall;refresh:()=>Promise<void>;audience?:'staff'|'students'}){
 const [entries,setEntries]=useState<Entry[]>([]),[target,setTarget]=useState('students'),[person,setPerson]=useState(''),[permission,setPermission]=useState('read'),[review,setReview]=useState<any>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const pending=useRef(false),plan=useRef<string|null>(null);
 type PersonForm={firstName:string;lastName:string;email:string;login:string;editing:number|null;staffRole:string};
 const emptyForm:PersonForm={firstName:'',lastName:'',email:'',login:'',editing:null,staffRole:'assistant'};
 const [forms,setForms]=useState<Record<string,PersonForm>>({}),[query,setQuery]=useState('');
 const {firstName,lastName,email,login,editing,staffRole}=forms[audience]??emptyForm;
 const field=<K extends keyof PersonForm>(key:K,value:PersonForm[K])=>setForms(prior=>({...prior,[audience]:{...emptyForm,...prior[audience],[key]:value}}));
 const setFirstName=(v:string)=>field('firstName',v),setLastName=(v:string)=>field('lastName',v),setEmail=(v:string)=>field('email',v),setLogin=(v:string)=>field('login',v),setEditing=(v:number|null)=>field('editing',v),setStaffRole=(v:string)=>field('staffRole',v);
 const students=audience==='students', title=students?'Students':'Course staff';
 const roster=settings.staff?.roster??{entries:[],revision:0},recovery=settings.staff?.pending;
 useEffect(()=>{setEntries(roster.entries);},[repo,roster.revision]);
 useEffect(()=>()=>{if(plan.current)void call({operation:'cancelStaffAccess',planId:plan.current}).catch(()=>{});},[repo,call]);
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await action();await refresh();}catch(e){setError(staffAccessMessages[(e as any).code]??'The request did not complete. Recheck settings before retrying.');setReview(null);plan.current=null;setAck(false);try{await refresh();}catch{}}finally{pending.current=false;setBusy(false);}};
 const close=()=>{if(busy)return;if(plan.current)void call({operation:'cancelStaffAccess',planId:plan.current}).catch(()=>{});plan.current=null;setReview(null);setAck(false);};
 const dirty=JSON.stringify(entries)!==JSON.stringify(roster.entries);
 const clearPerson=()=>setForms(prior=>({...prior,[audience]:emptyForm}));
 useEffect(()=>{setQuery('');setPerson('');setTarget('students');setPermission('read');close();},[audience]);
 const visible=entries.map((entry,index)=>({entry,index})).filter(({entry})=>(entry.role==='student')===students).filter(({entry})=>[entry.firstName,entry.lastName,entry.email,entry.login].join(' ').toLowerCase().includes(query.toLowerCase()));
 const savedPeople=roster.entries.filter((e:Entry)=>(e.role==='student')===students&&e.login);
 const validPerson=Boolean(firstName.trim()||lastName.trim()||email.trim()||login.trim())&&(!login.trim()||/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$/.test(login.trim())&&!login.includes('--'))&&(!email.trim()||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))&&!entries.some((e,i)=>i!==editing&&login.trim()&&e.login.toLowerCase()===login.trim().toLowerCase());
 return <section data-teach-area="TP7"><h2 tabIndex={-1}>{title}</h2><p>Keep names, emails and GitHub accounts in the private local course directory. Saving sends no email or invitation.</p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy||Boolean(recovery)}>
 <div className="teach-directory-form">
 <label>First name<input maxLength={100} value={firstName} onChange={e=>setFirstName(e.target.value)}/></label>
 <label>Last name<input maxLength={100} value={lastName} onChange={e=>setLastName(e.target.value)}/></label>
 <label>Email<input type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label>
 <label>GitHub username<input maxLength={39} value={login} autoCapitalize="none" spellCheck={false} onChange={e=>setLogin(e.target.value)}/></label>
 {!students&&<label>Course staff role<select aria-label="Course staff role" value={staffRole} onChange={e=>setStaffRole(e.target.value)}><option value="instructor">Instructor</option><option value="assistant">Assistant</option></select></label>}
 </div><p className="teach-settings-note">A GitHub username can be added later. Invitations require a saved username; email is for your reference.</p>
 <div className="teach-pipeline-actions"><button className="pws-button" disabled={!validPerson||(editing===null&&entries.filter(e=>(e.role==='student')===students).length>=(students?500:32))} onClick={()=>{const entry:Entry={firstName:firstName.trim(),lastName:lastName.trim(),email:email.trim(),login:login.trim(),role:students?'student':staffRole};setEntries(editing===null?[...entries,entry]:entries.map((e,i)=>i===editing?entry:e));clearPerson();}}>{editing===null?'Add to directory':'Update person'}</button>{editing!==null&&<button className="pws-button" onClick={clearPerson}>Cancel editing</button>}<button className="pws-button" disabled={!dirty||!settings.migrated||editing!==null} onClick={()=>void run(async()=>{await call({operation:'saveCourseStaff',repo,entries,revision:roster.revision});setNotice('Course directories saved locally. GitHub access unchanged.');})}>Save directories</button></div>
 <label className="teach-directory-search">Search directory<input value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <div className="teach-pipeline-table"><table><thead><tr><th>Name</th><th>Email</th><th>GitHub</th>{!students&&<th>Role</th>}<th>Actions</th></tr></thead><tbody>{visible.map(({entry:e,index})=><tr key={index}><td>{[e.firstName,e.lastName].filter(Boolean).join(' ')||'—'}</td><td>{e.email||'—'}</td><td>{e.login||'Not set'}</td>{!students&&<td>{e.role==='instructor'?'Instructor':'Assistant'}</td>}<td><div className="teach-directory-actions"><button className="pws-button" aria-label={`Edit ${e.login||e.firstName||'person'}`} onClick={()=>{setEditing(index);setFirstName(e.firstName??'');setLastName(e.lastName??'');setEmail(e.email??'');setLogin(e.login);setStaffRole(e.role);}}>Edit</button><button className="pws-button" aria-label={`Remove ${e.login||e.firstName||'person'} from local directory`} onClick={()=>{setEntries(entries.filter((_,i)=>i!==index));setForms({});}}>Remove</button></div></td></tr>)}</tbody></table>{!visible.length&&<p>{query?'No matching people.':'No people added yet.'}</p>}</div>

 <h3>Repository invitations and access</h3>{!settings.roles.find((r:any)=>r.role===target)?.sourceUrl&&<p className="teach-settings-note">Connect the selected repository in Delivery before reviewing access.</p>}{students&&<p>Student access is Read-only and limited to the Students repository. Public courses can be read without an invitation. Team project access is managed in Teams.</p>}<p>After connecting a repository in Delivery, review {students?'Read access':'Read or Write access'} for a saved course account. Existing higher or inherited rights stay unchanged; removing a person locally does not revoke GitHub access.</p><div className="teach-pipeline-actions"><label>Saved course account<select aria-label="Saved course account" value={person} onChange={e=>{close();setPerson(e.target.value);}}><option value="">Choose a person</option>{savedPeople.map((e:Entry)=><option key={e.login} value={e.login}>{[e.firstName,e.lastName].filter(Boolean).join(' ')||e.login} · {e.login}</option>)}</select></label><label>Course access repository<select aria-label="Course access repository" value={target} onChange={e=>{close();setTarget(e.target.value);}}>{settings.roles.filter((r:any)=>r.available&&(!students||r.role==='students')).map((r:any)=><option key={r.role} value={r.role}>{r.role==='students'?'Students':r.role==='instructors'?'Instructors':'Assistants'}</option>)}</select></label><label>Requested access<select aria-label="Requested access" value={permission} onChange={e=>{close();setPermission(e.target.value);}}><option value="read">Read</option>{!students&&<option value="write">Write</option>}</select></label><button className="pws-button" disabled={!person||dirty||editing!==null||!settings.roles.find((r:any)=>r.role===target)?.sourceUrl} onClick={()=>void run(async()=>{const p=await call({operation:'reviewStaffAccess',repo,role:target,login:person,permission});plan.current=p.planId;setReview(p);setAck(false);})}>Review repository access</button></div></fieldset>
 {recovery&&<div><h3>Pending access change</h3><p>{recovery.user.login} · {recovery.permission} · {recovery.remote.owner}/{recovery.remote.name}. Rechecking only reads GitHub; it never repeats the grant.</p><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const result=await call({operation:'recoverStaffAccess',repo,direction:'complete'});setNotice(result.status);})}>Recheck access change</button><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{const result=await call({operation:'recoverStaffAccess',repo,direction:'clear'});setNotice(result.status);})}>Verify no grant and clear intent</button></div>}<p role="status">{notice}</p>
 {review&&<CourseDialog title="Review repository access" onClose={close}><p>{review.user.login} · GitHub user ID {review.user.id}</p><p>{review.remote.owner}/{review.remote.name} · {review.remote.visibility} · repository ID {review.remote.id}</p><p>Signed in as {review.account.login}. Current access: {review.current}. Requested: {review.permission}.</p><p>{review.status}</p>{review.remote.ownerType==='User'&&review.action==='grant'&&<p>Personal repository collaborator access includes writing changes. This invitation grants Write access.</p>}<p>Organization owners and inherited access remain. GitHub may notify the recipient; a pending invitation must be accepted. No organization membership or other repository access is changed.</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed this account, repository and requested access.</label><button className="pws-button" disabled={busy||!ack} onClick={()=>void run(async()=>{const result=await call({operation:'applyStaffAccess',planId:review.planId});plan.current=null;setReview(null);setAck(false);setNotice(result.status);})}>{review.action==='none'?'Confirm access observation':'Confirm repository access'}</button></CourseDialog>}</section>;
}
