import {TeachProjectDetail} from './TeachProjectDetail';
import React,{useEffect,useRef,useState} from 'react';
import {CourseDialog} from './TeachCoursesStudy';
import type {PipelineCall} from './TeachPipelineSettings';

export function TeachProjectSettings({repo,year,season,call}:{repo:string;year:number;season:string;call:PipelineCall}){
 const [settings,setSettings]=useState<any>(null),[count,setCount]=useState(8),[review,setReview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(''),[existing,setExisting]=useState(''),[label,setLabel]=useState('Team01');
 const pending=useRef(false),plan=useRef<string|null>(null);
 const refresh=async()=>setSettings(await call({operation:'projectSettings',repo}));
 useEffect(()=>{let active=true;void call({operation:'projectSettings',repo}).then(v=>{if(active)setSettings(v);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;if(plan.current)void call({operation:'cancelProjectCreation',planId:plan.current}).catch(()=>{});};},[repo,call]);
 const run=async(action:()=>Promise<void>)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{pending.current=false;setBusy(false);}};
 const close=()=>{if(busy)return;if(plan.current)void call({operation:'cancelProjectCreation',planId:plan.current}).catch(()=>{});plan.current=null;setReview(null);};
 const teams=settings?.projects.filter((p:any)=>p.term===`${year}-${season}`)??[];
 return <section data-teach-area="TP8" aria-labelledby="teach-projects-title" aria-busy={busy}>
  <h2 id="teach-projects-title">Team projects</h2>
  <p>Separate local repositories for {year} {season}. GitHub setup, access grants and submission verification are separate steps.</p>
  {error&&<p role="alert">{error}</p>}
  <fieldset disabled={busy||!settings}>
   <div className="teach-pipeline-actions"><label>Number of teams<select value={count} onChange={e=>setCount(Number(e.target.value))}>{Array.from({length:8},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><button className="pws-button" disabled={Boolean(settings?.pending)} onClick={()=>void run(async()=>{const result=await call({operation:'reviewProjectCreation',repo,year,season,count});if(result.planId){plan.current=result.planId;setReview(result);}else setNotice(result.status);})}>Review team repositories</button></div>
   <details><summary>Use an existing or cloned project repository</summary><p>Clone through the normal repository controls first, then bind it here without replacing files or history.</p><div className="teach-pipeline-actions"><label>Team to bind<select aria-label="Team to bind" value={label} onChange={e=>setLabel(e.target.value)}>{Array.from({length:8},(_,i)=>`Team${String(i+1).padStart(2,'0')}`).filter(v=>!teams.some((p:any)=>p.label===v)).map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Existing project repository<select aria-label="Existing project repository" value={existing} onChange={e=>setExisting(e.target.value)}><option value="">Choose repository</option>{settings?.repositories?.map((r:any)=><option key={r.stableId} value={r.stableId}>{r.name}</option>)}</select></label><button className="pws-button" disabled={!existing||teams.some((p:any)=>p.label===label)||Boolean(settings?.pending)} onClick={()=>void run(async()=>{const result=await call({operation:'reviewProjectBinding',repo,year,season,label,repositoryId:existing});plan.current=result.planId;setReview({...result,binding:true});})}>Review existing project binding</button></div></details>
   {settings?.pending&&<><p role="alert">Local creation was interrupted. Resume using the same repository identities.</p><button className="pws-button" onClick={()=>void run(async()=>{await call({operation:'recoverProjectCreation',repo});await refresh();setNotice('Local team repositories recovered.');})}>Resume local creation</button></>}
   {teams.length>0&&<div className="teach-pipeline-table"><table><thead><tr><th>Team</th><th>Local repository</th><th>GitHub</th><th>Manage</th></tr></thead><tbody>{teams.map((p:any)=><tr key={p.id}><th scope="row">{p.label}</th><td>{p.name??'Unavailable'}</td><td>{p.github?.roles?.instructors?.remote?.url??'Not connected'}</td><td><button className="pws-button" onClick={()=>setSelected(p.id)}>Manage {p.label}</button></td></tr>)}</tbody></table></div>}
  </fieldset>
  {teams.find((p:any)=>p.id===selected)&&<TeachProjectDetail key={selected} repo={repo} team={teams.find((p:any)=>p.id===selected)} call={call} refresh={refresh}/>}
  <p role="status">{notice}</p>
  {review&&<CourseDialog title="Review local team repositories" onClose={close}><p>{review.status}</p><ul>{review.binding?<li>{review.team}: {review.name}</li>:review.teams.map((p:any)=><li key={p.id}>{p.label}: {p.localName}</li>)}</ul><p>{review.binding?'Existing content remains unchanged. No starter is copied.':'Each repository contains a project brief, six worksheets, environment, code, results, poster, video and submission manifest placeholders. No student access is granted.'}</p><button className="pws-button" disabled={busy} onClick={()=>void run(async()=>{await call({operation:review.binding?'applyProjectBinding':'applyProjectCreation',planId:review.planId});plan.current=null;setReview(null);await refresh();setNotice('Team repositories created locally.');})}>{review.binding?'Bind existing project repository':'Create local team repositories'}</button></CourseDialog>}
 </section>;
}
